// Stateless rendering of injected model samples. No API or runtime ownership.
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function chart(rows,key,label,scale=1){
 const valid=rows.filter(r=>r.error_code===null),values=valid.map(r=>r[key]/scale);if(!values.length)return `<p>${escape(label)}: 유효 표본 없음</p>`;
 const min=Math.min(...values),max=Math.max(...values),span=max-min||1;
 const segments=[];let line=[];for(let i=0;i<rows.length;i++){const row=rows[i];if(row.error_code!==null){if(line.length)segments.push(line);line=[];}else line.push(`${(50+520*i/(rows.length-1)).toFixed(3)},${(135-110*(row[key]/scale-min)/span).toFixed(3)}`);}if(line.length)segments.push(line);
 return `<figure style="margin:12px 0"><figcaption>${escape(label)}</figcaption><svg role="img" aria-label="${escape(label)} 시간별 모델 그래프" viewBox="0 0 600 160" style="width:100%;height:auto;background:#102d3a"><title>${escape(label)} · 오류 표본에서는 선이 끊깁니다</title><path d="M50 20V135H575" fill="none" stroke="#97aeb9"/><text x="4" y="25" fill="#eef6fa" font-size="10">${max.toFixed(3)}</text><text x="4" y="135" fill="#eef6fa" font-size="10">${min.toFixed(3)}</text>${segments.map(points=>`<polyline points="${points.join(' ')}" stroke="#63dcf0" fill="none" stroke-width="2"/>`).join('')}${segments.filter(points=>points.length===1).map(points=>{const [x,y]=points[0].split(',');return `<circle cx="${x}" cy="${y}" r="3" fill="#63dcf0"/>`;}).join('')}<text x="50" y="155" fill="#eef6fa" font-size="10">0초</text><text x="500" y="155" fill="#eef6fa" font-size="10">종료</text></svg></figure>`;
}
export function seriesMarkup(result,interval){
 if(!result)return '';
 const rows=result.rows,valid=rows.filter(r=>r.error_code===null),errors=rows.filter(r=>r.error_code!==null),directions=[];
 for(const row of valid){const label=row.range_rate_m_s<0?'접근':row.range_rate_m_s>0?'이탈':'거리 변화 없음';if(directions.at(-1)!==label)directions.push(label);}
 let summary='<p>전체 구간 요약 미확인 · 실패 표본이 있습니다.</p>';
 if(!errors.length){const nearest=valid.reduce((a,b)=>b.range_m<a.range_m?b:a),maximum=valid.reduce((a,b)=>Math.abs(b.doppler_hz)>Math.abs(a.doppler_hz)?b:a);summary=`<dl class="rf-metrics"><dt>표본 중 최근접 UTC</dt><dd>${escape(nearest.utc)}</dd><dt>표본 중 최소 거리 km</dt><dd>${(nearest.range_m/1000).toFixed(6)}</dd><dt>표본 중 절대 도플러 최대 Hz (부호 포함)</dt><dd>${maximum.doppler_hz.toFixed(6)}</dd><dt>해당 UTC</dt><dd>${escape(maximum.utc)}</dd></dl>`;}
 return `<p><strong>저장 궤도 모델 구간 · 실제 수신 미확인</strong></p><p>UTC ${escape(result.start_utc)} → ${escape(result.end_utc)}<br>SI 지속 ${result.duration_seconds.toFixed(6)}초 / 표본 ${rows.length}개 / 간격 ${result.step_seconds.toFixed(6)}초 / 송신 ${(result.frequency_hz/1e6).toFixed(6)}MHz<br>${interval.start_clipped?'시작 잘림 ':''}${interval.end_clipped?'종료 잘림':''}${!interval.start_clipped&&!interval.end_clipped?'기존 조회의 양쪽 경계 확인':''}</p><p>${directions.join(' → ')||'유효 표본 없음'}${errors.length?' · 실패 구간의 연속 흐름 미확인':''}</p>${summary}<p>표본 사이 선은 시각적 연결이며 연속 극값 탐색·실측 결과가 아닙니다. 기하 가시 경계를 다시 확정하거나 실제 통신 가능을 판정하지 않습니다.</p>${chart(rows,'range_m','거리 km',1000)}${chart(rows,'elevation_deg','고도각 °')}${chart(rows,'doppler_hz','도플러 Hz (수신−송신)')}<p>시간축: 시작으로부터 균등 SI 초, 시작 0 / 종료 ${result.duration_seconds.toFixed(6)}초. 오류 행은 선을 연결하지 않습니다.</p>${errors.length?`<ul>${errors.map(r=>`<li>${escape(r.utc)} / ${escape(r.error_code)}</li>`).join('')}</ul>`:''}<details><summary>단방향 모델 가정 및 자료 근거</summary><ul>${result.assumptions.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><p>입력 ${escape(result.input_id)} / revision ${result.revision}<br>SHA256 ${escape(result.input_hash)}<br>EOP ${escape(result.eop_sha256)}<br>윤초 ${escape(result.leap_sha256)} / ${escape(result.frame)} / ${escape(result.profile)}</p></details>`;
}
