// Actual ASGI/native responses and guarded original module replies over bounded stdin IPC.
import assert from 'node:assert/strict';
import {createInterface} from 'node:readline';
import {readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {createNodeDisplayTimeline} from '../../../user_application/web/scripts/nodes/node_timeline.js';
import {createNodeOpticalTimeline} from '../../../user_application/web/scripts/nodes/optical_timeline.js';
import {createNodeNetworkTimeline} from '../../../user_application/web/scripts/nodes/network_timeline.js';
import {createNodeLinkResolver} from '../../../user_application/web/scripts/nodes/links.js';
import {createNodeLibrary} from '../../../digital_twin/model_library/browser/satellite_nodes.js';
import {orbitElements,catalogElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import {createGroundLinkModel} from '../../../digital_twin/simulation/browser/ground_links.js';
import {createNetworkSnapshotModel} from '../../../digital_twin/simulation/browser/network_snapshot.js';
import * as stationModel from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as oisl from '../../../digital_twin/simulation/browser/oisl.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
import {createFabricExchange} from '../../../user_application/web/scripts/tabs/fabric_exchange.js';
import {createDataFabricClient} from '../../../communication/browser/data_fabric.js';
import {createPeriodicFabricExchange} from '../../../user_application/web/scripts/nodes/periodic_fabric_exchange.js';
import {createMixedRouteEmphasis} from '../../../user_application/web/scripts/nodes/mixed_route_emphasis.js';
const timing={},started=performance.now();const input=createInterface({input:process.stdin}),waiting=new Map();let requestId=0;
input.on('line',line=>{const value=JSON.parse(line),task=waiting.get(value.id);if(task){waiting.delete(value.id);task(value);}});
const http=(path,options={})=>new Promise(resolve=>{const id=++requestId;waiting.set(id,resolve);process.stdout.write(JSON.stringify({type:'http',id,path,method:options.method??'GET',headers:options.headers??{},body:options.body??null})+'\n');});
const fetchImpl=async(path,options)=>{const result=await http(path,options);return {ok:result.status>=200&&result.status<300,status:result.status,json:async()=>result.body};};
const original=JSON.parse(gunzipSync(await readFile(new URL('../fixtures/original_node_link_resolution.json.gz',import.meta.url))));
const bases=original.cases.find(c=>c.id==='dense-two-plane:0').rows.at(-1).input.nodes;
let equipment=0;const library=createNodeLibrary({orbitElements,catalogElements,createEquipmentId:()=>`EQ-REAL-${++equipment}`});
const nodes=Array.from({length:240},(_,i)=>library.cloneNode(bases[i%bases.length],{epoch:original.epoch,id:`REAL-${i}`,catalogNumber:920000+i}));
nodes.forEach((node,i)=>node.orbit.mean_anomaly=(node.orbit.mean_anomaly+Math.floor(i/bases.length)*2)%360);
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};freeze(nodes);const nodeRevision=Object.freeze({}),nodeScopeRevision=()=>nodeRevision;
const codec=createUtcCodec(LEAP_SHA256);let utc=codec.advance(new Date(original.epoch).toISOString(),0),wall=0;
const display=()=>({utc,key:'catalog:real-native-fixture',source:'catalog',leap_sha256:LEAP_SHA256});
const lease=Object.freeze({});const continuity={readContinuity:()=>lease,verifyContinuity:value=>value===lease};
let samples=0;
const timeline=createNodeDisplayTimeline({api:{nodeSamples:async body=>{samples++;const r=await fetchImpl('/api/nodes/samples',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.ok,true);return r.json();},nodeTrack:()=>{throw Error('no display-track request');}},periodFor:()=>95,requestId:()=>`native-module-${samples}`,yieldControl:async()=>{}});
timeline.setDefinitions(nodes);
const optical=createNodeOpticalTimeline({resolver:createNodeLinkResolver({library,oisl}),requestCommunicationStates:timeline.requestCommunicationStates,readNodes:()=>nodes,nodeScopeRevision,readDisplay:display,advanceUtc:codec.advance,...continuity});
let phase=performance.now();await optical.updateSampled();assert.equal(optical.sampledPresentation().status,'valid');timing.optical_ms=performance.now()-phase;
const states=await timeline.requestCommunicationStates(utc),position=new Map(states.states).get(nodes[0].id).geodetic;
const stations=[stationModel.createStation({name:'Native test ground',latitude:position.latitude,longitude:position.longitude,altitude_km:0,bands:['S','X','Ka'],min_elevation_deg:10},{id:'GS-REAL'})];
const model=createNetworkSnapshotModel({library,groundLinks:createGroundLinkModel({library,stationModel}),oisl});
const network=createNodeNetworkTimeline({model,optical,requestCommunicationStates:timeline.requestCommunicationStates,readNodes:()=>nodes,nodeScopeRevision,readDisplay:display,readStations:()=>stations,readFaults:()=>[],validateNode:library.validateNode,validateStation:stationModel.validateStation,advanceUtc:codec.advance,...continuity});
phase=performance.now();await network.updateSampled();const token=network.captureRawAnalysis();assert.ok(token);assert.equal(token.snapshot.node_definitions.length,240);assert.equal(network.verifyRawAnalysis(token),true);timing.network_raw_ms=performance.now()-phase;
const facade={networkSnapshot:network.snapshot,verifyNetworkSnapshot:network.verifySnapshot,captureRawAnalysis:network.captureRawAnalysis,verifyRawAnalysis:network.verifyRawAnalysis};
const fabric=createFabricExchange({client:createDataFabricClient({fetchImpl}),network:facade,clientId:'actual-native-periodic'});
const periodic=createPeriodicFabricExchange({fabric,capture:network.captureRawAnalysis,verify:network.verifyRawAnalysis,readRoute:()=>({source:nodes[0].id,target:'GS-REAL',objective:'balanced'}),now:()=>wall});
phase=performance.now();periodic.setActive(true);await periodic.tick();timing.first_exchange_route_ms=performance.now()-phase;
let view=fabric.analyticalPresentation();assert.ok(view);assert.equal(view.receipt.sequence,1);assert.equal(view.route.status,'available');assert.equal(view.route.path.at(-1),'GS-REAL');assert.equal(fabric.verifyAnalyticalPresentation(view),true);assert.equal(fabric.snapshot().receipt,null);
const first=view;utc=codec.advance(utc,1);wall=1000;assert.equal(network.verifyRawAnalysis(token),true);phase=performance.now();await periodic.tick();timing.repeat_exchange_route_ms=performance.now()-phase;view=fabric.analyticalPresentation();assert.ok(view);assert.equal(view.receipt.sequence,2);assert.notEqual(view.receipt.request_id,first.receipt.request_id);assert.equal(view.analysis_utc,token.analysis_utc);assert.equal(fabric.verifyAnalyticalPresentation(first),false);assert.equal(fabric.snapshot().receipt,null);assert.equal(samples,3);
const emphasis=createMixedRouteEmphasis({readNetwork:network.snapshot,verifyNetwork:network.verifySnapshot,readFabric:fabric.snapshot,readDisplay:display,readAnalyticalFabric:fabric.analyticalPresentation,verifyAnalyticalFabric:fabric.verifyAnalyticalPresentation,differenceUtc:codec.difference});
phase=performance.now();const visual=emphasis.readAnalytical({utc});assert.ok(visual);assert.equal(visual.fabric_view,view);assert.equal(visual.native_snapshot.node_definitions.length,240);assert.equal(emphasis.verifyAnalytical(visual,{utc,nodes}),true);assert.equal(emphasis.verifyAnalytical(structuredClone(visual),{utc,nodes}),false);assert.ok(visual.routed_ids.length>0);assert.equal(visual.age_seconds,1);assert.equal(visual.current_analysis,false);timing.visual_read_verify_ms=performance.now()-phase;timing.total_ms=performance.now()-started;
const proof={status:'passed',native_rows:240*3,native_queries:samples,full_nodes:view.network.nodes.length,sequence:view.receipt.sequence,route_status:view.route.status,route_hops:view.route.hop_list.length,analysis_utc:view.analysis_utc,display_utc:utc,natural_movement_raw_proof:true,exact_receipt_unavailable:true,guarded_source_module:true,registered_analytical_visual:true,visual_route_ids:visual.routed_ids.length,timing,scope:'isolated actual ASGI/Rust/original module and JS owners; no live deployment/browser/GPU proof'};
emphasis.destroy();
periodic.destroy();fabric.destroy();network.destroy();optical.destroy();timeline.destroy();input.close();process.stdout.write(JSON.stringify({type:'done',proof})+'\n');
