import test from 'node:test';
import assert from 'node:assert/strict';
import {createAnalysisTransport} from '../../../user_application/web/scripts/scenario/analysis_transport.js';
import {createAnalysisFollowCoordinator} from '../../../user_application/web/scripts/scenario/analysis_follow.js';
import {createOrbitSelection} from '../../../user_application/web/scripts/orbit_selection.js';
import {createCatalogTimeline} from '../../../user_application/web/scripts/catalog_timeline.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const codec=createUtcCodec(LEAP_SHA256),hash='a'.repeat(64),utc='2026-10-07T00:00:00.000000000Z',wall='2026-10-07T01:00:00.000000000Z';
async function fixture({observer=true}={}){
 const calls=[];let current={revision:0,input_id:null,ground_point:{latitude_deg:0,longitude_deg:0,ellipsoid_height_m:0},minimum_elevation_deg:5,play_rate:1,leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC'};
 const runtime={run_id:'run',running:false,speed:1,utc};let release=null,failure=false;
 const base={group:'active',catalog_number:25544,name:'ISS',utc,epoch_utc:utc,normalized_gp_sha256:hash,eop_sha256:hash,leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC',eop_kind:'IERS_A',eop_quality:{ut1:'final_b',polar_motion:'final_b'},source:'celestrak-cache',position_m:[7e6,1,2]};
 const stored=createOrbitSelection({orbitInputs:async()=>({inputs:[{input_id:'tle',raw_sha256:hash,epoch_utc:utc}]}),orbitState:async()=>structuredClone(current),selectOrbit:async p=>{calls.push(['select',p]);return current={...current,...p,revision:current.revision+1,input_hash:hash,current_utc:p.anchor_utc};},orbitSamples:async p=>{calls.push(['samples',p]);if(failure)throw Error('native unavailable');return {...p,frame:'ITRF',leap_sha256:LEAP_SHA256,profile:'WGS72_AFSPC',revision:p.selection_revision,input_hash:hash,status:'complete',stale:false,rows:[{utc:p.start_utc,status:'valid',position_m:[7e6,1,2]}]};}},()=>{},()=>String(calls.length));
 const catalog=createCatalogTimeline({catalogSamples:async p=>{calls.push(['catalog',p]);if(release!==null)await new Promise(r=>release=r);return {...base,...p,version:1,status:'valid',communication_status:'unknown',units:{position:'m',range:'m',elevation:'deg',azimuth:'deg',time:'UTC'},rows:Array.from({length:p.count},(_,i)=>({utc:codec.advance(p.start_utc,i),status:'valid',error_code:null,position_m:[7e6+i,1,2],elevation_deg:10,range_m:1000,azimuth_deg:0,visible:true,eop_quality:base.eop_quality}))};}},()=>{},()=>{},{now:()=>0,requestFrame:()=>1,cancelFrame(){},requestId:()=>String(calls.length)});
 await stored.load();await stored.select('tle');catalog.select(base);if(observer)catalog.observer({latitude_deg:0,longitude_deg:0,ellipsoid_height_m:0,virtual:true,ellipsoid:'WGS84'},5);calls.length=0;
 const c=createAnalysisFollowCoordinator({stored,catalog,readRuntime:()=>({...runtime}),utcOfRuntime:r=>r.utc,codec,wallNow:()=>Date.parse(wall)});
 return {c,stored,catalog,runtime,calls,base,fail:()=>failure=true,delay:()=>release=true,resolve:()=>release(),destroy(){c.destroy();stored.destroy();catalog.destroy();}};
}
test('explicit follow uses actual owners and native GP calculations, release restores source wall-live semantics',async()=>{const f=await fixture(),source={now(){throw Error('interpolated source is not authoritative');}};await f.c.followAll(source);assert.equal(f.c.followedSource(),source);assert.equal(f.stored.snapshot().state.current_utc,utc);assert.equal(f.catalog.snapshot().display.utc,utc);assert.equal(f.catalog.snapshot().display.frame,'ITRF');assert.equal(f.stored.snapshot().state.playing,false);assert.equal(f.catalog.snapshot().playing,false);await f.c.releaseAll(source);assert.equal(f.c.followedSource(),null);assert.equal(f.stored.snapshot().state.current_utc,wall);assert.equal(f.stored.snapshot().state.playing,true);assert.equal(f.stored.snapshot().state.play_rate,1);assert.equal(f.catalog.snapshot().utc,wall);assert.equal(f.catalog.snapshot().playing,true);assert.equal(f.catalog.snapshot().rate,1);f.destroy();});
test('preflight refuses missing observer or running SIM before any stored command',async()=>{for(const kind of ['observer','running']){const f=await fixture({observer:kind!=='observer'});if(kind==='running')f.runtime.running=true;await assert.rejects(f.c.followAll({now:()=>0}));assert.equal(f.calls.length,0);assert.equal(f.c.followedSource(),null);f.destroy();}});
test('native failure remains explicit, never claims following or releases failed selection',async()=>{const f=await fixture();f.fail();await assert.rejects(f.c.followAll({now:()=>0}),/native/);assert.equal(f.c.followedSource(),null);assert.equal(f.stored.snapshot().result,null);assert.equal(f.calls.filter(x=>x[0]==='catalog').length,0);f.destroy();});
test('run drift during native await rejects proof and late changed catalog cannot be reselected on release',async()=>{const f=await fixture();f.delay();const work=f.c.followAll({now:()=>0});while(typeof f.resolve!=='function'||!f.calls.some(x=>x[0]==='catalog'))await new Promise(r=>setImmediate(r));f.runtime.run_id='other';f.resolve();await assert.rejects(work,/changed/);assert.equal(f.c.followedSource(),null);f.destroy();});
test('changed selected GP blocks release rather than restoring an earlier selection',async()=>{const f=await fixture(),source={now:()=>0};await f.c.followAll(source);f.catalog.select({...f.base,normalized_gp_sha256:'b'.repeat(64)});const count=f.calls.length;await assert.rejects(f.c.releaseAll(source),/changed/);assert.equal(f.calls.length,count);assert.equal(f.catalog.snapshot().selected.normalized_gp_sha256,'b'.repeat(64));f.destroy();});
test('disposal detaches without wall-live server writes',async()=>{const f=await fixture();await f.c.followAll({now:()=>0});const count=f.calls.length;f.c.destroy();assert.equal(f.calls.length,count);assert.equal(f.c.followedSource(),null);await assert.rejects(f.c.align(),/disposed/);f.destroy();});
test('align advances existing native owners to the next actual paused instant without restarting GP playback',async()=>{const f=await fixture(),source={now:()=>0};await f.c.followAll(source);f.runtime.utc=codec.advance(utc,17);const receipt=await f.c.align();assert.equal(receipt.utc,f.runtime.utc);assert.equal(f.stored.snapshot().result.rows[0].utc,f.runtime.utc);assert.equal(f.catalog.snapshot().display.utc,f.runtime.utc);assert.equal(f.catalog.snapshot().playing,false);assert.equal(f.stored.snapshot().state.playing,false);assert.equal(f.c.followedSource(),source);f.destroy();});
test('catalog selection drift during query rejects late proof without overwriting the new GP',async()=>{const f=await fixture();f.delay();const work=f.c.followAll({now:()=>0});while(!f.calls.some(x=>x[0]==='catalog'))await new Promise(r=>setImmediate(r));f.catalog.select({...f.base,normalized_gp_sha256:'b'.repeat(64)});f.resolve();await assert.rejects(work,/changed/);assert.equal(f.catalog.snapshot().buffer,null);assert.equal(f.catalog.snapshot().selected.normalized_gp_sha256,'b'.repeat(64));assert.equal(f.c.followedSource(),null);f.destroy();});
test('wrong source release cannot detach active follow; native release failure never restarts playback',async()=>{const f=await fixture(),source={now:()=>0};await f.c.followAll(source);const count=f.calls.length;assert.equal(await f.c.releaseAll({now:()=>0}),false);assert.equal(f.calls.length,count);assert.equal(f.c.followedSource(),source);f.fail();await assert.rejects(f.c.releaseAll(source),/native/);assert.equal(f.c.followedSource(),null);assert.equal(f.stored.snapshot().state.playing,false);assert.equal(f.catalog.snapshot().playing,false);f.destroy();});
test('another window seeking the same stored GP while catalog waits cannot count as aligned',async()=>{const f=await fixture();f.delay();const work=f.c.followAll({now:()=>0});while(!f.calls.some(x=>x[0]==='catalog'))await new Promise(r=>setImmediate(r));const later=codec.advance(utc,60);await f.stored.seek(later);f.resolve();await assert.rejects(work,/cursor changed/);assert.equal(f.stored.snapshot().state.current_utc,later);assert.equal(f.c.followedSource(),null);f.destroy();});
test('disposal while native HTTP is pending prevents publication and further server commands',async()=>{const f=await fixture();f.delay();const work=f.c.followAll({now:()=>0});while(!f.calls.some(x=>x[0]==='catalog'))await new Promise(r=>setImmediate(r));const count=f.calls.length;f.c.destroy();f.resolve();await assert.rejects(work,/changed/);assert.equal(f.calls.length,count);assert.equal(f.c.followedSource(),null);f.destroy();});


test('explicit input invalidation detaches active follow without changing clocks or native owner values',async()=>{const f=await fixture();try{await f.c.followAll({now:()=>0});assert.equal(f.c.isFollowing(),true);const before=f.calls.length,stored=f.stored.snapshot(),catalog=f.catalog.snapshot();assert.equal(f.c.invalidate('station changed'),true);assert.equal(f.c.followedSource(),null);assert.equal(f.c.isFollowing(),false);assert.equal(f.calls.length,before);assert.deepEqual(f.stored.snapshot(),stored);assert.deepEqual(f.catalog.snapshot(),catalog);await assert.rejects(f.c.align(),/not engaged/);}finally{f.destroy();}});
test('invalidation during pending native follow keeps transport locked until rejected work drains',async()=>{const f=await fixture();try{f.delay();const work=f.c.followAll({now:()=>0});while(!f.calls.some(x=>x[0]==='catalog'))await new Promise(r=>setImmediate(r));assert.equal(f.c.isFollowing(),true);assert.equal(f.c.followedSource(),null);f.c.invalidate('observer changed');assert.equal(f.c.isFollowing(),true);f.resolve();await assert.rejects(work,/changed/);assert.equal(f.c.isFollowing(),false);assert.equal(f.c.followedSource(),null);}finally{f.destroy();}});

for(const kind of ['stored observer','catalog observer','catalog GP hash','foreign run'])test('external accepted '+kind+' detaches capability before next source transport',async()=>{const f=await fixture();try{let controls=0;const source={now:()=>0,play:()=>controls++};await f.c.followAll(source);if(kind==='stored observer')await f.stored.setGround({latitude_deg:1,longitude_deg:0,ellipsoid_height_m:0},5);if(kind==='catalog observer')f.catalog.observer({latitude_deg:1,longitude_deg:0,ellipsoid_height_m:0,virtual:true,ellipsoid:'WGS84'},5);if(kind==='catalog GP hash')f.catalog.select({...f.base,normalized_gp_sha256:'b'.repeat(64)});if(kind==='foreign run')f.runtime.run_id='other';const before=f.calls.length;const transport=createAnalysisTransport({follow:{source:f.c.followedSource,locked:f.c.isFollowing,pending:f.c.isPending,invalidate:f.c.invalidate},independent:{}});assert.equal(f.c.followedSource(),null);assert.equal(f.c.isFollowing(),false);await assert.rejects(transport.run('play'),/기존 분석/);assert.equal(controls,0);assert.equal(f.calls.length,before,'read fence causes no clock rollback/server commands');}finally{f.destroy();}});
