import {fixture} from './workspace_fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createCatalogueSceneTimeBinding} from '../../../user_application/web/scripts/catalogue_scene_time_binding.js';
import {createCatalogScene} from '../../../user_application/web/scripts/catalog_scene.js';
import {createOrbitSelection} from '../../../user_application/web/scripts/orbit_selection.js';
import {createWorkspacePlayback} from '../../../user_application/web/scripts/workspace_playback.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const codec=createUtcCodec(LEAP_SHA256),utc=codec.advance('2020-07-12T21:16:01Z',0),conditions={group:'active',query:'',orbit:'all'},H='a'.repeat(64);
const response=p=>({...conditions,version:1,status:'valid',client_request_id:p.client_request_id,utc:p.utc,source:'celestrak-cache',fetched_at:utc,warning:'',stale:false,scene_sha256:H,eop_sha256:'b'.repeat(64),leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC',eop_kind:'IERS_A',eop_quality:{ut1:'final_b',polar_motion:'final_b'},units:{position:'m',time:'UTC'},count:1,valid_count:1,error_count:0,rows:[{catalog_number:1,name:'one',orbit_regime:'LEO',normalized_gp_sha256:'c'.repeat(64),epoch_utc:utc,status:'valid',error_code:null,position_m:[7000000,1,2]}]});
const source=(kind='stored',time=utc,running=true)=>({kind,identity:kind+':scope1',running,context:{key:kind==='sim'?'sim:run1':kind==='catalog'?'catalog:1:'+H:'stored:input:'+H,utc:time,leap_sha256:LEAP_SHA256,eop_sha256:kind==='sim'?null:H,...(kind==='sim'?{source:'sim'}:{})}});
function setup(){let current=source(),ms=0,timer,fail=false;const calls=[];let binding;const scene=createCatalogScene({catalogScene:async p=>{calls.push(p);if(fail)throw Object.assign(Error('hash conflict'),{status:409});return response(p);}},v=>binding?.accept(v),()=>{}, {now:()=>ms,requestId:()=>String(calls.length+1),setTimer:fn=>(timer=fn,1),clearTimer:()=>{timer=null;}});scene.configure(conditions);binding=createCatalogueSceneTimeBinding({scene,readSource:()=>current,codec});return{scene,binding,calls,set:v=>{current=v;},advance:async time=>{ms=time;const fn=timer;timer=null;fn?.();await new Promise(r=>setImmediate(r));},fail:()=>{fail=true;}};}
test('actual stored selection and existing playback cursor drive station-free whole scene without a position buffer or command',async()=>{
 let ms=0,frame,driver,binding;const server={revision:1,input_id:'input',input_hash:H,current_utc:utc,playing:true,play_rate:1,leap_sha256:LEAP_SHA256};let writes=0,accepted=null;const client=createOrbitSelection({orbitInputs:async()=>({inputs:[{input_id:'input',raw_sha256:H,epoch_utc:utc}]}),orbitState:async()=>server,selectOrbit:async()=>{writes++;throw Error('unexpected command');},orbitSamples:async p=>({...p,revision:1,input_id:'input',input_hash:H,leap_sha256:LEAP_SHA256,status:'complete',stale:false,rows:[]})},s=>driver?.update(s),()=> 'stored',()=>ms);
 const f=setup();binding=f.binding;driver=createWorkspacePlayback(client,(s,row,time,error)=>{accepted=!error&&s.status==='ready'?{kind:'stored',identity:JSON.stringify([s.state.input_id,s.state.input_hash,s.state.revision,s.state.playing,s.state.play_rate]),running:s.state.playing,context:{key:`stored:${s.state.input_id}:${s.state.input_hash}`,utc:time,leap_sha256:s.state.leap_sha256,eop_sha256:null}}:null;f.set(accepted);binding.observe();},{now:()=>ms,requestFrame:fn=>(frame=fn,1),cancelFrame(){},setTimer:()=>1,clearTimer(){}});
 await client.load();await binding.enable(utc);assert.equal(f.calls[0].utc,utc);ms=1500;frame();await f.advance(1500);assert.equal(f.calls.at(-1).utc,codec.advance(utc,1.5));assert.equal(f.scene.snapshot().result.count,1);assert.equal(writes,0);driver.destroy();binding.destroy();client.destroy();f.scene.destroy();
});
test('registered full native snapshot retains analysis UTC during natural progress and paused exact UTC never borrows old positions',async()=>{const f=setup();await f.binding.enable(utc);const view=f.binding.presentation();assert.equal(view.snapshot.rows.length,1);assert.equal(view.analysis_utc,utc);assert.equal(Object.isFrozen(view.snapshot.rows[0].position_m),true);assert.equal(f.binding.verifyPresentation(structuredClone(view)),false);f.set(source('stored',codec.advance(utc,2)));assert.equal(f.binding.verifyPresentation(view),true);const next=f.binding.presentation();assert.equal(next.analysis_utc,utc);assert.equal(next.display_utc,codec.advance(utc,2));f.set(source('stored',codec.advance(utc,2),false));assert.equal(f.binding.verifyPresentation(view),false);f.set(source());assert.equal(f.binding.verifyPresentation(view),false);f.binding.destroy();f.scene.destroy();});
test('source/control replacement revokes permanently while fresh acceptance can establish a new scope',async()=>{const f=setup();await f.binding.enable(utc);const old=f.binding.presentation();const release=f.binding.beginControl();assert.equal(f.scene.snapshot().result,null);assert.equal(f.binding.verifyPresentation(old),false);f.set({...source(),identity:'new revision'});release();await new Promise(r=>setImmediate(r));assert.equal(f.calls.length,2);assert.equal(f.binding.verifyPresentation(f.binding.presentation()),true);assert.equal(f.binding.verifyPresentation(old),false);release();assert.equal(f.calls.length,2);f.binding.destroy();f.scene.destroy();});
test('no source uses the existing explicit draft once; OFF and terminal native conflict never automatically retry',async()=>{const f=setup();f.set(null);await f.binding.enable(utc);assert.equal(f.calls.length,1);assert.equal(f.binding.presentation(),null);f.binding.observe();assert.equal(f.calls.length,1);f.binding.disable();assert.equal(f.scene.snapshot().result,null);f.set(source());f.fail();await f.binding.enable(utc);assert.equal(f.calls.length,2);f.set(source('stored',codec.advance(utc,20)));f.binding.observe();await f.advance(3000);assert.equal(f.calls.length,2);f.binding.destroy();f.scene.destroy();});
test('SIM/catalog scopes retain full separate native scene provenance and source resolver rejects fake/old registrations',async()=>{for(const kind of ['sim','catalog']){const f=setup();f.set(source(kind));await f.binding.enable(utc);const v=f.binding.presentation();assert.equal(v.source_kind,kind);assert.equal(v.snapshot.eop_sha256,'b'.repeat(64));const context={key:`scene:${H}`,utc,leap_sha256:LEAP_SHA256};const control=f.binding.resolveSource(context);assert.equal(control.kind,kind);assert.equal(control.context.key,source(kind).context.key);assert.equal(f.binding.verifySource(control,{context}),true);assert.equal(f.binding.verifySource(structuredClone(control),{context}),false);f.set(null);assert.equal(f.binding.verifySource(control,{context}),false);f.set(source(kind));assert.equal(f.binding.verifySource(control,{context}),false);f.binding.destroy();f.scene.destroy();}});
test('late source getter reentry cannot publish a scope or revive a proof after disable',async()=>{let f,hook=false;f=setup();const previous=f.binding;previous.destroy();const b=createCatalogueSceneTimeBinding({scene:f.scene,codec,readSource:()=>{if(hook)b.disable();return source();}});hook=true;await b.enable(utc);assert.equal(f.calls.length,0);assert.equal(b.presentation(),null);b.destroy();f.scene.destroy();});

test('actual workspace ON uses accepted stored cursor even with no native row, station or selected catalogue; source error clears both scene views',async()=>{
 let server={revision:1,input_id:'input',input_hash:H,current_utc:utc,playing:false,play_rate:1,leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC',ground_point:null,minimum_elevation_deg:0},writes=0,offline=false;const ownerApi={orbitInputs:async()=>({inputs:[{input_id:'input',raw_sha256:H,epoch_utc:utc}]}),orbitState:async()=>{if(offline)throw Error('source unavailable');return structuredClone(server);},selectOrbit:async()=>{writes++;throw Error('no command');}};
 const f=fixture(1280,720,{hash:'#wall',orbitSelectionFactory:(_api,notify,_id,_now,onControl)=>createOrbitSelection(ownerApi,notify,()=> 'owner',()=>0,onControl)});
 try{await new Promise(r=>setImmediate(r));f.evaluate("catalogScene.configure({group:'active',query:'',orbit:'all'});globalThis.sceneCalls=[];");f.context.api.catalogScene=async p=>{f.context.sceneCalls.push(structuredClone(p));return response(p);};assert.equal(f.evaluate('catalogTimeline.snapshot().selected'),null);assert.equal(f.evaluate('globe.displayContext()'),null);f.context.setWorkspaceWallScope('toggle');await new Promise(r=>setImmediate(r));assert.equal(f.context.sceneCalls[0].utc,utc);assert.equal(f.evaluate('sceneTime.presentation().source_kind'),'stored');assert.equal(f.evaluate('sceneTime.presentation().snapshot.rows.length'),1);assert.equal(writes,0);
 server={...server,revision:2,current_utc:codec.advance(utc,5)};await f.evaluate('client.refresh()');await new Promise(r=>setImmediate(r));assert.equal(f.context.sceneCalls.at(-1).utc,server.current_utc);const old=f.evaluate('sceneTime.presentation()');offline=true;await f.evaluate('client.refresh()');assert.equal(f.evaluate('catalogScene.snapshot().result'),null);f.context.oldSceneProof=old;assert.equal(f.evaluate('sceneTime.verifyPresentation(oldSceneProof)'),false);assert.equal(writes,0);
 }finally{f.dispose();}
});

test('native response ignored after OFF/source change and source-less snapshot proof cannot become a fallback after revocation',async()=>{let finish,payload,current=source(),binding;const scene=createCatalogScene({catalogScene:p=>{payload=p;return new Promise(r=>finish=r);}},v=>binding?.accept(v),()=>{},{now:()=>0,requestId:()=> 'late'});scene.configure(conditions);binding=createCatalogueSceneTimeBinding({scene,readSource:()=>current,codec});const pending=binding.enable(utc);binding.disable();finish(response(payload));await pending;assert.equal(scene.snapshot().result,null);assert.equal(binding.presentation(),null);current=null;const next=binding.enable(utc);finish(response(payload));await next;const snapshot=scene.row(1);assert.equal(snapshot.catalog_number,1);assert.equal(binding.verifyUnboundSnapshot(response(payload)),false);binding.disable();binding.destroy();scene.destroy();});
test('source-less accepted ORIGINAL snapshot is visible only while source remains absent and failed proofs are irrevocable',async()=>{let current=null,original,binding;const scene=createCatalogScene({catalogScene:async p=>response(p)},v=>{if(v)original=v;binding?.accept(v);},()=>{},{now:()=>0,requestId:()=> 'unbound'});scene.configure(conditions);binding=createCatalogueSceneTimeBinding({scene,readSource:()=>current,codec});await binding.enable(utc);assert.equal(binding.verifyUnboundSnapshot(original),true);assert.equal(binding.verifyUnboundSnapshot(structuredClone(original)),false);current=source();assert.equal(binding.verifyUnboundSnapshot(original),false);current=null;assert.equal(binding.verifyUnboundSnapshot(original),false);binding.destroy();scene.destroy();});

test('time dock may show an accepted server cursor without promoting missing/error geometry into a clock control capability',()=>{const f=fixture();try{f.evaluate("globe.update(client.snapshot(),null,client.snapshot().state.current_utc);globalThis.cursorClock=readWorkspaceClock();");const value=structuredClone(f.context.cursorClock);assert.equal(value.utc,utc.replace('.000000000Z','.000416000Z'));assert.match(value.mode,/서버/);assert.equal(value.capabilities.play,false);assert.equal(value.capabilities.pause,false);assert.equal(value.capabilities.live,false);assert.equal(value.capabilities.step,false);assert.equal(value.capabilities.speed,false);}finally{f.dispose();}});

test('explicit catalogue follow with a foreign scene group cannot silently switch to the accepted stored cursor',()=>{const f=fixture();try{f.evaluate("catalogScene.configure({group:'active',query:'',orbit:'all'});const timelineBeforeGroup=catalogTimeline.snapshot;catalogTimeline.snapshot=()=>({...timelineBeforeGroup(),selected:{group:'foreign',catalog_number:1}});globalThis.foreignGroupSource=readCatalogueTimeSource();");assert.equal(f.context.foreignGroupSource,null);assert.equal(f.evaluate('client.snapshot().state.input_id'),'tle');}finally{f.dispose();}});

test('actual scene conflict callback clearing catalogue owner cannot erase terminal failure and automatically retry stored time',async()=>{const f=fixture(1280,720,{hash:'#wall'});let calls=0;try{f.evaluate("catalogScene.configure({group:'active',query:'',orbit:'all'});");f.context.api.catalogScene=async p=>{calls++;if(calls===1)throw Object.assign(Error('GP changed'),{status:409});return response(p);};f.context.setWorkspaceWallScope('toggle');await new Promise(r=>setImmediate(r));assert.equal(calls,1);f.evaluate('sceneTime.observe()');await new Promise(r=>setImmediate(r));assert.equal(calls,1);assert.equal(f.evaluate('catalogScene.snapshot().result'),null);}finally{f.dispose();}});

test('unrelated catalogue control preserves stored scene while nested catalogue controls revoke once and query only after outer settlement',async()=>{const f=setup();try{await f.binding.enable(utc);const stored=f.binding.presentation(),release=f.binding.beginControl('catalog');assert.equal(f.binding.verifyPresentation(stored),true);release();await new Promise(r=>setImmediate(r));assert.equal(f.calls.length,1);f.set(source('catalog'));f.binding.observe();await new Promise(r=>setImmediate(r));assert.equal(f.calls.length,2);const previous=f.binding.presentation(),outer=f.binding.beginControl('catalog'),inner=f.binding.beginControl('catalog');assert.equal(f.binding.verifyPresentation(previous),false);outer();await new Promise(r=>setImmediate(r));assert.equal(f.calls.length,2);inner();await new Promise(r=>setImmediate(r));assert.equal(f.calls.length,3);assert.equal(f.binding.verifyPresentation(f.binding.presentation()),true);}finally{f.binding.destroy();f.scene.destroy();}});
