import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './workspace_fixture.mjs';import {LEAP_SHA256,createUtcCodec} from '../../../user_application/web/scripts/orbit_utc.js';
const utc='2020-07-12T21:16:01.000416000Z',H='a'.repeat(64),codec=createUtcCodec(LEAP_SHA256),quality={ut1:'final_b',polar_motion:'final_b'};
for(const [w,h] of [[1280,720],[1920,1080]])test(`catalog observer/time real assembly uses preset and one globe without stored commands ${w}x${h}`,async()=>{
 let payload;const meta={name:'ISS',epoch_utc:utc,source:'celestrak-cache',normalized_gp_sha256:H,eop_sha256:H,leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC',eop_kind:'IERS_A',eop_quality:quality};
 const f=fixture(w,h,{hash:'#satellite',satelliteGroups:async()=>({items:[{id:'active',label:'Active'}]}),satellites:async p=>({...p,source:'celestrak-cache',items:[{NORAD_CAT_ID:25544,OBJECT_NAME:'ISS',MEAN_MOTION:15}],count:1,total:1,filtered_total:1}),satelliteProfile:async()=>({source:'gp-cache',catalog:{NORAD_CAT_ID:25544}}),catalogPosition:async p=>({...meta,...p,utc,version:1,status:'valid',position_m:[7e6,1,2]}),catalogSamples:async p=>(payload=p,{...meta,...p,version:1,status:'valid',communication_status:'unknown',units:{position:'m',range:'m',elevation:'deg',azimuth:'deg',time:'UTC'},rows:Array.from({length:p.count},(_,i)=>({utc:codec.advance(p.start_utc,i),position_m:[7e6+i,1,2],elevation_deg:10,range_m:1000+i,azimuth_deg:90,visible:10>=p.minimum_elevation_deg,eop_quality:quality,status:'valid',error_code:null}))})});
 try{for(let i=0;i<12;i++)await Promise.resolve();f.flush();const before=f.snapshot();await f.get('cat-sat-25544').dispatch('click');for(let i=0;i<12;i++)await Promise.resolve();f.flush();
  f.get('cat-time-height').value='123.45';await f.get('cat-time-height').dispatch('input');f.evaluate("location.hash='#ground'");await f.win.dispatch('hashchange');f.get('station-select').value='DAEJEON';await f.get('station-select').dispatch('change');await f.get('station-catalog-use').dispatch('click');f.evaluate("location.hash='#satellite'");await f.win.dispatch('hashchange');assert.equal(f.get('cat-time-station').value,'DAEJEON');assert.equal(f.get('cat-time-height').value,'123.45');
  await f.get('cat-time-calculate').dispatch('click');assert.equal(payload.ground_point.latitude_deg,36.3742);assert.equal(payload.ground_point.ellipsoid_height_m,123.45);assert.equal(payload.minimum_elevation_deg,5);assert.match(f.get('cat-time-result').innerHTML,/거리 km/);assert.equal(f.viewers.length,1);assert.equal(f.counts().commands,0);assert.deepEqual(f.snapshot(),before);
  await f.get('window-minimize').dispatch('click');await f.get('shelf-restore').dispatch('click');assert.equal(f.get('cat-time-height').value,'123.45');assert.match(f.get('cat-time-result').innerHTML,/실제 통신 미확인/);
  await f.get('cat-time-play').dispatch('click');assert.equal(f.frames.size>=1,true);await f.win.dispatch('pagehide',{persisted:false});assert.equal(f.frames.size,0);assert.equal(f.viewers[0].destroyCount,1);
 }finally{f.dispose();}
});
