import test from 'node:test';
import assert from 'node:assert/strict';
import {createCatalogTrack} from '../../../user_application/web/scripts/catalog_track.js';
import {LEAP_SHA256,createUtcCodec} from '../../../user_application/web/scripts/orbit_utc.js';
const codec=createUtcCodec(LEAP_SHA256),utc='2026-10-04T12:43:41.833920000Z';
const selected={group:'active',catalog_number:25544,normalized_gp_sha256:'a'.repeat(64),epoch_utc:utc,eop_sha256:'b'.repeat(64),leap_sha256:LEAP_SHA256,profile:'WGS72_AFSPC'};
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
function reply(p){const period=100,half=50,dense=45,offsets=new Set([-half,half,0]);for(let i=0;i<=120;i++){const t=-half+period*i/120;if(Math.abs(t)>dense)offsets.add(Math.round(t*1e9)/1e9);}for(let i=0;i<=900;i++)offsets.add(Math.round((-45+i*.1)*1e9)/1e9);const rows=[...offsets].sort((a,b)=>a-b).map(t=>({utc:codec.advance(p.utc,t),status:'valid',error_code:null,position_m:[7000000,t,3],eop_quality:{ut1:'predicted_a',polar_motion:'predicted_a'}}));return {...selected,version:1,status:'valid',client_request_id:p.client_request_id,reference_utc:p.utc,period_seconds:period,count:rows.length,valid_count:rows.length,error_count:0,rows,source:'celestrak-cache',frame:'ITRF',eop_kind:'IERS_A',units:{position:'m',time:'UTC',period:'s'}};}
test('track owns copies, compact metadata and splits failed rows without bridging',async()=>{const seen=[];let response;const c=createCatalogTrack({catalogTrack:async p=>{response=reply(p);response.rows[400]={...response.rows[400],status:'error',error_code:'decayed',position_m:null};response.status='partial';response.valid_count--;response.error_count++;return response;}},v=>seen.push(v));c.select(selected);await c.observe(utc);const out=seen.at(-1);assert.equal(out.segments.length,2);assert.equal(out.segments.flat().length,response.count-1);response.rows[0].position_m[0]=0;assert.equal(out.segments[0][0][0],7000000);assert.equal(c.snapshot().result.rows,undefined);assert.equal(c.snapshot().result.status,'partial');c.destroy();});
test('selection and disabled toggle abort and fence late track responses',async()=>{const d=deferred(),seen=[];let signal,p;const c=createCatalogTrack({catalogTrack:(v,o)=>(p=v,signal=o.signal,d.promise)},v=>seen.push(v));c.select(selected);const first=c.observe(utc);c.select({...selected,catalog_number:1});assert.equal(signal.aborted,true);d.resolve(reply(p));await first;assert.equal(seen.at(-1),null);assert.equal(c.snapshot().result,null);c.enabled(false);await c.observe(utc);assert.equal(c.snapshot().enabled,false);c.destroy();});
test('replay coalesces latest UTC with one pending, renews outside dense window',async()=>{const pending=[],calls=[];const c=createCatalogTrack({catalogTrack:p=>{calls.push(p);const d=deferred();pending.push(d);return d.promise;}});c.select(selected);const first=c.observe(utc);await c.observe(codec.advance(utc,50));await c.observe(codec.advance(utc,60));assert.equal(calls.length,1);pending[0].resolve(reply(calls[0]));await first;await Promise.resolve();assert.equal(calls.length,2);assert.equal(calls[1].utc,codec.advance(utc,60));pending[1].resolve(reply(calls[1]));await Promise.resolve();await Promise.resolve();await c.observe(codec.advance(utc,65));assert.equal(calls.length,2);c.destroy();});
test('malformed native responses clear geometry; GP409 disables renewal',async()=>{let mutate=v=>v,calls=0;const seen=[];const c=createCatalogTrack({catalogTrack:async p=>{calls++;return mutate(reply(p));}},v=>seen.push(v));c.select(selected);for(const change of [v=>v.rows[10].position_m[0]=NaN,v=>v.normalized_gp_sha256='d'.repeat(64),v=>v.rows[10].utc=v.rows[9].utc,v=>v.error_count++,v=>v.units.position='km']){mutate=v=>{change(v);return v;};await c.refresh(utc);assert.equal(c.snapshot().result,null);assert.match(c.snapshot().error,/応答|응답|표본/);assert.equal(seen.at(-1),null);}c.destroy();let conflicts=0;const conflict=createCatalogTrack({catalogTrack:async()=>{throw Object.assign(Error('GP changed'),{status:409});}},()=>{},()=>{},{onConflict:()=>conflicts++});conflict.select(selected);await conflict.observe(utc);assert.equal(conflicts,1);assert.equal(conflict.snapshot().enabled,false);conflict.destroy();});

test('failed automatic query waits for explicit refresh rather than retrying every replay update',async()=>{let calls=0;const c=createCatalogTrack({catalogTrack:async p=>{calls++;if(calls===1)throw Error('offline');return reply(p);}});c.select(selected);await c.observe(utc);await c.observe(codec.advance(utc,60));assert.equal(calls,1);await c.refresh(utc);assert.equal(calls,2);assert.equal(c.snapshot().error,'');assert.equal(c.snapshot().result.status,'valid');c.destroy();});

test('all failed native rows retain explicit error metadata and never produce a path; invalid UTC makes no request',async()=>{let calls=0;const shown=[];const c=createCatalogTrack({catalogTrack:async p=>{calls++;const v=reply(p);v.rows=v.rows.map(r=>({...r,status:'error',error_code:'decayed',position_m:null}));v.status='error';v.error_count=v.count;v.valid_count=0;return v;}},v=>shown.push(v));c.select(selected);await c.observe('invalid');assert.equal(calls,0);assert.equal(c.snapshot().result,null);await c.refresh(utc);assert.equal(calls,1);assert.deepEqual(shown.at(-1).segments,[]);assert.equal(c.snapshot().result.valid_count,0);assert.equal(c.snapshot().result.status,'error');c.destroy();});
