import test from 'node:test';
import assert from 'node:assert/strict';
import {createCatalogTimePanel} from '../../../user_application/web/scripts/tabs/catalog_time.js';
function fixture(){
 const fields=new Map(),calls=[];let source={running:false,speed:120,play:async()=>{calls.push('SIM-play');source.running=true;},pause:async()=>{calls.push('SIM-pause');source.running=false;},setSpeed:async n=>{calls.push(['SIM-speed',n]);source.speed=n;}};
 const element=()=>({isConnected:true,value:'',disabled:false,textContent:'',innerHTML:'',listeners:new Map(),addEventListener(k,fn){this.listeners.set(k,fn);},querySelector(id){if(!fields.has(id))fields.set(id,element());return fields.get(id);}});
 const document={createElement:element,getElementById:()=>({prepend(){}})},timeline={snapshot:()=>({selected:{normalized_gp_sha256:'hash',epoch_utc:'2026-10-07T00:00:00Z'},utc:'2026-10-07T00:00:00Z',rate:10,playing:false,buffer:{},pending:false}),play:()=>calls.push('GP-play'),pause:()=>calls.push('GP-pause'),rate:n=>calls.push(['GP-speed',n]),observer:()=>{calls.push('observer');return true;},invalidate:()=>calls.push('invalidate'),seek:()=>calls.push('GP-seek'),calculate:async()=>calls.push('calculate')};
 const original=globalThis.document;globalThis.document=document;const panel=createCatalogTimePanel(timeline,{site:{key:'site',name:'site',latitude:0,longitude:0,minElevationDeg:5}},{follow:{source:()=>source,locked:()=>source!==null,invalidate:reason=>{calls.push('detach');source=null;}}});panel.show('satellite');
 return {panel,calls,get:id=>fields.get('#cat-time-'+id),source:()=>source,destroy(){panel.destroy();globalThis.document=original;}};
}
test('catalog panel activefollow play/pause/rate delegate source and display its actual speed',async()=>{const f=fixture();try{assert.equal(f.get('rate').value,'120');await f.get('play').listeners.get('click')();await f.get('pause').listeners.get('click')();await f.get('rate').listeners.get('change')({target:{value:'20'}});assert.deepEqual(f.calls,['SIM-play','SIM-pause',['SIM-speed',20]]);assert.equal(f.get('rate').value,'20');assert.match(f.get('status').textContent,/SIM 따라가기/);f.panel.destroy();await f.get('play').listeners.get('click')();assert.equal(f.calls.length,3);}finally{f.destroy();}});
test('catalog station change detaches before observer mutation and unrelated external drafts preserve follow',()=>{const f=fixture();try{f.panel.applyDraft([{id:'unrelated',value:'value'}]);assert.deepEqual(f.calls,[]);assert.ok(f.source());assert.equal(f.panel.stage({key:'site',minElevationDeg:5}),true);assert.deepEqual(f.calls,['detach','observer']);assert.equal(f.source(),null);}finally{f.destroy();}});
