import test from 'node:test';import assert from 'node:assert/strict';
import {createCatalogPasses} from '../../../user_application/web/scripts/catalog_passes.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const codec=createUtcCodec(LEAP_SHA256),utc='2026-10-04T12:43:41.833920000Z';
const selected={group:'active',catalog_number:25544,normalized_gp_sha256:'a'.repeat(64),epoch_utc:utc,eop_sha256:'b'.repeat(64),leap_sha256:LEAP_SHA256,profile:'WGS72_AFSPC'};
const t={selected,utc,observer:{latitude_deg:36,longitude_deg:127,ellipsoid_height_m:10,virtual:true,ellipsoid:'WGS84'},minimumElevation:5};
const interval={start_utc:codec.advance(utc,60),end_utc:codec.advance(utc,120),peak_utc:codec.advance(utc,90),max_elevation_deg:25,start_clipped:false,end_clipped:false};
const reply=p=>({...selected,version:1,client_request_id:p.client_request_id,query_start_utc:p.query_start_utc,query_end_utc:p.query_end_utc,ground_point:p.ground_point,minimum_elevation_deg:p.minimum_elevation_deg,frame:'ITRF',eop_kind:'IERS_A',source:'celestrak-cache',communication_status:'unknown',units:{time:'UTC',elevation:'deg',duration:'s'},status:'complete',intervals:[{...interval}],contacts:[],errors:[]});
test('explicit next24h pins selectedGP/observer and AOS seeks catalog only',async()=>{let p,response;const seek=[];const c=createCatalogPasses({catalogVisibility:async v=>(p=v,response=reply(v))},()=>{},value=>seek.push(value));c.update(t);assert.equal(p,undefined);await c.query();assert.equal(codec.difference(p.query_end_utc,p.query_start_utc),86400);assert.deepEqual(p.ground_point,t.observer);assert.equal(c.snapshot().result.intervals.length,1);response.intervals[0].max_elevation_deg=0;assert.equal(c.snapshot().result.intervals[0].max_elevation_deg,25);assert.equal(c.seek(0),true);assert.deepEqual(seek,[interval.start_utc]);assert.equal(c.seek(99),false);c.destroy();});
test('observer/UTC/GP changes abort late responses and invalidate old intervals',async()=>{let resolve,p,signal;const c=createCatalogPasses({catalogVisibility:(v,o)=>(p=v,signal=o.signal,new Promise(r=>resolve=r))});c.update(t);const work=c.query();c.update({...t,observer:{...t.observer,ellipsoid_height_m:20}});assert.equal(signal.aborted,true);resolve(reply(p));await work;assert.equal(c.snapshot().result,null);assert.equal(c.snapshot().pending,false);c.destroy();});
test('strict response validation preserves partial/none/contact distinctions and rejects malformed data',async()=>{let mutate=v=>v;const c=createCatalogPasses({catalogVisibility:async p=>mutate(reply(p))});c.update(t);for(const change of [v=>v.normalized_gp_sha256='x',v=>v.intervals[0].peak_utc=v.query_end_utc,v=>v.intervals[0].max_elevation_deg=NaN,v=>v.units.elevation='rad',v=>v.communication_status='connected']){mutate=v=>{change(v);return v;};await c.query();assert.equal(c.snapshot().result,null);assert.match(c.snapshot().error,/응답|구간/);}mutate=v=>({...v,status:'partial',errors:[{utc:codec.advance(utc,300),error_code:'decayed'}]});await c.query();assert.equal(c.snapshot().result.status,'partial');mutate=v=>({...v,status:'none',intervals:[]});await c.query();assert.equal(c.snapshot().result.status,'none');mutate=v=>({...v,intervals:[],contacts:[{utc:codec.advance(utc,30),duration_seconds:0}]});await c.query();assert.equal(c.snapshot().result.contacts.length,1);c.destroy();});
test('unknown observer makes no request and destruction aborts pending',async()=>{let calls=0;const c=createCatalogPasses({catalogVisibility:async()=>{calls++;}});c.update({...t,observer:null});await c.query();assert.equal(calls,0);assert.match(c.snapshot().error,/관측/);c.destroy();});

test('partial failures with no known visible interval stay unknown, not none or malformed',async()=>{const c=createCatalogPasses({catalogVisibility:async p=>({...reply(p),status:'partial',intervals:[],errors:[{utc:codec.advance(utc,300),error_code:'decayed'}]})});c.update(t);await c.query();assert.equal(c.snapshot().result.status,'partial');assert.equal(c.snapshot().result.intervals.length,0);assert.equal(c.snapshot().error,'');c.destroy();});
