import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './workspace_fixture.mjs';import {LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const utc='2020-07-12T21:16:01.000416000Z';
const tick=async f=>{for(let i=0;i<12;i++)await Promise.resolve();f.flush();};
for(const [w,h]of [[1280,720],[1920,1080]])test(`whole scene real assembly explicit query/filter/draft/restore/sharedselection ${w}x${h}`,async()=>{
 const calls=[];const f=fixture(w,h,{hash:'#satellite',satelliteGroups:async()=>({items:[{id:'active',label:'전체'}]}),satellites:async p=>({...p,source:'celestrak-cache',items:[{NORAD_CAT_ID:25544,OBJECT_NAME:'ISS',MEAN_MOTION:15}],count:1,total:2,filtered_total:2,fetched_at:utc}),satelliteProfile:async number=>({source:'gp-cache',catalog:{NORAD_CAT_ID:number},gp:null}),catalogScene:async p=>(calls.push(p),{...p,version:1,status:'valid',source:'celestrak-cache',count:2,valid_count:2,error_count:0,scene_sha256:'a'.repeat(64),eop_sha256:'b'.repeat(64),leap_sha256:LEAP_SHA256,eop_kind:'IERS_A',eop_quality:{ut1:'final_b',polar_motion:'final_b'},frame:'ITRF',profile:'WGS72_AFSPC',units:{position:'m',time:'UTC'},rows:[25544,16633].map(number=>({catalog_number:number,name:`sat${number}`,status:'valid',error_code:null,normalized_gp_sha256:'c'.repeat(64),epoch_utc:utc,orbit_regime:'LEO',position_m:[7000000,number,0]}))}),catalogPosition:async p=>({...p,version:1,status:'valid',name:'offpage',source:'celestrak-cache',utc,epoch_utc:utc,normalized_gp_sha256:'c'.repeat(64),eop_sha256:'b'.repeat(64),leap_sha256:LEAP_SHA256,eop_kind:'IERS_A',eop_quality:{ut1:'final_b',polar_motion:'final_b'},frame:'ITRF',profile:'WGS72_AFSPC',position_m:[7000000,16633,0]})});
 try{await tick(f);assert.equal(calls.length,0);const before=f.snapshot();f.get('scene-utc').value=utc;await f.get('scene-utc').dispatch('input');await f.get('scene-load').dispatch('click');await tick(f);
  assert.equal(calls.length,1);assert.match(f.get('scene-status').textContent,/전체 2개/);assert.equal(f.viewers.length,1);assert.equal(f.get('stored-orbit-globe').dataset.catalogCount,'2');const catalogPoints=f.viewers[0].primitives.find(collection=>collection.items?.some(point=>point.id?.catalogNumber===25544));assert.ok(catalogPoints);assert.deepEqual(catalogPoints.items.map(point=>point.id.catalogNumber),[25544,16633]);
  await f.get('window-minimize').dispatch('click');await f.get('shelf-restore').dispatch('click');assert.equal(f.get('scene-utc').value,utc);assert.equal(calls.length,1);
  await f.get('window-minimize').dispatch('click');assert.equal(f.get('work-window').hidden,true);f.pickCatalog(16633);await tick(f);assert.equal(f.get('work-window').hidden,false);
  assert.match(f.get('cat-detail').innerHTML,/16633/);assert.match(f.get('orbit-globe-status').textContent,/선택 위성 UTC/);assert.deepEqual(f.snapshot(),before);assert.equal(f.counts().commands,0);
  f.context.applyWorkspaceDraft([{id:'scene-utc',value:'remote draft'},{id:'scene-follow',value:'false'}]);assert.equal(f.get('scene-utc').value,'remote draft');assert.equal(f.get('scene-follow').checked,false);assert.equal(calls.length,1);
  await f.get('scene-clear').dispatch('click');assert.equal(f.get('stored-orbit-globe').dataset.catalogCount,'0');assert.equal(f.viewers.length,1);await f.win.dispatch('pagehide',{persisted:false});
 }finally{f.dispose();}
});
