import test from 'node:test';
import assert from 'node:assert/strict';
import {createFabricExchange} from '../../../user_application/web/scripts/tabs/fabric_exchange.js';
const freeze=value=>{if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;};
function fixture(){
 const utc='2026-10-07T00:00:00.000000000Z';let live=utc,valid=true,exact=false,seq=0,mode='',release,endpoint={base:'',placement:'server',source:'server'};const calls=[],routes=[],registry=new WeakSet();
 const snapshot={status:'valid',utc,definition_hashes:Object.fromEntries(Array.from({length:240},(_,i)=>['N'+i,'b'.repeat(64)])),node_definitions:Array.from({length:240},(_,i)=>({id:'N'+i})),stations:[{id:'G'}],faults:[],network:{time:'2026-10-07T00:00:00.000Z',nodes:[...Array.from({length:240},(_,i)=>({id:'N'+i})),{id:'G'}],links:[{id:'N0|G',a:'N0',b:'G',kind:'ground'}]}};
 const token=freeze({kind:'NETWORK_RAW_ANALYSIS_V1',analysis_utc:utc,snapshot:structuredClone(snapshot)});registry.add(token);
 const client={endpoint:()=>structuredClone(endpoint),status:async()=>({exchange_contract:'guarded-v1',reachable:true,instance_id:'module',sequence:seq}),guardedUpdate:async(body,guard,options)=>{calls.push({body,guard,options});if(mode==='wait')await new Promise(r=>release=r);if(mode==='offline')throw Object.assign(Error('offline'),{unavailable:true});if(mode==='conflict')throw Object.assign(Error('conflict'),{conflict:true});seq=guard.expected_sequence+1;return {instance_id:'module',sequence:seq,request_id:guard.request_id,network_hash:'a'.repeat(64),links:[],nodes:[]};},guardedRoute:async(source,target,objective,guard)=>{routes.push(guard);return {instance_id:'module',sequence:guard.expected_sequence,network_hash:'a'.repeat(64),source,target,objective,status:'available',path:[source,target],hop_list:[{link_id:'N0|G',from:source,to:target,kind:'ground'}]};}};
 const network={networkSnapshot:()=>({...structuredClone(snapshot),utc:live}),verifyNetworkSnapshot:()=>exact,captureRawAnalysis:()=>token,verifyRawAnalysis:value=>valid&&registry.has(value)};
 const owner=createFabricExchange({client,network,clientId:'periodic'});
 return {owner,token,calls,routes,client,set live(value){live=value;},set exact(value){exact=value;},revoke(){valid=false;},mode:value=>mode=value,release:()=>release?.(),endpoint:value=>endpoint=value};
}
test('captured full240 native exchange survives natural movement, repeats fresh sequence and never promotes exact receipt',async()=>{const f=fixture();f.live='2026-10-07T00:00:02.000000000Z';const receipt=await f.owner.sendAnalytical(f.token);assert.equal(receipt.sequence,1);assert.equal(f.calls[0].body.nodes.length,241);assert.equal(f.calls[0].body.time,f.token.snapshot.network.time);assert.equal(f.owner.snapshot().receipt,null);const view=f.owner.analyticalPresentation();assert.equal(view.analysis_utc,f.token.analysis_utc);assert.equal(f.owner.verifyAnalyticalPresentation(view),true);assert.equal(f.owner.verifyAnalyticalPresentation(structuredClone(view)),false);await f.owner.sendAnalytical(f.token);assert.equal(f.calls[1].guard.expected_sequence,1);assert.notEqual(f.calls[0].guard.request_id,f.calls[1].guard.request_id);assert.equal(f.owner.verifyAnalyticalPresentation(view),false);f.owner.destroy();});
test('analytical selected route uses actual latest accepted guard and exact route stays unavailable',async()=>{const f=fixture();await f.owner.sendAnalytical(f.token);await f.owner.routeAnalytical('N0','G','balanced');assert.deepEqual(f.routes,[{instance_id:'module',expected_sequence:1}]);assert.equal(f.owner.analyticalPresentation().route.source,'N0');await assert.rejects(f.owner.route('N0','G'));f.owner.destroy();});
test('revoked raw proof/endpoint and ignored abort late result cannot publish analytical receipt',async()=>{for(const change of ['raw','endpoint','destroy']){const f=fixture();f.mode('wait');const work=f.owner.sendAnalytical(f.token);await new Promise(r=>setImmediate(r));if(change==='raw')f.revoke();if(change==='endpoint')f.endpoint({base:'http://foreign',placement:'remote',source:'settings'});if(change==='destroy')f.owner.destroy();f.release();await work;assert.equal(f.owner.analyticalPresentation(),null);f.owner.destroy();}});
test('automatic uncertain and conflict analytical request cannot allocate a replacement without explicit review',async()=>{for(const mode of ['offline','conflict']){const f=fixture();f.mode(mode);await f.owner.sendAnalytical(f.token);f.mode('');await f.owner.sendAnalytical(f.token);assert.equal(f.calls.length,1);assert.equal(f.owner.snapshot().refresh_required,true);f.owner.destroy();}});
test('exact and analytical commands share one lane; copied or sampled tokens never send',async()=>{const f=fixture();await f.owner.sendAnalytical(structuredClone(f.token));assert.equal(f.calls.length,0);f.mode('wait');const a=f.owner.sendAnalytical(f.token),b=f.owner.sendAnalytical(f.token);assert.equal(a,b);await new Promise(r=>setImmediate(r));const crossed=f.owner.send();f.release();await a;assert.equal(await crossed,null);assert.equal(f.calls.length,1);f.owner.destroy();});

test('analytical acceptance cannot satisfy an explicit exact send',async()=>{const f=fixture();await f.owner.sendAnalytical(f.token);assert.equal(await f.owner.send(),null);assert.equal(f.calls.length,1);f.owner.destroy();});
test('invalidated ignored-abort command retains the single lane until terminal',async()=>{const f=fixture();f.mode('wait');const pending=f.owner.sendAnalytical(f.token);await new Promise(r=>setImmediate(r));f.owner.invalidate();const next=f.owner.sendAnalytical(f.token);assert.equal(next,pending);assert.equal(f.calls.length,1);f.release();await pending;assert.equal(f.owner.analyticalPresentation(),null);f.owner.destroy();});

test('analytical entry never receives a pending exact command receipt or replaces its uncertain identity',async()=>{const f=fixture();f.exact=true;f.mode('wait');const work=f.owner.send();await new Promise(r=>setImmediate(r));assert.equal(await f.owner.sendAnalytical(f.token),null);f.release();await work;assert.equal(f.calls.length,1);f.owner.destroy();const g=fixture();g.exact=true;g.mode('offline');await g.owner.send();g.mode('');await g.owner.sendAnalytical(g.token);assert.equal(g.calls.length,1);assert.equal(g.owner.snapshot().refresh_required,true);g.owner.destroy();});
test('leaving after posted analytical request preserves uncertain review before any automatic reentry',async()=>{const f=fixture();f.mode('wait');const work=f.owner.sendAnalytical(f.token);await new Promise(r=>setImmediate(r));f.owner.invalidate();f.release();await work;assert.equal(f.owner.snapshot().refresh_required,true);f.mode('');await f.owner.sendAnalytical(f.token);assert.equal(f.calls.length,1);f.owner.destroy();});

test('analytical setup invalidation inside actual endpoint getter cannot start transport',async()=>{const f=fixture(),original=f.client.endpoint;let once=true;f.client.endpoint=()=>{if(once){once=false;f.owner.invalidate();}return original();};assert.equal(await f.owner.sendAnalytical(f.token),null);assert.equal(f.calls.length,0);assert.equal(f.owner.analyticalPresentation(),null);f.owner.destroy();});

test('explicit review refresh cannot return a captured analytical command receipt',async()=>{const f=fixture();f.mode('wait');const work=f.owner.sendAnalytical(f.token);await new Promise(r=>setImmediate(r));const review=f.owner.refresh();f.release();await work;assert.equal(await review,null);assert.equal(f.calls.length,1);f.owner.destroy();});

test('analytical presentation caches one full frozen native snapshot without command promotion or old registration revival',async()=>{const f=fixture();await f.owner.sendAnalytical(f.token);const view=f.owner.analyticalPresentation();assert.deepEqual(view.native_snapshot,f.token.snapshot);assert.equal(Object.isFrozen(view.native_snapshot.node_definitions[0]),true);assert.equal(f.owner.analyticalPresentation(),view);assert.equal(f.owner.snapshot().receipt,null);f.owner.invalidate();assert.equal(f.owner.verifyAnalyticalPresentation(view),false);assert.equal(f.owner.analyticalPresentation(),null);f.owner.destroy();});
