import test from 'node:test';import assert from 'node:assert/strict';
import {createFabricExchange} from '../../../user_application/web/scripts/tabs/fabric_exchange.js';
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){
 let sequence=0,instance='module',stage='',failure='',release,valid=true,endpoint={base:'',placement:'server',source:'server'},nextUtc=0;const registry=new WeakSet(),calls=[];
 const snapshot={status:'valid',utc:'2026-10-07T00:00:00.000000000Z',schema_version:1,node_definitions:Array.from({length:240},(_,i)=>({id:'N'+i,orbit:{altitude_km:550},updated_at:'source'})),definition_hashes:Object.fromEntries(Array.from({length:240},(_,i)=>['N'+i,'b'.repeat(64)])),stations:[{id:'G',latitude_deg:36}],faults:[],network:{time:'2026-10-07T00:00:00.000Z',nodes:[...Array.from({length:240},(_,i)=>({id:'N'+i})),{id:'G'}],links:[{id:'L',a:'N0',b:'G',kind:'ground'},{id:'L1',a:'N1',b:'G',kind:'ground'}]}};
 const token=(change={})=>{const snap=structuredClone(snapshot);Object.assign(snap,change);if(nextUtc++){snap.utc='2026-10-07T00:00:01.000000000Z';snap.network.time='2026-10-07T00:00:01.000Z';}const t=freeze({kind:'NETWORK_RAW_ANALYSIS_V1',analysis_utc:snap.utc,snapshot:snap});registry.add(t);return t;};
 const hold=async name=>{if(stage===name)await new Promise(r=>release=r);if(failure===name)throw Object.assign(Error(name+' failed'),{conflict:name==='conflict'});};
 const client={endpoint:()=>structuredClone(endpoint),status:async()=>{await hold('status');return{exchange_contract:'guarded-v1',reachable:true,instance_id:instance,sequence};},guardedUpdate:async(body,guard)=>{calls.push(guard);await hold('post');if(failure==='conflict')throw Object.assign(Error('conflict'),{conflict:true});return{instance_id:instance,sequence:++sequence,request_id:failure==='mismatch'?'wrong':guard.request_id,network_hash:'a'.repeat(64),nodes:[{id:'N0',stored_mb:12}],links:[{id:'L',usable:true,quality:85}]};},guardedRoute:async(source,target,objective,guard)=>{await hold('route');return{instance_id:instance,sequence:guard.expected_sequence,network_hash:'a'.repeat(64),source,target,objective,status:'available',path:[source,target],hop_list:[{link_id:source==='N1'?'L1':'L',from:source,to:target,kind:'ground'}]};}};
 const network={networkSnapshot:()=>null,verifyNetworkSnapshot:()=>false,captureRawAnalysis:()=>null,verifyRawAnalysis:t=>valid&&registry.has(t)};const owner=createFabricExchange({client,network,clientId:'retain'});
 return{owner,client,network,token,calls,hold:v=>stage=v,fail:v=>failure=v,release:()=>release?.(),revoke:()=>valid=false,restore:()=>valid=true,endpoint:v=>endpoint=v,instance:v=>instance=v};
}
for(const stage of ['status','post'])test(`full240 last registered historical report stays visible during same-scope ${stage}`,async()=>{
 const f=fixture();try{const token=f.token();await f.owner.sendAnalytical(token);const old=f.owner.analyticalPresentation();assert.equal(old.receipt.sequence,1);f.hold(stage);const work=f.owner.sendAnalytical(f.token());await tick();const view=f.owner.analyticalPresentation();assert.ok(view,'retain registered prior report');assert.equal(view.availability,'pending');assert.equal(view.receipt.sequence,1);assert.equal(view.analysis_utc,token.analysis_utc);assert.equal(view.native_snapshot.node_definitions.length,240);assert.equal(f.owner.verifyAnalyticalPresentation(view),true);assert.equal(f.owner.verifyAnalyticalPresentation(old),false);assert.equal(f.owner.snapshot().receipt,null);assert.equal(f.owner.snapshot().route,null);await assert.rejects(f.owner.route('N0','G'));assert.equal(await f.owner.send(),null); // explicit command clears visualization, never accepts historical receipt
 assert.equal(f.owner.analyticalPresentation(),null);f.release();await work;}finally{f.owner.destroy();}
});
test('same automatic pending replacement preserves old route and old endpoints only',async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());await f.owner.routeAnalytical('N0','G','balanced');const first=f.owner.analyticalPresentation();f.hold('route');const work=f.owner.routeAnalytical('N1','G','latency');await tick();const view=f.owner.analyticalPresentation();assert.ok(view);assert.equal(view.availability,'pending');assert.equal(view.route.source,'N0');assert.equal(view.route.objective,'balanced');assert.equal(view.route.sequence,view.receipt.sequence);assert.equal(f.owner.verifyAnalyticalPresentation(first),false);f.release();await work;const next=f.owner.analyticalPresentation();assert.equal(next.availability,'settled');assert.equal(next.route.source,'N1');assert.equal(f.owner.verifyAnalyticalPresentation(view),false);}finally{f.owner.destroy();}});
for(const field of ['node_definitions','definition_hashes','stations','faults'])test(`same UTC alone cannot retain changed full ${field}`,async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());f.hold('status');const changed={node_definitions:[{id:'different'}],definition_hashes:{N0:'c'.repeat(64)},stations:[{id:'G',latitude_deg:40}],faults:['fault']}[field];const work=f.owner.sendAnalytical(f.token({[field]:changed}));await tick();assert.equal(f.owner.analyticalPresentation(),null);f.release();await work;}finally{f.owner.destroy();}});
for(const reason of ['invalidate','raw','endpoint','destroy'])test(`pending ${reason} revokes historical registration without ABA revival`,async()=>{const f=fixture();await f.owner.sendAnalytical(f.token());f.hold('post');const work=f.owner.sendAnalytical(f.token());await tick();const view=f.owner.analyticalPresentation();assert.ok(view);if(reason==='invalidate')f.owner.invalidate();if(reason==='raw')f.revoke();if(reason==='endpoint')f.endpoint({base:'http://foreign',source:'settings',placement:'remote'});if(reason==='destroy')f.owner.destroy();assert.equal(f.owner.verifyAnalyticalPresentation(view),false);assert.equal(f.owner.analyticalPresentation(),null);if(reason==='raw')f.restore();if(reason==='endpoint')f.endpoint({base:'',placement:'server',source:'server'});assert.equal(f.owner.verifyAnalyticalPresentation(view),false);f.release();await work;f.owner.destroy();});
for(const failure of ['post','conflict','mismatch'])test(`terminal ${failure} clears retained historical report`,async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());f.hold('post');const work=f.owner.sendAnalytical(f.token());await tick();const view=f.owner.analyticalPresentation();assert.ok(view);f.fail(failure);f.release();await work;assert.equal(f.owner.analyticalPresentation(),null);assert.equal(f.owner.verifyAnalyticalPresentation(view),false);assert.equal(f.owner.snapshot().receipt,null);}finally{f.owner.destroy();}});
test('pending module replacement clears old receipt before posting new command',async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());f.hold('status');const work=f.owner.sendAnalytical(f.token());await tick();assert.ok(f.owner.analyticalPresentation());f.instance('new-module');f.hold('post');f.release();await tick();assert.equal(f.owner.analyticalPresentation(),null);f.release();await work;}finally{f.owner.destroy();}});
test('copied/refrozen pending projection has no registration and successful replacement revokes it',async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());f.hold('post');const work=f.owner.sendAnalytical(f.token());await tick();const view=f.owner.analyticalPresentation();assert.ok(view);assert.equal(f.owner.verifyAnalyticalPresentation(structuredClone(view)),false);assert.equal(f.owner.verifyAnalyticalPresentation(freeze(structuredClone(view))),false);f.release();await work;const next=f.owner.analyticalPresentation();assert.equal(next.availability,'settled');assert.equal(next.receipt.sequence,2);assert.equal(f.owner.verifyAnalyticalPresentation(view),false);}finally{f.owner.destroy();}});

for(const method of ['send','route','refresh'])test(`explicit ${method} clears historical view even while automatic work drains`,async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());f.hold('post');const work=f.owner.sendAnalytical(f.token());await tick();const view=f.owner.analyticalPresentation();assert.ok(view);const result=method==='route'?f.owner.route('N0','G'):f.owner[method]();await Promise.resolve(result).catch(()=>{});assert.equal(f.owner.analyticalPresentation(),null);assert.equal(f.owner.verifyAnalyticalPresentation(view),false);f.release();await work;assert.equal(f.owner.analyticalPresentation(),null);}finally{f.owner.destroy();}});
test('terminal owner invalidation from display proof callback cannot republish a prior view',async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());f.hold('status');const work=f.owner.sendAnalytical(f.token());await tick();const view=f.owner.analyticalPresentation();assert.ok(view);const verify=f.network.verifyRawAnalysis;let once=true;f.network.verifyRawAnalysis=t=>{if(once){once=false;f.owner.invalidate();}return verify(t);};assert.equal(f.owner.verifyAnalyticalPresentation(view),false);assert.equal(f.owner.analyticalPresentation(),null);f.release();await work;assert.equal(f.owner.analyticalPresentation(),null);}finally{f.owner.destroy();}});
test('status observation of foreign module irreversibly clears historical registration',async()=>{const f=fixture();try{await f.owner.sendAnalytical(f.token());const view=f.owner.analyticalPresentation();f.instance('other');await f.owner.pollStatus();assert.equal(f.owner.verifyAnalyticalPresentation(view),false);assert.equal(f.owner.analyticalPresentation(),null);f.instance('module');assert.equal(f.owner.verifyAnalyticalPresentation(view),false);}finally{f.owner.destroy();}});
