import assert from 'node:assert/strict';
import {createFuturePasses} from '../../../user_application/web/scripts/nodes/future_passes.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
let raw='';for await(const chunk of process.stdin)raw+=chunk;
const {query,bundle}=JSON.parse(raw),codec=createUtcCodec(LEAP_SHA256);
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
const site=query.sites[0],station={id:site.station_id,name:'HTTP native site',enabled:true,latitude:site.ground_point.latitude_deg,longitude:site.ground_point.longitude_deg,altitude_km:site.ground_point.ellipsoid_height_m/1000,min_elevation_deg:site.minimum_elevation_deg};
// Registered fixture only: proves HTTP/native->query owner, not actual accepted workspace deployment.
const input=freeze({presentation_kind:'FUTURE_PASS_INPUT_V1',analysis_utc:query.start_utc,nodes:structuredClone(query.nodes),station,deployment:{revision:1,run_id:'http-probe'}}),registered=new WeakSet([input]);
const display={utc:query.start_utc,key:'stored:http-probe',source:'stored',leap_sha256:LEAP_SHA256,eop_sha256:null};
async function run(response){let calls=0;const owner=createFuturePasses({api:{nodeMissionWindows:async(payload,options)=>{calls++;assert.deepEqual(payload,query);assert.deepEqual(Object.keys(options),['signal']);assert.ok(options.signal instanceof AbortSignal);return structuredClone(response);}},inputs:{captureFuturePassInputs:()=>input,verifyFuturePassInputs:v=>registered.has(v)},readDisplay:()=>display,codec,nextRequestId:()=>query.request_id});await owner.setActive(true);return {owner,calls};}
const good=await run(bundle);try{
 const view=good.owner.presentation();assert.equal(view.status,'valid',JSON.stringify(view));assert.equal(view.satellite_count,240);assert.equal(view.communication_status,'unknown');assert.equal(good.calls,1);assert.equal(good.owner.verifyPresentation(view),true);assert.equal(good.owner.verifyPresentation(structuredClone(view)),false);
 const rows=[];for(const node of query.nodes){const passes=bundle.contact_reports[0].geometry.passes.filter(r=>r.satellite===node.id).sort((a,b)=>codec.difference(a.start,b.start)).slice(0,3);for(const r of passes)rows.push({satellite:r.satellite,name:node.name||node.id,start:r.start,end:r.end,peak:r.peak,max_elevation_deg:r.max_elevation_deg,duration_seconds:codec.difference(r.end,r.start),in_progress:r.in_progress,truncated:r.truncated,live:codec.difference(display.utc,r.start)>=0&&codec.difference(r.end,display.utc)>=0});}rows.sort((a,b)=>codec.difference(a.start,b.start));assert.deepEqual(view.rows,rows.slice(0,12));assert.equal(view.rows.length,12);assert.equal(view.analysis_utc,query.start_utc);assert.equal(view.end_utc,query.end_utc);
}finally{good.owner.destroy();}
for(const kind of ['hidden_contact','eclipse','accepted']){const bad=structuredClone(bundle);if(kind==='hidden_contact'){const r=structuredClone(bad.contact_reports[0].geometry.passes[0]);r.id='malformed-hidden-last';r.satellite='foreign';bad.contact_reports[0].geometry.passes.push(r);}if(kind==='eclipse')bad.eclipse_report.coverage.resolution_seconds=1;if(kind==='accepted')bad.accepted_context={status:'verified_analysis_inputs'};const check=await run(bad);try{const view=check.owner.presentation();assert.equal(view.status,'error',kind);assert.deepEqual(view.rows,[]);}finally{check.owner.destroy();}}
process.stdout.write(JSON.stringify({status:'passed',full_nodes:query.nodes.length,raw_contacts:bundle.contact_reports[0].geometry.passes.length,display_rows:12,mutations_rejected:3,scope:'HTTP installed Rust native -> fixture-registered readonly future owner; not live workspace approval'}));
