import test from 'node:test';
import assert from 'node:assert/strict';
import {createFuturePasses} from '../../../user_application/web/scripts/nodes/future_passes.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
import {NODE_COMMUNICATION_METADATA as metadata} from '../../../user_application/web/scripts/nodes/node_timeline.js';
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
function fixture(count=240){
 const codec=createUtcCodec(LEAP_SHA256),start=codec.advance('2026-10-07T00:00:00Z',0),stations=[{id:'G',name:'Ground',enabled:true,latitude:37,longitude:127,altitude_km:.1,min_elevation_deg:10},{id:'H',name:'Other',enabled:true,latitude:0,longitude:0,min_elevation_deg:0}];
 const nodes=Array.from({length:count},(_,i)=>({id:'N'+i,name:'Node '+i,orbit:{altitude_km:550},equipment:[]}));
 let utc=start,epoch={},active=0,maxActive=0,hook=null,notify=null,displayHook=null,verifyHook=null,idHook=null;const registered=new WeakMap(),calls=[];
 const inputs={captureFuturePassInputs(id){const station=id===null?stations[0]:stations.find(s=>s.id===id&&s.enabled);if(!station)return null;const token=freeze(structuredClone({presentation_kind:'FUTURE_PASS_INPUT_V1',analysis_utc:utc,nodes,station,deployment:{revision:1,nodes}}));registered.set(token,epoch);return token;},verifyFuturePassInputs(token){verifyHook?.();return registered.get(token)===epoch;}};
 function bundle(q){const hashes=Object.fromEntries(nodes.map(n=>[n.id,'a'.repeat(64)])),coverage={start_utc:q.start_utc,end_utc:q.end_utc,resolution_seconds:30,peak_bracket_seconds:.1,boundary_bracket_seconds:1,short_intervals_may_be_missed:true};
  const passes=nodes.flatMap(n=>Array.from({length:4},(_,i)=>({id:n.id+':'+i,satellite:n.id,start:codec.advance(q.start_utc,i*60),end:codec.advance(q.start_utc,i*60+30),peak:codec.advance(q.start_utc,i*60+15),max_elevation_deg:45,in_progress:i===0,truncated:false})));
  return{schema_version:1,status:'sampled',communication_status:'unknown',request_id:q.request_id,node_definitions:structuredClone(q.nodes),definition_hashes:hashes,conditions:Object.fromEntries(['sites','target','external','max_external_range_km','start_utc','end_utc'].map(k=>[k,structuredClone(q[k])])),contact_reports:[{station_id:q.sites[0].station_id,geometry:{schema_version:1,status:'sampled',...metadata,definition_hashes:hashes,site:q.sites[0].ground_point,minimum_elevation_deg:q.sites[0].minimum_elevation_deg,coverage,passes}}],eclipse_report:{status:'sampled',...metadata,definition_hashes:hashes,coverage:{start_utc:q.start_utc,end_utc:q.end_utc,resolution_seconds:60,boundary_tolerance_seconds:1,short_intervals_may_be_missed:true},windows:[]},target_report:null,external_report:null};
 }
 const api={async nodeMissionWindows(q,options){calls.push({q:structuredClone(q),options});active++;maxActive=Math.max(maxActive,active);try{return hook?await hook(q,options):bundle(q);}finally{active--;}}};
 let ids=0;const owner=createFuturePasses({api,inputs,readDisplay:()=>{displayHook?.();return{utc,source:'catalog',key:'catalog:x',profile:'WGS72_AFSPC'};},codec,nextRequestId:()=>{idHook?.();return 'q'+(++ids);},onChange:()=>notify?.()});
 return{owner,codec,start,nodes,stations,calls,bundle,get maxActive(){return maxActive;},setUtc:v=>utc=v,revoke:()=>epoch={},query:fn=>hook=fn,onChange:fn=>notify=fn,display:fn=>displayHook=fn,verify:fn=>verifyHook=fn,requestId:fn=>idHook=fn};
}
const settle=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
test('headerless whole240 fixed3h bundle validates before stable pernode3 first12 and private current flags',async()=>{
 const f=fixture();await f.owner.setActive(true);await settle();const view=f.owner.presentation();
 assert.equal(f.calls.length,1);const {q,options}=f.calls[0];assert.equal(q.nodes.length,240);assert.equal(q.sites.length,1);assert.equal(f.codec.difference(q.end_utc,q.start_utc),10800);assert.equal('contextHash'in options,false);assert.equal(view.satellite_count,240);assert.equal(view.rows.length,12);assert.deepEqual(view.rows.map(r=>r.satellite),Array.from({length:12},(_,i)=>'N'+i));assert.equal(view.rows[0].duration_seconds,30);assert.equal(view.rows[0].live,true);assert.equal(view.communication_status,'unknown');assert.equal(Object.isFrozen(view.rows[0]),true);assert.equal(f.owner.verifyPresentation(view),true);assert.equal(f.owner.verifyPresentation(structuredClone(view)),false);assert.equal(f.owner.verifyPresentation(f.owner.snapshot()),false);f.owner.destroy();
});
test('strict60s forward/backward boundary refresh and inclusive live derive exact UTC',async()=>{
 const f=fixture(1);await f.owner.setActive(true);await settle();f.setUtc(f.codec.advance(f.start,30));let v=f.owner.presentation();assert.equal(v.rows[0].live,true);f.setUtc(f.codec.advance(f.start,30.000000001));v=f.owner.presentation();assert.equal(v.rows[0].live,false);f.setUtc(f.codec.advance(f.start,60));await f.owner.observe();assert.equal(f.calls.length,1);f.setUtc(f.codec.advance(f.start,60.001));await f.owner.observe();await settle();assert.equal(f.calls.length,2);f.setUtc(f.codec.advance(f.start,.001));await f.owner.observe();assert.equal(f.calls.length,2);f.setUtc(f.start);await f.owner.observe();await settle();assert.equal(f.calls.length,3);f.owner.destroy();
});
for(const kind of ['hidden-contact','eclipse','accepted','foreign-node','foreign-site'])test('rejects full bundle '+kind+' before display truncation',async()=>{
 const f=fixture();f.query(q=>{const b=f.bundle(q);if(kind==='hidden-contact')b.contact_reports[0].geometry.passes.at(-1).max_elevation_deg=NaN;if(kind==='eclipse')b.eclipse_report.windows=[{satellite:'foreign'}];if(kind==='accepted')b.accepted_context={status:'verified_analysis_inputs'};if(kind==='foreign-node')b.node_definitions.at(-1).name='changed';if(kind==='foreign-site')b.conditions.sites[0].station_id='foreign';return b;});await f.owner.setActive(true);await settle();assert.equal(f.owner.presentation().rows.length,0);assert.equal(f.owner.snapshot().status,'error');await f.owner.observe();assert.equal(f.calls.length,1);f.owner.destroy();
});
test('pending natural UTC coalesces latest serially and never starts parallel native query',async()=>{
 const f=fixture(1);await f.owner.setActive(true);await settle();let finish;f.query(q=>new Promise(r=>finish=()=>r(f.bundle(q))));f.setUtc(f.codec.advance(f.start,61));void f.owner.observe();await settle();f.setUtc(f.codec.advance(f.start,122));void f.owner.observe();f.setUtc(f.codec.advance(f.start,183));void f.owner.observe();assert.equal(f.calls.length,2);assert.equal(f.owner.presentation().availability,'pending');finish();await settle();assert.equal(f.calls.length,3);assert.equal(f.maxActive,1);assert.equal(f.calls[2].q.start_utc,f.codec.advance(f.start,183));finish();await settle();f.owner.destroy();
});
test('cancel/leave/disposal and ignored abort cannot resurrect or auto restart same UTC',async()=>{
 const f=fixture(1);let finish;f.query(q=>new Promise(r=>finish=()=>r(f.bundle(q))));void f.owner.setActive(true);await settle();f.owner.cancel();assert.equal(f.calls[0].options.signal.aborted,true);finish();await settle();await f.owner.observe();assert.equal(f.calls.length,1);assert.equal(f.owner.presentation().rows.length,0);void f.owner.refresh();await settle();assert.equal(f.calls.length,2);f.owner.setActive(false);finish();await settle();assert.equal(f.owner.presentation().rows.length,0);void f.owner.setActive(true);await settle();f.owner.destroy();finish();await settle();assert.equal(f.owner.verifyPresentation(f.owner.presentation()),false);
});
test('station changes, owner revocation and getter/onChange reentry cannot publish old proofs',async()=>{
 const f=fixture(1);await f.owner.setActive(true);await settle();const old=f.owner.presentation();await f.owner.selectStation('H');await settle();assert.equal(f.owner.presentation().station.id,'H');assert.equal(f.owner.verifyPresentation(old),false);f.revoke();assert.equal(f.owner.verifyPresentation(f.owner.presentation()),false);await f.owner.observe();await settle();let once=true;f.display(()=>{if(once){once=false;f.owner.cancel();}});assert.equal(f.owner.presentation().rows.length,0);f.display(null);f.onChange(()=>f.owner.setActive(false));await f.owner.refresh();await settle();assert.equal(f.owner.presentation().rows.length,0);f.owner.destroy();
});
test('same UTC fullscope revocation during first pending query queues a fresh token after retired native work',async()=>{
 const f=fixture(1);let finish;f.query(q=>new Promise(r=>finish=()=>r(f.bundle(q))));void f.owner.setActive(true);await settle();f.revoke();f.nodes[0].name='fresh';void f.owner.observe();assert.equal(f.calls.length,1);finish();await settle();assert.equal(f.calls.length,2);assert.equal(f.calls[1].q.nodes[0].name,'fresh');finish();await settle();assert.equal(f.owner.presentation().rows[0].name,'fresh');assert.equal(f.maxActive,1);f.owner.destroy();
});
test('request ID callback refresh cannot overwrite the newer job or its lane',async()=>{
 const f=fixture(1);let once=true;f.requestId(()=>{if(once){once=false;void f.owner.refresh();}});await f.owner.setActive(true);await settle();assert.equal(f.calls.length,1);assert.equal(f.owner.presentation().status,'valid');assert.equal(f.maxActive,1);f.owner.destroy();
});
test('abort listener reentry cannot restart cancelled same UTC; changing failed actual input can recover',async()=>{
 const f=fixture(1);let finish;f.query((q,{signal})=>{signal.addEventListener('abort',()=>void f.owner.refresh());return new Promise(r=>finish=()=>r(f.bundle(q)));});void f.owner.setActive(true);await settle();f.owner.cancel();finish();await settle();assert.equal(f.calls.length,1);assert.equal(f.owner.presentation().rows.length,0);
 f.query(()=>{throw Error('offline');});await f.owner.refresh();assert.equal(f.owner.snapshot().status,'error');const calls=f.calls.length;await f.owner.observe();assert.equal(f.calls.length,calls);f.revoke();f.nodes[0].name='new scope';f.query(q=>f.bundle(q));await f.owner.observe();await settle();assert.equal(f.calls.length,calls+1);assert.equal(f.owner.presentation().rows[0].name,'new scope');f.owner.destroy();
});
test('source pernode three excludes fourth only after complete validation and derives unused raw duration',async()=>{
 const f=fixture(2);f.query(q=>{const b=f.bundle(q);for(const row of b.contact_reports[0].geometry.passes)row.duration_seconds=-999;return b;});await f.owner.setActive(true);const view=f.owner.presentation();assert.equal(view.rows.length,6);assert.deepEqual(view.rows.map(r=>r.satellite),['N0','N1','N0','N1','N0','N1']);assert.ok(view.rows.every(r=>r.duration_seconds===30));f.owner.destroy();
});
test('notification throw fails closed without leaving a stranded lane or making a query from presentation',async()=>{
 const f=fixture(1);f.onChange(()=>{throw Error('panel failed');});await assert.doesNotReject(async()=>f.owner.setActive(true));await settle();assert.equal(f.owner.presentation().rows.length,0);const calls=f.calls.length;f.owner.presentation();f.owner.snapshot();assert.equal(f.calls.length,calls);f.onChange(null);await f.owner.refresh();assert.equal(f.owner.presentation().status,'valid');f.owner.destroy();
});
test('late rejected old input cannot publish a stale error after scope revocation',async()=>{
 const f=fixture(1);let reject;f.query(()=>new Promise((_,r)=>reject=r));void f.owner.setActive(true);await settle();f.revoke();reject(Error('old scope offline'));await settle();assert.equal(f.owner.snapshot().status,'unavailable');assert.doesNotMatch(f.owner.snapshot().error,/old scope/);f.owner.destroy();
});
test('failed natural UTC proof is irrevocable when same lease returns to the old UTC',async()=>{
 const f=fixture(1);await f.owner.setActive(true);const old=f.owner.presentation();f.setUtc(f.codec.advance(f.start,1));assert.equal(f.owner.verifyPresentation(old),false);f.setUtc(f.start);assert.equal(f.owner.verifyPresentation(old),false);const fresh=f.owner.presentation();assert.equal(f.owner.verifyPresentation(fresh),true);f.owner.destroy();
});
test('getter failure retires only failed registered view and reentrant refresh cannot revoke its new proof',async()=>{
 const f=fixture(1);await f.owner.setActive(true);const old=f.owner.presentation();f.display(()=>{throw Error('display unavailable');});assert.equal(f.owner.verifyPresentation(old),false);f.display(null);assert.equal(f.owner.verifyPresentation(old),false);const before=f.owner.presentation();let once=true;f.display(()=>{if(once){once=false;void f.owner.refresh();}});assert.equal(f.owner.verifyPresentation(before),false);f.display(null);await settle();const fresh=f.owner.presentation();assert.equal(f.owner.verifyPresentation(fresh),true);assert.equal(f.owner.verifyPresentation(before),false);assert.equal(f.owner.verifyPresentation(fresh),true);f.owner.destroy();
});
