import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
import {createGroundNetworkPanel} from '../../../user_application/web/scripts/tabs/ground_network.js';
import * as model from '../../../digital_twin/model_library/browser/ground_stations.js';
function setup(width=1920,height=1080,availability='settled'){const f=fixture(width,height,{hash:'#ground'}),store=f.evaluate('sourceGround');f.evaluate('groundNetworkPanel.destroy()');let valid=true,hook=null;const value=Object.freeze({presentation_kind:'FABRIC_ANALYTICAL_UI_V1',availability,analysis_utc:'2026-10-07T00:00:00.000000000Z',current_analysis:false,source:'captured_native_analysis',network:{nodes:[{id:'A'},{id:'B'}],links:[]},receipt:{instance_id:'M',sequence:3,summary:{stored_mb:9,delivered_mb:4,dropped_mb:0},nodes:[{id:'A',custody:'storing',stored_mb:9,capacity_mb:100,generation_mbps:2,next_hop:'B'}],links:[{id:'A|B',quality:97,usable:true}]},route:{status:'available',path:['A','B'],hop_list:[{link_id:'A|B',from:'A',to:'B',kind:'oisl',delay_ms:7,capacity_mbps:2000,quality:97}],total_delay_ms:7,bottleneck_mbps:2000,reliability:0.97}});const network={networkSnapshot:()=>({status:'unavailable',utc:'2026-10-07T00:00:02.000000000Z'}),verifyNetworkSnapshot:()=>false,clearNetwork(){}};const fabric={snapshot:()=>({status:'accepted',receipt:null,route:null,pending:false}),analyticalPresentation:()=>value,verifyAnalyticalPresentation:v=>{hook?.();return valid&&v===value;}};const panel=createGroundNetworkPanel({store,model,network,fabric,document:f.doc,host:f.win,refreshRuntime:async()=>{}});panel.show('ground');return{f,panel,value,set valid(v){valid=v;},set hook(v){hook=v;},dispose(){panel.destroy();f.dispose();}};}
for(const [w,h]of[[1920,1080],[2560,1440]])test(`captured native module receipt is labelled separately from exact approval ${w}x${h}`,()=>{const s=setup(w,h);try{assert.match(s.f.get('ground-node-fabric-analytical-status').textContent,/2026-10-07T00:00:00/);assert.match(s.f.get('ground-node-fabric-analytical-status').textContent,/過去|과거|분석/);const html=s.f.get('ground-node-fabric-analytical-results').innerHTML;assert.match(html,/9/);for(const value of ['100','2','A|B','97','2000','0.97'])assert.ok(html.includes(value),value+' complete original detail');assert.equal(s.f.get('ground-node-fabric-route').disabled,true);assert.equal(s.f.get('ground-node-fabric-send').disabled,true);assert.equal(s.f.counts().commands,0);const choice=s.panel.routeRequest();assert.ok(Object.isFrozen(choice));assert.deepEqual(choice,{source:'',target:'',objective:'balanced'});}finally{s.dispose();}});
test('revoked and reentrant analytical display cannot retain stale receipt or authorize route',()=>{const s=setup();try{s.valid=false;s.panel.update();assert.equal(s.f.get('ground-node-fabric-analytical-results').innerHTML,'');s.valid=true;let once=true;s.hook=()=>{if(once){once=false;s.panel.show('satellite');}};s.panel.update();assert.equal(s.f.get('ground-node-fabric-analytical-results').innerHTML,'');assert.equal(s.f.counts().commands,0);}finally{s.dispose();}});

for(const [w,h]of[[1920,1080],[2560,1440]])test(`retained historical pending report marks refresh without enabling commands ${w}x${h}`,()=>{const s=setup(w,h,'pending');try{assert.match(s.f.get('ground-node-fabric-analytical-status').textContent,/갱신 중/);assert.match(s.f.get('ground-node-fabric-analytical-status').textContent,/과거 분석 UTC 2026-10-07T00:00:00/);assert.match(s.f.get('ground-node-fabric-analytical-status').textContent,/응답 3/);assert.match(s.f.get('ground-node-fabric-analytical-status').textContent,/현재 UTC 통신 승인.*미확인/);assert.match(s.f.get('ground-node-fabric-analytical-results').innerHTML,/A\|B/);assert.equal(s.f.get('ground-node-fabric-send').disabled,true);assert.equal(s.f.get('ground-node-fabric-route').disabled,true);assert.equal(s.f.counts().commands,0);}finally{s.dispose();}});
