import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
import {createGroundNetworkPanel} from '../../../user_application/web/scripts/tabs/ground_network.js';
import * as model from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as diagram from '../../../digital_twin/visualization/network_diagram.js';
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
function setup(){const f=fixture(1920,1080,{hash:'#ground'}),store=f.evaluate('sourceGround');f.evaluate('groundNetworkPanel.destroy()');const stations=store.enabled,station=stations[0],state={valid:true,camera:true,verifyHook:null,canHook:null},calls=[];
 const view=freeze({presentation_kind:'NETWORK_SAMPLED_UI_V1',status:'valid',analysis_utc:'2026-10-07T00:00:00.000000000Z',display_utc:'2026-10-07T00:00:02.000000000Z',age_seconds:2,current_analysis:false,node_definitions:[{id:'A',name:'Satellite A',orbit:{}}],stations:structuredClone(stations),network:{nodes:[{id:'A',kind:'satellite'},...stations.map(s=>({...s,kind:'ground'}))],links:[]}});
 const network={networkSnapshot:()=>({status:'unavailable'}),verifyNetworkSnapshot:()=>false,networkSampledPresentation:()=>view,verifySampledNetworkPresentation:value=>{state.verifyHook?.();return state.valid&&value===view;},canFocusGroundNetworkStation:id=>{state.canHook?.();return state.valid&&state.camera&&stations.some(s=>s.id===id);},focusGroundNetworkStation:id=>{calls.push(['focus',id]);return true;},clearNetwork(){state.valid=false;}};
 const panel=createGroundNetworkPanel({store,model,network,fabric:{snapshot:()=>({status:'unavailable',receipt:null,route:null,pending:false}),route:async()=>calls.push('route'),send:async()=>calls.push('send')},diagram,document:f.doc,host:f.win,refreshRuntime:async()=>{}});panel.show('ground');
 const select=async id=>f.get('ground-node-diagram').dispatch('click',{target:{closest:()=>({getAttribute:key=>key==='data-diagram-node'?id:null})}});
 const button=action=>{const el=f.doc.getElementById('ground-node-detail-'+action);assert.ok(el,'station detail button exists');return el;};
 const click=async(action,target=button(action))=>f.get('ground-node-diagram-detail').dispatch('click',{target});
 return{f,store,station,stations,state,calls,panel,select,button,click,dispose(){panel.destroy();f.dispose();}};}
test('moving sampled station details use actual camera owner and existing editor without communication approval',async()=>{const s=setup();try{await s.select(s.station.id);assert.equal(s.button('focus').disabled,false);assert.equal(s.button('edit').disabled,false);await s.click('focus');assert.deepEqual(s.calls,[['focus',s.station.id]]);await s.click('edit');assert.equal(s.f.get('ground-node-name').value,s.station.name);assert.equal(s.f.get('ground-node-fabric-route').disabled,true);assert.equal(s.f.get('ground-node-fabric-send').disabled,true);assert.equal(s.f.doc.getElementById('ground-node-detail-route-target').disabled,true);}finally{s.dispose();}});
test('sampled station detail navigation preserves a different pending station editor',async()=>{const s=setup();try{await s.select(s.station.id);await s.click('edit');assert.ok(s.f.doc.getElementById('ground-node-name'),'actual station editor opened');s.f.get('ground-node-name').value='unsaved first station';await s.select(s.stations[1].id);await s.click('edit');assert.equal(s.f.get('ground-node-name').value,'unsaved first station');assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
for(const kind of ['revoked','hide','dispose','old-paint','verify-reentry','camera-reentry'])test('sampled station focus/edit cannot bypass '+kind,async()=>{const s=setup();try{await s.select(s.station.id);const focus=s.button('focus'),edit=s.button('edit');if(kind==='revoked')s.state.valid=false;if(kind==='hide')s.panel.show('satellite');if(kind==='dispose')s.panel.destroy();if(kind==='old-paint')await s.select(s.stations[1].id);if(kind==='verify-reentry')s.state.verifyHook=()=>{s.state.verifyHook=null;s.panel.show('satellite');};if(kind==='camera-reentry')s.state.canHook=()=>{s.state.canHook=null;s.panel.show('satellite');};await s.click('focus',focus);await s.click('edit',edit);assert.deepEqual(s.calls,[]);assert.equal(s.f.doc.getElementById('ground-node-name'),null);}finally{s.dispose();}});
