import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
import {createGroundNetworkPanel} from '../../../user_application/web/scripts/tabs/ground_network.js';
import * as model from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as pure from '../../../digital_twin/visualization/network_diagram.js';
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
function setup(width=1920,height=1080,historical=true){const f=fixture(width,height,{hash:'#ground'});f.evaluate('groundNetworkPanel.destroy()');const stations=[{...model.createStation({preset:'daejeon'}),id:'G'}];const nodes=Array.from({length:240},(_,i)=>({id:'N'+i,name:'Node '+i,orbit:{raan:Math.floor(i/40)*60},formation:{id:'F',plane:Math.floor(i/40),index:i%40}}));
 const native=freeze({status:'valid',faults:[],definition_hashes:Object.fromEntries(nodes.map(n=>[n.id,'a'.repeat(64)])),schema_version:1,utc:'2026-10-07T00:00:00.000000000Z',node_definitions:nodes,stations,network:{nodes:[...nodes.map(n=>({...n,kind:'satellite'})),...stations.map(n=>({...n,kind:'ground'}))],links:[{id:'O',a:'N0',b:'N1',kind:'oisl'},{id:'G',a:'N1',b:'G',kind:'ground'},{id:'old',a:'N2',b:'G',kind:'ground'}]}});
 const view=freeze({...native,analysis_utc:native.utc,display_utc:native.utc,age_seconds:0,availability:'sampled',network:{...native.network,links:[...native.network.links.slice(0,2),{id:'new',a:'N3',b:'G',kind:'ground'}]}});
 const fabricView=freeze({presentation_kind:'FABRIC_ANALYTICAL_UI_V1',native_snapshot:native,analysis_utc:native.utc,availability:'pending',receipt:{instance_id:'M',sequence:1,elapsed_s:7,summary:{stored_mb:12},nodes:[{id:'N0',kind:'satellite',custody:'storing',stored_mb:12}],links:[{id:'O',quality:88,usable:true},{id:'G',quality:77,usable:true},{id:'old',quality:66,usable:true}]},route:{status:'available',path:['N0','N1','G'],hop_list:[{link_id:'O'},{link_id:'G'}]}});
 const projection=freeze({presentation_kind:'MIXED_ROUTE_ANALYTICAL_UI_V1',fabric_view:fabricView,native_snapshot:native,node_definitions:nodes,routed_ids:['O','G','old'],analysis_utc:native.utc,display_utc:view.display_utc,age_seconds:2.5,source:'captured_native_analysis',availability:'accepted'});
 const state={valid:true,projection,fabricView,view,hook:null,verifyHook:null,sceneHook:null},calls=[],registered=new WeakSet([projection]);const store={ready:true,stations,enabled:stations,selectedId:'G',persistence:'memory_only',error:'',availablePresets:()=>[],find:id=>stations.find(n=>n.id===id),subscribe:()=>()=>{}};
 const network={networkSnapshot:()=>structuredClone(state.view),verifyNetworkSnapshot:()=>state.valid,readAnalyticalRoute:()=>state.projection,verifyAnalyticalRoute:(value,{utc,nodes:definitions})=>{state.verifyHook?.();return state.valid&&value===state.projection&&registered.has(value)&&utc===state.view.display_utc&&JSON.stringify(definitions)===JSON.stringify(state.view.node_definitions);},clearNetwork(){state.valid=false;}};
 const fabric={snapshot:()=>({status:'unavailable',receipt:null,route:null,pending:false}),analyticalPresentation:()=>historical?state.fabricView:null,verifyAnalyticalPresentation:value=>state.valid&&value===state.fabricView,route:async()=>calls.push('route'),send:async()=>calls.push('send')};
 const diagram={...pure,diagramMarkup(...args){state.hook?.();return pure.diagramMarkup(...args);}};
 const scene={setSnapshot(){},setActive(){},clear(){},setGroundLinksVisible(){},setCoverageVisible(){state.sceneHook?.();}};
 const panel=createGroundNetworkPanel({store,model,network,fabric,diagram,networkScene:scene,document:f.doc,host:f.win,refreshRuntime:async()=>{}});
 const select=async(id,type='link')=>f.get('ground-node-diagram').dispatch('click',{target:{closest:()=>({getAttribute:key=>key==='data-diagram-'+type?id:null})}});
 return {f,panel,state,registered,projection,fabricView,view,native,calls,select,dispose(){panel.destroy();f.dispose();}};}

for(const [w,h]of[[1280,720],[1920,1080]])test(`paused exact native diagram without receipt preserves unknown geometry ${w}x${h}`,async()=>{const s=setup(w,h,false);try{s.panel.show('ground');const svg=s.f.get('ground-node-diagram').innerHTML;assert.ok(svg.includes('data-diagram-link="O"'),'current native OISL is inspectable');assert.ok(svg.includes('data-diagram-link="G"'),'native ground contact uses original ground tag');assert.doesNotMatch(svg,/88%|routed|12 MB/);assert.match(s.f.get('ground-node-diagram-status').textContent,/품질.*미확인/);assert.equal(s.f.get('ground-node-fabric-route').disabled,true);assert.deepEqual(s.calls,[]);assert.equal(s.view.network.links.length,3);}finally{s.dispose();}});
test('paused exact registered historical report uses same full scope and pending marker',async()=>{const s=setup();try{s.panel.show('ground');const svg=s.f.get('ground-node-diagram').innerHTML;assert.match(svg,/88%/);assert.match(svg,/12 MB/);assert.match(s.f.get('ground-node-diagram-status').textContent,/갱신 중/);assert.equal(s.f.get('ground-node-fabric-route').disabled,true);assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
for(const field of ['definition_hashes','stations','faults'])test('paused historical fullscope mismatch falls back to unknown '+field,()=>{const s=setup();try{const changed=structuredClone(s.view);changed[field]=field==='definition_hashes'?{N0:'b'.repeat(64)}:field==='stations'?[{...changed.stations[0],latitude:10}]:['fault'];s.state.view=freeze(changed);s.panel.show('ground');const svg=s.f.get('ground-node-diagram').innerHTML;assert.doesNotMatch(svg,/88%|routed|12 MB/);assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
test('paused native no_radio excluded from SVG input but complete envelope retained',()=>{const s=setup(1920,1080,false);try{const changed=structuredClone(s.view);changed.network.links[1].state='no_radio';s.state.view=freeze(changed);s.panel.show('ground');assert.doesNotMatch(s.f.get('ground-node-diagram').innerHTML,/data-diagram-link="G"/);assert.match(s.f.get('ground-node-diagram').innerHTML,/data-diagram-link="O"/);assert.equal(s.state.view.network.links.length,3);}finally{s.dispose();}});
for(const cause of ['revoked','hide','dispose','callback'])test('paused native frame invalidates geometry on '+cause,()=>{const s=setup();try{s.panel.show('ground');if(cause==='revoked')s.state.valid=false;if(cause==='hide')s.panel.show('satellite');if(cause==='dispose')s.panel.destroy();if(cause==='callback')s.state.hook=()=>{s.state.hook=null;s.state.valid=false;};s.panel.update();assert.doesNotMatch(s.f.get('ground-node-diagram').innerHTML,/88%|routed|12 MB/);}finally{s.dispose();}});

for(const cause of ['copied','cross-pair','endpoints','metadata','missinglink','scene'])test('paused historical projection rejects '+cause,()=>{const s=setup();try{if(cause==='copied')s.state.projection=freeze(structuredClone(s.projection));if(cause==='cross-pair')s.state.fabricView=freeze(structuredClone(s.fabricView));if(cause==='endpoints'){const v=structuredClone(s.state.view);v.network.links[0].b='N9';s.state.view=freeze(v);}if(cause==='metadata'){const v=structuredClone(s.state.view);v.schema_version=2;s.state.view=freeze(v);}if(cause==='missinglink'){const v=structuredClone(s.state.view);v.network.links=v.network.links.filter(l=>l.id!=='O');s.state.view=freeze(v);}if(cause==='scene')s.state.sceneHook=()=>{s.state.valid=false;};s.panel.show('ground');const svg=s.f.get('ground-node-diagram').innerHTML;if(cause==='endpoints'||cause==='missinglink'){assert.doesNotMatch(svg,/88%/);assert.doesNotMatch(svg,/data-diagram-link="O"/);}else assert.doesNotMatch(svg,/88%|routed|12 MB/);assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
test('nested fresh paused paint survives obsolete native diagram callback',()=>{const s=setup();try{s.panel.show('ground');const newerFabric=freeze({...s.fabricView,receipt:{...s.fabricView.receipt,nodes:[{id:'N0',custody:'full',stored_mb:33}],links:s.fabricView.receipt.links.map(l=>({...l,quality:99}))}}),newer=freeze({...s.projection,fabric_view:newerFabric});s.registered.add(newer);s.state.hook=()=>{s.state.hook=null;s.state.projection=newer;s.state.fabricView=newerFabric;s.panel.update();};s.panel.update();assert.match(s.f.get('ground-node-diagram').innerHTML,/99%/);assert.match(s.f.get('ground-node-diagram').innerHTML,/33 MB/);}finally{s.dispose();}});
