import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
import {createGroundNetworkPanel} from '../../../user_application/web/scripts/tabs/ground_network.js';
import * as model from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as diagram from '../../../digital_twin/visualization/network_diagram.js';
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
function setup(sampled=false,width=1920,height=1080,historical=false){const f=fixture(width,height,{hash:'#ground'}),store=f.evaluate('sourceGround');f.evaluate('groundNetworkPanel.destroy()');const station=store.enabled[0],calls=[],state={valid:true,readHook:null,verifyHook:null};
 const link={id:'AG',a:'A',b:station.id,kind:'ground',band:'X',frequency_ghz:8.2,range_km:432.4,eirp_dbw:20,gt_dbk:18,data_rate_mbps:40};const native={status:'valid',utc:'2026-10-07T00:00:00.000000000Z',node_definitions:[{id:'A',name:'Satellite A',orbit:{}}],stations:store.enabled,network:{nodes:[{id:'A',kind:'satellite'},...store.enabled.map(s=>({...s,kind:'ground'}))],links:[link]}};
 const view=freeze({...structuredClone(native),presentation_kind:'NETWORK_SAMPLED_UI_V1',analysis_utc:native.utc,display_utc:'2026-10-07T00:00:02.500000000Z',age_seconds:2.5});
 const network={networkSnapshot:()=>{state.readHook?.();return sampled?{status:'unavailable'}:structuredClone(native);},verifyNetworkSnapshot:()=>{state.verifyHook?.();return state.valid;},clearNetwork(){state.valid=false;}};
 if(sampled){network.networkSampledPresentation=()=>{state.readHook?.();return view;};network.verifySampledNetworkPresentation=value=>{state.verifyHook?.();return state.valid&&value===view;};}
 const moduleReceipt={sequence:1,nodes:[],links:[{id:'AG',quality:88,usable:true,range_km:9999,frequency_ghz:99}]};
 const fabric={snapshot:()=>({status:'accepted',pending:false,receipt:moduleReceipt,route:null})};
 if(historical){const captured=freeze(structuredClone(native)),fabricView=freeze({presentation_kind:'FABRIC_ANALYTICAL_UI_V1',native_snapshot:captured,analysis_utc:native.utc,receipt:moduleReceipt,route:null}),projection=freeze({presentation_kind:'MIXED_ROUTE_ANALYTICAL_UI_V1',fabric_view:fabricView,native_snapshot:captured,node_definitions:view.node_definitions,routed_ids:[],analysis_utc:native.utc,display_utc:view.display_utc,age_seconds:2.5,source:'captured_native_analysis',availability:'accepted'});network.readAnalyticalRoute=()=>projection;network.verifyAnalyticalRoute=(value,{utc,nodes})=>state.valid&&value===projection&&utc===view.display_utc&&JSON.stringify(nodes)===JSON.stringify(view.node_definitions);fabric.analyticalPresentation=()=>fabricView;fabric.verifyAnalyticalPresentation=value=>state.valid&&value===fabricView;}
 const panel=createGroundNetworkPanel({store,model,network,fabric,diagram,document:f.doc,host:f.win,refreshRuntime:async()=>{},onRfLinkDraft:(value,context)=>{calls.push({value,context});assert.equal(context.isCurrent(),true);return true;}});panel.show('ground');
 const select=async()=>f.get('ground-node-diagram').dispatch('click',{target:{closest:()=>({getAttribute:key=>key==='data-diagram-link'?'AG':null})}});
 const button=()=>{const value=f.doc.getElementById('ground-node-detail-rf-draft');assert.ok(value,'ground-link explicit RF draft button exists');return value;};const click=async value=>f.get('ground-node-diagram-detail').dispatch('click',{target:value??button()});
 return{f,store,station,link,native,view,panel,state,calls,select,button,click,dispose(){panel.destroy();f.dispose();}};}
for(const [sampled,width,height]of [[false,1920,1080],[true,2560,1440]])test(`explicit source RF transfer copies native inputs and their analysis UTC sampled=${sampled} ${width}x${height}`,async()=>{const s=setup(sampled,width,height);try{await s.select();assert.equal(s.calls.length,0);await s.click();assert.equal(s.calls.length,1);assert.deepEqual(s.calls[0].value,s.link);assert.equal(s.calls[0].context.source,'native_geometry');assert.equal(s.calls[0].context.analysis_utc,s.native.utc);assert.equal(s.calls[0].context.display_utc,sampled?s.view.display_utc:s.native.utc);s.calls[0].value.range_km=1;assert.equal(s.link.range_km,432.4);assert.equal(s.f.counts().commands,0);}finally{s.dispose();}});
for(const kind of ['revoked','hide','dispose','repaint','read-reentry','verify-reentry','endpoint-change'])test('RF detail transfer refuses '+kind,async()=>{const s=setup();try{await s.select();const old=s.button();if(kind==='revoked')s.state.valid=false;if(kind==='hide')s.panel.show('satellite');if(kind==='dispose')s.panel.destroy();if(kind==='repaint')s.panel.update();if(kind==='read-reentry')s.state.readHook=()=>{s.state.readHook=null;s.panel.show('satellite');};if(kind==='verify-reentry')s.state.verifyHook=()=>{s.state.verifyHook=null;s.panel.show('satellite');};if(kind==='endpoint-change')s.link.b='foreign';await s.click(old);assert.equal(s.calls.length,0);}finally{s.dispose();}});
test('readonly transfer fence cannot revive once scope is revoked and preserves unrelated station draft',async()=>{const s=setup(true);try{await s.select();s.store.select(s.station.id);await s.f.get('ground-node-edit').dispatch('click');s.f.get('ground-node-name').value='unsaved';await s.click();assert.equal(s.f.get('ground-node-name').value,'unsaved');const guard=s.calls[0].context.isCurrent;s.state.valid=false;assert.equal(guard(),false);s.state.valid=true;assert.equal(guard(),false);assert.equal(s.calls.length,1);}finally{s.dispose();}});

test('registered historical module detail transfers only copied native geometry to RF draft',async()=>{const s=setup(true,1920,1080,true);try{await s.select();assert.match(s.f.get('ground-node-diagram-detail').innerHTML,/captured_module/);assert.match(s.f.get('ground-node-diagram-detail').innerHTML,/9999/);await s.click();assert.equal(s.calls.length,1);assert.equal(s.calls[0].value.range_km,432.4);assert.equal(s.calls[0].value.frequency_ghz,8.2);assert.equal(s.calls[0].context.analysis_utc,s.native.utc);assert.equal(s.calls[0].context.display_utc,s.view.display_utc);assert.equal(s.f.counts().commands,0);}finally{s.dispose();}});
test('non-ground link never creates the ground RF draft shortcut',async()=>{const s=setup();try{s.link.kind='oisl';await s.select();assert.equal(s.f.doc.getElementById('ground-node-detail-rf-draft'),null);assert.equal(s.calls.length,0);}finally{s.dispose();}});
