import test from 'node:test';
import assert from 'node:assert/strict';
import {createGroundVisibility,visibilityMarkup} from '../../../user_application/web/scripts/tabs/ground_visibility.js';
const ground={latitude_deg:33.4996,longitude_deg:126.5312,ellipsoid_height_m:0,virtual:true,ellipsoid:'WGS84'};
const state={revision:1,input_id:'tle',input_hash:'hash',eop_sha256:'eop',leap_sha256:'leap',frame:'ITRF',profile:'WGS72_AFSPC',ground_point:ground,minimum_elevation_deg:10};
const response=p=>({...p,revision:p.selection_revision,input_hash:'hash',eop_sha256:'eop',leap_sha256:'leap',frame:'ITRF',profile:'WGS72_AFSPC',stale:false,status:'none',intervals:[],contacts:[],errors:[],query_start_utc:p.start_utc,query_end_utc:p.end_utc,communication_status:'unknown'});
function fixture(call=p=>Promise.resolve(response(p))){let current=structuredClone(state);const client={snapshot:()=>({state:current,status:'ready'})};const api={orbitVisibility:call};return {controller:createGroundVisibility(client,api,()=>{},()=> 'query'),change:()=>{current={...current,revision:2};},client};}
test('visibility uses selected ground/revision without changing UTC or sample buffer',async()=>{let body;const {controller}=fixture(p=>{body=p;return Promise.resolve(response(p));});await controller.query('2020-07-12T21:16:01Z','2020-07-12T21:17:01Z');assert.deepEqual(body.ground_point,ground);assert.equal(body.selection_revision,1);assert.equal(controller.snapshot().result.status,'none');});
test('late response after selection changes is discarded even if abort is ignored',async()=>{let release;const {controller,change}=fixture(p=>new Promise(r=>{release=()=>r(response(p));}));const pending=controller.query('start','end');change();controller.update();release();await pending;assert.equal(controller.snapshot().result,null);assert.equal(controller.snapshot().status,'idle');});
test('every result context field gates visibility display',async()=>{for(const field of ['revision','input_id','input_hash','eop_sha256','leap_sha256','frame','profile','client_request_id','ground_point','minimum_elevation_deg','query_start_utc','query_end_utc','communication_status']){const {controller}=fixture(p=>Promise.resolve({...response(p),[field]:'wrong'}));await controller.query('start','end');assert.equal(controller.snapshot().status,'stale',field);assert.equal(controller.snapshot().result,null);}});
test('replacement query and explicit cancellation cannot restore old results',async()=>{const releases=[];const {controller}=fixture(p=>new Promise(r=>releases.push(()=>r(response(p)))));const first=controller.query('first','end');const second=controller.query('second','end');releases[1]();await second;releases[0]();await first;assert.equal(controller.snapshot().result.query_start_utc,'second');controller.cancel();assert.equal(controller.snapshot().result,null);});
test('failure stays visible and none/partial/error/contact/clipped have distinct wording',async()=>{const {controller}=fixture(()=>Promise.reject(new Error('EOP outside range')));await controller.query('start','end');assert.equal(controller.snapshot().status,'error');assert.match(controller.snapshot().error,/EOP/);assert.match(visibilityMarkup({status:'none',intervals:[],contacts:[],errors:[]}),/가시 구간 없음/);const html=visibilityMarkup({status:'partial',query_start_utc:'start',query_end_utc:'end',revision:1,intervals:[{start_utc:'a',end_utc:'b',peak_utc:'c',max_elevation_deg:16.3,start_clipped:true,end_clipped:true}],contacts:[{utc:'touch',duration_seconds:0,elevation_deg:10}],errors:[{utc:'bad',error_code:'<fault>'}]});assert.match(html,/부분 결과/);assert.match(html,/시작 잘림/);assert.match(html,/종료 잘림/);assert.match(html,/접점/);assert.match(html,/&lt;fault&gt;/);assert.match(html,/실제 통신 미확인/);assert.match(visibilityMarkup({status:'error',intervals:[],contacts:[],errors:[]}),/계산 실패/);});

test('ground form adopts asynchronously loaded server height and retains an edited draft',async()=>{
 const {createGroundPanel}=await import('../../../user_application/web/scripts/tabs/ground_visibility.js');let current=null;
 const fields=new Map(),element=id=>{if(!fields.has(id))fields.set(id,{value:'',textContent:'',innerHTML:'',listeners:{},addEventListener(name,fn){this.listeners[name]=fn;}});return fields.get(id);};
 const panel={isConnected:false,querySelector:selector=>element(selector.slice(1)),innerHTML:''};const screen={prepend(){panel.isConnected=true;}};
 globalThis.document={getElementById:()=>screen,createElement:()=>panel};
 const input={input_id:'tle',epoch_utc:'2020-07-12T21:16:01.000416000Z'};const client={snapshot:()=>({state:current,inputs:[input],status:current?'ready':'loading'})};
 try{const ui=createGroundPanel(client,{});ui.show('ground');current={...state,ground_point:{...ground,ellipsoid_height_m:500},leap_sha256:'6cb6f5d4b819f2e568e25db4b0b26d89dedf031fdffb18bc94d40f4e94e268d7'};ui.update();assert.equal(Number(element('ground-height').value),500);element('ground-height').value='800';element('ground-height').listeners.input();current={...current,ground_point:{...ground,ellipsoid_height_m:100}};ui.update();assert.equal(element('ground-height').value,'800');ui.destroy();}finally{delete globalThis.document;}
});
