import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
import {createGroundNetworkPanel} from '../../../user_application/web/scripts/tabs/ground_network.js';
import * as model from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as diagram from '../../../digital_twin/visualization/network_diagram.js';
function setup(width=1920,height=1080,sampled=false){const f=fixture(width,height,{hash:'#ground'}),store=f.evaluate('sourceGround');f.evaluate('groundNetworkPanel.destroy()');const station=store.enabled[0],state={valid:true,hook:null,readHook:null,proofChecks:0,readyHook:null,stationsHook:null},calls=[];const snapshot={status:'valid',utc:'2026-10-07T00:00:00.000000000Z',node_definitions:[{id:'A',name:'A',orbit:{altitude_km:550}},{id:'B',name:'B',orbit:{altitude_km:560}}],stations:store.stations,network:{nodes:[{id:'A',kind:'satellite'},{id:'B',kind:'satellite'},...store.enabled.map(s=>({...s,kind:'ground'}))],links:[]}};const network={networkSnapshot:()=>{state.readHook?.();return structuredClone(snapshot);},verifyNetworkSnapshot:()=>{state.proofChecks++;state.hook?.();return state.valid;},clearNetwork(){state.valid=false;}};if(sampled){const value=Object.freeze({...structuredClone(snapshot),presentation_kind:'NETWORK_SAMPLED_UI_V1',analysis_utc:snapshot.utc,display_utc:'2026-10-07T00:00:01.000000000Z'});network.networkSnapshot=()=>({status:'unavailable'});network.networkSampledPresentation=()=>value;network.verifySampledNetworkPresentation=v=>state.valid&&v===value;}const observedStore=new Proxy(store,{get(target,key){if(key==='ready')state.readyHook?.();if(key==='stations')state.stationsHook?.();return Reflect.get(target,key);}});const panel=createGroundNetworkPanel({store:observedStore,model,network,fabric:{snapshot:()=>({status:'unavailable',pending:false}),route:async(...args)=>calls.push(args)},diagram,document:f.doc,host:f.win,refreshRuntime:async()=>{}});panel.show('ground');return{f,store,station,state,snapshot,panel,calls,network,spec:{source:'A',target:station.id,objective:'latency'},dispose(){panel.destroy();f.dispose();}};}
for(const [w,h]of [[1920,1080],[2560,1440]])test(`scenario route draft fills existing controls without command or editor loss ${w}x${h}`,async()=>{const s=setup(w,h);try{s.store.select(s.station.id);await s.f.get('ground-node-edit').dispatch('click');s.f.get('ground-node-name').value='unsaved';assert.equal(typeof s.panel.adoptRouteDraft,'function');assert.equal(s.panel.adoptRouteDraft(s.spec),true);assert.deepEqual(s.panel.routeRequest(),s.spec);assert.equal(s.f.get('ground-node-fabric-source').value,'A');assert.equal(s.f.get('ground-node-fabric-target').value,s.station.id);assert.equal(s.f.get('ground-node-fabric-objective').value,'latency');assert.equal(s.f.get('ground-node-name').value,'unsaved');assert.deepEqual(s.calls,[]);assert.equal(s.f.counts().commands,0);}finally{s.dispose();}});
test('hidden route draft is retained without mounting and reflected on next show',()=>{const s=setup();try{s.panel.show('satellite');const before=s.f.doc.getElementById('ground-node-config');assert.equal(s.panel.adoptRouteDraft(s.spec),true);assert.equal(s.f.doc.getElementById('ground-node-config'),before);s.panel.show('ground');assert.equal(s.f.get('ground-node-fabric-source').value,'A');assert.equal(s.f.get('ground-node-fabric-objective').value,'latency');assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
for(const kind of ['foreign','same','objective','revoked','error','dispose','definition-change','read-reentry','verify-reentry'])test('handoff preserves old choices for '+kind,()=>{const s=setup();try{const before=s.panel.routeRequest();const spec={...s.spec};if(kind==='foreign')spec.target='foreign';if(kind==='same')spec.target='A';if(kind==='objective')spec.objective='unknown';if(kind==='revoked')s.state.valid=false;if(kind==='error')s.snapshot.status='error';if(kind==='dispose')s.panel.destroy();if(kind==='definition-change')s.state.hook=()=>{s.state.hook=null;s.snapshot.node_definitions[1].orbit.altitude_km=600;};if(kind==='read-reentry')s.state.readHook=()=>{s.state.readHook=null;s.panel.update();};if(kind==='verify-reentry')s.state.hook=()=>{s.state.hook=null;s.panel.destroy();};assert.equal(s.panel.adoptRouteDraft(spec),false);assert.deepEqual(s.panel.routeRequest(),before);assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
test('nested newer handoff survives obsolete outer adoption',()=>{const s=setup();try{let once=true;s.state.hook=()=>{if(once){once=false;assert.equal(s.panel.adoptRouteDraft({...s.spec,source:'B',objective:'reliability'}),true);}};assert.equal(s.panel.adoptRouteDraft(s.spec),false);assert.deepEqual(s.panel.routeRequest(),{...s.spec,source:'B',objective:'reliability'});assert.deepEqual(s.calls,[]);}finally{s.dispose();}});

test('complete 240 definitions including non-route member replacement must stay identical',()=>{const s=setup();try{s.snapshot.node_definitions=Array.from({length:240},(_,i)=>({id:i===0?'A':'N'+i,orbit:{altitude_km:550+i}}));s.snapshot.network.nodes=[...s.snapshot.node_definitions.map(n=>({id:n.id,kind:'satellite'})),...s.store.enabled.map(n=>({id:n.id,kind:'ground'}))];assert.equal(s.panel.adoptRouteDraft(s.spec),true);const before=s.panel.routeRequest();s.state.hook=()=>{s.state.hook=null;s.snapshot.node_definitions[239].orbit.altitude_km++;};assert.equal(s.panel.adoptRouteDraft({...s.spec,objective:'reliability'}),false);assert.deepEqual(s.panel.routeRequest(),before);assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
test('registered sampled full roster can receive draft without current approval',()=>{const s=setup(1920,1080,true);try{assert.equal(s.panel.adoptRouteDraft(s.spec),true);assert.deepEqual(s.panel.routeRequest(),s.spec);assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
test('terminal actual station owner replacement rejects hidden adoption',()=>{const s=setup();try{s.panel.show('satellite');let n=0;s.state.hook=()=>{if(++n===3)s.store.update(s.station.id,{name:'changed station'});};assert.equal(s.panel.adoptRouteDraft(s.spec),false);assert.equal(s.panel.routeRequest().source,'');assert.deepEqual(s.calls,[]);}finally{s.dispose();}});

for(const kind of ['ready','stations'])test('late '+kind+' getter revoking actual native proof cannot adopt stale draft',()=>{const s=setup();try{s.state.proofChecks=0;let revoked=false;const hook=()=>{if(s.state.proofChecks===3&&!revoked){revoked=true;s.state.valid=false;}};s.state[kind==='ready'?'readyHook':'stationsHook']=hook;assert.equal(s.panel.adoptRouteDraft(s.spec),false);assert.equal(revoked,true);assert.equal(s.panel.routeRequest().source,'');assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
