import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
import {createGroundNetworkPanel} from '../../../user_application/web/scripts/tabs/ground_network.js';
import * as model from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as diagram from '../../../digital_twin/visualization/network_diagram.js';
function setup(sampled=false){const f=fixture(1920,1080,{hash:'#ground'}),store=f.evaluate('sourceGround');f.evaluate('groundNetworkPanel.destroy()');const state={valid:!sampled,revoked:false,ready:true,read:null,verify:null,can:null};const calls=[];
 const proof={status:'valid',utc:'2026-10-07T00:00:00.000000000Z',node_definitions:[{id:'A',name:'Satellite A',orbit:{}},{id:'B',name:'Satellite B',orbit:{}}],stations:store.enabled,network:{nodes:[{id:'A',kind:'satellite'},{id:'B',kind:'satellite'}],links:[]}};
 const sample=Object.freeze({...proof,presentation_kind:'NETWORK_SAMPLED_UI_V1',analysis_utc:proof.utc,display_utc:proof.utc,age_seconds:0});
 const network={networkSnapshot:()=>{state.read?.();return structuredClone(proof);},verifyNetworkSnapshot:()=>{state.verify?.();return state.valid;},clearNetwork(){state.valid=false;},canFocusSourceNetworkNode:id=>{state.can?.();return state.ready&&['A','B'].includes(id);},focusSourceNetworkNode:async id=>{calls.push(id);return true;}};
 if(sampled){network.networkSampledPresentation=()=>sample;network.verifySampledNetworkPresentation=value=>{state.verify?.();return value===sample&&!state.revoked;};}
 const panel=createGroundNetworkPanel({store,model,network,fabric:{snapshot:()=>({pending:false,receipt:null,route:null})},diagram,document:f.doc,host:f.win,refreshRuntime:async()=>{}});panel.show('ground');
 const select=async id=>f.get('ground-node-diagram').dispatch('click',{target:{closest:()=>({getAttribute:key=>key==='data-diagram-node'?id:null})}});
 const button=()=>{const value=f.doc.getElementById('ground-node-detail-focus');assert.ok(value,'satellite detail focus exists');return value;};
 const click=async value=>f.get('ground-node-diagram-detail').dispatch('click',{target:value??button()});
 return {f,store,state,calls,network,panel,proof,select,button,click,dispose(){panel.destroy();f.dispose();}};
}
for(const sampled of [false,true])test(`satellite detail delegates existing actual native focus owner sampled=${sampled}`,async()=>{const s=setup(sampled);try{await s.select('B');assert.equal(s.button().disabled,false);await s.click();assert.deepEqual(s.calls,['B']);assert.equal(s.f.counts().commands,0);assert.equal(s.f.get('ground-node-fabric-route').disabled,true);}finally{s.dispose();}});
for(const kind of ['revoked','hidden','disposed','old-paint','read-reentry','verify-reentry','can-reentry','native-not-ready'])test('satellite detail focus refuses '+kind,async()=>{const s=setup();try{await s.select('A');const old=s.button();if(kind==='revoked')s.state.valid=false;if(kind==='hidden')s.panel.show('satellite');if(kind==='disposed')s.panel.destroy();if(kind==='old-paint')await s.select('B');if(kind==='read-reentry')s.state.read=()=>{s.state.read=null;s.panel.update();};if(kind==='verify-reentry')s.state.verify=()=>{s.state.verify=null;s.panel.show('satellite');};if(kind==='can-reentry')s.state.can=()=>{s.state.can=null;s.panel.show('satellite');};if(kind==='native-not-ready')s.state.ready=false;await s.click(old);assert.deepEqual(s.calls,[]);}finally{s.dispose();}});
test('late asynchronous native focus completion cannot repaint a hidden detail',async()=>{const s=setup();try{let finish;s.network.focusSourceNetworkNode=id=>{s.calls.push(id);return new Promise(resolve=>finish=resolve);};await s.select('A');const button=s.button(),pending=s.click(button);s.panel.show('satellite');const before=s.f.get('ground-node-diagram-detail').innerHTML;finish(false);await pending;assert.equal(s.f.get('ground-node-diagram-detail').innerHTML,before);assert.deepEqual(s.calls,['A']);}finally{s.dispose();}});
test('sampled focus refuses same-UTC owner revocation and edited complete scope',async()=>{for(const kind of ['revocation','scope']){const s=setup(true);try{await s.select('A');const old=s.button();if(kind==='revocation')s.state.revoked=true;else s.proof.node_definitions[1].name='changed';await s.click(old);assert.deepEqual(s.calls,[]);}finally{s.dispose();}}});
