import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
import {createGroundNetworkPanel} from '../../../user_application/web/scripts/tabs/ground_network.js';
import * as model from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as diagram from '../../../digital_twin/visualization/network_diagram.js';
function setup(sampled=false){const f=fixture(1920,1080,{hash:'#ground'}),store=f.evaluate('sourceGround');f.evaluate('groundNetworkPanel.destroy()');let panel;const state={valid:true,hook:null,read:null};const station=store.enabled[0];
 const proof={status:'valid',utc:'2026-10-07T00:00:00.000000000Z',node_definitions:[{id:'A',name:'Satellite A',orbit:{}},{id:'B',name:'Satellite B',orbit:{}}],stations:[station],network:{nodes:[{id:'A',kind:'satellite'},{id:'B',kind:'satellite'},{id:station.id,kind:'ground'}],links:[{id:'AB',a:'A',b:'B',kind:'oisl'},{id:'AG',a:'A',b:station.id,kind:'ground'}]}};
 const receipt={sequence:1,nodes:[],links:[{id:'AB',quality:50,usable:true},{id:'AG',quality:50,usable:true}]};const commands=[];
 const network={networkSnapshot:()=>{state.read?.();return structuredClone(proof);},verifyNetworkSnapshot:()=>{state.hook?.();return state.valid;},clearNetwork:()=>{state.valid=false;},canFocusGroundNetworkStation:()=>state.valid,focusGroundNetworkStation:id=>{commands.push(['focus',id]);return true;}};
 if(sampled){state.valid=false;const view=Object.freeze({...proof,presentation_kind:'NETWORK_SAMPLED_UI_V1',display_utc:proof.utc,analysis_utc:proof.utc,age_seconds:0});network.networkSampledPresentation=()=>view;network.verifySampledNetworkPresentation=value=>value===view&&!state.revoked;}
 panel=createGroundNetworkPanel({store,model,network,fabric:{snapshot:()=>({status:'accepted',pending:false,receipt}),route:async()=>commands.push('route'),send:async()=>commands.push('send')},diagram,document:f.doc,host:f.win,refreshRuntime:async()=>{}});panel.show('ground');
 const select=async(id,type='link')=>f.get('ground-node-diagram').dispatch('click',{target:{closest:()=>({getAttribute:key=>key==='data-diagram-'+type?id:null})}});
 const button=side=>{const value=f.doc.getElementById('ground-node-detail-select-'+side);assert.ok(value,'link endpoint button exists');return value;};
 const click=async side=>f.get('ground-node-diagram-detail').dispatch('click',{target:button(side)});
 return {f,store,proof,state,network,panel,commands,select,button,click,station,dispose(){panel.destroy();f.dispose();}};}
test('link endpoint buttons select actual satellite/ground details without commands and preserve editing',async()=>{const s=setup();try{await s.select('AB');s.store.select(s.station.id);await s.f.get('ground-node-edit').dispatch('click');s.f.get('ground-node-name').value='unsaved';await s.click('a');assert.match(s.f.get('ground-node-diagram-detail').innerHTML,/Satellite A/);assert.equal(s.f.get('ground-node-name').value,'unsaved');await s.select('AB');await s.click('b');assert.match(s.f.get('ground-node-diagram-detail').innerHTML,/Satellite B/);await s.select('AG');await s.click('b');assert.match(s.f.get('ground-node-diagram-detail').innerHTML,new RegExp(s.station.id));assert.deepEqual(s.commands,[]);}finally{s.dispose();}});
for(const kind of ['revoked','hidden','disposed','repaint','reentrant','read-reentrant','replaced-endpoint'])test('stale link endpoint is inert after '+kind,async()=>{const s=setup();try{await s.select('AB');const old=s.button('a'),detail=s.f.get('ground-node-diagram-detail');if(kind==='revoked')s.state.valid=false;if(kind==='hidden')s.panel.show('satellite');if(kind==='disposed')s.panel.destroy();if(kind==='repaint')await s.select('AG');if(kind==='reentrant')s.state.hook=()=>{s.state.hook=null;s.panel.show('satellite');};if(kind==='read-reentrant')s.state.read=()=>{s.state.read=null;s.panel.update();};if(kind==='replaced-endpoint')s.proof.network.links[0].a='B';const before=detail.innerHTML;await detail.dispatch('click',{target:old});if(kind==='reentrant'){/* ADR0062: hide revokes exact diagram/detail too; stale clicks must not resurrect it. */assert.equal(detail.innerHTML,'');assert.equal(s.f.get('ground-node-diagram').innerHTML,'');assert.equal(s.f.get('ground-node-focus').disabled,true);s.panel.update();assert.equal(detail.innerHTML,'','hidden panel does not repaint');s.panel.show('ground');const fresh=detail.innerHTML;assert.notEqual(fresh,'');await detail.dispatch('click',{target:old});assert.equal(detail.innerHTML,fresh,'old button remains inert after a fresh ground paint');}else assert.equal(detail.innerHTML,before);assert.deepEqual(s.commands,[]);}finally{s.dispose();}});

test('station detail edits through existing editor and focuses actual owner without discarding pending edit',async()=>{const s=setup();try{await s.select(s.station.id,'node');const focus=s.f.doc.getElementById('ground-node-detail-focus'),edit=s.f.doc.getElementById('ground-node-detail-edit');assert.ok(focus);assert.ok(edit);await s.f.get('ground-node-diagram-detail').dispatch('click',{target:edit});assert.equal(s.f.get('ground-node-name').value,s.station.name);s.f.get('ground-node-name').value='pending station edit';await s.select(s.station.id,'node');await s.f.get('ground-node-diagram-detail').dispatch('click',{target:s.f.doc.getElementById('ground-node-detail-edit')});assert.equal(s.f.get('ground-node-name').value,'pending station edit');await s.f.get('ground-node-diagram-detail').dispatch('click',{target:s.f.doc.getElementById('ground-node-detail-focus')});assert.deepEqual(s.commands,[['focus',s.station.id]]);}finally{s.dispose();}});
test('station detail focus/edit old paint cannot bypass hidden or revoked current network',async()=>{for(const kind of ['hidden','revoked','repaint']){const s=setup();try{await s.select(s.station.id,'node');const focus=s.f.doc.getElementById('ground-node-detail-focus'),edit=s.f.doc.getElementById('ground-node-detail-edit');assert.ok(focus);assert.ok(edit);if(kind==='hidden')s.panel.show('satellite');if(kind==='revoked')s.state.valid=false;if(kind==='repaint')await s.select('A','node');await s.f.get('ground-node-diagram-detail').dispatch('click',{target:focus});await s.f.get('ground-node-diagram-detail').dispatch('click',{target:edit});assert.deepEqual(s.commands,[]);assert.equal(s.f.doc.getElementById('ground-node-name'),null);}finally{s.dispose();}}});

test('registered sampled link endpoints navigate geometry only and revoke without current communication claims',async()=>{const s=setup(true);try{await s.select('AB');await s.click('b');assert.match(s.f.get('ground-node-diagram-detail').innerHTML,/Satellite B/);assert.equal(s.f.doc.getElementById('ground-node-detail-route-source').disabled,true);await s.select('AG');const old=s.button('b'),before=s.f.get('ground-node-diagram-detail').innerHTML;s.state.revoked=true;await s.f.get('ground-node-diagram-detail').dispatch('click',{target:old});assert.equal(s.f.get('ground-node-diagram-detail').innerHTML,before);assert.deepEqual(s.commands,[]);}finally{s.dispose();}});
