import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {OrbitGlobe} from '../../../digital_twin/visualization/orbit_globe.js';
function fixture(){
 const handlers=[],viewers=[],flights=[],selected=[],focused=[],fallback=[],releases=[];
 class Handler{constructor(){this.actions=new Map();handlers.push(this);}setInputAction(fn,type){this.actions.set(type,fn);}destroy(){this.destroyed=(this.destroyed??0)+1;}}
 class Viewer{constructor(){this.entities={add:v=>v,remove(){},removeAll(){}};this.scene={mode:3,canvas:{style:{}},globe:{},pick:()=>this.picked,requestRender:()=>{this.renders=(this.renders??0)+1;},renderError:{addEventListener:()=>()=>{}}};this.camera={flyTo:options=>flights.push(options)};this.clock={};this.imageryLayers={};viewers.push(this);}destroy(){this.dead=true;}}
 const C={Viewer,EllipsoidTerrainProvider:class{},Cartesian3:class{constructor(x,y,z){Object.assign(this,{x,y,z});}static fromDegrees(longitude,latitude,height){return {longitude,latitude,height};}},Color:{CYAN:'cyan',WHITE:'white',fromCssColorString:v=>v},ConstantPositionProperty:class{constructor(value){this.value=value;}},ReferenceFrame:{FIXED:'fixed'},JulianDate:{fromIso8601:v=>v},ScreenSpaceEventHandler:Handler,ScreenSpaceEventType:{LEFT_CLICK:1,LEFT_DOUBLE_CLICK:2,MOUSE_MOVE:3},SceneMode:{MORPHING:0,SCENE2D:2,SCENE3D:3}};
 const globe=new OrbitGlobe(C,{style:{},addEventListener(){},removeEventListener(){}}),station=Object.freeze({id:'G',name:'Operator',enabled:true,longitude:127,latitude:37,altitude_km:.1}),token=Object.freeze({id:'G',station}),entity={id:'station-G',properties:{stationId:'G'}},coverage={id:'station-coverage-G',properties:{stationId:'G'}};
 let valid=true,readHook=null,verifyHook=null,selectHook=null,focusHook=null;
 const port={read:picked=>{readHook?.();return picked?.id===entity||picked?.id===coverage?token:null;},verify:value=>{verifyHook?.();return valid&&value===token;},onSelect:value=>{selected.push(value);selectHook?.();},onFocus:value=>{focused.push(value);focusHook?.();}};
 globe.cameraMotion.release=()=>{releases.push(true);};
 return {globe,C,port,token,station,entity,coverage,handlers,viewers,flights,selected,focused,fallback,releases,set readHook(v){readHook=v;},set verifyHook(v){verifyHook=v;},set selectHook(v){selectHook=v;},revoke(){valid=false;},bind(){globe.setGroundNetworkInteraction(port);},click(picked={id:entity},double=false){globe.viewer.picked=picked;handlers[0].actions.get(double?2:1)({position:{x:1,y:2}});}};
}
test('owned operator single click selects only; double click rechecks and explicitly focuses with one handler',()=>{const f=fixture();f.bind();f.click();assert.deepEqual(f.selected,[f.token]);assert.equal(f.focused.length,0);assert.equal(f.flights.length,0);f.click({id:f.coverage},true);assert.deepEqual(f.selected,[f.token,f.token]);assert.deepEqual(f.focused,[f.token]);f.bind();assert.equal(f.handlers.length,1);assert.equal(f.viewers.length,1);});
test('rejected station-ID hint blocks node/catalog/reference fallback and never grants ownership',()=>{const f=fixture();f.bind();f.globe.setNodeInteraction({owns:()=>true,onSelect:id=>f.fallback.push(id)});f.globe.onCatalogSelect=id=>f.fallback.push(id);f.globe.catalogPoints.set(99,{show:true});for(const fake of [{nodeId:'A',properties:{stationId:'G'}},{catalogNumber:99,properties:{stationId:'G'}},{id:'station-G',properties:{stationId:'G'}}]){f.click({id:fake});f.click({id:fake},true);}assert.deepEqual(f.selected,[]);assert.deepEqual(f.focused,[]);assert.deepEqual(f.fallback,[]);});
test('nonoperator null read retains node, catalog and reference station choices',()=>{const f=fixture();f.bind();f.globe.setNodeInteraction({owns:()=>true,onSelect:id=>f.fallback.push('node:'+id)});f.globe.onCatalogSelect=id=>f.fallback.push('catalog:'+id);f.globe.catalogPoints.set(99,{show:true});f.globe.setStations([{key:'SITE',name:'Reference',longitude:126,latitude:36,altitudeKm:.1}],id=>f.fallback.push('reference:'+id));f.click({id:{nodeId:'A'}});f.click({id:{catalogNumber:99}});f.click({id:{id:'reference-ground-SITE'}});assert.deepEqual(f.fallback,['node:A','catalog:99','reference:SITE']);assert.equal(f.flights.length,0);assert.equal(f.handlers.length,1);});
for(const action of ['revoke','unbind','replace','destroy','viewer','morph'])test(`read callback ${action} cannot publish station selection or focus`,()=>{const f=fixture();f.bind();f.readHook=()=>{f.readHook=null;if(action==='revoke')f.revoke();if(action==='unbind')f.globe.setGroundNetworkInteraction(null);if(action==='replace')f.globe.setGroundNetworkInteraction({...f.port});if(action==='destroy')f.globe.destroy();if(action==='viewer')f.globe.viewer={scene:{mode:3}};if(action==='morph')f.globe.viewer.scene.mode=0;};f.click({id:f.entity},true);assert.deepEqual(f.selected,[]);assert.deepEqual(f.focused,[]);});
test('select callback lease revocation or binding replacement suppresses the double-click focus continuation',()=>{for(const replacement of [false,true]){const f=fixture();f.bind();f.selectHook=()=>replacement?f.globe.setGroundNetworkInteraction({...f.port}):f.revoke();f.click(undefined,true);assert.deepEqual(f.selected,[f.token]);assert.deepEqual(f.focused,[]);}});
test('nested newer click owns its focus continuation rather than the obsolete outer double click',()=>{const f=fixture();f.bind();let once=true;f.selectHook=()=>{if(once){once=false;f.click();}};f.click(undefined,true);assert.equal(f.selected.length,2);assert.equal(f.focused.length,0);});
test('scene pick callback replacement cannot dispatch an old event to the new ground binding',()=>{const f=fixture();f.bind();let replacement=0;f.globe.viewer.scene.pick=()=>{f.globe.setGroundNetworkInteraction({...f.port,onSelect:()=>replacement++});return {id:f.entity};};f.click();assert.equal(replacement,0);assert.equal(f.selected.length,0);});
test('owner verification starting morph without changing scene mode cannot authorize station selection',()=>{const f=fixture();f.bind();f.verifyHook=()=>{f.globe.viewControls.cancelMorph=()=>{};};f.click();assert.equal(f.selected.length,0);});
test('post-verification mode getter revoking station token cannot authorize selection',()=>{const f=fixture();f.bind();let armed=false,revoked=false;f.verifyHook=()=>{armed=true;};Object.defineProperty(f.globe.viewer.scene,'mode',{get(){if(armed){revoked=true;f.revoke();}return 3;}});f.click();assert.equal(revoked,true);assert.equal(f.selected.length,0);assert.equal(f.focused.length,0);});
test('morph, disposed globe and stale captured input handler never dispatch station callbacks',()=>{const f=fixture();f.bind();const click=f.handlers[0].actions.get(1);f.globe.viewControls.cancelMorph=()=>{};f.click();assert.equal(f.selected.length,0);f.globe.viewControls.cancelMorph=null;f.globe.destroy();click({position:{}});assert.equal(f.selected.length,0);assert.equal(f.handlers[0].destroyed,1);});
test('registered readonly focus uses source camera height/duration, releases tracking and requests render',()=>{const f=fixture();f.bind();const clock=f.globe.viewer.clock;clock.currentTime='unchanged';assert.equal(f.globe.focusGroundNetworkStation(f.station,{verify:()=>f.port.verify(f.token)}),true);assert.equal(f.releases.length,1);assert.deepEqual(f.flights,[{destination:{longitude:127,latitude:37,height:2400000},duration:1.4}]);assert.ok(f.globe.viewer.renders>0);assert.equal(clock.currentTime,'unchanged');assert.equal(f.globe.selectedCatalog,null);assert.equal(f.globe.selectedStation,null);});
test('focus requires finite station and verified authority before any tracking release',()=>{const f=fixture();f.bind();for(const station of [null,{...f.station,longitude:NaN},{...f.station,latitude:91},{...f.station,longitude:181}])assert.equal(f.globe.focusGroundNetworkStation(station,{verify:()=>true}),false);assert.equal(f.globe.focusGroundNetworkStation(f.station),false);assert.equal(f.globe.focusGroundNetworkStation(f.station,{verify:()=>false}),false);assert.equal(f.releases.length,0);assert.equal(f.flights.length,0);});
test('final focus verification starting pending morph after tracking release cannot fly',()=>{const f=fixture();f.bind();assert.equal(f.globe.focusGroundNetworkStation(f.station,{verify:()=>{if(f.releases.length)f.globe.viewControls.cancelMorph=()=>{};return true;}}),false);assert.equal(f.releases.length,1);assert.equal(f.flights.length,0);});
test('final focus verification cannot mutate supplied station coordinates after validation and still fly',()=>{const f=fixture();f.bind();const station={...f.station};assert.equal(f.globe.focusGroundNetworkStation(station,{verify:()=>{if(f.releases.length)station.longitude=0;return true;}}),false);assert.equal(f.flights.length,0);});
test('post-tracking verification mode getter revocation cannot perform an obsolete flight',()=>{const f=fixture();f.bind();let armed=false,revoked=false;Object.defineProperty(f.globe.viewer.scene,'mode',{get(){if(armed){revoked=true;f.revoke();}return 3;}});const result=f.globe.focusGroundNetworkStation(f.station,{verify:()=>{if(f.releases.length)armed=true;return f.port.verify(f.token);}});assert.equal(revoked,true);assert.equal(result,false);assert.equal(f.releases.length,1);assert.equal(f.flights.length,0);});
for(const action of ['revoke','unbind','replace','viewer','destroy','morph'])test(`tracking release ${action} prevents the obsolete focus flight`,()=>{const f=fixture();f.bind();f.globe.cameraMotion.release=()=>{if(action==='revoke')f.revoke();if(action==='unbind')f.globe.setGroundNetworkInteraction(null);if(action==='replace')f.globe.setGroundNetworkInteraction({...f.port});if(action==='viewer')f.globe.viewer={scene:{mode:3},camera:{flyTo:()=>{throw Error('foreign camera');}}};if(action==='destroy')f.globe.destroy();if(action==='morph')f.globe.viewer.scene.mode=0;};assert.equal(f.globe.focusGroundNetworkStation(f.station,{verify:()=>f.port.verify(f.token)}),false);assert.equal(f.flights.length,0);});
let workspaceFixtureId=0;
async function workspaceFixture(){
 const instances=[];globalThis.GroundInteractionGlobe=class{constructor(){this.viewer={scene:{renderError:{addEventListener:()=>()=>{}}}};instances.push(this);}update(){return false;}setGroundPoint(){}setViewStyle(){}setViewImagery(){return Promise.resolve(true);}setGroundNetworkInteraction(port){this.port=port;}focusGroundNetworkStation(station,options){this.focus={station,options};return options.verify(station);}destroy(){this.dead=true;}};
 const source=(await readFile(new URL('../../../user_application/web/scripts/workspace_globe.js',import.meta.url),'utf8')).replace("'./orbit_utc.js'",JSON.stringify(new URL('../../../user_application/web/scripts/orbit_utc.js',import.meta.url).href)).replace(/import \{OrbitGlobe\} from [^;]+;/,'const OrbitGlobe=globalThis.GroundInteractionGlobe;');
 const {createWorkspaceGlobe}=await import(`data:text/javascript;base64,${Buffer.from(source+'\n// fixture '+(++workspaceFixtureId)).toString('base64')}`),host={Cesium:{},setTimeout:()=>1,clearTimeout(){},addEventListener(){},removeEventListener(){}},ui=createWorkspaceGlobe({dataset:{}},{},{addEventListener(){},removeEventListener(){}},host);
 delete globalThis.GroundInteractionGlobe;return {ui,owner:instances[0]};
}
test('workspace binding cleanup cannot detach its replacement; old read/verify/select/focus callbacks fail closed',async()=>{const {ui,owner}=await workspaceFixture();let chosen=0;const token=Object.freeze({id:'G',station:Object.freeze({id:'G',longitude:127,latitude:37})}),port={read:()=>token,verify:v=>v===token,onSelect:()=>chosen++,onFocus:()=>chosen++};const oldRemove=ui.bindGroundNetworkInteraction(port),old=owner.port,newRemove=ui.bindGroundNetworkInteraction(port);oldRemove();assert.ok(owner.port);assert.equal(old.read({}),null);assert.equal(old.verify(token),false);old.onSelect(token);old.onFocus(token);assert.equal(chosen,0);assert.equal(owner.port.read({}),token);newRemove();assert.equal(owner.port,null);ui.destroy();});
test('workspace callbacks recheck actual binding after external reads and reject disposal or nested replacement',async()=>{for(const operation of ['destroy','replace']){const {ui,owner}=await workspaceFixture();let calls=0;const port={read:()=>{operation==='destroy'?ui.destroy():ui.bindGroundNetworkInteraction({...port,read:()=>null});return {};},verify:()=>true,onSelect:()=>calls++,onFocus:()=>calls++};ui.bindGroundNetworkInteraction(port);const old=owner.port;assert.equal(old.read({}),null);assert.equal(old.verify({}),false);old.onSelect({});assert.equal(calls,0);ui.destroy();}});
test('workspace station focus requires active binding and current closure, and cannot mark a replaced owner focus successful',async()=>{const {ui,owner}=await workspaceFixture(),station={id:'G',longitude:127,latitude:37},port={read:()=>null,verify:()=>true,onSelect(){},onFocus(){}};assert.equal(ui.focusGroundNetworkStation(station,{verify:()=>true}),false);const remove=ui.bindGroundNetworkInteraction(port);assert.equal(ui.focusGroundNetworkStation(station,{verify:()=>true}),true);assert.equal(ui.focusGroundNetworkStation(station,{verify:()=>{remove();return true;}}),false);assert.equal(owner.port,null);ui.destroy();assert.equal(ui.focusGroundNetworkStation(station,{verify:()=>true}),false);});
