import test from 'node:test';
import assert from 'node:assert/strict';
import {createHilWorkspace} from '../../../user_application/web/scripts/tabs/hil_workspace.js';
export const device=(id='A',connected=true)=>({id,name:'Mock '+id,role:'test',protocol:'UDP',mode:'MOCK',connected,health:88,latency_ms:14.2,channels:2,clock_offset_us:12,jitter_us:2,clock_state:'LOCKED'});
export const boot=()=>({runtime:{mode:'SIM',run_id:'R',scenario_id:'S',elapsed_seconds:0,sequence:1,recording:true},devices:[device(),device('B',false)],events:[]});
const flight=(run_id='R')=>({run_id,passed:false,status:'BLOCKED',mode:'MOCK-HIL',evaluated_at:'2026-10-05T00:00:00Z',checks:[{id:'connect:B',name:'B',passed:false,value:'OFFLINE'}]});
function fixture(extra={}){let b=boot(),calls=[];const api={bootstrap:async()=>structuredClone(b),hilPreflight:async()=>flight(b.runtime.run_id),deviceAction:async(id,action)=>{calls.push([id,action]);const d=b.devices.find(d=>d.id===id);d.connected=action==='disconnect'?false:action==='connect'?true:d.connected;return structuredClone(d);},recording:async enabled=>{b.runtime.recording=enabled;return {run_id:'R',recording:enabled};},hilSequence:async kind=>({sequence_id:kind,run_id:'R',status:'failed',steps:Array.from({length:kind==='fault_recovery'?5:4},(_,i)=>({id:`S${i+1}`,name:'Check',status:i?'passed':'failed'})),preflight:flight()}),...extra};return {c:createHilWorkspace(api),calls,b};}
test('mock actions reuse requests; copies, local selection, recording and immutable sequence evidence',async()=>{const {c,calls,b}=fixture();await c.load();c.select('B');await c.action('sync');assert.equal(calls.length,0);await c.action('connect');assert.deepEqual(calls,[['B','connect']]);assert.equal(c.snapshot().selected,'B');await c.recording();assert.equal(c.snapshot().runtime.recording,false);c.editSequence('fault_recovery');await c.sequence();assert.equal(c.snapshot().result.sequence_id,'fault_recovery');const s=c.snapshot();s.devices[0].health=0;assert.equal(c.snapshot().devices[0].health,88);assert.equal(b.runtime.elapsed_seconds,0);c.destroy();});
test('pending serialization, partial batch failure, persistent error and explicit refresh',async()=>{let release;const {c,calls}=fixture({deviceAction:async(id,action)=>{calls.push([id,action]);if(id==='B')throw Error('offline');return device(id);}});await c.load();c.receive({...boot(),devices:[device(),device('B')]});await c.all('sync');assert.equal(calls.length,2);assert.match(c.snapshot().error,/1\/2/);c.receive(boot());assert.match(c.snapshot().error,/offline/);await c.load();assert.equal(c.snapshot().error,'');const p=fixture({hilPreflight:()=>new Promise(r=>release=r)});const pending=p.c.load();await p.c.action('connect');p.c.destroy();release(flight());await pending;assert.equal(p.c.snapshot().devices.length,0);c.destroy();});
test('preflight becomes obsolete on stream context change; malformed payloads retain last good values',async()=>{const {c}=fixture();await c.load();assert.ok(c.snapshot().preflight);const v=boot();v.devices[0].health=89;c.receive(v);assert.equal(c.snapshot().preflight,null);assert.equal(c.snapshot().devices[0].health,89);c.receive({...v,devices:[{...device(),latency_ms:NaN}]});assert.equal(c.snapshot().devices[0].health,89);assert.match(c.snapshot().error,/응답/);c.connection('closed');assert.equal(c.snapshot().stale,true);c.destroy();});
test('abort fences late mutation and no retry after failure',async()=>{let release,signal,count=0;const {c}=fixture({deviceAction:(id,action,o)=>{signal=o.signal;count++;return new Promise(r=>release=r);}});await c.load();const p=c.action('disconnect');await c.action('disconnect');assert.equal(count,1);c.destroy();assert.equal(signal.aborted,true);release(device('A',false));await p;assert.equal(c.snapshot().devices[0].connected,true);});
test('mutation stream barrier rejects pre-command device state and preflight run mismatch',async()=>{const {c}=fixture();await c.load();await c.action('disconnect');c.receive(boot());assert.equal(c.snapshot().devices[0].connected,false);const v=boot();v.devices[0].connected=false;c.receive(v);assert.equal(c.snapshot().stale,false);const bad=fixture({hilPreflight:async()=>flight('other')});await bad.c.load();assert.match(bad.c.snapshot().error,/응답/);c.destroy();bad.c.destroy();});
