import test from 'node:test';
import assert from 'node:assert/strict';
import {createKpiWorkspace,parseCsvReport} from '../../../user_application/web/scripts/tabs/kpi_workspace.js';
const runtime=(values={})=>({mode:'SIM',run_id:'R',scenario_id:'S',elapsed_seconds:1,sequence:1,...values});
const analytics=(values={})=>({run_id:'R',scenario_id:'S',generated_at:'2026-10-04T00:00:00Z',overall:100,verdict:'PASS',provenance:{mode:'SIM',data_quality:'GOOD',is_simulation:true,rule_set:'SIM-VNV-0.2',recording:true},kpis:[{id:'KPI-02',name:'Delay',value:20,target:50,unit:'ms',status:'pass',inverse:true,formula:'current',source:'SIM',delta:-30,samples:1,missing_percent:0}],requirements:[{id:'REQ',name:'Requirement',test:'TC',result:'PASS',evidence:'R',kpi_id:'KPI-02'}],...values});
const frame=(i=1)=>({type:'telemetry',runtime:runtime({sequence:i,elapsed_seconds:i}),analytics:analytics(),events:[],telemetry:{delay_ms:i},wall_time:'2026-10-04T00:00:00Z',data_quality:{source:'deterministic-sim',mode:'SIM'}});
const boot=()=>({runtime:runtime(),analytics:analytics(),events:[]});
const report=(kind,payload)=>({kind,filename:kind==='json'?'spacetwin-snapshot.json':'spacetwin-report.csv',mediaType:kind==='json'?'application/json':'text/csv',bytes:new TextEncoder().encode(typeof payload==='string'?payload:JSON.stringify(payload))});
function setup(extra={}){const files=[];let timer;const c=createKpiWorkspace({bootstrap:async()=>boot(),report:async kind=>report(kind,kind==='json'?{...boot(),generated_at:'2026-10-04T00:00:01Z'}:'\ufeffKPI,Name,Value,Target,Unit,Status\r\nKPI-02,Delay,20,50,ms,pass\r\n'),...extra},()=>{},file=>files.push(file),{setTimer:fn=>(timer=fn,1),clearTimer:()=>timer=null});return {c,files,tick:()=>timer?.()};}
test('reuses values/filters/details and bounded history; replay changes only display',async()=>{const f=setup();await f.c.load();f.c.selectKpi('KPI-02');f.c.filter('PASS',false);assert.equal(f.c.snapshot().filters.PASS,false);for(let i=1;i<=301;i++)f.c.receive(frame(i));assert.equal(f.c.snapshot().history.length,300);f.c.scrub(0);assert.equal(f.c.snapshot().display.runtime.sequence,2);f.c.play();f.tick();assert.equal(f.c.snapshot().display.runtime.sequence,3);f.c.live();assert.equal(f.c.snapshot().display.runtime.sequence,301);f.c.receive({...frame(1),runtime:runtime({run_id:'OTHER'}),analytics:analytics({run_id:'OTHER',requirements:[{...analytics().requirements[0],evidence:'OTHER'}]})});assert.equal(f.c.snapshot().history.length,1);f.c.destroy();});
test('exports exactly received bytes; JSON freezes display and CSV has independent preview',async()=>{const f=setup();await f.c.load();await f.c.export('json');const saved=f.c.snapshot().display.analytics;f.c.receive(frame(20));assert.deepEqual(f.c.snapshot().display.analytics,saved);assert.equal(f.c.snapshot().mode,'json');assert.deepEqual(JSON.parse(new TextDecoder().decode(f.files[0].bytes)).analytics,saved);await f.c.export('csv');assert.equal(f.c.snapshot().csv[0][2],'20');assert.equal(new TextDecoder('utf-8',{ignoreBOM:true}).decode(f.files[1].bytes)[0],'\ufeff');f.c.live();assert.equal(f.c.snapshot().display.runtime.sequence,20);f.c.destroy();});
test('serialized export, destroy abort and late reply fenced',async()=>{let resolve,signal,count=0;const f=setup({report:(kind,o)=>{count++;signal=o.signal;return new Promise(r=>resolve=r);}});const p=f.c.export('json');await f.c.export('csv');assert.equal(count,1);f.c.destroy();assert.equal(signal.aborted,true);resolve(report('json',{...boot(),generated_at:'2026-10-04T00:00:01Z'}));await p;assert.equal(f.files.length,0);});
test('malformed provenance/numbers/trace and failed fetch stay explicit across good stream',async()=>{const f=setup({report:async()=>{throw Error('offline');}});await f.c.load();f.c.receive({...frame(),analytics:analytics({run_id:'wrong'})});assert.match(f.c.snapshot().error,/응답/);await f.c.export('json');f.c.receive(frame());assert.match(f.c.snapshot().error,/offline/);assert.equal(f.files.length,0);const s=f.c.snapshot();s.display.analytics.kpis[0].value=-1;assert.equal(f.c.snapshot().display.analytics.kpis[0].value,20);f.c.destroy();});
test('CSV accepts quoted multiline/escaped fields and refuses wrong header/numeric/status',()=>{assert.equal(parseCsvReport('KPI,Name,Value,Target,Unit,Status\r\nK,"a,b\n""c""",1,2,%,pass\r\n')[0][1],'a,b\n"c"');for(const bad of ['wrong\n','KPI,Name,Value,Target,Unit,Status\nK,name,NaN,2,%,pass','KPI,Name,Value,Target,Unit,Status\nK,name,1,2,%,oops','KPI,Name,Value,Target,Unit,Status\nK,"unterminated,1,2,%,pass'])assert.throws(()=>parseCsvReport(bad));});
