import test from 'node:test';import assert from 'node:assert/strict';import {createMixedRouteEmphasis} from '../../../user_application/web/scripts/nodes/mixed_route_emphasis.js';import {NODE_COMMUNICATION_METADATA} from '../../../user_application/web/scripts/nodes/node_timeline.js';import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const codec=createUtcCodec(LEAP_SHA256),utc=codec.advance('2026-10-07T00:00:00Z',0),hash='a'.repeat(64),freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
function fixture({count=2,mutate=null}={}){let display={utc:codec.advance(utc,2),key:'catalog:native',source:'catalog',leap_sha256:LEAP_SHA256,eop_sha256:'b'.repeat(64)},valid=true,selected='A|B',hook=null,displayHook=null,selectedHook=null,view;
 const ids=Array.from({length:count},(_,i)=>i<2?['A','B'][i]:'N'+i),native={...NODE_COMMUNICATION_METADATA,schema_version:1,status:'valid',error:null,utc,node_definitions:ids.map(id=>({id,schema:1})),definition_hashes:Object.fromEntries(ids.map(id=>[id,hash])),stations:[{id:'G',enabled:true}],faults:[],network:{time:new Date(Date.parse(utc)).toISOString(),nodes:[...ids.map(id=>({id,kind:'satellite'})),{id:'G',kind:'ground'}],links:[{id:'A|B',a:'A',b:'B',kind:'oisl'},{id:'B|G',a:'B',b:'G',kind:'ground'}]}};
 const receipt={instance_id:'module',sequence:1,network_hash:hash},route={...receipt,status:'available',source:'A',target:'G',path:['A','B','G'],hop_list:[{link_id:'A|B',from:'A',to:'B',kind:'oisl'},{link_id:'B|G',from:'B',to:'G',kind:'ground'}]};const data={presentation_kind:'FABRIC_ANALYTICAL_UI_V1',analysis_utc:utc,receipt,route,native_snapshot:native,network:native.network,source:'captured_native_analysis',current_analysis:false};mutate?.(data);view=freeze(data);
 const owner=createMixedRouteEmphasis({readNetwork:()=>null,verifyNetwork:()=>false,readFabric:()=>null,readDisplay:()=>{displayHook?.();return structuredClone(display);},readAnalyticalFabric:()=>view,verifyAnalyticalFabric:value=>{hook?.();return valid&&value===view;},readSelectedLinkId:()=>{selectedHook?.();return selected;},differenceUtc:codec.difference});return {owner,view,native,display,set selected(value){selected=value;},set hook(value){hook=value;},set displayHook(value){displayHook=value;},set selectedHook(value){selectedHook=value;},revoke(){valid=false;},replace(){view=freeze(structuredClone(view));},read:()=>owner.readAnalytical({utc:display.utc})};}
test('registered full240 historical route borrows full native/fabric identity and preserves captured UTC',()=>{const f=fixture({count:240}),view=f.read();assert.ok(view);assert.equal(view.fabric_view,f.view);assert.equal(view.native_snapshot,f.view.native_snapshot);assert.equal(view.node_definitions.length,240);assert.deepEqual(view.routed_ids,['A|B','B|G']);assert.equal(view.selected_id,'A|B');assert.equal(view.analysis_utc,utc);assert.equal(view.display_utc,f.display.utc);assert.equal(view.age_seconds,2);assert.equal(view.current_analysis,false);assert.equal(Object.isFrozen(view),true);assert.equal(f.owner.verifyAnalytical(view,{utc:f.display.utc,nodes:view.node_definitions}),true);assert.equal(f.owner.verifyAnalytical(structuredClone(view),{utc:f.display.utc}),false);assert.equal(f.owner.verify(view,{utc}),false);assert.equal(f.read(),view);f.owner.destroy();});
for(const mutate of [v=>v.native_snapshot.definition_hashes.A='bad',v=>v.native_snapshot.definition_hashes.X=hash,v=>v.native_snapshot.frame='foreign',v=>v.native_snapshot.network.links[0].b='foreign',v=>v.route.hop_list[1].to='foreign',v=>v.route.hop_list[0].kind='ground',v=>v.route.sequence++,v=>v.native_snapshot.network.time='2020-01-01T00:00:00Z',v=>v.native_snapshot.network.nodes.pop()])test('all captured native metadata/hash/fullhop roster validated before projection '+String(mutate),()=>{const f=fixture({mutate});assert.equal(f.read(),null);f.owner.destroy();});
for(const change of ['fabric','selection','source','UTC','clear','dispose'])test('analytical route revocation '+change+' cannot resurrect same old registration',()=>{const f=fixture(),view=f.read();assert.ok(view);if(change==='fabric')f.replace();if(change==='selection')f.selected='B|G';if(change==='source')f.display.key='stored:foreign';if(change==='UTC')f.display.utc=codec.advance(utc,3);if(change==='clear')f.owner.clearAnalytical();if(change==='dispose')f.owner.destroy();assert.equal(f.owner.verifyAnalytical(view,{utc:view.display_utc}),false);assert.equal(f.owner.verifyAnalytical(view,{utc:view.display_utc}),false);f.owner.destroy();});
test('terminal actual verifier callback clear/source mutation prevents analytical publication',()=>{for(const change of ['clear','source']){const f=fixture();let once=true;f.hook=()=>{if(once){once=false;if(change==='clear')f.owner.clearAnalytical();else f.display.key='catalog:foreign';}};assert.equal(f.read(),null);f.owner.destroy();}});

for(const getter of ['display','selection'])test('terminal '+getter+' owner callback revokes fabric registration before final proof',()=>{const f=fixture(),value=f.read();assert.ok(value);let reads=0;const hook=()=>{if(++reads===(getter==='display'?3:3))f.revoke();};if(getter==='display')f.displayHook=hook;else f.selectedHook=hook;assert.equal(f.owner.verifyAnalytical(value,{utc:f.display.utc}),false);assert.equal(f.owner.verifyAnalytical(value,{utc:f.display.utc}),false);f.owner.destroy();});
