import test from 'node:test';
import assert from 'node:assert/strict';
import {createMixedRouteEmphasis} from '../../../user_application/web/scripts/nodes/mixed_route_emphasis.js';
const utc='2026-10-04T22:01:12.000000000Z',hash='a'.repeat(64),freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
function fixture(){
 const nodes=[{schema:1,id:'A',name:'A'},{schema:1,id:'B',name:'B'}],proof={status:'valid',utc,node_definitions:nodes,definition_hashes:{A:hash,B:hash},stations:[{id:'G'}],faults:[],network:{time:'2026-10-04T22:01:12.000Z',nodes:[{id:'A'},{id:'B'},{id:'G'}],links:[{id:'A|B',a:'A',b:'B',kind:'oisl'},{id:'B|G',a:'B',b:'G',kind:'ground'}]}};
 const receipt={instance_id:'module',sequence:1,network_hash:hash},route={instance_id:'module',sequence:1,network_hash:hash,status:'available',path:['A','B','G'],hop_list:[{link_id:'A|B',from:'A',to:'B',kind:'oisl'},{link_id:'B|G',from:'B',to:'G',kind:'ground'}]};let state={status:'accepted',pending:false,error:'',refresh_required:false,receipt,route},display={utc,key:'stored:one',source:'stored'},valid=true,reads=0,hook=null,verifyHook=null;
 const owner=createMixedRouteEmphasis({readNetwork:()=>{reads++;hook?.();return structuredClone(proof);},verifyNetwork:()=>{verifyHook?.();return valid;},readFabric:()=>structuredClone(state),readDisplay:()=>structuredClone(display)});
 return {owner,proof,receipt,route,nodes,get state(){return state;},set state(v){state=v;},display,set valid(v){valid=v;},get reads(){return reads;},set hook(v){hook=v;},set verifyHook(v){verifyHook=v;},capture:()=>owner.capture({snapshot:proof,receipt,route,selectedLinkId:'A|B'})};
}
test('mixed full-hop native/fabric proof projects only OISL IDs with source selection',()=>{const f=fixture(),view=f.capture();assert.equal(view.presentation_kind,'MIXED_ROUTE_EMPHASIS_UI_V1');assert.deepEqual(view.routed_ids,['A|B']);assert.equal(view.selected_id,'A|B');assert.deepEqual(view.node_definitions,f.nodes);assert.equal(Object.isFrozen(view.oisl_links[0]),true);assert.equal(f.owner.verify(view,{utc,nodes:f.nodes}),true);assert.equal(f.owner.verify(structuredClone(view),{utc}),false);assert.equal(f.owner.verify(freeze(structuredClone(view)),{utc}),false);f.owner.destroy();});
test('selection-only native projection does not require module acceptance or create route claims',()=>{const f=fixture();f.state={status:'error',pending:true,error:'unavailable',refresh_required:true,receipt:null,route:null};const view=f.owner.capture({snapshot:f.proof,selectedLinkId:'A|B'});assert.ok(view);assert.deepEqual(view.routed_ids,[]);assert.equal(view.selected_id,'A|B');assert.equal(f.owner.verify(view,{utc}),true);f.owner.destroy();});
for(const change of ['native','node','hash','station','fault','UTC','source','pending','error','review','instance','sequence','route','hop','clear','dispose'])test('route proof revocation '+change,()=>{const f=fixture(),view=f.capture();assert.ok(view);if(change==='native')f.valid=false;if(change==='node')f.proof.node_definitions[0].name='edited';if(change==='hash')f.proof.definition_hashes.A='b'.repeat(64);if(change==='station')f.proof.stations[0].id='X';if(change==='fault')f.proof.faults.push({id:'F'});if(change==='UTC')f.display.utc='2026-10-04T22:01:13.000000000Z';if(change==='source')f.display.key='stored:foreign';if(['pending','error','review'].includes(change))f.state[change==='review'?'refresh_required':change]=change==='error'?'failed':true;if(change==='instance')f.state.receipt.instance_id='foreign';if(change==='sequence')f.state.receipt.sequence++;if(change==='route')f.state.route.status='unavailable';if(change==='hop')f.state.route.hop_list[1].link_id='foreign';if(change==='clear')f.owner.clear();if(change==='dispose')f.owner.destroy();assert.equal(f.owner.verify(view,{utc,nodes:f.nodes}),false);assert.equal(f.owner.read({utc}),null);});
test('sampled/foreign hop/false copied native proof never registers route',()=>{for(const mutate of [f=>f.proof.presentation_kind='NETWORK_SAMPLED_UI_V1',f=>f.route.hop_list[1].to='foreign',f=>f.route.sequence++,f=>f.route.hop_list[0].kind='ground']){const f=fixture();mutate(f);assert.equal(f.capture(),null);f.owner.destroy();}});
test('full240 node scope is retained and changed final roster rejects',()=>{const f=fixture();f.proof.node_definitions=Array.from({length:240},(_,i)=>({schema:1,id:i<2?['A','B'][i]:'N'+i}));f.proof.definition_hashes=Object.fromEntries(f.proof.node_definitions.map(n=>[n.id,hash]));const view=f.capture();assert.equal(view.node_definitions.length,240);assert.equal(f.owner.verify(view,{utc,nodes:f.proof.node_definitions.slice(0,239)}),false);f.owner.destroy();});
test('inactive or different UTC uses zero full network getters; failed registration never revives',()=>{const f=fixture();assert.equal(f.owner.read({utc}),null);assert.equal(f.reads,0);const view=f.capture(),count=f.reads;assert.equal(f.owner.read({utc:'2026-10-04T22:01:13.000000000Z'}),null);assert.equal(f.reads,count);assert.equal(f.owner.verify(view,{utc}),false);f.owner.destroy();});
test('reentrant clear during full native callback cannot publish or revive old projection',()=>{const f=fixture();let once=true;f.hook=()=>{if(once){once=false;f.owner.clear();}};assert.equal(f.capture(),null);f.hook=null;const view=f.capture();f.hook=()=>f.owner.clear();assert.equal(f.owner.verify(view,{utc}),false);f.hook=null;assert.equal(f.owner.verify(view,{utc}),false);f.owner.destroy();});

for(const change of ['pending','source'])test('terminal native verifier mutation revokes route '+change,()=>{const f=fixture(),view=f.capture();let calls=0;f.verifyHook=()=>{if(++calls===3){if(change==='pending')f.state.pending=true;else f.display.key='stored:other';}};assert.equal(f.owner.verify(view,{utc}),false);f.verifyHook=null;assert.equal(f.owner.verify(view,{utc}),false);f.owner.destroy();});
