import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('./native_network_sampled_scene.test.mjs',import.meta.url),'utf8');
const prefix=source.slice(0,source.indexOf('const shown=')).replace(/from '([^']+)'/g,(all,path)=>path.startsWith('.')?`from '${new URL(path,import.meta.url).href}'`:all);
const {fixture,freeze,Collection,analysis,hash,C}=await import('data:text/javascript;base64,'+Buffer.from(prefix+'\nexport {fixture,freeze,Collection,analysis,hash,C};').toString('base64'));
function setup(count=1){const f=fixture(count);f.activate();let valid=true,hook=null;const view=freeze({presentation_kind:'MIXED_ROUTE_ANALYTICAL_UI_V1',analysis_utc:analysis,display_utc:f.utc,age_seconds:.5,current_analysis:false,availability:'accepted',reason:'captured_native_analysis',source:'captured_native_analysis',fabric_view:freeze({}),native_snapshot:structuredClone(f.original),node_definitions:structuredClone(f.original.node_definitions),definition_hashes:structuredClone(f.original.definition_hashes),oisl_links:[],ground_links:f.original.network.links.map(l=>({id:l.id,a:l.a,b:l.b})),routed_ids:['G0A0'],selected_id:'G0A0'});f.scene.analyticalRouteEmphasis={read:()=>view,verify:v=>{hook?.();return valid&&v===view;}};return {f,scene:f.scene,view,get line(){return f.scene.groundLinks.get('G0A0').line;},set valid(v){valid=v;},set hook(v){hook=v;}};}
test('historical ground route overrides only existing material width/color and preserves current geometry',()=>{const x=setup();try{const material=x.line.material,positions=x.line.positions;x.scene.syncFrame(x.f.utc,2000);assert.equal(x.line.width,4.5);assert.equal(x.line.material.uniforms.color.css,'#a78bfa');assert.deepEqual(x.line.positions,positions);assert.equal(x.scene.groundLinks.size,1);assert.equal(x.scene.analyticalRouteReceipt.view,x.view);assert.equal(x.scene.receipt,null);x.valid=false;x.scene.syncFrame(x.f.utc);assert.equal(x.line.width,2);assert.equal(x.line.material,material);assert.equal(x.scene.analyticalRouteReceipt,null);}finally{x.scene.destroy();}});
test('selected-only ground retains source base material and does not create missing captured links',()=>{const x=setup();try{const v=freeze({...x.view,routed_ids:['missing']});x.scene.analyticalRouteEmphasis={read:()=>v,verify:value=>value===v};x.scene.syncFrame(x.f.utc);assert.equal(x.line.width,4);assert.equal(x.line.material.type,'PolylineDash');assert.equal(x.scene.groundLinks.size,1);}finally{x.scene.destroy();}});
test('all 240 native endpoints remain checked even if route contains one satellite',()=>{const x=setup(240);try{let calls=0;const read=x.scene.geometryFor;x.scene.geometryFor=(...a)=>{calls++;const g=read(...a);return a[0].id==='A239'?{...g,definition_hash:'b'.repeat(64)}:g;};assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.f.utc),false);assert.equal(calls,240);assert.equal(x.line.width,2);assert.equal(x.scene.analyticalRouteReceipt,null);}finally{x.scene.destroy();}});
for(const kind of ['copy','hash','scope','native','morph','UTC'])test('analytical ground refuses '+kind,()=>{const x=setup();try{x.scene.applyAnalyticalRouteEmphasis(x.f.utc);if(kind==='copy')x.scene.analyticalRouteEmphasis={read:()=>freeze(structuredClone(x.view)),verify:()=>false};if(kind==='hash')x.f.geometryHook=g=>({...g,definition_hash:'b'.repeat(64)});if(kind==='scope'){const v=freeze({...x.view,node_definitions:[]});x.scene.analyticalRouteEmphasis={read:()=>v,verify:()=>true};}if(kind==='native')x.f.geometryHook=g=>({...g,row:{...g.row,position_m:[NaN,2,3]}});if(kind==='morph')x.f.viewer.scene.mode=0;if(kind==='UTC')x.f.utc=analysis;assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.view.display_utc),false);assert.equal(x.line.width,2);assert.equal(x.scene.analyticalRouteReceipt,null);}finally{x.scene.destroy();}});
test('hidden/clear consumer cannot reuse old projection after reentry',()=>{const x=setup();try{x.scene.applyAnalyticalRouteEmphasis(x.f.utc);x.scene.setGroundLinksVisible(false);x.scene.setGroundLinksVisible(true);x.scene.syncFrame(x.f.utc);assert.equal(x.line.width,2);const v=freeze({...x.view,fabric_view:freeze({})});x.scene.analyticalRouteEmphasis={read:()=>v,verify:value=>value===v};x.scene.syncFrame(x.f.utc);assert.equal(x.line.width,4.5);x.scene.clear();x.f.activate();assert.equal(x.line.width,2);}finally{x.scene.destroy();}});
test('early morph failure cannot revive the previous analytical ground projection',()=>{const x=setup();try{x.scene.applyAnalyticalRouteEmphasis(x.f.utc);x.f.viewer.scene.mode=0;assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.f.utc),false);x.f.viewer.scene.mode=3;assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.f.utc),false);assert.equal(x.line.width,2);}finally{x.scene.destroy();}});
test('analytical marker can never enter exact network path even with permissive injected owners',()=>{const x=setup();try{x.scene.coverageRadiusKm=()=>100;assert.equal(x.scene.setSnapshot({snapshot:{...x.f.original,utc:x.f.utc,presentation_kind:'MIXED_ROUTE_ANALYTICAL_UI_V1'}}),false);assert.equal(x.scene.snapshot,null);}finally{x.scene.destroy();}});
test('newer nested selected-only analytical ground projection survives stale outer attempt',()=>{const x=setup();try{const next=freeze({...x.view,routed_ids:[]});let current=x.view,once=true;x.scene.analyticalRouteEmphasis={read:()=>current,verify:v=>{if(once){once=false;current=next;x.scene.applyAnalyticalRouteEmphasis(x.f.utc);}return current===v;}};assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.f.utc),false);assert.equal(x.line.width,4);assert.equal(x.scene.analyticalRouteReceipt.view,next);}finally{x.scene.destroy();}});
test('late mode getter lease revocation cannot publish analytical ground style',()=>{const x=setup();try{let checks=0,revoked=false;x.hook=()=>checks++;Object.defineProperty(x.f.viewer.scene,'mode',{get(){if(checks===3&&!revoked){revoked=true;x.valid=false;}return 3;},configurable:true});assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.f.utc),false);assert.equal(revoked,true);assert.equal(x.line.width,2);}finally{x.scene.destroy();}});
test('exact usable ground flow retains original material and phase under analytical color override',()=>{const x=setup();try{x.scene.coverageRadiusKm=()=>100;assert.equal(x.scene.setSnapshot({snapshot:{...x.f.original,utc:x.f.utc},receipt:{links:[{id:'G0A0',usable:true}]}}),true);const e=x.scene.groundLinks.get('G0A0'),material=e.material;x.scene.syncFrame(x.f.utc,3000);const time=material.uniforms.time;assert.equal(x.line.width,4.5);assert.equal(x.line.material,material);assert.equal(material.uniforms.color.css,'#a78bfa');assert.equal(material.uniforms.color.alpha,.55);x.valid=false;x.scene.applyAnalyticalRouteEmphasis(x.f.utc);assert.equal(x.line.width,2);assert.equal(x.line.material,material);assert.equal(material.uniforms.color.css,'#4ac4ee');assert.equal(material.uniforms.time,time);}finally{x.scene.destroy();}});
test('bounded 240-node analytical styling work records current native reads without claiming frame acceptance',t=>{const x=setup(240);try{const before=x.f.geometryReads,start=performance.now();for(let i=0;i<10;i++)assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.f.utc),true);const elapsed=performance.now()-start;assert.equal(x.f.geometryReads-before,2400);assert.equal(x.scene.groundLinks.size,240);assert.equal(x.f.fabricReads,0);t.diagnostic(JSON.stringify({kind:'isolated CPU styling only; shared host load, not GPU/frame acceptance',frames:10,nodes:240,existing_ground_lines:240,native_buffer_reads:x.f.geometryReads-before,fabric_queries:x.f.fabricReads,elapsed_ms:elapsed}));}finally{x.scene.destroy();}});
for(const kind of ['Viewer','UTC','clear','lease'])test('terminal ground proof callback '+kind+' restores prior source style',()=>{const x=setup();try{let checks=0,viewer=x.f.viewer;x.scene.viewerProvider=()=>viewer;x.hook=()=>{if(++checks===3){if(kind==='Viewer')viewer={scene:{mode:3,primitives:new Collection()},dataSources:new Collection()};if(kind==='UTC')x.f.utc=analysis;if(kind==='clear')x.scene.clear();if(kind==='lease')x.valid=false;}};assert.equal(x.scene.applyAnalyticalRouteEmphasis(x.f.utc),false);assert.equal(x.scene.analyticalRouteReceipt,null);if(x.scene.groundLinks.size)assert.equal(x.line.width,2);}finally{x.scene.destroy();}});
