import test from 'node:test';
import assert from 'node:assert/strict';
import {NativeNetworkScene,GROUND_LINK_COLORS} from '../../../digital_twin/visualization/native_network_scene.js';
class Collection{constructor(){this.items=[];}add(x){this.items.push(x);return x;}remove(x){this.items=this.items.filter(y=>y!==x);return true;}}
class Color{constructor(css,alpha=1){Object.assign(this,{css,alpha});}static fromCssColorString(css){return new Color(css);}withAlpha(alpha){return new Color(this.css,alpha);}}
Color.WHITE=new Color('white');
class Cartesian3{constructor(...values){this.values=values;}static fromDegrees(...values){return {degrees:values};}}
class Material{constructor(options){this.uniforms=options.fabric.uniforms;}static fromType(type,uniforms){return {type,uniforms};}}
const C={Color,Cartesian3,Material,PolylineCollection:Collection,CustomDataSource:class{constructor(){this.entities=new Collection();}},Cartesian2:class{},LabelStyle:{FILL_AND_OUTLINE:'outline'}};
const utc='2026-10-07T00:00:00.000000000Z',hash='a'.repeat(64),node={id:'A',schema:1,orbit:{altitude_km:550}},station={id:'G',name:'Ground',enabled:true,longitude:127,latitude:37,altitude_km:.1,min_elevation_deg:10};
function fixture(){let valid=true,stamp=utc,geometryValid=true,fabric={receipt:null,route:null};const viewer={scene:{primitives:new Collection()},dataSources:new Collection()};const proof={status:'valid',utc,definition_hashes:{A:hash},node_definitions:[structuredClone(node)],stations:[structuredClone(station)],network:{links:[{id:'AG',a:'G',b:'A',kind:'ground',state:'visible'}]}};
 const scene=new NativeNetworkScene({viewer,cesium:C,timeSource:()=>stamp,verifyNetworkSnapshot:()=>valid,readFabricState:()=>fabric,coverageRadiusKm:()=>100,geometryFor:(definition,{utc})=>geometryValid?{node_id:'A',node_definition:definition,definition_hash:hash,frame:'EARTH_FIXED_GMST_UTC_APPROX',inertial_frame:'SOURCE_MEAN_EQUATOR_EQUINOX_APPROX',time_model:'unix_ms_utc_approx',model_profile:'SOURCE_KEPLER_J2_V1',source_commit:'1a1e00297a0301637455b0ef2cf48b2e74576b07',quality:'engineering_assumption',row:{utc,status:'valid',error_code:null,position_m:[1,2,3]}}:null});
 return {scene,viewer,proof,set valid(v){valid=v;},set stamp(v){stamp=v;},set geometryValid(v){geometryValid=v;},set fabric(v){fabric=v;}};
}
test('source station ellipse and ground link geometry use shared viewer native positions only',()=>{const f=fixture();assert.equal(f.scene.setSnapshot({snapshot:f.proof}),true);const s=f.scene.stations.get('G'),l=f.scene.groundLinks.get('AG');assert.equal(s.coverage.ellipse.semiMajorAxis,100000);assert.equal(s.entity.point.pixelSize,10);assert.equal(l.line.show,true);assert.deepEqual(l.line.positions[0].degrees,[127,37,100]);assert.deepEqual(l.line.positions[1].values,[1,2,3]);assert.equal(l.line.material.type,'PolylineDash');assert.equal(l.line.width,2);assert.equal(GROUND_LINK_COLORS.visible,'#7a95ab');f.scene.destroy();assert.equal(f.viewer.scene.primitives.items.length,0);assert.equal(f.viewer.dataSources.items.length,0);});
test('fabric owner receipt route emphasis is revoked on failure and native epoch drift',()=>{const f=fixture(),receipt={links:[{id:'AG',usable:true}]},route={status:'available',hop_list:[{link_id:'AG'}]};f.fabric={status:'accepted',pending:false,error:'',refresh_required:false,receipt,route};f.scene.setSnapshot({snapshot:f.proof,receipt,route});const link=f.scene.groundLinks.get('AG');assert.equal(link.line.width,4.5);assert.equal(link.state,'usable');f.fabric={receipt:null,route:null};f.scene.syncFrame(utc,2000);assert.equal(link.line.width,2);assert.equal(link.state,'visible');f.stamp='other';f.scene.syncFrame('other');assert.equal(link.line.show,false);assert.equal(f.scene.stations.get('G').entity.show,false);f.scene.destroy();});
test('invalid snapshot and native proof cannot retain a drawable foreign endpoint',()=>{const f=fixture();f.scene.setSnapshot({snapshot:f.proof});f.geometryValid=false;f.scene.syncFrame(utc);assert.equal(f.scene.groundLinks.get('AG').line.show,false);f.valid=false;assert.equal(f.scene.setSnapshot({snapshot:f.proof}),false);assert.equal(f.scene.stations.size,0);f.scene.destroy();});
test('source visibility preferences and ownership cleanup preserve foreign resources',()=>{const f=fixture(),foreign={};f.viewer.scene.primitives.add(foreign);f.scene.setSnapshot({snapshot:f.proof});f.scene.setGroundLinksVisible(false);f.scene.setCoverageVisible(false);assert.equal(f.scene.groundLinks.get('AG').line.show,false);assert.equal(f.scene.stations.get('G').coverage.show,false);f.scene.destroy();assert.deepEqual(f.viewer.scene.primitives.items,[foreign]);});

test('retained fabric receipt cannot revive quality while conflicted, pending or failed',()=>{for(const update of [{pending:true},{status:'conflict'},{error:'failed'},{refresh_required:true}]){const f=fixture(),receipt={links:[{id:'AG',usable:true}]},route={status:'available',hop_list:[{link_id:'AG'}]};f.fabric={status:'accepted',pending:false,error:'',refresh_required:false,receipt,route};f.scene.setSnapshot({snapshot:f.proof,receipt,route});assert.equal(f.scene.groundLinks.get('AG').state,'usable');f.fabric={status:'accepted',pending:false,error:'',refresh_required:false,receipt,route,...update};f.scene.syncFrame(utc);assert.equal(f.scene.groundLinks.get('AG').state,'visible');assert.equal(f.scene.groundLinks.get('AG').line.width,2);f.scene.destroy();}});
test('coverage visibility control cannot revive a stale epoch',()=>{const f=fixture();f.scene.setSnapshot({snapshot:f.proof});f.stamp='other';f.scene.setCoverageVisible(true);assert.equal(f.scene.stations.get('G').coverage.show,false);f.scene.destroy();});

test('foreign or malformed native geometry is never drawn or relabeled as ITRF',()=>{for(const modify of [g=>({...g,frame:'ITRF'}),g=>({...g,inertial_frame:'GCRF'}),g=>({...g,time_model:'tai'}),g=>({...g,node_id:'other'}),g=>({...g,definition_hash:'bad'}),g=>({...g,node_definition:{...g.node_definition,id:'other'}}),g=>({...g,row:{...g.row,utc:'other'}}),g=>({...g,row:{...g.row,position_m:[NaN,2,3]}})]){const f=fixture(),original=f.scene.geometryFor;f.scene.geometryFor=(...args)=>modify(original(...args));f.scene.setSnapshot({snapshot:f.proof});assert.equal(f.scene.groundLinks.get('AG').line.show,false);f.scene.destroy();}});
test('malformed station proof is rejected before adding entities',()=>{const f=fixture();f.proof.stations[0].longitude=NaN;assert.equal(f.scene.setSnapshot({snapshot:f.proof}),false);assert.equal(f.viewer.dataSources.items.length,0);f.scene.destroy();});

test('frame-local endpoint reuse is fenced if an injected native read invalidates the owner',()=>{const f=fixture(),original=f.scene.geometryFor;let reads=0;for(let i=1;i<4;i++){f.proof.stations.push({...station,id:'G'+i});f.proof.network.links.push({...f.proof.network.links[0],id:'AG'+i,a:'G'+i});}f.scene.geometryFor=(...args)=>{reads++;return original(...args);};f.scene.setSnapshot({snapshot:f.proof});reads=0;f.scene.syncFrame(utc);assert.equal(reads,1);f.scene.geometryFor=(...args)=>{f.valid=false;return original(...args);};f.scene.syncFrame(utc);for(const entry of f.scene.groundLinks.values())assert.equal(entry.line.show,false);for(const entry of f.scene.stations.values())assert.equal(entry.coverage.show,false);f.scene.destroy();});
