import test from 'node:test';
import assert from 'node:assert/strict';
import {NativeNetworkScene} from '../../../digital_twin/visualization/native_network_scene.js';
class Collection{constructor(){this.items=[];}add(v){this.items.push(v);return v;}remove(v){this.items=this.items.filter(x=>x!==v);return true;}}
class Color{constructor(css,alpha=1){Object.assign(this,{css,alpha});}static fromCssColorString(css){return new Color(css);}withAlpha(alpha){return new Color(this.css,alpha);}}
Color.WHITE=new Color('white');
class Cartesian3{constructor(...values){this.values=values;}static fromDegrees(...degrees){return {degrees};}}
class Material{constructor(o){this.uniforms=o.fabric.uniforms;}static fromType(type,uniforms){return {type,uniforms};}}
const C={Color,Cartesian3,Material,PolylineCollection:Collection,CustomDataSource:class{constructor(){this.entities=new Collection();}},Cartesian2:class{},LabelStyle:{},SceneMode:{MORPHING:0,SCENE3D:3,SCENE2D:2}};
const metadata={frame:'EARTH_FIXED_GMST_UTC_APPROX',inertial_frame:'SOURCE_MEAN_EQUATOR_EQUINOX_APPROX',time_model:'unix_ms_utc_approx',model_profile:'SOURCE_KEPLER_J2_V1',source_commit:'1a1e00297a0301637455b0ef2cf48b2e74576b07',quality:'engineering_assumption'};
const analysis='2026-10-07T00:00:00.000000000Z',display='2026-10-07T00:00:00.500000000Z',hash='a'.repeat(64);
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
function fixture(count=1,stationCount=1){
 let utc=display,live=true,lease=0,readCount=0,geometryReads=0,fabricReads=0,checks=0,readHook=null,geometryHook=null,verifyHook=null,coverageHook=null;
 const viewer={scene:{mode:3,primitives:new Collection()},dataSources:new Collection()};
 const nodes=Array.from({length:count},(_,i)=>({id:'A'+i,schema:1,orbit:{altitude_km:550},name:'Satellite '+i}));
 const stations=Array.from({length:stationCount},(_,i)=>({id:'G'+i,name:'Ground '+i,enabled:true,longitude:127-i,latitude:37,altitude_km:.1,min_elevation_deg:10}));
 const links=stations.flatMap(s=>nodes.map(n=>({id:s.id+n.id,a:s.id,b:n.id,kind:'ground',state:'visible',faulted:false})));
 const original={schema_version:1,...metadata,status:'valid',error:null,utc:analysis,node_definitions:nodes,definition_hashes:Object.fromEntries(nodes.map(n=>[n.id,hash])),stations,faults:[],network:{time:'2026-10-07T00:00:00.000Z',nodes:[...nodes.map(n=>({id:n.id,kind:'satellite'})),...stations.map(s=>({id:s.id,kind:'ground'}))],links}};
 const registered=new WeakMap();let last=null,availability='sampled',substitute=null;
 const read=()=>{readCount++;readHook?.();if(substitute)return substitute;last=freeze({...structuredClone(original),presentation_kind:'NETWORK_SAMPLED_UI_V1',analysis_utc:analysis,display_utc:utc,age_seconds:(Date.parse(utc)-Date.parse(analysis))/1000,current_analysis:utc===analysis,availability,reason:'current_analysis_unavailable'});registered.set(last,lease);return last;};
 const verify=(v,{utc:requested}={})=>{checks++;verifyHook?.();return live&&registered.has(v)&&registered.get(v)===lease&&v.display_utc===utc&&requested===utc;};
 const scene=new NativeNetworkScene({viewer,cesium:C,timeSource:()=>utc,verifyNetworkSnapshot:()=>true,readFabricState:()=>{fabricReads++;return {status:'accepted',pending:false,receipt:{links:links.map(l=>({id:l.id,usable:true}))}};},coverageRadiusKm:(s,scope)=>{coverageHook?.(s,scope);assert.equal(scope.presentation_kind,'NETWORK_SAMPLED_UI_V1');assert.equal(scope.node_definitions.length,count);return 100;},sampledNetwork:{read,verify},geometryFor:(n,{utc:stamp})=>{geometryReads++;const row={utc:stamp,status:'valid',error_code:null,position_m:[Date.parse(stamp)-Date.parse(analysis),2,3]};const g={...metadata,node_id:n.id,node_definition:n,definition_hash:hash,row};return geometryHook?.(g)??g;}});
 return {scene,viewer,original,get last(){return last;},get utc(){return utc;},set utc(v){utc=v;},get reads(){return readCount;},get geometryReads(){return geometryReads;},get fabricReads(){return fabricReads;},get checks(){return checks;},set availability(v){availability=v;},set substitute(v){substitute=v;},set readHook(v){readHook=v;},set geometryHook(v){geometryHook=v;},set verifyHook(v){verifyHook=v;},set coverageHook(v){coverageHook=v;},revoke(){lease++;},fail(){live=false;},activate(){scene.setSampledActive(true);scene.syncFrame(utc,1000);}};
}
const shown=f=>[...f.scene.groundLinks.values()].filter(e=>e.line.show).length;
const hidden=f=>{assert.equal(shown(f),0);for(const e of f.scene.stations.values()){assert.equal(e.entity.show,false);assert.equal(e.coverage.show,false);}};
test('sampled port is inactive by default and draws historical analysis at current native endpoints without fabric authority',()=>{const f=fixture();f.scene.syncFrame(f.utc);assert.equal(f.reads,0);f.activate();assert.equal(shown(f),1);const e=f.scene.groundLinks.get('G0A0');assert.deepEqual(e.line.positions[1].values,[500,2,3]);assert.equal(e.state,'visible');assert.equal(e.line.material.type,'PolylineDash');assert.equal(e.line.width,2);assert.equal(f.fabricReads,0);assert.equal(f.scene.snapshot,null);assert.equal(f.scene.sampledSnapshot.utc,analysis);assert.equal(f.scene.sampledSnapshot.display_utc,display);assert.equal(f.scene.stations.get('G0').coverage.ellipse.semiMajorAxis,100000);});
test('clear disables before cleanup and no valid lease can resurrect until explicit consumer reentry',()=>{const f=fixture();f.activate();const old=[...f.scene.groundLinks.values()][0].line;f.scene.clear();assert.equal(old.show,false);const reads=f.reads;f.scene.syncFrame(f.utc);assert.equal(f.reads,reads);assert.equal(f.scene.stations.size,0);f.activate();assert.equal(shown(f),1);});
test('sampled marker cannot enter exact snapshot even with a permissive exact verifier',()=>{const f=fixture();f.activate();assert.equal(f.scene.setSnapshot({snapshot:f.last}),false);assert.equal(f.scene.snapshot,null);assert.equal(f.scene.stations.size,0);});
test('verified retained pending analysis remains visible; copied/fake/unavailable/error projections hide',()=>{const f=fixture();f.activate();f.availability='pending';f.scene.syncFrame(f.utc);assert.equal(shown(f),1);f.substitute=freeze(structuredClone(f.last));f.scene.syncFrame(f.utc);hidden(f);f.substitute=null;f.availability='unavailable';f.scene.syncFrame(f.utc);hidden(f);f.availability='error';f.scene.syncFrame(f.utc);hidden(f);});
test('same UTC station/fault/scope revocation at final transition callback hides all owned resources',()=>{const f=fixture();f.activate();let revoke=false;f.scene.isTransitioning=()=>{if(revoke)f.revoke();return false;};revoke=true;f.scene.syncFrame(f.utc);hidden(f);});
test('transition callback clear or deactivate cannot publish or resurrect a stale frame',()=>{for(const operation of ['clear','deactivate','destroy']){const f=fixture();f.activate();let once=true;f.scene.isTransitioning=()=>{if(once){once=false;operation==='deactivate'?f.scene.setSampledActive(false):f.scene[operation]();}return false;};f.scene.syncFrame(f.utc);hidden(f);const reads=f.reads;f.scene.syncFrame(f.utc);assert.equal(f.reads,reads);}});
test('stable Viewer replacement hides old owned lines without moving or deleting foreign primitives',()=>{const f=fixture();f.activate();const foreign={};f.viewer.scene.primitives.add(foreign);const next={scene:{mode:3,primitives:new Collection()},dataSources:new Collection()};f.scene.viewerProvider=next;f.scene.syncFrame(f.utc);hidden(f);assert.equal(next.scene.primitives.items.length,0);f.scene.destroy();assert.deepEqual(f.viewer.scene.primitives.items,[foreign]);});
test('a final transition callback changing the actual Viewer behind an unchanged provider cannot publish old-owner resources',()=>{const f=fixture();let actual=f.viewer;f.scene.viewerProvider=()=>actual;f.activate();const next={scene:{mode:3,primitives:new Collection()},dataSources:new Collection()};let calls=0;f.scene.isTransitioning=()=>{if(++calls===3)actual=next;return false;};f.scene.syncFrame(f.utc);assert.equal(calls,3);hidden(f);assert.equal(next.scene.primitives.items.length,0);});
test('a final owner verifier changing the actual Viewer behind a stable provider hides old owned resources',()=>{const f=fixture();let actual=f.viewer;f.scene.viewerProvider=()=>actual;f.activate();const next={scene:{mode:3,primitives:new Collection()},dataSources:new Collection()};let checks=0;f.verifyHook=()=>{if(++checks===3)actual=next;};f.scene.syncFrame(f.utc);hidden(f);assert.equal(f.scene.sampledSnapshot,null);assert.equal(next.scene.primitives.items.length,0);});
test('post-verifier actual provider reads that revoke a same-UTC lease require terminal owner proof',()=>{const f=fixture();f.activate();let checks=0,revoked=false;f.verifyHook=()=>{checks++;};f.scene.viewerProvider=()=>{if(checks===3&&!revoked){revoked=true;f.revoke();}return f.viewer;};f.scene.syncFrame(f.utc);assert.equal(revoked,true);hidden(f);assert.equal(f.scene.sampledSnapshot,null);});
test('material construction reentry cannot overwrite the newer registered frame state or clear its visual',()=>{const f=fixture();f.activate();f.original.network.links[0].faulted=true;const original=C.Material.fromType;let once=false;C.Material.fromType=(...args)=>{if(!once){once=true;f.original.network.links[0].faulted=false;f.scene.syncFrame(f.utc);}return original(...args);};try{f.scene.syncFrame(f.utc);const entry=f.scene.groundLinks.get('G0A0');assert.equal(f.scene.sampledSnapshot.network.links[0].faulted,false);assert.equal(entry.state,'visible');assert.equal(entry.line.material.uniforms.dashLength,10);assert.equal(entry.line.show,true);}finally{C.Material.fromType=original;}});
test('native endpoint failure, foreign definition/hash/profile, and display drift hide all sampled coverage',()=>{for(const modify of [g=>({...g,definition_hash:'b'.repeat(64)}),g=>({...g,node_definition:{...g.node_definition,name:'foreign'}}),g=>({...g,frame:'ITRF'}),g=>({...g,row:{...g.row,position_m:[NaN,2,3]}}),g=>({...g,row:{...g.row,utc:analysis}})]){const f=fixture();f.activate();f.geometryHook=modify;f.scene.syncFrame(f.utc);hidden(f);}const f=fixture();f.activate();f.geometryHook=g=>{f.utc=analysis;return g;};f.scene.syncFrame(display);hidden(f);});
test('source native proof and complete immutable model/station/hash scope are mandatory even with permissive injected verification',()=>{for(const mutate of [v=>v.quality='measured',v=>v.analysis_utc=display,v=>v.network.time='other',v=>delete v.definition_hashes.A0,v=>v.stations[0].longitude=NaN,v=>v.node_definitions.push({...v.node_definitions[0]}),v=>v.network.nodes.pop(),v=>v.network.links[0].a='foreign',v=>v.age_seconds=NaN]){const f=fixture();f.activate();const v=structuredClone(f.last);mutate(v);f.substitute=freeze(v);f.scene.sampledNetwork.verify=()=>true;f.scene.syncFrame(f.utc);hidden(f);}const f=fixture();f.activate();f.substitute=structuredClone(f.last);f.scene.sampledNetwork.verify=()=>true;f.scene.syncFrame(f.utc);hidden(f);});
test('coverage callback reentry and verifier reentry cannot write after clear',()=>{for(const hook of ['coverageHook','verifyHook']){const f=fixture();let once=true;f[hook]=()=>{if(once){once=false;f.scene.clear();}};f.activate();assert.equal(f.scene.stations.size,0);assert.equal(f.scene.groundLinks.size,0);}});
test('morph and preferences hide ground lines and coverage, and 2D resumes source geometry',()=>{const f=fixture();f.activate();f.viewer.scene.mode=0;f.scene.syncFrame(f.utc);hidden(f);f.viewer.scene.mode=2;f.scene.syncFrame(f.utc);assert.equal(shown(f),1);f.scene.setGroundLinksVisible(false);assert.equal(shown(f),0);f.scene.setCoverageVisible(false);assert.equal(f.scene.stations.get('G0').coverage.show,false);f.scene.setGroundLinksVisible(true);assert.equal(shown(f),1);assert.equal(f.scene.stations.get('G0').coverage.show,false);});
test('all 240 nodes and 24 stations preserve source fleet coverage and reuse one current endpoint per satellite',()=>{const f=fixture(240,24);f.activate();assert.equal(f.scene.stations.size,24);assert.equal(shown(f),5760);assert.equal(f.geometryReads,240);const lines=[...f.scene.groundLinks.values()].map(e=>e.line),before=f.geometryReads;f.utc='2026-10-07T00:00:00.600000000Z';f.scene.syncFrame(f.utc);assert.equal(f.geometryReads-before,240);assert.equal(shown(f),5760);assert.deepEqual([...f.scene.groundLinks.values()].map(e=>e.line),lines);assert.equal(f.fabricReads,0);});
