import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {createNodeNetworkTimeline} from '../../../user_application/web/scripts/nodes/network_timeline.js';
import {createNodeOpticalTimeline} from '../../../user_application/web/scripts/nodes/optical_timeline.js';
import {createNodeLinkResolver} from '../../../user_application/web/scripts/nodes/links.js';
import {createNodeLibrary} from '../../../digital_twin/model_library/browser/satellite_nodes.js';
import {orbitElements,catalogElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import * as stationModel from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as oisl from '../../../digital_twin/simulation/browser/oisl.js';
import {createGroundLinkModel} from '../../../digital_twin/simulation/browser/ground_links.js';
import {createNetworkSnapshotModel} from '../../../digital_twin/simulation/browser/network_snapshot.js';
import {NODE_COMMUNICATION_METADATA} from '../../../user_application/web/scripts/nodes/node_timeline.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const fixture=JSON.parse(gunzipSync(await readFile(new URL('../fixtures/original_node_link_resolution.json.gz',import.meta.url))));
const scenario=fixture.cases.find(c=>c.id==='dense-two-plane:0'),codec=createUtcCodec(LEAP_SHA256);
function setup(action,observer,options={}){
 let lease=Object.freeze({}),available=true,hook=null;let nodes=structuredClone(scenario.rows[0].input.nodes),utc=codec.advance(new Date(fixture.epoch).toISOString(),0),stations=[stationModel.createStation({preset:'daejeon'})],faults=[];
 let eq=0;const calls=[],events=[],library=createNodeLibrary({orbitElements,catalogElements,createEquipmentId:()=>`EQ-NET-SAMPLE-${++eq}`});
 if(options.count)nodes=Array.from({length:options.count},(_,i)=>library.cloneNode(nodes[0],{epoch:fixture.epoch,id:'NET-'+i,catalogNumber:900001+i}));
 const request=async(stamp,options)=>{
  calls.push({utc:stamp,signal:options.signal});
  const source=new Map(scenario.rows.find(r=>r.input.date===Date.parse(stamp))?.input.states??scenario.rows.at(-1).input.states);
  const value={utc:stamp,node_definitions:structuredClone(nodes),states:nodes.map(node=>[node.id,{...NODE_COMMUNICATION_METADATA,...structuredClone(source.get(node.id)??source.get(scenario.rows[0].input.nodes.find(n=>n.catalog_number===node.catalog_number)?.id)??source.values().next().value),node_id:node.id,node_definition:structuredClone(node),definition_hash:'a'.repeat(64),utc:stamp,interpolated:false}])};
  return action?action(value,options,calls):value;
 };
 const optical=createNodeOpticalTimeline({resolver:createNodeLinkResolver({library,oisl}),requestCommunicationStates:request,readNodes:()=>nodes,readDisplay:()=>{const value={utc,key:'catalog:sampled',source:'catalog',leap_sha256:LEAP_SHA256};hook?.();return value;},advanceUtc:codec.advance,readContinuity:()=>available?lease:null,verifyContinuity:v=>available&&v===lease});
 const model=createNetworkSnapshotModel({library,groundLinks:createGroundLinkModel({library,stationModel}),oisl});
 const network=createNodeNetworkTimeline({model,optical:options.opticalFacade?.(optical)??optical,requestCommunicationStates:request,readNodes:options.readNodes??(()=>nodes),nodeScopeRevision:options.nodeScopeRevision??null,readDisplay:()=>{const value={utc,key:'catalog:sampled',source:'catalog',leap_sha256:LEAP_SHA256};hook?.();return value;},readStations:()=>stations,readFaults:()=>faults,validateNode:library.validateNode,validateStation:stationModel.validateStation,advanceUtc:codec.advance,readContinuity:options.noContinuity?null:()=>available?lease:null,verifyContinuity:options.noContinuity?null:v=>available&&v===lease,onChange:value=>{events.push(value);observer?.(value);}});
 return {network,optical,calls,events,model,revoke(){lease=Object.freeze({});},set hook(v){hook=v;},unavailable(){available=false;},recover(){available=true;lease=Object.freeze({});},recoverSameLease(){available=true;},get nodes(){return structuredClone(nodes);},set nodes(v){nodes=structuredClone(v);},get utc(){return utc;},set utc(v){utc=v;},get stations(){return structuredClone(stations);},set stations(v){stations=structuredClone(v);},get faults(){return structuredClone(faults);},set faults(v){faults=structuredClone(v);}};
}

const until=async predicate=>{for(let i=0;i<100&&!predicate();i++)await new Promise(resolve=>setImmediate(resolve));assert.ok(predicate());};
const close=s=>{s.network.destroy();s.optical.destroy();};
for(const owner of ['optical','network'])test(`${owner} raw native capability survives natural next analysis without authorizing an exact action`,async()=>{const s=setup(undefined,undefined,{count:2});try{await s.optical.updateSampled();await s.network.updateSampled();const o=s[owner],token=o.captureRawAnalysis(),at=s.utc,history=s.optical.historyEntries(),calls=s.calls.length;assert.ok(token);assert.equal(token.kind,owner==='optical'?'OPTICAL_RAW_ANALYSIS_V1':'NETWORK_RAW_ANALYSIS_V1');assert.equal(token.analysis_utc,at);assert.equal(token.snapshot.utc,at);assert.equal(token.snapshot.presentation_kind,undefined);assert.ok(Object.isFrozen(token.snapshot.node_definitions));assert.equal(o.verifyRawAnalysis(token),true);assert.equal(o.verifyRawAnalysis(structuredClone(token)),false);s.utc=codec.advance(s.utc,1);assert.equal(o.verifyRawAnalysis(token),true);assert.deepEqual(s.optical.historyEntries(),history);assert.equal(s.calls.length,calls);assert.equal(owner==='optical'?o.verifyLinkSnapshot(token.snapshot,{nodes:s.nodes,utc:s.utc}):o.verifySnapshot(token.snapshot),false);await s.optical.updateSampled();await s.network.updateSampled();assert.equal(o.verifyRawAnalysis(token),true,'next accepted native record preserves captured analysis');assert.equal(token.snapshot.utc,at);const next=o.captureRawAnalysis();assert.equal(next.analysis_utc,s.utc);assert.notEqual(next,token);}finally{close(s);}});
for(const owner of ['optical','network'])for(const change of ['lease','nodes','cancel','failure','destroy'])test(`${owner} raw capability permanently rejects ${change} and copied UI provenance`,async()=>{let failed=false;const s=setup(v=>{if(failed)throw Error('native failed');return v;},undefined,{count:1});try{await s.optical.updateSampled();await s.network.updateSampled();const o=s[owner],token=o.captureRawAnalysis();assert.ok(token);const oldNodes=s.nodes;if(change==='lease')s.revoke();if(change==='nodes'){const n=s.nodes;n[0].notes='changed';s.nodes=n;}if(change==='cancel')o.cancelSampled();if(change==='failure'){s.utc=codec.advance(s.utc,1);if(owner==='network')await s.optical.updateSampled();failed=true;await o.updateSampled();}if(change==='destroy')o.destroy();assert.equal(o.verifyRawAnalysis(token),false);if(change==='nodes')s.nodes=oldNodes;if(change==='failure')failed=false;assert.equal(o.verifyRawAnalysis(token),false,'revoked registration cannot revive');assert.equal(o.verifyRawAnalysis(o.sampledPresentation()),false);}finally{close(s);}});
for(const change of ['station','fault','optical reset'])test(`network raw whole native scope rejects ${change}`,async()=>{const s=setup(undefined,undefined,{count:2});try{await s.optical.updateSampled();await s.network.updateSampled();const token=s.network.captureRawAnalysis();if(change==='station'){const a=s.stations;a[0].dish_m++;s.stations=a;}if(change==='fault')s.faults=[{kind:'node_outage',target:s.nodes[1].id,active:true}];if(change==='optical reset')s.optical.resetHistories();assert.equal(s.network.verifyRawAnalysis(token),false);}finally{close(s);}});
test('generic exact raw capability requires actual same UTC and no continuity fallback',async()=>{const s=setup(undefined,undefined,{noContinuity:true,count:1});try{await s.network.update();const token=s.network.captureRawAnalysis();assert.ok(token);assert.equal(s.network.verifyRawAnalysis(token),true);s.utc=codec.advance(s.utc,1);assert.equal(s.network.verifyRawAnalysis(token),false);}finally{close(s);}});
test('raw network command scope preserves full240 native definitions/hashes and all24 station inputs',async()=>{const s=setup(undefined,undefined,{count:240});try{s.stations=Array.from({length:24},(_,i)=>({...s.stations[0],id:'RAW-SITE-'+i,name:'site '+i,enabled:i!==23}));await s.optical.updateSampled();await s.network.updateSampled();const token=s.network.captureRawAnalysis();assert.ok(token);assert.equal(token.snapshot.node_definitions.length,240);assert.equal(Object.keys(token.snapshot.definition_hashes).length,240);assert.deepEqual(token.snapshot.stations,s.stations);s.utc=codec.advance(s.utc,0.1);assert.equal(s.network.verifyRawAnalysis(token),true);const nodes=s.nodes;nodes[239].notes='hidden whole cohort mutation';s.nodes=nodes;assert.equal(s.network.verifyRawAnalysis(token),false);}finally{close(s);}});
for(const owner of ['optical','network'])test(`${owner} raw capability revokes on final actual owner callback`,async()=>{const s=setup(undefined,undefined,{count:1});try{await s.optical.updateSampled();await s.network.updateSampled();const o=s[owner],token=o.captureRawAnalysis();let reads=0;s.hook=()=>{if(++reads===3)s.revoke();};assert.equal(o.verifyRawAnalysis(token),false);s.hook=null;assert.equal(o.verifyRawAnalysis(token),false);}finally{close(s);}});
for(const owner of ['optical','network'])for(const method of ['update','updateSampled'])test(`${owner} ${method} preflight failure permanently revokes recovered same-lease raw token`,async()=>{const s=setup(undefined,undefined,{count:1});try{await s.optical.updateSampled();await s.network.updateSampled();const o=s[owner],token=o.captureRawAnalysis(),utc=s.utc;s.utc='invalid';await o[method]();s.utc=utc;assert.equal(o.verifyRawAnalysis(token),false);}finally{close(s);}});
for(const owner of ['optical','network'])test(`${owner} failed raw capture records an irreversible observed UTC gap`,async()=>{const s=setup(undefined,undefined,{count:1});try{await s.optical.updateSampled();await s.network.updateSampled();const o=s[owner],token=o.captureRawAnalysis(),utc=s.utc;s.utc='invalid';assert.equal(o.captureRawAnalysis(),null);s.utc=utc;assert.equal(o.verifyRawAnalysis(token),false);}finally{close(s);}});

test('raw network capture observes a full station gap and prevents old-token revival',async()=>{const s=setup(undefined,undefined,{count:1});try{await s.optical.updateSampled();await s.network.updateSampled();const token=s.network.captureRawAnalysis(),stations=s.stations;s.stations=stations.map(n=>({...n,dish_m:n.dish_m+1}));assert.equal(s.network.captureRawAnalysis(),null);s.stations=stations;assert.equal(s.network.verifyRawAnalysis(token),false);}finally{close(s);}});

for(const owner of ['optical','network'])test(`${owner} observed continuity gap requires a fresh accepted native analysis`,async()=>{const s=setup(undefined,undefined,{count:1});try{await s.optical.updateSampled();await s.network.updateSampled();const o=s[owner],old=o.captureRawAnalysis();s.unavailable();assert.equal(o.captureRawAnalysis(),null);s.recoverSameLease();assert.equal(o.verifyRawAnalysis(old),false);assert.equal(o.captureRawAnalysis(),null);await s.optical.updateSampled();await s.network.updateSampled();const fresh=o.captureRawAnalysis();assert.ok(fresh);assert.equal(o.verifyRawAnalysis(fresh),true);assert.equal(o.verifyRawAnalysis(old),false);}finally{close(s);}});
