import test from 'node:test';
import assert from 'node:assert/strict';
import {createSatelliteNodePanelTools} from '../../../user_application/web/scripts/tabs/satellite_nodes.js';
import {createNodeClockControls} from '../../../user_application/web/scripts/nodes/clock_controls.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
function panel(display){const mode={textContent:''},clock={textContent:''},pause={dataset:{},setAttribute(){},addEventListener(){},removeEventListener(){}};const root={querySelector:id=>({'#node-clock-mode':mode,'#node-clock':clock,'#node-clock-pause':pause}[id]??null),querySelectorAll:()=>[],addEventListener(){},removeEventListener(){}};const ui=createSatelliteNodePanelTools({library:{}}).createNodeSceneControls({root,readDisplay:()=>display,actions:{play(){},pause(){}}});return{ui,mode,clock,pause};}
test('actual catalog owner without buffer labels validated UTC without enabling playback',()=>{const codec=createUtcCodec(LEAP_SHA256),utc='2026-10-07T00:00:00.000000000Z',hash='a'.repeat(64),context={key:'catalog:25994:'+hash,utc,leap_sha256:LEAP_SHA256};const catalog={snapshot:()=>({selected:{catalog_number:25994,normalized_gp_sha256:hash},playing:false,rate:1,buffer:null})};const owner=createNodeClockControls({readContext:()=>context,stored:{snapshot:()=>({})},catalog,advanceUtc:codec.advance,now:()=>0});const display={...owner.read(context),utc};assert.equal(Object.hasOwn(display,'running'),false);const f=panel(display);try{assert.equal(f.mode.textContent,'카탈로그 분석 시각 · 재생 샘플 미계산');assert.equal(f.clock.textContent,utc);assert.equal(f.pause.disabled,true);assert.equal(Object.hasOwn(display,'running'),false);}finally{f.ui.destroy();owner.destroy();}});
for(const mode of ['카탈로그','저장 궤도','SIM','SIM 따라가기'])for(const running of [true,false])test(`known source label ${mode} running=${running}`,()=>{const display={mode,running,utc:'unchanged'},f=panel(display);try{assert.equal(f.mode.textContent,mode+' 분석 시각 · '+(running?'재생':'정지'));assert.equal(f.clock.textContent,'unchanged');assert.equal(f.pause.disabled,false);assert.deepEqual(display,{mode,running,utc:'unchanged'});}finally{f.ui.destroy();}});
for(const [display,label]of [[{mode:'live'},'현재 시각'],[{mode:'paused'},'분석 시각 · 정지'],[{},'표시 시각 미확인'],[{mode:'foreign',running:true},'분석 시각 · 재생'],[{running:true},'분석 시각 · 재생'],[{mode:'카탈로그',running:null},'표시 시각 미확인'],[{mode:'카탈로그',running:undefined},'표시 시각 미확인'],[{mode:'SIM'},'표시 시각 미확인'],[{mode:'저장 궤도'},'표시 시각 미확인'],[{mode:'SIM 따라가기'},'표시 시각 미확인']])test('legacy/unknown source label '+JSON.stringify(display),()=>{const f=panel(display);try{assert.equal(f.mode.textContent,label);}finally{f.ui.destroy();}});
