import test from 'node:test';
import assert from 'node:assert/strict';
import {NodeScene,LINK_COLORS} from '../../../digital_twin/visualization/node_scene.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const codec=createUtcCodec(LEAP_SHA256),utc=codec.advance('2026-10-04T00:00:00Z',0),hash='a'.repeat(64),freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
class Collection{constructor(){this.items=[];}add(v){this.items.push(v);return v;}remove(v){this.items=this.items.filter(x=>x!==v);return true;}}
class Color{constructor(css,alpha=1){Object.assign(this,{css,alpha});}static fromCssColorString(css){return new Color(css);}withAlpha(alpha){return new Color(this.css,alpha);}}
class Material{constructor(o){this.uniforms=o.fabric.uniforms;}static fromType(type,uniforms){return {type,uniforms};}}
const meta={model_profile:'SOURCE_KEPLER_J2_V1',frame:'EARTH_FIXED_GMST_UTC_APPROX',inertial_frame:'SOURCE_MEAN_EQUATOR_EQUINOX_APPROX',time_model:'unix_ms_utc_approx',source_commit:'1a1e00297a0301637455b0ef2cf48b2e74576b07',quality:'engineering_assumption'};
async function fixture(){
 let currentUtc=utc,morph=false,valid=true,hook=null;const nodes=[{schema:1,id:'A'},{schema:1,id:'B'}],view=freeze({presentation_kind:'MIXED_ROUTE_EMPHASIS_UI_V1',analysis_utc:utc,node_definitions:nodes,definition_hashes:{A:hash,B:hash},oisl_links:[{id:'A|B',a:'A',b:'B'}],routed_ids:['A|B'],selected_id:'A|B'}),C={Color,Material,PolylineCollection:Collection,Cartesian3:class{constructor(...v){this.values=v;}},SceneMode:{SCENE3D:3,MORPHING:0}},viewer={scene:{mode:3,primitives:new Collection()}};
 const scene=new NodeScene({viewer,cesium:C,timeSource:()=>currentUtc,advanceUtc:codec.advance,pathFor:()=>null,geometryFor:(node,{utc:stamp})=>({...meta,node_id:node.id,node_definition:node,definition_hash:hash,row:{utc:stamp,status:'valid',error_code:null,position_m:[node.id==='A'?1:2,0,550000]}}),isTransitioning:()=>morph,verifyLinkSnapshot:()=>true,animationNow:()=>2000,routeEmphasis:{read:()=>valid?view:null,verify:value=>{hook?.();return valid&&value===view;}}});
 await scene.setNodes(nodes.map(n=>({id:n.id,definition:n,model:null})));const snapshot={...meta,status:'valid',utc,node_definitions:structuredClone(nodes),definition_hashes:{A:hash,B:hash},terminals:[],pairs:[{key:'A|B',a:'A',b:'B',state:'locked'}]};scene.setLinks(snapshot);
 return {scene,C,viewer,view,nodes,snapshot,get line(){return scene.links.get('A|B').line;},set valid(v){valid=v;},set hook(v){hook=v;},set utc(v){currentUtc=v;},set morph(v){morph=v;}};
}
test('original OISL purple route and widths preserve the same locked material and flow phase',async()=>{const f=await fixture();try{const entry=f.scene.links.get('A|B'),material=entry.material,time=material.uniforms.time;assert.equal(typeof f.scene.applyRouteEmphasis,'function');f.scene.applyRouteEmphasis(utc);assert.equal(f.line.width,4.5);assert.equal(f.line.material,material);assert.equal(material.uniforms.color.css,'#a78bfa');assert.equal(material.uniforms.time,time);f.valid=false;f.scene.applyRouteEmphasis(utc);assert.equal(f.line.width,2);assert.equal(material.uniforms.color.css,LINK_COLORS.locked);assert.equal(f.line.material,material);}finally{f.scene.destroy();}});
test('route changes cannot overwrite native base material on repeated exact native snapshots',async()=>{const f=await fixture();try{f.scene.applyRouteEmphasis(utc);f.scene.setLinks(f.snapshot);f.valid=false;f.scene.applyRouteEmphasis(utc);assert.equal(f.line.material.uniforms.color.css,LINK_COLORS.locked);assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
test('selected native OISL has width4 without route approval',async()=>{const f=await fixture();try{const view=freeze({...f.view,routed_ids:[]});f.scene.routeEmphasis={read:()=>view,verify:v=>v===view};f.scene.applyRouteEmphasis(utc);assert.equal(f.line.width,4);assert.equal(f.line.material.uniforms.color.css,LINK_COLORS.locked);}finally{f.scene.destroy();}});
for(const reason of ['copy','scope','UTC','morph','hidden','clear','dispose','reentry'])test('route emphasis refuses '+reason+' without creating or showing links',async()=>{const f=await fixture();try{const originalCount=f.scene.links.size;if(reason==='copy')f.scene.routeEmphasis={read:()=>structuredClone(f.view),verify:()=>false};if(reason==='scope')f.scene.definitionScope='foreign';if(reason==='UTC')f.utc=codec.advance(utc,1);if(reason==='morph')f.morph=true;if(reason==='hidden')f.scene.setLinksVisible(false);if(reason==='clear')f.scene.clearLinks();if(reason==='dispose')f.scene.destroy();if(reason==='reentry')f.hook=()=>{f.valid=false;};f.scene.applyRouteEmphasis(utc);assert.ok(f.scene.links.size<=originalCount);if(f.scene.links.size){assert.equal(f.line.width,2);assert.notEqual(f.line.material.uniforms.color.css,'#a78bfa');}}finally{f.scene.destroy();}});
test('final provider replacement during owner callback cannot retain old Viewer emphasis',async()=>{const f=await fixture();try{f.hook=()=>{f.scene.viewerProvider={scene:{mode:3,primitives:new Collection()}};};f.scene.applyRouteEmphasis(utc);assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
test('animation callback revocation restores base style after direct flow update',async()=>{const f=await fixture();try{f.scene.animationNow=()=>{f.valid=false;return 5000;};f.scene.animateLinkFlow(undefined,utc);assert.equal(f.line.width,2);assert.equal(f.line.material.uniforms.color.css,LINK_COLORS.locked);}finally{f.scene.destroy();}});
test('current endpoint hash cannot be substituted by a registered route proof',async()=>{const f=await fixture();try{const read=f.scene.geometryFor;f.scene.geometryFor=(...args)=>({...read(...args),definition_hash:'b'.repeat(64)});f.scene.applyRouteEmphasis(utc);assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
test('newer reentrant selected-only publication is retained without outer route overwrite',async()=>{const f=await fixture();try{let view=f.view,once=true;f.scene.routeEmphasis={read:()=>view,verify:v=>{if(once){once=false;view=freeze({...view,routed_ids:[]});f.scene.applyRouteEmphasis(utc);}return v===view;}};f.scene.applyRouteEmphasis(utc);assert.equal(f.line.width,4);assert.equal(f.line.material.uniforms.color.css,LINK_COLORS.locked);}finally{f.scene.destroy();}});
for(const change of ['Viewer','UTC'])test('terminal third owner proof cannot retain emphasis after stable '+change+' provider backing changes',async()=>{const f=await fixture();try{let calls=0,viewer=f.viewer;f.scene.viewerProvider=()=>viewer;f.hook=()=>{if(++calls===3){if(change==='Viewer')viewer={scene:{mode:3,primitives:new Collection()}};else f.utc=codec.advance(utc,1);}};assert.equal(f.scene.applyRouteEmphasis(utc),false);assert.equal(f.line.width,2);assert.equal(f.line.material.uniforms.color.css,LINK_COLORS.locked);}finally{f.scene.destroy();}});
