import test from 'node:test';
import assert from 'node:assert/strict';
import {createNodeClockControls} from '../../../user_application/web/scripts/nodes/clock_controls.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const utc='2026-10-07T00:00:00.000000000Z',hash='a'.repeat(64);
function fixture(kind='stored'){
 let alive=true,view,hook=()=>{},commandHook=()=>{};const calls=[],codec=createUtcCodec(LEAP_SHA256),display={key:'scene:'+hash,utc,leap_sha256:LEAP_SHA256};
 const state={input_id:'input',input_hash:hash,revision:1,current_utc:utc,playing:false,play_rate:1},catalogState={selected:{catalog_number:1,normalized_gp_sha256:hash},buffer:{count:601},playing:false,rate:1},runtime={run_id:'RUN',running:false,speed:1,utc};
 const sourceContext={key:kind==='stored'?`stored:input:${hash}`:kind==='catalog'?`catalog:1:${hash}`:'sim:RUN',utc,leap_sha256:LEAP_SHA256,...(kind==='sim'?{source:'sim',eop_sha256:null}:{})};view=Object.freeze({kind,context:Object.freeze(sourceContext)});const registered=new WeakSet([view]);
 const stored={snapshot:()=>({status:'ready',state:structuredClone(state)}),control:async(action,value)=>{calls.push(['stored',action,value]);state.revision++;state.playing=action==='play';alive=false;await commandHook();},seek:async value=>{calls.push(['seek',value]);state.revision++;state.current_utc=value;alive=false;await commandHook();}};
 const catalog={snapshot:()=>structuredClone(catalogState),play:()=>{calls.push(['catalog','play']);alive=false;},pause:()=>{calls.push(['catalog','pause']);alive=false;},rate:n=>{calls.push(['catalog','speed',n]);alive=false;}};
 const scenario={readRuntime:()=>structuredClone(runtime),utcOfRuntime:r=>r.utc,controls:{play:()=>{calls.push(['sim','play']);alive=false;runtime.running=true;},pause:()=>{calls.push(['sim','pause']);alive=false;},setSpeed:n=>{calls.push(['sim','speed',n]);alive=false;runtime.speed=n;},speeds:[1,4]}};
 const clock=createNodeClockControls({readContext:()=>display,stored,catalog,scenario,advanceUtc:codec.advance,now:()=>Date.parse(utc),resolveSceneSource:()=>view,verifySceneSource:candidate=>registered.has(candidate)&&alive,runStored:async fn=>{hook();return fn();}});
 return {clock,display,calls,state,catalogState,runtime,stored,catalog,revoke:()=>alive=false,replaceView:()=>view=structuredClone(view),hook:fn=>hook=fn,commandHook:fn=>commandHook=fn};
}
for(const kind of ['stored','catalog','sim'])test(`registered scene source reads and delegates existing ${kind} without changing scene identity`,async()=>{const f=fixture(kind),before=structuredClone(f.display);assert.equal(f.clock.read(f.display).running,false);await f.clock.actions.play();assert.equal(f.calls[0][0],kind==='stored'?'stored':kind==='catalog'?'catalog':'sim');assert.deepEqual(f.display,before);assert.deepEqual(f.clock.read(f.display),{});});
test('foreign copied and revoked resolver views never authorize scene commands',async()=>{for(const mutate of [f=>f.replaceView(),f=>f.revoke()]){const f=fixture();mutate(f);assert.deepEqual(f.clock.read(f.display),{});await assert.rejects(f.clock.actions.play());assert.deepEqual(f.calls,[]);}});
test('runStored callback cannot revoke source before the actual command',async()=>{const f=fixture();f.hook(f.revoke);await assert.rejects(f.clock.actions.play());assert.deepEqual(f.calls,[]);});
test('normal source control revocation succeeds but unrelated settlement identity change is rejected',async()=>{const f=fixture();await f.clock.actions.step(1);assert.equal(f.state.current_utc,'2026-10-07T00:00:01.000000000Z');const changed=fixture();changed.commandHook(()=>changed.state.input_hash='b'.repeat(64));await assert.rejects(changed.clock.actions.play());assert.equal(changed.calls.length,1);const disposed=fixture();disposed.commandHook(()=>disposed.clock.destroy());await assert.rejects(disposed.clock.actions.play());});
test('same identity with failed source settlement is rejected and pending source cannot start a command',async()=>{const f=fixture();f.commandHook(()=>f.stored.snapshot=()=>({status:'error',error:'offline',state:structuredClone(f.state)}));await assert.rejects(f.clock.actions.play());assert.equal(f.calls.length,1);const pending=fixture();pending.stored.snapshot=()=>({status:'ready',fetching:true,state:structuredClone(pending.state)});assert.deepEqual(pending.clock.read(pending.display),{});await assert.rejects(pending.clock.actions.play());assert.deepEqual(pending.calls,[]);});
test('scene UTC and codec provenance cannot acquire a source fallback',async()=>{for(const mutate of [f=>f.display.utc='invalid',f=>f.display.leap_sha256='foreign']){const f=fixture();mutate(f);assert.deepEqual(f.clock.read(f.display),{});await assert.rejects(f.clock.actions.play());assert.deepEqual(f.calls,[]);}});
test('catalogue seek callback cannot switch the source before the following calculation',async()=>{const f=fixture('catalog');f.catalog.seek=()=>{f.revoke();f.catalogState.selected.catalog_number=2;};f.catalog.calculate=async()=>f.calls.push(['wrong-calculation']);await assert.rejects(f.clock.actions.step(1));assert.deepEqual(f.calls,[]);});
