import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
// Borrow the existing exact renderer fixture without executing its tests.
const source=await readFile(new URL('./node_scene_route_emphasis.test.mjs',import.meta.url),'utf8');
const prefix=source.slice(0,source.indexOf("test('original")).replace(/from '([^']+)'/g,(all,path)=>path.startsWith('.')?`from '${new URL(path,import.meta.url).href}'`:all);
const {fixture,utc,freeze,meta,hash,Collection,codec}=await import('data:text/javascript;base64,'+Buffer.from(prefix+'\nexport {fixture,utc,freeze,meta,hash,Collection,codec};').toString('base64'));
async function setup(){const f=await fixture();f.scene.restoreRouteEmphasis();f.scene.routeEmphasis=null;let valid=true,hook=null;
 const view=freeze({presentation_kind:'MIXED_ROUTE_ANALYTICAL_UI_V1',analysis_utc:codec.advance(utc,-1),display_utc:utc,age_seconds:1,current_analysis:false,availability:'accepted',reason:'captured_native_analysis',source:'captured_native_analysis',fabric_view:freeze({}),native_snapshot:{schema_version:1,...meta,status:'valid',node_definitions:f.nodes,definition_hashes:{A:hash,B:hash}},node_definitions:f.nodes,definition_hashes:{A:hash,B:hash},oisl_links:[{id:'A|B',a:'A',b:'B'}],ground_links:[],routed_ids:['A|B'],selected_id:'A|B'});
 f.scene.analyticalRouteEmphasis={read:()=>view,verify:v=>{hook?.();return valid&&v===view;}};
 return {...f,view,get line(){return f.line;},set valid(v){valid=v;},set hook(v){hook=v;},moveUtc:v=>{f.utc=v;},set morph(v){f.morph=v;}};
}
test('historical OISL route styles existing current endpoints and retains locked material/time only',async()=>{const f=await setup();try{const e=f.scene.links.get('A|B'),material=e.material,time=material.uniforms.time;assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),true);assert.equal(f.line.width,4.5);assert.equal(f.line.material,material);assert.equal(material.uniforms.color.css,'#a78bfa');assert.equal(material.uniforms.time,time);assert.equal(f.scene.analyticalRouteReceipt.view,f.view);assert.equal(f.scene.links.size,1);f.valid=false;f.scene.applyAnalyticalRouteEmphasis(utc);assert.equal(f.line.width,2);assert.equal(material.uniforms.color.css,'#3ddc84');assert.equal(f.scene.analyticalRouteReceipt,null);}finally{f.scene.destroy();}});
test('selected only and missing captured IDs do not invent links or route approval',async()=>{const f=await setup();try{const view=freeze({...f.view,routed_ids:['missing'],selected_id:'A|B'});f.scene.analyticalRouteEmphasis={read:()=>view,verify:v=>v===view};f.scene.applyAnalyticalRouteEmphasis(utc);assert.equal(f.line.width,4);assert.equal(f.line.material.uniforms.color.css,'#3ddc84');assert.equal(f.scene.links.size,1);}finally{f.scene.destroy();}});
for(const kind of ['copy','hash','scope','UTC','native','morph','clear','dispose'])test('analytical OISL fails closed for '+kind,async()=>{const f=await setup();try{f.scene.applyAnalyticalRouteEmphasis(utc);if(kind==='copy')f.scene.analyticalRouteEmphasis={read:()=>freeze(structuredClone(f.view)),verify:()=>false};if(kind==='hash'){const g=f.scene.geometryFor;f.scene.geometryFor=(...a)=>({...g(...a),definition_hash:'b'.repeat(64)});}if(kind==='scope')f.scene.definitionScope='foreign';if(kind==='UTC')f.moveUtc(codec.advance(utc,1));if(kind==='native'){const g=f.scene.geometryFor;f.scene.geometryFor=(...a)=>({...g(...a),row:{utc,status:'error',error_code:'missing',position_m:null}});}if(kind==='morph')f.morph=true;if(kind==='clear')f.scene.clearLinks();if(kind==='dispose')f.scene.destroy();f.scene.applyAnalyticalRouteEmphasis(utc);assert.equal(f.scene.analyticalRouteReceipt,null);if(f.scene.links.size)assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
test('hide revokes an old registered projection irreversibly until fresh owner value',async()=>{const f=await setup();try{f.scene.applyAnalyticalRouteEmphasis(utc);f.scene.setLinksVisible(false);f.scene.setLinksVisible(true);f.scene.applyAnalyticalRouteEmphasis(utc);assert.equal(f.line.width,2);const next=freeze({...f.view,fabric_view:freeze({})});f.scene.analyticalRouteEmphasis={read:()=>next,verify:v=>v===next};f.scene.applyAnalyticalRouteEmphasis(utc);assert.equal(f.line.width,4.5);}finally{f.scene.destroy();}});
test('early morph failure irreversibly revokes the previously borrowed projection',async()=>{const f=await setup();try{f.scene.applyAnalyticalRouteEmphasis(utc);f.morph=true;assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),false);f.morph=false;assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),false);assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
test('full 240-node scope is checked including unrelated native endpoint',async()=>{const f=await setup();try{const nodes=freeze([...f.nodes,...Array.from({length:238},(_,i)=>({schema:1,id:'X'+i}))]),hashes=freeze(Object.fromEntries(nodes.map(n=>[n.id,hash])));await f.scene.setNodes(nodes.map(n=>({id:n.id,definition:n,model:null})));f.scene.setLinks({...f.snapshot,node_definitions:nodes,definition_hashes:hashes});const view=freeze({...f.view,node_definitions:nodes,definition_hashes:hashes,native_snapshot:{...f.view.native_snapshot,node_definitions:nodes,definition_hashes:hashes}});f.scene.analyticalRouteEmphasis={read:()=>view,verify:v=>v===view};let calls=0;const g=f.scene.geometryFor;f.scene.geometryFor=(...a)=>{calls++;const row=g(...a);return a[0].id==='X237'?{...row,definition_hash:'b'.repeat(64)}:row;};assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),false);assert.equal(calls,240);assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
test('newer nested analytical selection survives the outer stale publication',async()=>{const f=await setup();try{const next=freeze({...f.view,routed_ids:[]});let current=f.view,once=true;f.scene.analyticalRouteEmphasis={read:()=>current,verify:v=>{if(once){once=false;current=next;f.scene.applyAnalyticalRouteEmphasis(utc);}return v===current;}};assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),false);assert.equal(f.line.width,4);assert.equal(f.scene.analyticalRouteReceipt.view,next);}finally{f.scene.destroy();}});
test('late mode getter revocation is followed by terminal private-owner proof',async()=>{const f=await setup();try{let checks=0,revoked=false;f.hook=()=>checks++;Object.defineProperty(f.viewer.scene,'mode',{get(){if(checks===3&&!revoked){revoked=true;f.valid=false;}return 3;},configurable:true});assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),false);assert.equal(revoked,true);assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
test('historical approval cannot style an existing line whose native placement receipt belongs to another UTC',async()=>{const f=await setup();try{f.scene.linkReceipt={...f.scene.linkReceipt,utc:codec.advance(utc,-1)};assert.equal(f.line.show,true);assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),false);assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
for(const kind of ['Viewer','UTC','clear','lease'])test('late analytical proof '+kind+' cannot publish old style',async()=>{const f=await setup();try{let checks=0,viewer=f.viewer;f.scene.viewerProvider=()=>viewer;f.hook=()=>{if(++checks===3){if(kind==='Viewer')viewer={scene:{mode:3,primitives:new Collection()}};if(kind==='UTC')f.moveUtc(codec.advance(utc,1));if(kind==='clear')f.scene.clearLinks();if(kind==='lease')f.valid=false;}};assert.equal(f.scene.applyAnalyticalRouteEmphasis(utc),false);assert.equal(f.scene.analyticalRouteReceipt,null);if(f.scene.links.size)assert.equal(f.line.width,2);}finally{f.scene.destroy();}});
