import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSatelliteNodePanelTools} from '../../../user_application/web/scripts/tabs/satellite_nodes.js';
import {createNodeLibrary} from '../../../digital_twin/model_library/browser/satellite_nodes.js';
import {orbitElements,catalogElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import {createConstellationStore} from '../../../user_application/web/scripts/nodes/constellation.js';
const epoch=1791151272000,utc='2026-10-04T22:01:12.000000000Z';
const metadata={model_profile:'SOURCE_KEPLER_J2_V1',frame:'EARTH_FIXED_GMST_UTC_APPROX',inertial_frame:'SOURCE_MEAN_EQUATOR_EQUINOX_APPROX',time_model:'unix_ms_utc_approx',source_commit:'1a1e00297a0301637455b0ef2cf48b2e74576b07',quality:'engineering_assumption'};
function setup(){let seq=0;const library=createNodeLibrary({orbitElements,catalogElements,createEquipmentId:()=>`EQ-${++seq}`});const store=createConstellationStore({library,storage:null,now:()=>epoch});store.load();const node=store.add({bus:'flat_panel'});return {library,store,node,tools:createSatelliteNodePanelTools({library})};}
function geometry(node){return {...metadata,node_id:node.id,node_definition:structuredClone(node),definition_hash:'fixture-geometry',row:{utc,status:'valid',error_code:null,position_m:[7000000,0,0],inertial_velocity_km_s:[3,4,0],raan_deg:12.25,argp_deg:34.5,mean_anomaly_deg:56.75,latitude_deg:1.23456,longitude_deg:-2.34567,height_km:621.123,sunlit:true}};}
function links(nodes){return {status:'valid',utc,source_commit:metadata.source_commit,quality:'engineering_assumption',node_definitions:structuredClone(nodes),terminals:[],pairs:[]};}
test('original static status/fleet builders and known live values match pinned source',async()=>{const {tools}=setup();const fixture=JSON.parse(await readFile(new URL('../fixtures/original_node_status.json',import.meta.url),'utf8'));for(const c of fixture.cases){assert.equal(tools.statusFrame(c.node,{match:c.match}),c.frame);assert.equal(tools.fleetMarkup([c.node]),c.fleet);const state=c.state,g={...metadata,node_id:c.node.id,node_definition:c.node,definition_hash:'source-fixture',row:{utc,status:'valid',error_code:null,position_m:state.fixed.r.map(v=>v*1000),inertial_velocity_km_s:state.inertial.v,raan_deg:state.raan,argp_deg:state.argp,mean_anomaly_deg:state.meanAnomaly,latitude_deg:state.geodetic.latitude,longitude_deg:state.geodetic.longitude,height_km:state.geodetic.altitude,sunlit:state.sunlit}};const value=tools.statusPresentation(c.node,{utc,geometry:g,links:links([c.node]),nodes:[c.node],verifyLinkSnapshot:()=>true});for(const [key,text]of Object.entries(c.live.texts))assert.equal(value.texts[key],text,`${c.node.id}:${key}`);assert.equal(value.equipmentMarkup,c.live.equipment);assert.equal(value.terminalMarkup,c.live.terminals);assert.equal(value.powerBar.width,c.live.bar.width);}});
test('static model credit/name/formation values are escaped and numeric epoch is displayed in UTC',()=>{const {tools,node}=setup();node.name='<img>';const markup=tools.statusFrame(node,{match:{label:'<shape>',title:'thing',credit:'<credit>',thumbnail:'/static/thumb.png',quality:'assigned',sizeMeters:10}});assert.ok(markup.includes('&lt;img&gt;'));assert.ok(markup.includes('&lt;credit&gt;'));assert.ok(markup.includes('2026-10-04 22:01'));});
test('missing geometry and unverified terminals remain unknown instead of sunny/active/green',()=>{const {tools,node}=setup();const value=tools.statusPresentation(node,{utc,nodes:[node],links:links([node])});assert.equal(value.canLocate,false);assert.equal(value.texts.generation,'미확인');assert.equal(value.texts.consumption,'미확인');assert.equal(value.texts.margin,'미확인');assert.match(value.texts.sun,/미확인/);assert.match(value.texts['terminal-summary'],/미확인/);assert.ok(!value.equipmentMarkup.includes('사용 중'));});
test('native degree/position/velocity units feed source formatted fields without static angle fallback',()=>{const {tools,node}=setup();const value=tools.statusPresentation(node,{utc,geometry:geometry(node),nodes:[node]});assert.equal(value.texts.raan,'12.25°');assert.equal(value.texts.argp,'34.50°');assert.equal(value.texts.anomaly,'56.75°');assert.equal(value.texts.speed,'5.000 km/s');assert.equal(value.texts.altitude,'621.1 km');assert.equal(value.canLocate,true);assert.equal(value.texts.generation,'4,500 W');assert.equal(value.texts.consumption,'미확인');});
test('wrong time/node/definition/profile/frame/NaN/error rows suppress stale geometry',()=>{const {tools,node}=setup();const baseline=geometry(node);for(const patch of [{node_id:'OTHER'},{node_definition:{...node,name:'old'}},{frame:'ITRF'},{model_profile:'SGP4'},{row:{...baseline.row,utc:'2026-10-04T22:01:13Z'}},{row:{...baseline.row,status:'error',error_code:'failed'}},{row:{...baseline.row,raan_deg:NaN}}]){const value=tools.statusPresentation(node,{utc,geometry:{...baseline,...patch},nodes:[node]});assert.equal(value.canLocate,false);assert.equal(value.texts.raan,'—°');assert.equal(value.texts.generation,'미확인');}});
test('safe mode known non-OISL consumption remains available, sun-dependent margin does not',()=>{const {tools,node}=setup();node.mode='safe';const value=tools.statusPresentation(node,{utc,nodes:[node]});assert.notEqual(value.texts.consumption,'미확인');assert.equal(value.texts.generation,'미확인');assert.equal(value.texts.margin,'미확인');assert.match(value.texts['terminal-summary'],/활성 OISL 단말 없음/);});
test('link data requires matching source/time/roster and an injected actual verification path',()=>{const {tools,node}=setup();const input={utc,geometry:geometry(node),nodes:[node],links:links([node])};const unknown=tools.statusPresentation(node,input);assert.equal(unknown.linksStatus,'unknown');for(const patch of [{utc:'old'},{node_definitions:[]},{status:'error'}])assert.equal(tools.statusPresentation(node,{...input,links:{...input.links,...patch},verifyLinkSnapshot:()=>true}).linksStatus,patch.status==='error'?'error':'unknown');assert.notEqual(tools.statusPresentation(node,{...input,verifyLinkSnapshot:()=>true}).texts.consumption,'미확인');});
class Element {constructor(){this.listeners=new Map();this.dataset={};this.hidden=false;this.disabled=false;this.textContent='';this.innerHTML='';this.style={};this.className='';this.attributes=new Map();}addEventListener(key,fn){const listeners=this.listeners.get(key)??new Set();listeners.add(fn);this.listeners.set(key,listeners);}removeEventListener(key,fn){this.listeners.get(key)?.delete(fn);}async dispatch(key,event={}){for(const fn of [...(this.listeners.get(key)??[])])await fn({target:this,...event});}setAttribute(key,value){this.attributes.set(key,value);}}
class StatusHost extends Element {constructor(){super();this.cells=new Map();this.ids=new Map();this.builds=0;}set innerHTML(value){this.html=value;if(!this.cells)return;this.builds++;this.cells.clear();this.ids.clear();for(const m of value.matchAll(/data-live="([^"]+)"/g))this.cells.set(m[1],new Element());for(const m of value.matchAll(/id="([^"]+)"/g))this.ids.set(m[1],new Element());}get innerHTML(){return this.html;}querySelector(selector){if(selector.startsWith('#'))return this.ids.get(selector.slice(1));return this.cells.get(/data-live="([^"]+)"/.exec(selector)?.[1]);}}
test('mounted status retains DOM between native updates and user-only focus; stale actions and cleanup are owned',async()=>{const {tools,store,node}=setup(),host=new StatusHost();let focus=0,edits=0;const controller=tools.createNodeStatusPanel({host,store,readDisplay:()=>({utc}),geometryFor:next=>geometry(next),onFocus:()=>focus++,onEdit:()=>edits++});controller.refresh();assert.equal(focus,0);const initial=host.builds,oldEdit=host.ids.get('node-edit');controller.refresh();assert.equal(host.builds,initial);await host.ids.get('node-locate').dispatch('click');assert.equal(focus,1);await oldEdit.dispatch('click');assert.equal(edits,1);store.update(node.id,{...node,name:'changed'});controller.refresh();await oldEdit.dispatch('click');assert.equal(edits,1);const current=host.ids.get('node-edit');controller.destroy();await current.dispatch('click');assert.equal(edits,1);assert.throws(()=>controller.refresh(),/disposed/);});
test('error/missing read owners reset previous numeric values and disable focus; open editor hides status',()=>{const {tools,store}=setup(),host=new StatusHost();let available=true,editing=false;const controller=tools.createNodeStatusPanel({host,store,readDisplay:()=>({utc}),geometryFor:node=>{if(!available)throw Error('query failed');return geometry(node);},editor:{isOpen:()=>editing}});controller.refresh();assert.equal(host.cells.get('raan').textContent,'12.25°');available=false;controller.refresh();assert.equal(host.cells.get('raan').textContent,'—°');assert.equal(host.ids.get('node-locate').disabled,true);editing=true;controller.refresh();assert.equal(host.hidden,true);controller.destroy();});
test('duplicate/remove actions use actual store, preserve failed deletion and never auto-focus',async()=>{const {tools,store,node}=setup(),host=new StatusHost(),errors=[];const controller=tools.createNodeStatusPanel({host,store,readDisplay:()=>({utc}),onError:error=>errors.push(error)});controller.refresh();await host.ids.get('node-duplicate').dispatch('click');assert.equal(store.drafts.length,2);controller.refresh();await host.ids.get('node-remove').dispatch('click');assert.equal(store.drafts.length,1);assert.equal(store.drafts[0].id,node.id);controller.destroy();});

test('deletion persistence failure leaves selected node and actions intact with a visible error callback',async()=>{const {library,tools}=setup();let deny=false;const values=new Map(),storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>{if(deny)throw Error('storage denied');values.set(key,value);}};const store=createConstellationStore({library,storage,now:()=>epoch});store.load();const node=store.add({bus:'cubesat_3u'}),host=new StatusHost(),errors=[];const panel=tools.createNodeStatusPanel({host,store,readDisplay:()=>({utc}),onError:error=>errors.push(error)});panel.refresh();deny=true;await host.ids.get('node-remove').dispatch('click');assert.equal(store.drafts.length,1);assert.equal(store.selectedId,node.id);assert.equal(errors.length,1);assert.ok(host.ids.has('node-remove'));panel.destroy();});
test('focus revalidates live geometry at the click; missing focus/edit owner disables controls',async()=>{const {tools,store}=setup(),host=new StatusHost();let available=true,focus=0;const panel=tools.createNodeStatusPanel({host,store,readDisplay:()=>({utc}),geometryFor:node=>available?geometry(node):null,onFocus:()=>focus++});panel.refresh();assert.equal(host.ids.get('node-edit').disabled,true);available=false;await host.ids.get('node-locate').dispatch('click');assert.equal(focus,0);assert.equal(host.ids.get('node-locate').disabled,true);panel.destroy();});
test('credit links reject executable schemes and malformed verified-terminal presentation resets stale power',()=>{const {tools,node}=setup();const input={utc,geometry:geometry(node),nodes:[node],links:{...links([node]),terminals:[{nodeId:node.id,equipmentId:node.equipment[0].id,targetId:'N-2'}]},verifyLinkSnapshot:()=>true,oislPresentation:{phaseLabel:()=>'',blockedLabel:()=>'',acquisitionProgress:()=>null}};const value=tools.statusPresentation(node,input);assert.equal(value.linksStatus,'error');assert.equal(value.texts.consumption,'미확인');const store={selected:node,drafts:[node]},host=new StatusHost();const panel=tools.createNodeStatusPanel({host,store,readDisplay:()=>({utc}),modelFor:()=>({label:'model',title:'representative',credit:'<credit>',creditUrl:'javascript:alert(1)',quality:'assigned'})});panel.refresh();assert.ok(!host.innerHTML.includes('href="javascript'));assert.ok(host.innerHTML.includes('&lt;credit&gt;'));panel.destroy();});
test('nonempty terminal presentation retains source fields and escapes targets without inventing an active link',()=>{const {tools,node}=setup();const spec={label:'<terminal>',kind:'oisl'},terminal={spec,state:{phase:'locked',azimuth:1,elevation:2,pointingError:0.003},geometry:{range_km:123},margin:{margin_db:4},targetId:'OTHER',role:'fore',dataRateMbps:10000};const markup=tools.terminalRow(terminal,new Date(epoch),{findNode:()=>({name:'<target>'}),acquisitionProgress:()=>0.5,phaseLabel:()=>'<locked>',blockedLabel:()=>''});assert.ok(markup.includes('&lt;target&gt;'));assert.ok(markup.includes('123 km'));assert.ok(markup.includes('4.0 dB'));assert.ok(markup.includes('width:50%'));});

class FleetHost extends Element {constructor(){super();this.rows=[];this.builds=0;}set innerHTML(value){this.html=value;if(!this.rows)return;this.builds++;this.rows=[...value.matchAll(/data-node-id="([^"]+)"/g)].map(match=>{const row=new Element();row.dataset.nodeId=match[1];row.dot=new Element();row.querySelector=()=>row.dot;return row;});}get innerHTML(){return this.html;}querySelectorAll(){return this.rows;}}
test('fleet selection updates actual owner without focus or rebuilding membership rows; stale rows dispose',async()=>{const {tools,store,node}=setup();store.add({name:'second'});const host=new FleetHost(),count=new Element();let selected=0;const panel=tools.createNodeFleetPanel({host,count,store,readDisplay:()=>({utc}),onSelected:()=>selected++});panel.refresh();assert.equal(count.textContent,'2');const builds=host.builds,first=host.rows[0];assert.equal(first.attributes.get('aria-selected'),'false');await first.dispatch('click');assert.equal(store.selectedId,node.id);assert.equal(selected,1);assert.equal(host.builds,builds);assert.equal(first.attributes.get('aria-selected'),'true');store.update(node.id,{...node,name:'changed'});panel.refresh();assert.equal(first.listeners.get('click').size,0);panel.destroy();assert.equal(host.rows[0].listeners.get('click').size,0);});
test('fleet link dots remain neutral without a validated current roster; verification does not mutate source objects',()=>{const {tools,store,node}=setup();const other=store.add({name:'other'}),host=new FleetHost();const snapshot={...links(store.drafts),pairs:[{a:node.id,b:other.id,state:'locked'}]};const panel=tools.createNodeFleetPanel({host,store,readDisplay:()=>({utc}),linksFor:()=>snapshot});panel.refresh();assert.equal(host.rows[0].dot.className,'status-dot neutral');panel.destroy();const before=structuredClone(snapshot);const verified=tools.createNodeFleetPanel({host,store,readDisplay:()=>({utc}),linksFor:()=>snapshot,verifyLinkSnapshot:value=>{value.pairs[0].state='blocked';return true;}});verified.refresh();assert.equal(host.rows[0].dot.className,'status-dot ok');assert.deepEqual(snapshot,before);verified.destroy();});
function timers(){let seq=0;return {pending:new Map(),set(fn,delay){const id=++seq;this.pending.set(id,{fn,delay});return id;},clear(id){this.pending.delete(id);},run(){for(const [id,entry]of [...this.pending]){this.pending.delete(id);entry.fn();}}};}
test('source tooltip delay/placement/text and disposal use only scoped injected event/timer owners',async()=>{const {tools}=setup(),root=new Element(),tip=new Element(),scroll=new Element(),clock=timers();tip.offsetWidth=100;tip.offsetHeight=40;let exists=true;const target={dataset:{tip:'<initial>'},closest(){return this;},contains:()=>false,getBoundingClientRect:()=>({left:300,width:20,top:2,bottom:20})};const release=tools.bindNodeTooltips({root,tip,timers:clock,viewport:()=>({width:320,height:200}),contains:()=>exists,scrollTarget:scroll});await root.dispatch('mouseover',{target});assert.equal([...clock.pending.values()][0].delay,220);target.dataset.tip='<latest>';clock.run();assert.equal(tip.textContent,'<latest>');assert.equal(tip.style.left,'212px');assert.equal(tip.style.top,'28px');assert.equal(tip.hidden,false);await scroll.dispatch('scroll');assert.equal(tip.hidden,true);await root.dispatch('focusin',{target});const stale=[...clock.pending.values()][0].fn;release();stale();assert.equal(tip.hidden,true);assert.equal(clock.pending.size,0);assert.equal(root.listeners.get('mouseover').size,0);assert.equal(scroll.listeners.get('scroll').size,0);});

test('unknown terminal activity retains source all-enabled consumption explicitly as an assumption',async()=>{const {tools,node}=setup();const missing=tools.statusPresentation(node,{utc,nodes:[node]});assert.equal(missing.texts.consumption,'미확인');assert.equal(missing.powerAssumption?.margin_w,null);assert.match(missing.texts['power-assumption'],/전체 활성 단말 운용 가정/);const fixture=JSON.parse(await readFile(new URL('../fixtures/original_node_status.json',import.meta.url),'utf8'));for(const c of fixture.cases){const state=c.state,g={...metadata,node_id:c.node.id,node_definition:c.node,definition_hash:'original',row:{utc,status:'valid',error_code:null,position_m:state.fixed.r.map(v=>v*1000),inertial_velocity_km_s:state.inertial.v,raan_deg:state.raan,argp_deg:state.argp,mean_anomaly_deg:state.meanAnomaly,latitude_deg:state.geodetic.latitude,longitude_deg:state.geodetic.longitude,height_km:state.geodetic.altitude,sunlit:state.sunlit}};const assumed=tools.statusPresentation(c.node,{utc,nodes:[c.node],geometry:g});assert.equal(assumed.powerAssumption.consumption_w,c.allTerminalsPower.consumption_w);assert.equal(assumed.powerAssumption.margin_w,c.allTerminalsPower.margin_w);assert.equal(assumed.powerAssumption.quality,'engineering_assumption');}});

test('mounted virtual catalog number is explicitly a sandbox identity',()=>{const {tools,store,node}=setup(),host=new StatusHost();const panel=tools.createNodeStatusPanel({host,store,readDisplay:()=>({utc})});panel.refresh();assert.ok(host.innerHTML.includes(`샌드박스 가상 번호 ${node.catalog_number}`));assert.ok(host.innerHTML.includes('실제 NORAD 등록 번호가 아닙니다'));panel.destroy();});
