import test from 'node:test';
import assert from 'node:assert/strict';
import {createOrbitRadio,radioMarkup} from '../../../user_application/web/scripts/tabs/orbit_radio.js';
import {LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const state={revision:1,input_id:'ISS',input_hash:'hash',current_utc:'2020-07-12T21:16:01.000416000Z',ground_point:{latitude_deg:0,longitude_deg:0,ellipsoid_height_m:0,virtual:true,ellipsoid:'WGS84'},minimum_elevation_deg:10,eop_sha256:'eop',leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC'};
const client={snapshot:()=>({state:structuredClone(state),status:'ready'})};
const reply=p=>({client_request_id:p.client_request_id,revision:p.selection_revision,input_id:p.input_id,input_hash:'hash',utc:p.utc,frequency_hz:p.frequency_hz,ground_point:{...state.ground_point},minimum_elevation_deg:10,position_m:[6778137,0,0],velocity_m_s:[-1000,7500,0],elevation_deg:90,range_m:400000,range_rate_m_s:-1000,doppler_hz:p.frequency_hz*1000/299792458,received_frequency_hz:p.frequency_hz*(1+1000/299792458),error_code:null,eop_sha256:'eop',leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC',stale:false,status:'valid',communication_status:'unknown',model:'one_way_first_order_v1',units:{position:'m',velocity:'m/s',range:'m',range_rate:'m/s',frequency:'Hz',doppler:'Hz',elevation:'deg',time:'UTC'},assumptions:['same epoch']});
test('explicit UTC/MHz input, no hidden defaults, owned result and model meaning',async()=>{
 let calls=0;const c=createOrbitRadio(client,{orbitRadio:async p=>{calls++;return reply(p);}},()=>{},()=> 'query');await c.calculate();assert.equal(calls,0);assert.equal(c.snapshot().status,'error');c.useUtc();c.setDraft({frequency_mhz:'437.825'});await c.calculate();assert.equal(calls,1);assert.match(radioMarkup(c.snapshot()),/실제 수신 미확인/);assert.equal(c.snapshot().result.frequency_hz,437825000);const copy=c.snapshot();copy.result.range_m=0;assert.equal(c.snapshot().result.range_m,400000);c.destroy();
});
test('late reply after edit/context change/destroy is ignored; local same-value retains result',async()=>{
 const waits=[];const c=createOrbitRadio(client,{orbitRadio:(p,{signal})=>new Promise(resolve=>waits.push({p,signal,resolve}))},()=>{},()=> 'query');c.useUtc();c.setDraft({frequency_mhz:'437.825'});const first=c.calculate();c.setDraft({frequency_mhz:'145.8'});assert.equal(waits[0].signal.aborted,true);const second=c.calculate();waits[1].resolve(reply(waits[1].p));await second;waits[0].resolve(reply(waits[0].p));await first;assert.equal(c.snapshot().result.frequency_hz,145800000);c.setDraft({frequency_mhz:'145.8'});assert.ok(c.snapshot().result);state.revision++;c.update();assert.equal(c.snapshot().result,null);state.revision--;c.update();const last=c.calculate();c.destroy();waits[2].resolve(reply(waits[2].p));await last;assert.equal(c.snapshot().result,null);
});
test('strict provenance, geometry echoes and numeric failures fail closed',async()=>{
 for(const patch of [{stale:true},{input_hash:'wrong'},{communication_status:'pass'},{range_m:NaN},{doppler_hz:0},{utc:'2020-01-01T00:00:00Z'},{ground_point:{...state.ground_point,latitude_deg:1}},{units:{range:'km'}}]){const c=createOrbitRadio(client,{orbitRadio:async p=>({...reply(p),...patch})});c.useUtc();c.setDraft({frequency_mhz:'437.825'});await c.calculate();assert.equal(c.snapshot().result,null);assert.equal(c.snapshot().status,'error');c.destroy();}
});
test('frequency bounds and UTC use leap-aware codec; native failures have no numeric result',async()=>{
 let count=0;const c=createOrbitRadio(client,{orbitRadio:async p=>{count++;const r=reply(p);for(const key of ['position_m','velocity_m_s','elevation_deg','range_m','range_rate_m_s','doppler_hz','received_frequency_hz'])r[key]=null;return {...r,status:'error',error_code:'DECAYED'};}});c.useUtc();for(const frequency_mhz of ['','0','-1','300001','Infinity']){c.setDraft({frequency_mhz});await c.calculate();assert.equal(count,0);}c.setDraft({frequency_mhz:'437.825',utc:'2016-12-31T23:59:60Z'});await c.calculate();assert.equal(count,1);assert.equal(c.snapshot().status,'error');assert.match(c.snapshot().error,/DECAYED/);c.destroy();
});
