import test from 'node:test';import assert from 'node:assert/strict';
import {createRadioSeries} from './orbit_radio_series_fixture.mjs';
import {seriesMarkup} from '../../../digital_twin/visualization/orbit_radio_series.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
const codec=createUtcCodec(LEAP_SHA256),start='2020-07-12T21:16:01.000416000Z',end=codec.advance(start,2);
const state={revision:1,input_id:'tle',input_hash:'hash',ground_point:{latitude_deg:0,longitude_deg:0,ellipsoid_height_m:0,virtual:true,ellipsoid:'WGS84'},minimum_elevation_deg:10,eop_sha256:'eop',leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC'};
export const source={...state,status:'complete',stale:false,communication_status:'unknown',intervals:[{start_utc:start,end_utc:end,peak_utc:codec.advance(start,1),max_elevation_deg:45,start_clipped:true,end_clipped:false}]};
export function answer(p){const rows=[-1000,0,1000].map((rate,i)=>({utc:codec.advance(start,i),frequency_hz:p.frequency_hz,position_m:[6778137,0,0],velocity_m_s:[rate,7500,0],range_m:400000+(i===1?0:1000),range_rate_m_s:rate,doppler_hz:-p.frequency_hz*rate/299792458,received_frequency_hz:p.frequency_hz*(1-rate/299792458),elevation_deg:30,error_code:null,status:'valid',eop_sha256:'eop',leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC'}));return {...state,client_request_id:p.client_request_id,start_utc:p.start_utc,end_utc:p.end_utc,frequency_hz:p.frequency_hz,duration_seconds:2,step_seconds:1,rows,status:'complete',stale:false,communication_status:'unknown',model:'one_way_first_order_v1',units:{position:'m',velocity:'m/s',range:'m',range_rate:'m/s',frequency:'Hz',doppler:'Hz',elevation:'deg',time:'UTC'},assumptions:['same epoch model']};}
function setup(api){return createRadioSeries({snapshot:()=>({state:structuredClone(state),status:'ready'})},api,()=>{},()=> 'series');}
test('interval source is copied; series summary is sampled and clipped',async()=>{let payload;const c=setup({orbitRadioSeries:async p=>(payload=p,answer(p))});c.choose(source,0);c.setFrequency('437.825');await c.calculate();assert.equal(payload.frequency_hz,437825000);assert.equal(c.snapshot().status,'ready');const html=seriesMarkup(c.snapshot().result,c.snapshot().interval);assert.equal((html.match(/<svg/g)||[]).length,3);assert.match(html,/표본 중/);assert.match(html,/접근 → 거리 변화 없음 → 이탈/);assert.match(html,/시작 잘림/);const copy=c.snapshot();copy.result.rows[0].range_m=0;assert.equal(c.snapshot().result.rows[0].range_m,401000);});
test('same-value remote frequency and interval edits discard late work',async()=>{let resolve,signal;const c=setup({orbitRadioSeries:(p,o)=>(signal=o.signal,new Promise(r=>resolve=()=>r(answer(p))))});c.choose(source,0);c.setFrequency('437.825');const work=c.calculate();c.setFrequency('437.825',true);assert.ok(signal.aborted);resolve();await work;assert.equal(c.snapshot().result,null);c.choose(source,0);c.clearInterval();assert.equal(c.snapshot().interval,null);c.destroy();});
test('wrong endpoints grid status or provenance cannot draw normal chart',async()=>{for(const corrupt of [r=>({...r,start_utc:end}),r=>({...r,step_seconds:2}),r=>({...r,rows:r.rows.slice(1)}),r=>({...r,eop_sha256:'other'}),r=>({...r,rows:r.rows.map((x,i)=>i===1?{...x,utc:start}:x)}),r=>({...r,status:'partial'})]){const c=setup({orbitRadioSeries:async p=>corrupt(answer(p))});c.choose(source,0);c.setFrequency('437.825');await c.calculate();assert.equal(c.snapshot().status,'error');assert.equal(c.snapshot().result,null);}});
test('failed row creates chart gaps and suppresses full summary',async()=>{const c=setup({orbitRadioSeries:async p=>{const r=answer(p);r.status='partial';r.rows[1]={...r.rows[1],status:'error',error_code:'DECAYED',position_m:null,velocity_m_s:null,range_m:null,range_rate_m_s:null,doppler_hz:null,received_frequency_hz:null,elevation_deg:null};return r;}});c.choose(source,0);c.setFrequency('437.825');await c.calculate();assert.equal(c.snapshot().status,'ready');const html=seriesMarkup(c.snapshot().result,c.snapshot().interval);assert.match(html,/전체 구간 요약 미확인/);assert.match(html,/DECAYED/);assert.equal((html.match(/<polyline/g)||[]).length,6);assert.equal((html.match(/<circle/g)||[]).length,6);});
test('missing interval or invalid frequency and mismatched visibility context rejected',async()=>{const c=setup({orbitRadioSeries:()=>assert.fail()});await c.calculate();assert.equal(c.snapshot().status,'error');c.choose({...source,revision:0},0);assert.equal(c.snapshot().interval,null);c.choose(source,0);c.setFrequency('0');await c.calculate();assert.equal(c.snapshot().status,'error');});
