import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSatelliteNodePanelTools} from '../../../user_application/web/scripts/tabs/satellite_nodes.js';
import {createNodeLibrary} from '../../../digital_twin/model_library/browser/satellite_nodes.js';
import {orbitElements,catalogElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import {createConstellationStore} from '../../../user_application/web/scripts/nodes/constellation.js';
const epoch=1791151272000;
function setup(){let sequence=0,id=0;const library=createNodeLibrary({orbitElements,catalogElements,createEquipmentId:()=>`EQ-${++sequence}`});const store=createConstellationStore({library,storage:null,now:()=>epoch});store.load();const timers={pending:new Map(),set(fn,delay){const key=++id;this.pending.set(key,{fn,delay});return key;},clear(key){this.pending.delete(key);},run(){for(const [key,entry]of [...this.pending]){this.pending.delete(key);entry.fn();}}};const tools=createSatelliteNodePanelTools({library});const errors=[];let formations=0;return {library,store,timers,tools,errors,controller:tools.createFormationPanel({store,now:()=>epoch,createFormationId:()=>`F-${++formations}`,timers,onError:error=>errors.push(error)})};}
test('four original formation presets preserve controls markup and summary',async()=>{const {tools}=setup();const fixture=JSON.parse(await readFile(new URL('../fixtures/original_node_panel.json',import.meta.url),'utf8'));for(const c of fixture.formations){assert.equal(tools.formationControlsMarkup(c.params),c.markup);assert.equal(tools.formationSummaryText(c.params),c.summary);}});
test('every slider remains present with preset-specific disabled controls and source tooltips',()=>{const {tools,library}=setup();const markup=tools.formationControlsMarkup({...library.FORMATION_DEFAULTS,preset:'single'});for(const control of library.FORMATION_CONTROLS)assert.ok(markup.includes(`data-control="${control.key}"`));assert.match(markup,/aria-disabled="true"/);assert.match(markup,/현재 프리셋에서는 사용하지 않습니다/);});
test('explicit create and live edits preserve formation identities with 120ms debounce',()=>{const {controller,store,timers}=setup();const nodes=controller.generate();assert.equal(nodes.length,40);const ids=nodes.map(n=>n.id);controller.setLive(true);assert.equal(controller.change('altitude_km','600'),true);controller.change('altitude_km','650');assert.equal(timers.pending.size,1);assert.equal([...timers.pending.values()][0].delay,120);assert.equal(store.drafts[0].orbit.altitude_km,550);timers.run();assert.equal(store.drafts[0].orbit.altitude_km,650);assert.deepEqual(store.drafts.map(n=>n.id),ids);});
test('typing without active formation never mutates store or requests propagation/deployment',()=>{const {controller,store,timers}=setup();const before=store.snapshot();controller.setLive(true);controller.change('altitude_km','700');assert.equal(timers.pending.size,0);assert.deepEqual(store.snapshot(),before);});
test('blank/nonfinite/unknown or disabled controls fail visibly without changing last valid params',()=>{const {controller,errors}=setup();const before=controller.snapshot();for(const [key,value]of [['planes',''],['altitude_km',NaN],['bus','missing'],['__proto__','x']])assert.equal(controller.change(key,value),false);assert.deepEqual(controller.snapshot(),before);assert.equal(errors.length,4);controller.change('preset','single');assert.equal(controller.change('planes',4),false);});
test('preset normalization keeps original phasing rules, clears live timer and keeps detached members',()=>{const {controller,store,timers}=setup();const nodes=controller.generate();const detached=nodes[0];assert.deepEqual(store.update(detached.id,{...detached,name:'detached'}),[]);controller.setLive(true);controller.change('planes','2');controller.change('phasing','9');assert.equal(controller.snapshot().params.phasing,1);timers.run();assert.equal(store.find(detached.id).name,'detached');assert.equal(store.find(detached.id).formation,null);const count=store.drafts.length;controller.remove();assert.equal(store.drafts.length,1);assert.ok(count>1);assert.equal(store.drafts[0].id,detached.id);});
test('adopting another selection cancels stale timer; individual selection does not activate a formation',()=>{const {controller,store,timers}=setup();controller.generate();controller.setLive(true);controller.change('altitude_km','700');const stale=[...timers.pending.values()][0].fn;controller.adopt(null);assert.equal(timers.pending.size,0);stale();assert.equal(store.drafts[0].orbit.altitude_km,550);assert.equal(controller.snapshot().activeFormationId,null);});
test('storage failure rolls back candidate and IDs; duplicate formation identity rejected',()=>{const {library,tools,timers,errors}=setup();let deny=false;const values=new Map();const storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>{if(deny)throw Error('denied');values.set(key,value);}};const store=createConstellationStore({library,storage,now:()=>epoch});store.load();const controller=tools.createFormationPanel({store,timers,now:()=>epoch,createFormationId:()=> 'F-fixed',onError:error=>errors.push(error)});const before=store.snapshot();deny=true;assert.deepEqual(controller.generate(),[]);assert.deepEqual(store.snapshot().drafts,before.drafts);assert.equal(store.idFactory()().id,'NODE-0001');deny=false;assert.equal(controller.generate().length,40);assert.deepEqual(controller.generate(),[]);assert.equal(store.drafts.length,40);});
test('disposal cancels queued writes and getters are copies',()=>{const {controller,store,timers}=setup();controller.generate();controller.setLive(true);controller.change('altitude_km',900);const stale=[...timers.pending.values()][0].fn;const snapshot=controller.snapshot();snapshot.params.altitude_km=10;assert.equal(controller.snapshot().params.altitude_km,900);controller.destroy();assert.equal(timers.pending.size,0);stale();assert.equal(store.drafts[0].orbit.altitude_km,550);assert.throws(()=>controller.generate(),/disposed/);});

test('invalid raw numeric input cancels pending live update and blocks explicit generation until corrected',()=>{const {controller,store,timers}=setup();controller.generate();controller.setLive(true);controller.change('altitude_km',700);const stale=[...timers.pending.values()][0].fn;assert.equal(controller.change('altitude_km',''),false);assert.equal(timers.pending.size,0);stale();assert.equal(store.drafts[0].orbit.altitude_km,550);assert.deepEqual(controller.generate(),[]);assert.equal(store.drafts.length,40);controller.change('altitude_km',800);assert.equal(controller.generate().length,40);});
class Element {constructor(){this.listeners=new Map();this.dataset={};this.value='';this.checked=false;this.disabled=false;this.max='11';}addEventListener(event,handler){const list=this.listeners.get(event)??new Set();list.add(handler);this.listeners.set(event,list);}removeEventListener(event,handler){this.listeners.get(event)?.delete(handler);}dispatch(event){for(const handler of [...(this.listeners.get(event)??[])])handler({target:this});}setAttribute(key,value){this[key]=value;}querySelectorAll(){return this.children??[];}}
class Host extends Element {set innerHTML(value){this.html=value;this.children=[...value.matchAll(/data-control="([^"]+)"/g)].map(match=>{const label=new Element();label.dataset.control=match[1];label.children=[new Element(),new Element()];const range=label.children[0];range.max=/type="range" min="[^"]+" max="([^"]+)"/.exec(value.slice(match.index))?.[1]??'11';return label;});}get innerHTML(){return this.html;}}
class Root {constructor(library){this.ids=new Map(['formation-controls','formation-prefix','formation-bus','formation-links','formation-generate','formation-remove','formation-live'].map(id=>[id,id==='formation-controls'?new Host():new Element()]));this.presets=Object.keys(library.FORMATION_PRESETS).map(preset=>{const el=new Element();el.dataset.formationPreset=preset;return el;});}querySelector(selector){return this.ids.get(selector.slice(1));}querySelectorAll(){return this.presets;}}
test('mounted original paired inputs/presets are scoped, update phasing bounds and release owned listeners',()=>{const {library,tools,store,timers}=setup(),root=new Root(library),errors=[];let next=0;const panel=tools.createFormationPanel({root,store,timers,now:()=>epoch,createFormationId:()=>`F-${++next}`,onError:error=>errors.push(error)});const host=root.ids.get('formation-controls');const find=key=>host.children.find(label=>label.dataset.control===key);let [range,number]=find('planes').children;number.value='2';number.dispatch('change');assert.equal(panel.snapshot().params.planes,2);assert.equal(find('phasing').children[0].max,'1');assert.equal(range.value,'2');const star=root.presets.find(button=>button.dataset.formationPreset==='walker_star');star.dispatch('click');assert.equal(panel.snapshot().params.raan_spread,180);assert.equal(star['aria-pressed'],'true');assert.equal(number.listeners.get('change').size,0);root.ids.get('formation-generate').dispatch('click');assert.equal(store.drafts.length,20);root.ids.get('formation-live').checked=true;root.ids.get('formation-live').dispatch('change');number=find('altitude_km').children[1];number.value='';number.dispatch('change');assert.equal(number.value,'');assert.equal(errors.length,1);const external=()=>{};root.ids.get('formation-generate').addEventListener('click',external);panel.destroy();assert.equal(root.ids.get('formation-generate').listeners.get('click').size,1);assert.equal(number.listeners.get('change').size,0);});
