import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const url=new URL('../../../user_application/web/scripts/scenario/workspace_adapter.js',import.meta.url);
let imports=0;
async function fixture(onRoute){let deps,changes=0,stationHook=null;const runtime={mode:'SIM',run_id:'R',scenario_id:'S',running:false,started_at:'2026-10-07T00:00:00Z',elapsed_seconds:0},nodes=[{id:'A',equipment:{radio:'X'}},{id:'B'}],stations=[{id:'G',enabled:true}],definition={id:'S',route:{source:'A',target:'G',objective:'latency'}},state={phase:'playing',runId:'R',scenarioId:'S',routeSpec:{source:'A',target:'G',objective:'latency'}};
 let source=await readFile(url,'utf8');source=source.replace("import {createScenarioRunner} from './runner.js';","const createScenarioRunner=globalThis.__routeHandoffRunner;").replace(/from '([^']+)'/g,(_,path)=>`from '${new URL(path,url).href}'`);
 globalThis.__routeHandoffRunner=options=>{deps=options;return{state,definition,stop(){state.phase='selected';},suspend(){},subscribe:()=>()=>{},setup:async()=>{},pause:async()=>{},advance:async()=>{},skipToNextStep:async()=>{},select:async()=>{}};};const {createWorkspaceScenario}=await import('data:text/javascript;base64,'+Buffer.from(source+'\n// fixture '+(++imports)).toString('base64'));delete globalThis.__routeHandoffRunner;
 const api=Object.fromEntries(['dataManagementRequest','runtimeSpeed','selectScenario','scenarioAdvance','injectFault'].map(k=>[k,async()=>runtime]));Object.assign(api,{runtimeControl:async()=>runtime,dataManagementDashboard:async()=>({module:{reachable:true}}),securityDashboard:async()=>({module:{reachable:true}})});
 const store={snapshot:()=>({drafts:structuredClone(nodes)}),get drafts(){return structuredClone(nodes);},get deployed(){return structuredClone(nodes);},idFactory:()=>()=> 'id'};const ports={store,deployment:{deploy(){}},prepareSimUtc(){},verifySimUtc(){},preflightSimScenario:async()=>true};
 const owner=createWorkspaceScenario({api,nodeWorkspace:{scenarioPorts:()=>ports},ground:{get stations(){stationHook?.();return structuredClone(stations);}},missionServices:{store:{missions:[]},execution:{plan(){},commit(){},abort(){},inspection(){}},queryModule:async()=>({reachable:true,exchange_contract:'guarded-v1',committed:{}})},fabric:{refresh:async()=>({reachable:true})},simController:{snapshot:()=>({runtime}),load:async()=>{}},nodeLibrary:{},missionTypes:{},stationModel:{},assemblyFactory:()=>({assembleConstellation:()=>({nodes:[]})}),kpi:{},onChange:()=>changes++,onRouteSpec:onRoute});await owner.preflight(definition);await deps.beginTick();return{owner,deps,api,runtime,nodes,stations,state,definition,set stationHook(value){stationHook=value;},get changes(){return changes;}};
}
test('actual scenario route copies only3 fields and preserves original onChange order',async()=>{const calls=[],f=await fixture(value=>{calls.push(value);value.source='mutated';});try{f.deps.emit('scenario:step',{source:'foreign'});assert.equal(calls.length,0);f.deps.emit('scenario:route',{...f.state.routeSpec,extra:'not forwarded'});assert.equal(calls.length,1);assert.deepEqual(calls[0],{source:'mutated',target:'G',objective:'latency'});assert.equal(f.state.routeSpec.source,'A');assert.equal(f.changes,2);}finally{f.owner.destroy();}});
for(const kind of ['run','scenario','definition','nodes','stations','route','stop','dispose'])test('route handoff refuses stale '+kind,async()=>{let calls=0;const f=await fixture(()=>calls++);try{f.deps.emit('scenario:route',f.state.routeSpec);assert.equal(calls,1);calls=0;const spec=structuredClone(f.state.routeSpec);if(kind==='run')f.runtime.run_id='other';if(kind==='scenario')f.runtime.scenario_id='other';if(kind==='definition')f.definition.route.objective='capacity';if(kind==='nodes')f.nodes[0].equipment.radio='Ka';if(kind==='stations')f.stations[0].name='sameID changed';if(kind==='route')spec.target='foreign';if(kind==='stop')f.owner.runner.stop();if(kind==='dispose')f.owner.destroy();f.deps.emit('scenario:route',spec);assert.equal(calls,0);}finally{f.owner.destroy();}});
test('route observer throw/rejected promise never changes source step event behavior',async()=>{for(const callback of [()=>{throw Error('draft rejected');},()=>Promise.reject(Error('draft rejected'))]){const f=await fixture(callback);try{assert.doesNotThrow(()=>f.deps.emit('scenario:route',f.state.routeSpec));await new Promise(r=>setImmediate(r));assert.equal(f.changes,1);}finally{f.owner.destroy();}}});
test('route payload cannot hand off after tick completion or new selection entry',async()=>{let calls=0;const f=await fixture(()=>calls++);try{f.deps.emit('scenario:route',f.state.routeSpec);assert.equal(calls,1);const lease=await f.deps.beginTick();await f.deps.endTick(lease,false,'paused');f.deps.emit('scenario:route',f.state.routeSpec);assert.equal(calls,1);await f.deps.beginTick();await f.owner.runner.select('S');f.deps.emit('scenario:route',f.state.routeSpec);assert.equal(calls,1);}finally{f.owner.destroy();}});
test('late beginTick pause response cannot hand off replaced same-ID node definitions',async()=>{let calls=0;const f=await fixture(()=>calls++);try{let release;f.runtime.running=true;f.api.runtimeControl=()=>new Promise(resolve=>release=resolve);const pending=f.deps.beginTick();assert.equal(typeof release,'function');f.nodes[0].equipment.radio='new definition';f.runtime.running=false;release(f.runtime);await pending;f.deps.emit('scenario:route',f.state.routeSpec);assert.equal(calls,0);}finally{f.owner.destroy();}});

test('terminal actual station getter cannot hand off a superseded runner routeSpec',async()=>{const calls=[],f=await fixture(spec=>calls.push(spec));try{let reads=0;f.stationHook=()=>{if(++reads===2)f.state.routeSpec={source:'B',target:'G',objective:'latency'};};f.deps.emit('scenario:route',{source:'A',target:'G',objective:'latency'});assert.deepEqual(calls,[]);assert.equal(f.state.routeSpec.source,'B');}finally{f.owner.destroy();}});
test('route payload accessor cannot swap owned route during three-field copying',async()=>{const calls=[],f=await fixture(spec=>calls.push(spec));try{let reads=0;const payload={get source(){if(++reads===3)f.state.routeSpec={source:'B',target:'G',objective:'latency'};return'A';},target:'G',objective:'latency'};f.deps.emit('scenario:route',payload);assert.deepEqual(calls,[]);assert.equal(f.state.routeSpec.source,'B');}finally{f.owner.destroy();}});
