import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkspaceNodes} from '../../../user_application/web/scripts/workspace_nodes.js';
import {createNodeLibrary} from '../../../digital_twin/model_library/browser/satellite_nodes.js';
import {orbitElements,catalogElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import * as oisl from '../../../digital_twin/simulation/browser/oisl.js';
import {NODE_COMMUNICATION_METADATA} from '../../../user_application/web/scripts/nodes/node_timeline.js';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
import {fixture as actualWorkspaceFixture} from './workspace_fixture.mjs';
import * as stationModel from '../../../digital_twin/model_library/browser/ground_stations.js';
import {createGroundLinkModel} from '../../../digital_twin/simulation/browser/ground_links.js';
import {createNetworkSnapshotModel} from '../../../digital_twin/simulation/browser/network_snapshot.js';

function fixture({native=false,solar=null,view=null,storage=null,storageGetter=null,fetchOverride=null,onHover=()=>{},networkInputs=null,readClock=()=>({}),scenarioClock=null}={}){
 let id=0,context=null,displayListener,rendererFactory,panelOptions,interaction,renderer,removeCount=0;const calls=[],sections=new Map();
 const host={innerWidth:1280,innerHeight:720,localStorage:storage,crypto:{randomUUID:()=>`test-${++id}`},setTimeout,clearTimeout,addEventListener(){},removeEventListener(){},confirm:()=>true};
 if(storageGetter)Object.defineProperty(host,'localStorage',{get:storageGetter});
 const buttons=new Map(['nodes-deploy','nodes-recall','nodes-reapply','nodes-recall-reviewed','deploy-state','node-server-configuration'].map(key=>[key,{disabled:false,textContent:'',addEventListener(k,fn){this.fn=fn;},removeEventListener(){}}]));
 const document={getElementById:id=>id==='screen'?{prepend:root=>sections.set(root.id,root)}:sections.get(id)??null,createElement:()=>({querySelector:selector=>buttons.get(selector.slice(1))??null,remove(){sections.delete(this.id);}})};
 const globe={observeDisplayContext(fn){displayListener=fn;fn(context);return()=>removeCount++;},bindNodeRenderer(fn){rendererFactory=fn;return()=>removeCount++;},nodeRendererState:()=>({phase:'ready'}),observeNodeRenderer:()=>()=>removeCount++,setSatelliteModel:(...v)=>calls.push(['model',...v]),clearSatelliteModel:()=>calls.push(['clear']),focusSatelliteModel:()=>{calls.push(['focus']);return true;},releaseSatelliteModel:()=>calls.push(['release'])};
 globe.bindNodeInteraction=value=>{interaction=value;return()=>removeCount++;};
 const Scene=class{constructor(options){this.options=options;this.points=new Map();this.labels=new Map();this.models=new Map();}async setNodes(entries){calls.push(['nodes',entries]);this.points=new Map(entries.map(entry=>[entry.id,{show:true}]));}setTheme(value){calls.push(['theme',value]);}setHovered(id){calls.push(['hover',id]);}select(id){calls.push(['select',id]);}setLinks(){}update(){}destroy(){calls.push(['destroy']);}syncFrame(){}setLinksVisible(){}setModelsVisible(){}};
 const library=createNodeLibrary({orbitElements,catalogElements,createEquipmentId:()=>`EQ-${++id}`});
 const tools={workPanelMarkup:()=>'<panel>',createNodeWorkPanel(options){panelOptions=options;return{refresh(){},destroy(){calls.push(['panel-destroy']);}};}};
 const fetchImpl=async(url,options)=>{calls.push(['http',url,options.method]);if(fetchOverride)return fetchOverride(url,options);return{ok:true,json:async()=>({revision:0,run_id:'run',scope_id:'run:unconfigured',deployment_id:null,nodes:[]})};};
 const codec=createUtcCodec(LEAP_SHA256),row=utc=>({utc,status:'valid',error_code:null,position_m:[7000000,2,3],inertial_position_km:[7000,0,0],lvlh_basis:{x:[1,0,0],y:[0,1,0],z:[0,0,1]},inertial_velocity_km_s:[0,7.5,0],raan_deg:0,argp_deg:0,mean_anomaly_deg:0,sunlit:true,longitude_deg:0,latitude_deg:0,height_km:550});
 const api={nodeSamples:async p=>{calls.push(['samples']);if(!native)throw Error('test unavailable');return{schema_version:1,...NODE_COMMUNICATION_METADATA,request_id:p.request_id,status:'valid',nodes:p.nodes.map(node=>({node_id:node.id,definition_hash:'a'.repeat(64),rows:Array.from({length:p.count},(_,i)=>row(codec.advance(p.start_utc,i)))}))};},nodeTrack:async p=>{if(!native)throw Error('test unavailable');return{schema_version:1,...NODE_COMMUNICATION_METADATA,request_id:p.request_id,status:'valid',nodes:p.nodes.map(node=>{const period=Math.round(orbitElements(node.orbit).period/60*1000)/1000;return{node_id:node.id,definition_hash:'a'.repeat(64),period_minutes:period,path_visible:true,rows:Array.from({length:121},(_,i)=>row(codec.advance(new Date(Math.trunc(Date.parse(p.center_utc)+(i-60)*period*60000/120)).toISOString(),0)))};})};}};
 if(view)Object.assign(globe,view);
 const network=networkInputs?{...networkInputs,model:createNetworkSnapshotModel({library,oisl,groundLinks:createGroundLinkModel({library,stationModel})}),validateStation:stationModel.validateStation}:null;
 const workspace=createWorkspaceNodes({api,globe,solar,library,orbitElements,catalogElements,oisl,Scene,tools,document,host,now:()=>1791151272000,resolveModel:()=>({key:'flat',url:'/flat.glb'}),models:()=>[],fetchImpl,onHover,networkInputs:network,readClock,scenarioClock});
 return{workspace,host,globe,calls,buttons,sections,context(value){context=value;displayListener(value);},get options(){return panelOptions;},get interaction(){return interaction;},get renderer(){return renderer;},attach(){return renderer=rendererFactory({},{});},get removeCount(){return removeCount;}};
}


import {createScenarioAssembly} from '../../../digital_twin/model_library/browser/scenario_assembly.js';
import {createMissionTypes} from '../../../digital_twin/model_library/browser/mission_types.js';
import {createScenarioRunner} from '../../../user_application/web/scripts/scenario/runner.js';
import * as kpi from '../../../digital_twin/verification/browser/scenario_kpi.js';

function setup(){let runtime={mode:'SIM',run_id:'run',started_at:'2026-10-07T00:00:00Z',elapsed_seconds:0,running:false,speed:1};let f;const scenarioClock={readRuntime:()=>runtime,setDisplayUtc:value=>{f.context({key:'sim:'+value.run_id,source:'sim',utc:value.utc,leap_sha256:value.leap_sha256});return true;},clearDisplayUtc:()=>{f.context(null);return true;}};f=fixture({native:true,scenarioClock,readClock:()=>({running:runtime.running,speed:runtime.speed})});return {f,runtime};}

test('node scenario ports preserve actual store and readonly native preflight before draft mutation',async()=>{const {f,runtime}=setup();await f.workspace.start();const p=f.workspace.scenarioPorts();assert.equal(p.store,f.options?.store??p.store);const library=p.nodeLibrary,assembly=createScenarioAssembly({nodeLibrary:library,stationModel,missionTypes:createMissionTypes(library)});const definition={id:'poc',constellation:{prefix:'SDC',preset:'walker_delta',planes:4,per_plane:10,altitude_km:550,inclination:53,phasing:1,raan_start:0,raan_spread:60,anomaly_start:0,bus:'comms_small',link_policy:'grid',roles:{}},stations:['daejeon'],missions:[],steps:[]};const nodes=assembly.assembleConstellation(definition,{epoch:Date.parse(runtime.started_at),idFactory:p.store.idFactory()}).nodes;const before=p.store.snapshot();assert.equal(await p.preflightSimScenario({definition,nodes}),true);assert.deepEqual(p.store.snapshot(),before);assert.equal(f.calls.filter(c=>c[0]==='samples').length,1);assert.equal(f.calls.some(c=>c[0]==='http'&&c[2]==='POST'),false);f.workspace.destroy();});

test('native SIM preparation refuses running owner and empty/unaccepted roster before shared display changes',async()=>{const {f,runtime}=setup();await f.workspace.start();const p=f.workspace.scenarioPorts();runtime.running=true;await assert.rejects(p.prepareSimUtc('2026-10-07T00:00:00.000000000Z'),/paused|정지/);runtime.running=false;await assert.rejects(p.prepareSimUtc('2026-10-07T00:00:00.000000000Z'),/배치|roster/);assert.equal(f.workspace.snapshot().display,null);f.workspace.destroy();});

test('runner tick lifecycle hooks cover the whole original step transaction and release after success',async()=>{const events=[];const runner=createScenarioRunner({assembly:{},missionTypes:{},kpi,pairKey:()=>'',api:{scenario:async()=>({id:'poc',steps:[]})},constellation:{},groundSegment:{},missionStore:{},dataDeployment:{},planner:{},networkTwin:{tick:()=>events.push('native-network'),last:{}},clock:{elapsed:()=>0,now:()=>0},beginTick:async()=>{events.push('pause');return 'lease';},endTick:async(lease,ok)=>events.push([lease,ok])});await runner.select('poc');runner.state.phase='ready';await runner.tick();assert.deepEqual(events,['pause','native-network',['lease',true]]);});


test('accepted native SIM receipt rejects UTC drift, definition edits, and running clock',async()=>{
 let runtime={mode:'SIM',run_id:'run',started_at:'2026-10-07T00:00:00Z',elapsed_seconds:0,running:false,speed:1},f,server={revision:0,run_id:'run',scope_id:'run:unconfigured',deployment_id:null,nodes:[]};
 const scenarioClock={readRuntime:()=>runtime,setDisplayUtc:v=>{f.context({key:'sim:'+v.run_id,source:'sim',utc:v.utc,leap_sha256:v.leap_sha256});return true;},clearDisplayUtc:()=>true};
 f=fixture({native:true,scenarioClock,readClock:()=>({running:runtime.running}),fetchOverride:async(url,o)=>{if(o.method==='POST'){const v=JSON.parse(o.body);server={revision:1,run_id:'run',scope_id:'run:deployment:'+v.deployment_id,deployment_id:v.deployment_id,nodes:v.nodes};}return {ok:true,json:async()=>structuredClone(server)};}});
 await f.workspace.start();const p=f.workspace.scenarioPorts();p.store.add({name:'actual native'});await p.deployment.deploy();
 const utc='2026-10-07T00:00:00.000000000Z',receipt=await p.prepareSimUtc(utc);assert.equal(p.verifySimUtc(receipt,utc),true);receipt.states[0][1].definition_hash='b'.repeat(64);assert.equal(p.verifySimUtc(receipt,utc),false);
 const good=await p.prepareSimUtc(utc);runtime.running=true;assert.equal(p.verifySimUtc(good,utc),false);runtime.running=false;runtime.elapsed_seconds=1;assert.equal(p.verifySimUtc(good,utc),false);runtime.elapsed_seconds=0;p.store.update(p.store.drafts[0].id,{name:'edited'});assert.equal(p.verifySimUtc(good,utc),false);f.workspace.destroy();
});

test('tick error releases lifecycle lease as unsuccessful rather than resuming silently',async()=>{const ends=[];const runner=createScenarioRunner({assembly:{},missionTypes:{},kpi,pairKey:()=>'',api:{scenario:async()=>({id:'poc',steps:[]})},constellation:{},groundSegment:{},missionStore:{},dataDeployment:{},planner:{},networkTwin:{tick:()=>{throw Error('native failure');}},clock:{elapsed:()=>0,now:()=>0},beginTick:async()=>({running:true}),endTick:async(lease,ok)=>ends.push(ok)});await runner.select('poc');runner.state.phase='ready';await assert.rejects(runner.tick(),/native failure/);assert.deepEqual(ends,[false]);});

test('explicit advance waits for the existing whole-step native transaction',async()=>{let release,calls=0;const block=new Promise(resolve=>release=resolve);let first=true;const runner=createScenarioRunner({assembly:{},missionTypes:{},kpi,pairKey:()=>'',api:{scenario:async()=>({id:'poc',steps:[]}),scenarioAdvance:async()=>{calls++;return {elapsed_seconds:1};}},constellation:{},groundSegment:{},missionStore:{},dataDeployment:{},planner:{},networkTwin:{tick:()=>{if(first){first=false;return block;}return null;},exchange:async()=>null,last:{}},clock:{elapsed:()=>0,now:()=>0}});await runner.select('poc');runner.state.phase='ready';const active=runner.tick();await Promise.resolve();const advancing=runner.advance(1);await Promise.resolve();const before=calls;release();await Promise.all([active,advancing]);assert.equal(before,0);assert.equal(calls,1);});

test('forward advance and all forced native exchanges share an actually paused SIM lease',async()=>{const runtime={running:true,elapsed:0};const calls=[];const runner=createScenarioRunner({assembly:{},missionTypes:{},kpi,pairKey:()=>'',api:{scenario:async()=>({id:'poc',steps:[]}),scenarioAdvance:async()=>{assert.equal(runtime.running,false);calls.push('advance');runtime.elapsed++;return {elapsed_seconds:runtime.elapsed};}},constellation:{deployed:[],drafts:[]},groundSegment:{stations:[]},missionStore:{find:()=>null},dataDeployment:{},planner:{},networkTwin:{tick:()=>{assert.equal(runtime.running,false);calls.push('native');},exchange:async()=>null,reachable:()=>false,report:null,last:{}},clock:{elapsed:()=>runtime.elapsed,now:()=>runtime.elapsed*1000,disengage(){}},beginTick:async()=>{const lease={running:runtime.running};runtime.running=false;return lease;},endTick:async(lease,ok,phase)=>{if(lease.running&&ok&&phase==='playing')runtime.running=true;}});await runner.select('poc');runner.state.phase='playing';await runner.advance(1);assert.equal(runtime.running,true);assert.deepEqual(calls,['advance','native','native']);runner.stop();});

test('SIM snapshot UTC delegates source milliseconds/offset conversion to the existing common owner',async()=>{let f;const runtime={mode:'SIM',run_id:'run',started_at:'2026-10-06T19:46:48.928502+09:00',elapsed_seconds:1.234,running:false,speed:1};const codec=createUtcCodec(LEAP_SHA256);const scenarioClock={readRuntime:()=>runtime,utcOfRuntime:s=>codec.advance(new Date(Date.parse(s.started_at)+s.elapsed_seconds*1000).toISOString(),0),setDisplayUtc:()=>true,clearDisplayUtc:()=>true};f=fixture({native:true,scenarioClock});await f.workspace.start();assert.equal(f.workspace.scenarioPorts().simUtc(),'2026-10-06T10:46:50.162000000Z');f.workspace.destroy();});
