// Guard tests with fake transport receipts. Actual native integration is the ASGI capture tool.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWorkspaceScenario} from '../../../user_application/web/scripts/scenario/workspace_adapter.js';
import {createScenarioAssembly as assemblyFactory} from '../../../digital_twin/model_library/browser/scenario_assembly.js';
import {createNodeLibrary} from '../../../digital_twin/model_library/browser/satellite_nodes.js';
import {createMissionTypes} from '../../../digital_twin/model_library/browser/mission_types.js';
import * as stationModel from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as kpi from '../../../digital_twin/verification/browser/scenario_kpi.js';
import {orbitElements,catalogElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import {NODE_COMMUNICATION_METADATA} from '../../../user_application/web/scripts/nodes/node_timeline.js';
import {STORAGE_KEY} from '../../../user_application/web/scripts/scenario/runner.js';
const definition=JSON.parse(await readFile(new URL('../fixtures/source_sdc_poc.json',import.meta.url)));
const clone=v=>structuredClone(v);
function fixture(clockOwners={}){
 let id=0;const library=createNodeLibrary({orbitElements,catalogElements,createEquipmentId:()=>`EQ-${++id}`}),model=createMissionTypes(library),assembly=assemblyFactory({nodeLibrary:library,stationModel,missionTypes:model});
 const nodes=assembly.assembleConstellation(definition,{epoch:Date.parse('2026-10-07T00:00:00Z'),idFactory:()=>({id:'N'+(++id),catalogNumber:900000+id})}).nodes;
 const stations=assembly.assembleStations(definition),missionIds={relay:'M1',observe:'M2',fleet_update:'M3'},missions=['M1','M2','M3'].map((id,i)=>({id,kind:definition.missions[i].kind,params:definition.missions[i].params,notes:'[scenario:SDC_POC_01]',version:1,status:i<2?'committed':'planned',plan:{plan_sequence:i+1,context_hash:'a'.repeat(64),tasks:[{id:id+'T1'}]}}));
 const deployment={run_id:'run',revision:1,deployment_id:'deployment',scope_id:'run:deployment:deployment',nodes:nodes.map(n=>({id:n.id,name:n.name,mode:n.mode,equipment:n.equipment.map(e=>({id:e.id,catalog:e.catalog,enabled:e.enabled}))}))};
 const module={reachable:true,exchange_contract:'guarded-v1',instance_id:'module',sequence:5,committed:{M1:{tasks:missions[0].plan.tasks},M2:{tasks:missions[1].plan.tasks}},accepted_plans:Object.fromEntries(missions.map(m=>[m.id,clone(m.plan)]))};
 const hashes=Object.fromEntries(nodes.map(n=>[n.id,'b'.repeat(64)])),runtime={mode:'SIM',run_id:'run',scenario_id:definition.id,started_at:'2026-10-07T00:00:00Z',elapsed_seconds:0,running:false,speed:2,active_faults:[]};
 let dirty=false,mutations=0,nativeReads=0,late=()=>{},confirmed=true;
 const store={get deployed(){return clone(nodes);},get deploymentConfirmed(){return confirmed;},isDirty:()=>dirty};
 const receipt={run_id:'run',utc:'2026-10-07T00:00:00.000000000Z',nodes:clone(nodes),deployment:clone(deployment),states:nodes.map(n=>[n.id,{definition_hash:hashes[n.id]}])};
 const ports={store,nodeLibrary:library,deployment:{state:{server:deployment,syncRequired:false,busy:false},refresh:async()=>deployment,reacceptCachedDeployment:async()=>deployment},simUtc:()=>receipt.utc,prepareSimUtc:async()=>{nativeReads++;return clone(receipt);},verifySimUtc:()=>!dirty&&runtime.running===false&&runtime.run_id==='run'};
 const roster=()=>missions.map(m=>Object.fromEntries(['id','kind','params','notes','version','status','plan'].map(k=>[k,m[k]])));
 const evidence={schema_version:1,contract:'source-scenario-resume-v1',source_commit:NODE_COMMUNICATION_METADATA.source_commit,run_id:runtime.run_id,started_at:runtime.started_at,definition:clone(definition),nodes:clone(nodes),deployment:clone(deployment),stations:clone(stations),missions:roster(),module:{instance_id:module.instance_id,committed:clone(module.committed),accepted_plans:clone(module.accepted_plans)},faults:[],native_definition_hashes:clone(hashes)};
 const saved={phase:'playing',scenarioId:definition.id,runId:'run',missions:missionIds,workspaceEvidence:evidence};let raw=JSON.stringify(saved);
 const context=()=>({utc:receipt.utc,nodes:clone(nodes),stations:clone(stations),faults:clone(runtime.active_faults),deployment:clone(deployment),module:{instance:module.instance_id,sequence:module.sequence},external:null});
 const workspace=createWorkspaceScenario({api:{scenario:async()=>clone(definition),runtimeControl:async()=>{mutations++;throw Error('unexpected mutation');},nodeMissionContext:async command=>{late();return {schema_version:1,status:'verified_analysis_inputs',communication_status:'unknown',context_hash:'c'.repeat(64),utc:command.utc,nodes:command.nodes,stations:command.stations,faults:command.faults,deployment:clone(deployment),definition_hashes:clone(hashes),external:null,module_instance:command.module_instance,module_sequence:command.module_sequence};}},nodeWorkspace:{scenarioPorts:()=>ports},ground:{get stations(){return clone(stations);},get enabled(){return clone(stations);}},missionServices:{store:{get missions(){return clone(missions);}},queryModule:async()=>clone(module),context},fabric:{},simController:{snapshot:()=>({runtime:clone(runtime)})},nodeLibrary:library,missionTypes:model,stationModel,assemblyFactory,kpi,clockOwners,storage:{getItem:()=>raw,setItem:(key,value)=>{if(key===STORAGE_KEY)raw=value;}}});
 return {workspace,nodes,stations,missions,module,runtime,receipt,evidence,saved,read:()=>({mutations,nativeReads}),dirty:()=>dirty=true,late:fn=>late=fn,legacy:()=>{delete saved.workspaceEvidence;raw=JSON.stringify(saved);}};
}
test('same-run explicit resume verifies all40 definitions and native context without runtime commands',async()=>{const f=fixture();assert.equal(await f.workspace.runner.restore(),true);assert.equal(f.workspace.runner.state.phase,'paused');const accepted=await f.workspace.resumePreflight();assert.equal(accepted.node_count,40);assert.equal(accepted.communication_status,'unknown');assert.deepEqual(f.read(),{mutations:0,nativeReads:1});f.workspace.destroy();});
for(const [name,change] of [['foreign run',f=>f.runtime.run_id='other'],['running SIM',f=>f.runtime.running=true],['dirty definition',f=>f.dirty()],['station edit',f=>f.stations[0].longitude++],['foreign held mission',f=>f.module.committed.FOREIGN={tasks:[]}],['changed native proof',f=>f.receipt.states[0][1].definition_hash='d'.repeat(64)],['legacy record',f=>f.legacy()]])test(name+' rejects resume and never changes runtime',async()=>{const f=fixture();change(f);await f.workspace.runner.restore();await assert.rejects(f.workspace.resumePreflight());assert.equal(f.read().mutations,0);f.workspace.destroy();});
test('last-await change cannot publish prepared authorization',async()=>{const f=fixture();await f.workspace.runner.restore();f.late(()=>f.dirty());await assert.rejects(f.workspace.resumePreflight(),/検証|검증|바뀌/);await assert.rejects(f.workspace.runner.play(),/native.*SIM UTC/);assert.equal(f.read().mutations,0);f.workspace.destroy();});
test('prepared resume cannot issue controls to a later foreign run',async()=>{const f=fixture();await f.workspace.runner.restore();await f.workspace.resumePreflight();f.runtime.run_id='later-run';await assert.rejects(f.workspace.runner.play(),/실제 SIM 실행/);assert.equal(f.read().mutations,0);f.workspace.destroy();});

test('explicit analysis follow waits for the existing coordinator and reviewed stop awaits release',async()=>{let source=null,releaseFinish;const events=[];const f=fixture({followedSource:()=>source,followAll:async value=>{events.push('follow');await Promise.resolve();source=value;return {frame:'ITRF'};},releaseAll:async value=>{assert.equal(value,source);events.push('release-start');await new Promise(resolve=>releaseFinish=resolve);source=null;events.push('release-done');return true;}});try{await f.workspace.runner.restore();await f.workspace.resumePreflight();const result=await f.workspace.followAnalysis();assert.equal(result.frame,'ITRF');assert.equal(source,f.workspace.clock);const stopping=f.workspace.stopReviewed();await Promise.resolve();assert.equal(f.workspace.runner.state.phase,'paused');releaseFinish();await stopping;assert.equal(f.workspace.runner.state.phase,'idle');assert.deepEqual(events,['follow','release-start','release-done']);assert.equal(f.read().mutations,0);}finally{f.workspace.destroy();}});
test('follow cannot silently accept a changed runtime after coordinator await',async()=>{let source=null,f;f=fixture({followedSource:()=>source,followAll:async value=>{source=value;f.runtime.run_id='different';}});try{await f.workspace.runner.restore();await f.workspace.resumePreflight();await assert.rejects(f.workspace.followAnalysis(),/실제 SIM/);assert.equal(f.read().mutations,0);}finally{f.workspace.destroy();}});
test('failed release preserves scenario phase and disposal issues no release writes',async()=>{let source=null,releases=0;const f=fixture({followedSource:()=>source,followAll:async value=>{source=value;},releaseAll:async()=>{releases++;throw Error('native release failed');}});await f.workspace.runner.restore();await f.workspace.resumePreflight();await f.workspace.followAnalysis();await assert.rejects(f.workspace.stopReviewed(),/native release failed/);assert.equal(f.workspace.runner.state.phase,'paused');f.workspace.destroy();assert.equal(releases,1);});
