// Guard tests with fake transport receipts. Actual native integration is the ASGI capture tool.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createWorkspaceScenario} from '../../../user_application/web/scripts/scenario/workspace_adapter.js';
import {createScenarioAssembly as assemblyFactory} from '../../../digital_twin/model_library/browser/scenario_assembly.js';
import {createNodeLibrary} from '../../../digital_twin/model_library/browser/satellite_nodes.js';
import {createMissionTypes} from '../../../digital_twin/model_library/browser/mission_types.js';
import * as stationModel from '../../../digital_twin/model_library/browser/ground_stations.js';
import * as kpi from '../../../digital_twin/verification/browser/scenario_kpi.js';
import {orbitElements,catalogElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import {NODE_COMMUNICATION_METADATA} from '../../../user_application/web/scripts/nodes/node_timeline.js';
import {STORAGE_KEY} from '../../../user_application/web/scripts/scenario/runner.js';
const definition=JSON.parse(await readFile(new URL('../fixtures/source_sdc_poc.json',import.meta.url)));
const clone=v=>structuredClone(v);
function fixture(clockOwners={}){
 let id=0;const library=createNodeLibrary({orbitElements,catalogElements,createEquipmentId:()=>`EQ-${++id}`}),model=createMissionTypes(library),assembly=assemblyFactory({nodeLibrary:library,stationModel,missionTypes:model});
 const nodes=assembly.assembleConstellation(definition,{epoch:Date.parse('2026-10-07T00:00:00Z'),idFactory:()=>({id:'N'+(++id),catalogNumber:900000+id})}).nodes;
 const stations=assembly.assembleStations(definition),missionIds={relay:'M1',observe:'M2',fleet_update:'M3'},missions=['M1','M2','M3'].map((id,i)=>({id,kind:definition.missions[i].kind,params:definition.missions[i].params,notes:'[scenario:SDC_POC_01]',version:1,status:i<2?'committed':'planned',plan:{exchange_contract:'guarded-v1',instance_id:'module',mission_id:id,mission_version:1,version:1,request_id:'plan:'+id,time:'2026-10-07T00:00:00.000000000Z',sequence:i+1,plan_sequence:i+1,feasible:true,context_hash:'a'.repeat(64),tasks:[{id:id+'T1',satellite:'N1',kind:'downlink',start:'2026-10-07T00:00:00Z',end:'2026-10-07T00:01:00Z'}]}}));
 const deployment={run_id:'run',revision:1,deployment_id:'deployment',scope_id:'run:deployment:deployment',nodes:nodes.map(n=>({id:n.id,name:n.name,mode:n.mode,equipment:n.equipment.map(e=>({id:e.id,catalog:e.catalog,enabled:e.enabled}))}))};
 const held=m=>({version:m.plan.mission_version,sequence:5,time:m.plan.time,tasks:m.plan.tasks.map(t=>({task_id:t.id,satellite:t.satellite,kind:t.kind,start:t.start,end:t.end}))});
 const module={reachable:true,exchange_contract:'guarded-v1',instance_id:'module',sequence:5,committed:{M1:held(missions[0]),M2:held(missions[1])},accepted_plans:Object.fromEntries(missions.map(m=>[m.id,clone(m.plan)]))};
 const hashes=Object.fromEntries(nodes.map(n=>[n.id,'b'.repeat(64)])),runtime={mode:'SIM',run_id:'run',scenario_id:definition.id,started_at:'2026-10-07T00:00:00Z',elapsed_seconds:0,running:false,speed:2,active_faults:[]};
 let dirty=false,mutations=0,nativeReads=0,late=()=>{},confirmed=true;
 const store={get deployed(){return clone(nodes);},get deploymentConfirmed(){return confirmed;},isDirty:()=>dirty};
 const receipt={run_id:'run',utc:'2026-10-07T00:00:00.000000000Z',nodes:clone(nodes),deployment:clone(deployment),states:nodes.map(n=>[n.id,{definition_hash:hashes[n.id]}])};
 const ports={store,nodeLibrary:library,deployment:{state:{server:deployment,syncRequired:false,busy:false},refresh:async()=>deployment,reacceptCachedDeployment:async()=>{confirmed=true;return clone(deployment);}},simUtc:()=>receipt.utc,prepareSimUtc:async()=>{nativeReads++;return clone(receipt);},verifySimUtc:()=>!dirty&&runtime.running===false&&runtime.run_id==='run'};
 const roster=()=>missions.map(m=>Object.fromEntries(['id','kind','params','notes','version','status','plan'].map(k=>[k,m[k]])));
 const evidence={schema_version:1,contract:'source-scenario-resume-v1',source_commit:NODE_COMMUNICATION_METADATA.source_commit,run_id:runtime.run_id,started_at:runtime.started_at,definition:clone(definition),nodes:clone(nodes),deployment:clone(deployment),stations:clone(stations),missions:roster(),module:{instance_id:module.instance_id,committed:clone(module.committed),accepted_plans:clone(module.accepted_plans)},faults:[],native_definition_hashes:clone(hashes)};
 const saved={phase:'playing',scenarioId:definition.id,runId:'run',missions:missionIds,workspaceEvidence:evidence};let raw=JSON.stringify(saved);
 const context=()=>({utc:receipt.utc,nodes:clone(nodes),stations:clone(stations),faults:clone(runtime.active_faults),deployment:clone(deployment),module:{instance:module.instance_id,sequence:module.sequence},external:null});
 const workspace=createWorkspaceScenario({api:{dataManagementDashboard:async()=>({}),securityDashboard:async()=>({}),scenario:async()=>clone(definition),runtimeControl:async()=>{mutations++;throw Error('unexpected mutation');},nodeMissionContext:async command=>{late();return {schema_version:1,status:'verified_analysis_inputs',communication_status:'unknown',context_hash:'c'.repeat(64),utc:command.utc,nodes:command.nodes,stations:command.stations,faults:command.faults,deployment:clone(deployment),definition_hashes:clone(hashes),external:null,module_instance:command.module_instance,module_sequence:command.module_sequence};}},nodeWorkspace:{scenarioPorts:()=>ports,updateNetwork:async()=>({}),networkSnapshot:()=>({nodes:[],links:[]})},ground:{get stations(){return clone(stations);},get enabled(){return clone(stations);}},missionServices:{store:{get missions(){return clone(missions);},find:id=>clone(missions.find(m=>m.id===id))},queryModule:async()=>clone(module),context},fabric:{snapshot:()=>({status:'accepted',receipt:{nodes:[],links:[],sequence:1}}),send:async()=>({accepted:true})},simController:{snapshot:()=>({runtime:clone(runtime)})},nodeLibrary:library,missionTypes:model,stationModel,assemblyFactory,kpi,clockOwners,storage:{getItem:()=>raw,setItem:(key,value)=>{if(key===STORAGE_KEY)raw=value;}}});
 return {workspace,nodes,stations,missions,module,runtime,receipt,evidence,saved,deployment,read:()=>({mutations,nativeReads}),dirty:()=>dirty=true,late:fn=>late=fn,legacy:()=>{delete saved.workspaceEvidence;raw=JSON.stringify(saved);},finish:()=>{confirmed=false;saved.phase='finished';saved.verdict={ok:false,groups:[{id:'source-nominal',ok:false}]};saved.finishedAt='2026-10-07T00:14:44.681Z';runtime.elapsed_seconds=884.681;receipt.utc='2026-10-07T00:14:44.681000000Z';raw=JSON.stringify(saved);}};
}
test('same-run explicit resume verifies all40 definitions and native context without runtime commands',async()=>{const f=fixture();assert.equal(await f.workspace.runner.restore(),true);assert.equal(f.workspace.runner.state.phase,'paused');const accepted=await f.workspace.resumePreflight();assert.equal(accepted.node_count,40);assert.equal(accepted.communication_status,'unknown');assert.deepEqual(f.read(),{mutations:0,nativeReads:1});f.workspace.destroy();});
for(const [name,change] of [['foreign run',f=>f.runtime.run_id='other'],['running SIM',f=>f.runtime.running=true],['dirty definition',f=>f.dirty()],['station edit',f=>f.stations[0].longitude++],['foreign held mission',f=>f.module.committed.FOREIGN={tasks:[]}],['changed native proof',f=>f.receipt.states[0][1].definition_hash='d'.repeat(64)],['legacy record',f=>f.legacy()]])test(name+' rejects resume and never changes runtime',async()=>{const f=fixture();change(f);await f.workspace.runner.restore();await assert.rejects(f.workspace.resumePreflight());assert.equal(f.read().mutations,0);f.workspace.destroy();});
test('last-await change cannot publish prepared authorization',async()=>{const f=fixture();await f.workspace.runner.restore();f.late(()=>f.dirty());await assert.rejects(f.workspace.resumePreflight(),/検証|검증|바뀌/);await assert.rejects(f.workspace.runner.play(),/native.*SIM UTC/);assert.equal(f.read().mutations,0);f.workspace.destroy();});
test('prepared resume cannot issue controls to a later foreign run',async()=>{const f=fixture();await f.workspace.runner.restore();await f.workspace.resumePreflight();f.runtime.run_id='later-run';await assert.rejects(f.workspace.runner.play(),/실제 SIM 실행/);assert.equal(f.read().mutations,0);f.workspace.destroy();});

test('explicit analysis follow waits for the existing coordinator and reviewed stop awaits release',async()=>{let source=null,releaseFinish;const events=[];const f=fixture({followedSource:()=>source,followAll:async value=>{events.push('follow');await Promise.resolve();source=value;return {frame:'ITRF'};},releaseAll:async value=>{assert.equal(value,source);events.push('release-start');await new Promise(resolve=>releaseFinish=resolve);source=null;events.push('release-done');return true;}});try{await f.workspace.runner.restore();await f.workspace.resumePreflight();const result=await f.workspace.followAnalysis();assert.equal(result.frame,'ITRF');assert.equal(source,f.workspace.clock);const stopping=f.workspace.stopReviewed();await Promise.resolve();assert.equal(f.workspace.runner.state.phase,'paused');releaseFinish();await stopping;assert.equal(f.workspace.runner.state.phase,'idle');assert.deepEqual(events,['follow','release-start','release-done']);assert.equal(f.read().mutations,0);}finally{f.workspace.destroy();}});
test('follow cannot silently accept a changed runtime after coordinator await',async()=>{let source=null,f;f=fixture({followedSource:()=>source,followAll:async value=>{source=value;f.runtime.run_id='different';}});try{await f.workspace.runner.restore();await f.workspace.resumePreflight();await assert.rejects(f.workspace.followAnalysis(),/실제 SIM/);assert.equal(f.read().mutations,0);}finally{f.workspace.destroy();}});
test('failed release preserves scenario phase and disposal issues no release writes',async()=>{let source=null,releases=0;const f=fixture({followedSource:()=>source,followAll:async value=>{source=value;},releaseAll:async()=>{releases++;throw Error('native release failed');}});await f.workspace.runner.restore();await f.workspace.resumePreflight();await f.workspace.followAnalysis();await assert.rejects(f.workspace.stopReviewed(),/native release failed/);assert.equal(f.workspace.runner.state.phase,'paused');f.workspace.destroy();assert.equal(releases,1);});

test('finished workspace input revalidation preserves original verdict/phase and cannot enable playback commands',async()=>{const f=fixture();f.finish();await f.workspace.runner.restore();const runtime=clone(f.runtime),state=clone(f.workspace.runner.state);const result=await f.workspace.resumePreflight();assert.equal(result.playback_authorized,false);assert.equal(result.validation_kind,'finished_workspace_inputs');assert.equal(result.utc,'2026-10-07T00:14:44.681000000Z');assert.deepEqual(f.workspace.runner.state,state);assert.deepEqual(f.runtime,runtime);assert.deepEqual(f.read(),{mutations:0,nativeReads:1});await f.workspace.runner.play();await assert.rejects(f.workspace.runner.advance(30),/native.*SIM UTC/);await assert.rejects(f.workspace.runner.setSpeed(60),/native.*SIM UTC/);assert.deepEqual(f.workspace.runner.state,state);assert.deepEqual(f.read(),{mutations:0,nativeReads:1});f.workspace.destroy();});
for(const [name,change]of [['module instance',f=>f.module.instance_id='foreign'],['node roster',f=>f.nodes[0].name='changed'],['late UTC',f=>f.late(()=>{f.runtime.elapsed_seconds++;f.receipt.utc='2026-10-07T00:14:45.681000000Z';})]])test('finished input revalidation rejects '+name+' without resetting the completed record',async()=>{const f=fixture();f.finish();await f.workspace.runner.restore();const state=clone(f.workspace.runner.state);change(f);await assert.rejects(f.workspace.resumePreflight());assert.deepEqual(f.workspace.runner.state,state);assert.equal(f.read().mutations,0);await assert.rejects(f.workspace.runner.advance(30));assert.equal(f.read().mutations,0);f.workspace.destroy();});

test('finished validation catches owner elapsed drift even if a stale UTC accessor retains its old value',async()=>{const f=fixture();f.finish();await f.workspace.runner.restore();const state=clone(f.workspace.runner.state);f.late(()=>{f.runtime.elapsed_seconds++;});await assert.rejects(f.workspace.resumePreflight(),/실제 실행 상태/);assert.deepEqual(f.workspace.runner.state,state);assert.equal(f.read().mutations,0);await assert.rejects(f.workspace.runner.setSpeed(30));f.workspace.destroy();});
test('finished validation cannot publish authority after the original record or workspace lifetime changes',async()=>{for(const kind of ['record','disposed']){const f=fixture();f.finish();await f.workspace.runner.restore();f.late(()=>{if(kind==='record')f.workspace.runner.setAutoFollow(false);else f.workspace.destroy();});await assert.rejects(f.workspace.resumePreflight(),/완료 기록|실제 실행 상태/);assert.equal(f.workspace.runner.state.phase,'finished');assert.deepEqual(f.workspace.runner.state.verdict,{ok:false,groups:[{id:'source-nominal',ok:false}]});assert.equal(f.read().mutations,0);await assert.rejects(f.workspace.runner.advance(30));f.workspace.destroy();}});

for(const [field,change]of [['missions',f=>{f.missions[0].plan.context_hash='d'.repeat(64);}],['module.accepted_plans',f=>{f.module.accepted_plans.M1.context_hash='e'.repeat(64);}],['module.instance_id',f=>{f.module.instance_id='foreign-module';}],['deployment',f=>{f.deployment.revision++;}]])test('strict resume diagnostic names only changed evidence field '+field,async()=>{const f=fixture();f.finish();await f.workspace.runner.restore();const state=clone(f.workspace.runner.state);change(f);await assert.rejects(f.workspace.resumePreflight(),error=>{assert.match(error.message,/불일치:/);assert.ok(error.message.includes(field),error.message);assert.doesNotMatch(error.message,/dddddddd|eeeeeeee|foreign-module/);return true;});assert.deepEqual(f.workspace.runner.state,state);assert.equal(f.read().mutations,0);await assert.rejects(f.workspace.runner.advance(30));f.workspace.destroy();});

function changedFinished(f){f.finish();f.runtime.active_faults=[{id:'expired-source-fault',active:false}];for(const id of ['M1','M2']){const local=f.missions.find(m=>m.id===id);local.plan.version=local.plan.mission_version=2;local.plan.sequence=local.plan.plan_sequence+=5;local.plan.context_hash='d'.repeat(64);f.module.accepted_plans[id]=clone(local.plan);f.module.committed[id]={version:2,sequence:10,time:local.plan.time,tasks:local.plan.tasks.map(t=>({task_id:t.id,satellite:t.satellite,kind:t.kind,start:t.start,end:t.end}))};}f.module.sequence=10;}
test('explicit finished current-input review proves current owners but preserves stale historical checkpoint/result byte for byte',async()=>{const f=fixture();changedFinished(f);await f.workspace.runner.restore();const state=JSON.stringify(f.workspace.runner.state),record=JSON.stringify(f.workspace.runner.record()),runtime=clone(f.runtime);await assert.rejects(f.workspace.resumePreflight(),/불일치:/);assert.equal(typeof f.workspace.reviewFinishedInputs,'function');const result=await f.workspace.reviewFinishedInputs();assert.equal(result.validation_kind,'finished_current_inputs_review');assert.equal(result.playback_authorized,false);assert.equal(result.node_count,40);assert.ok(result.changed_fields.includes('missions'));assert.equal(JSON.stringify(f.workspace.runner.state),state);assert.equal(JSON.stringify(f.workspace.runner.record()),record);assert.deepEqual(f.runtime,runtime);assert.equal(f.read().mutations,0);await assert.rejects(f.workspace.runner.advance(30));await assert.rejects(f.workspace.followAnalysis());f.workspace.destroy();});
for(const [name,change] of [['stale local plan',f=>f.missions[0].plan.tasks[0].id='tampered'],['changed instance',f=>f.module.instance_id='new-module'],['changed roster',f=>f.nodes[0].name='new-node'],['malformed remote proof',f=>f.module.accepted_plans.M1.context_hash='bad'],['late module change',f=>f.late(()=>f.module.sequence++)],['late UTC change',f=>f.late(()=>f.runtime.elapsed_seconds++)],['disposed',f=>f.late(()=>f.workspace.destroy())],['changed source mission template',f=>f.missions[0].notes='edited'],['foreign held mission',f=>f.module.committed.FOREIGN={version:1}],['changed held tasks',f=>f.module.committed.M1.tasks[0].satellite='other'],['changed held version',f=>f.module.committed.M1.version=99],['changed local committed status',f=>f.missions[0].status='planned']])test('finished new review rejects '+name+' and preserves historical proof without runtime commands',async()=>{const f=fixture();changedFinished(f);await f.workspace.runner.restore();change(f);const state=JSON.stringify(f.workspace.runner.state);assert.equal(typeof f.workspace.reviewFinishedInputs,'function');await assert.rejects(f.workspace.reviewFinishedInputs());assert.equal(JSON.stringify(f.workspace.runner.state),state);assert.equal(f.read().mutations,0);await assert.rejects(f.workspace.runner.advance(30));f.workspace.destroy();});
test('automatic source verdict tick checkpoints final mission/fault owners before losing playback authority',async()=>{const f=fixture();await f.workspace.runner.restore();await f.workspace.resumePreflight();const state=f.workspace.runner.state;state.phase='playing';state.roles={};state.routeSpec=null;state.steps={};f.workspace.runner.definition.steps=[{id:'last',order:1,tab:'compare',at:{offset_s:0},actions:[{kind:'verdict'}]}];f.missions[0].plan.context_hash='d'.repeat(64);f.module.accepted_plans.M1=clone(f.missions[0].plan);f.runtime.active_faults=[{id:'source-ended',active:false}];await f.workspace.runner.tick();assert.equal(state.phase,'finished');assert.deepEqual(state.workspaceEvidence.faults,f.runtime.active_faults);assert.deepEqual(state.workspaceEvidence.missions[0].plan,f.missions[0].plan);assert.deepEqual(state.workspaceEvidence.module.accepted_plans.M1,f.module.accepted_plans.M1);await assert.rejects(f.workspace.runner.advance(30));f.workspace.destroy();});

test('finished new review cannot authorize after record presentation changes during native acceptance',async()=>{const f=fixture();changedFinished(f);await f.workspace.runner.restore();const proof=JSON.stringify(f.workspace.runner.state.workspaceEvidence),record=JSON.stringify(f.workspace.runner.record());f.late(()=>f.workspace.runner.setAutoFollow(false));await assert.rejects(f.workspace.reviewFinishedInputs(),/완료 기록|실제 실행 상태/);assert.equal(JSON.stringify(f.workspace.runner.state.workspaceEvidence),proof);assert.equal(JSON.stringify(f.workspace.runner.record()),record);assert.equal(f.read().mutations,0);await assert.rejects(f.workspace.runner.advance(30));f.workspace.destroy();});
