import test from 'node:test';
import assert from 'node:assert/strict';
import {createShellPreferences} from '../../../user_application/web/scripts/settings/shell_preferences.js';
import {fixture} from './workspace_fixture.mjs';
function setup(saved=null){const records=new Map(saved?[['spacetwin-theme',saved]]:[]),events=new Map();const document={documentElement:{dataset:{},style:{}},fullscreenElement:null,addEventListener:(key,fn)=>events.set(key,fn),removeEventListener:key=>events.delete(key)};const storage={getItem:key=>records.get(key)??null,setItem:(key,value)=>records.set(key,value)};let changes=0;const prefs=createShellPreferences({document,storage,onChange:()=>changes++});return {prefs,document,storage,records,events,get changes(){return changes;}};}
test('shell defaults dark and restores only original persisted light/dark key without map changes',()=>{const f=setup();assert.equal(f.document.documentElement.dataset.theme,'dark');assert.equal(f.records.size,0);f.prefs.setTheme('light');assert.equal(f.records.get('spacetwin-theme'),'light');assert.equal(f.document.documentElement.style.colorScheme,'light');assert.equal(setup('light').prefs.snapshot().theme,'light');assert.equal(setup('invalid').prefs.snapshot().theme,'dark');});
test('storage failure reports unsaved presentation preference and allows recovery',()=>{const f=setup();f.storage.setItem=()=>{throw Error('blocked');};f.prefs.setTheme('light');assert.equal(f.prefs.snapshot().theme,'light');assert.match(f.prefs.snapshot().error,/저장/);f.storage.setItem=(key,value)=>f.records.set(key,value);f.prefs.setTheme('dark');assert.equal(f.prefs.snapshot().error,'');assert.equal(f.records.get('spacetwin-theme'),'dark');});
test('fullscreen follows actual document state and never claims unsupported or rejected success',async()=>{const f=setup();await f.prefs.toggleFullscreen();assert.match(f.prefs.snapshot().error,/지원/);f.document.documentElement.requestFullscreen=async()=>{throw Error('denied');};f.document.exitFullscreen=async()=>{};await f.prefs.toggleFullscreen();assert.match(f.prefs.snapshot().error,/denied/);assert.equal(f.prefs.snapshot().fullscreen,false);f.document.documentElement.requestFullscreen=async()=>{f.document.fullscreenElement=f.document.documentElement;};await f.prefs.toggleFullscreen();assert.equal(f.prefs.snapshot().fullscreen,true);f.document.exitFullscreen=async()=>{f.document.fullscreenElement=null;};await f.prefs.toggleFullscreen();assert.equal(f.prefs.snapshot().fullscreen,false);});
test('one fullscreen request is active and destroy removes observer and rejects late publication',async()=>{const f=setup();let resolve,calls=0;f.document.exitFullscreen=async()=>{};f.document.documentElement.requestFullscreen=()=>{calls++;return new Promise(r=>resolve=r);};const first=f.prefs.toggleFullscreen();await f.prefs.toggleFullscreen();assert.equal(calls,1);assert.equal(f.prefs.snapshot().busy,true);const before=f.changes;f.prefs.destroy();resolve();await first;assert.equal(f.changes,before);assert.equal(f.events.size,0);f.prefs.setTheme('light');assert.equal(f.records.size,0);});
for(const [width,height] of [[1280,720],[1920,1080]])test(`existing environment panel explicitly changes only shell preference ${width}x${height}`,async()=>{
 const records=new Map(),f=fixture(width,height,{hash:'#settings',storage:{getItem:key=>records.get(key)??null,setItem:(key,value)=>records.set(key,value)}});
 try{const before=f.counts();f.doc.documentElement={dataset:{},style:{},requestFullscreen:async()=>{f.doc.fullscreenElement=f.doc.documentElement;}};f.doc.exitFullscreen=async()=>{f.doc.fullscreenElement=null;};f.get('st-theme').value='light';await f.get('st-theme').dispatch('change');assert.equal(records.get('spacetwin-theme'),'light');assert.equal(f.doc.documentElement.dataset.theme,'light');assert.deepEqual(f.counts(),before);assert.equal(f.viewers.length,1);await f.get('st-fullscreen').dispatch('click');await Promise.resolve();assert.equal(f.get('st-fullscreen').textContent,'전체화면 종료');await f.get('st-fullscreen').dispatch('click');assert.equal(f.doc.fullscreenElement,null);f.evaluate("location.hash='#integration'");await f.win.dispatch('hashchange');f.evaluate("location.hash='#settings'");await f.win.dispatch('hashchange');assert.equal(f.get('st-theme').value,'light');await f.win.dispatch('pagehide',{persisted:false});const previous=records.get('spacetwin-theme');f.get('st-theme').value='dark';await f.get('st-theme').dispatch('change');assert.equal(records.get('spacetwin-theme'),previous);
 }finally{f.dispose();}
});
