import test from 'node:test';
import assert from 'node:assert/strict';
import {createSimWorkspace} from '../../../user_application/web/scripts/tabs/sim_workspace.js';
const status=(values={})=>({mode:'SIM',running:false,speed:1,elapsed_seconds:0,sequence:0,run_id:'RUN-A',scenario_id:'A',active_faults:[],...values});
const metrics=()=>Object.fromEntries(['power','temperature','attitude_error','storage','link_quality','delay_ms','loss_percent','throughput_mbps','ber','auth_percent'].map(k=>[k,1]));
const bootstrap=()=>({runtime:status(),scenarios:[{id:'A',name:'Existing'}],events:[],missions:[]});
const frame=(values={})=>({type:'telemetry',runtime:status(values),telemetry:metrics(),events:[],missions:[],wall_time:'2026-10-04T00:00:00Z',data_quality:{mode:'SIM',source:'deterministic-sim'}});
test('SIM control observer holds through bootstrap adoption and final busy cleanup; GET load does not acquire',async()=>{
 let depth=0,entries=0,releases=0,command=false,c;const seen=[];
 const api={bootstrap:async()=>{if(command)assert.equal(depth,1);return bootstrap();},runtimeControl:async()=>{assert.equal(depth,1);command=true;return status();}};
 c=createSimWorkspace(api,()=>()=>{},()=>{if(command)seen.push({depth,busy:c.snapshot().busy});},()=>{}, {setTimer:()=>1,clearTimer(){}},{control:()=>{entries++;depth++;return()=>{releases++;depth--;};}});
 await c.load();assert.equal(entries,0);await c.control('pause');assert.equal(entries,1);assert.equal(releases,1);assert.equal(depth,0);assert.ok(seen.every(s=>s.depth===1));assert.equal(seen.at(-1).busy,false);c.destroy();
});
test('SIM control observer releases after synchronous failure and rejects reentrant disposal before request',async()=>{
 let release=0,calls=0,c;const api={runtimeControl:()=>{calls++;throw Error('offline');}};
 c=createSimWorkspace(api,()=>()=>{},()=>{},()=>{},undefined,{control:()=>()=>release++});await c.control('pause');assert.equal(release,1);assert.match(c.snapshot().error,/offline/);c.destroy();
 c=createSimWorkspace(api,()=>()=>{},()=>{},()=>{},undefined,{control:()=>{c.destroy();return()=>release++;}});await c.control('pause');assert.equal(calls,1);assert.equal(release,2);
});
test('SIM observer rejects acquisition throw, ignores nested busy command and cleanup failure cannot mask adoption',async()=>{
 let calls=0,entries=0,releases=0,c;const api={bootstrap:async()=>bootstrap(),runtimeControl:async()=>{calls++;return status();}};
 c=createSimWorkspace(api,()=>()=>{},()=>{},()=>{},undefined,{control:()=>{throw Error('capture failed');}});await assert.rejects(c.control('pause'),/capture failed/);assert.equal(calls,0);c.destroy();
 c=createSimWorkspace(api,()=>()=>{},()=>{},()=>{}, {setTimer:()=>1,clearTimer(){}},{control:()=>{entries++;void c.control('start');return()=>{releases++;throw Error('cleanup failed');};}});await c.control('pause');assert.equal(calls,1);assert.equal(entries,1);assert.equal(releases,1);assert.equal(c.snapshot().error,'');assert.equal(c.snapshot().busy,false);c.destroy();
});
function setup(extra={}){let message,connection,closed=0,timeout;const calls=[];const api={bootstrap:async()=>bootstrap(),runtimeControl:async action=>{calls.push(action);return status();},runtimeSpeed:async speed=>{calls.push(speed);return status({speed});},selectScenario:async id=>{calls.push(id);return status();},injectFault:async p=>{calls.push(p);return {id:'F',expires_at:60};},...extra};const c=createSimWorkspace(api,(m,s)=>{message=m;connection=s;return()=>closed++;},()=>{},()=>{}, {setTimer:fn=>(timeout=fn,1),clearTimer:()=>{timeout=null;}});return {c,calls,send:x=>message(x),connection:x=>connection(x),expire:()=>timeout(),closed:()=>closed};}
test('strict drafts, existing requests, copies and one socket cleanup',async()=>{const f=setup();f.c.connect();f.c.connect();await f.c.load();f.c.edit({speed:''});await f.c.speed();assert.equal(f.calls.length,0);f.c.edit({speed:'2.5'});await f.c.speed();assert.deepEqual(f.calls,[2.5]);f.c.edit({target:'label',kind:'latency_spike',severity:'high',duration_seconds:'60'});await f.c.fault();assert.deepEqual(f.calls[1],{target:'label',kind:'latency_spike',severity:'high',duration_seconds:60});const s=f.c.snapshot();s.draft.target='external';assert.equal(f.c.snapshot().draft.target,'label');f.c.destroy();f.c.destroy();assert.equal(f.closed(),1);});
test('serialized command and matching stream barrier, ordered frames, stale/error',async()=>{let resolve;const f=setup({runtimeControl:()=>new Promise(r=>resolve=r),bootstrap:async()=>({...bootstrap(),runtime:status({speed:2,sequence:4})})});f.c.connect();await f.c.load();const pending=f.c.control('pause');await f.c.control('start');f.send(frame({speed:9,sequence:20}));assert.equal(f.c.snapshot().runtime.speed,2);resolve(status({speed:2,sequence:4}));await pending;f.send(frame({speed:1,sequence:3}));assert.equal(f.c.snapshot().metrics,null);f.send(frame({speed:2,sequence:5}));assert.equal(f.c.snapshot().runtime.sequence,5);f.send(frame({speed:2,sequence:4}));assert.equal(f.c.snapshot().runtime.sequence,5);f.expire();assert.equal(f.c.snapshot().stale,true);f.connection('closed');assert.equal(f.c.snapshot().connection,'closed');f.send({...frame(),telemetry:{power:NaN}});assert.match(f.c.snapshot().error,/응답/);f.c.destroy();});
test('fault barrier rejects pre-injection snapshot and accepts simulation-time expiry',async()=>{const f=setup();f.c.connect();await f.c.load();f.c.edit({target:'label'});await f.c.fault();f.send(frame());assert.equal(f.c.snapshot().metrics,null);f.send(frame({elapsed_seconds:60}));assert.ok(f.c.snapshot().metrics);f.c.destroy();});
test('manual reload after an external reset clears old-run metrics',async()=>{let fresh=false;const f=setup({bootstrap:async()=>({...bootstrap(),runtime:status({run_id:fresh?'RUN-B':'RUN-A'})})});f.c.connect();await f.c.load();f.send(frame());fresh=true;await f.c.load();assert.equal(f.c.snapshot().runtime.run_id,'RUN-B');assert.equal(f.c.snapshot().metrics,null);assert.equal(f.c.snapshot().stale,true);f.c.destroy();});
test('transport failure persists through telemetry and commands never retry',async()=>{let count=0;const f=setup({runtimeControl:async()=>{count++;throw Error('offline');}});f.c.connect();await f.c.load();await f.c.control('pause');assert.equal(count,1);assert.match(f.c.snapshot().error,/새로고침/);f.send(frame());assert.match(f.c.snapshot().error,/offline/);assert.equal(f.c.snapshot().status,'요청 실패');f.c.destroy();});
