import test from 'node:test';
import assert from 'node:assert/strict';
import {createSourceSecurityPanel} from '../../../user_application/web/scripts/tabs/source_security.js';
const report=run=>({module:{reachable:true,placement:'embedded',implementation:'sim-rule-stand-in'},overview:{observation:{run_id:run,observed_at:'2026-10-07T00:00:00Z',auth_percent:99.5},verdict:{authentication:'nominal'}},events:{events:[]},runtime:{run_id:run}});
function fixture(){const timers=new Map(),listeners=new Map(),fields=new Map(),calls=[];let serial=0,time=1000,nowHook=null;
 const el=()=>({dataset:{},listeners:new Map(),addEventListener(k,f){this.listeners.set(k,f);},removeEventListener(k){this.listeners.delete(k);},querySelector(id){if(!fields.has(id))fields.set(id,el());return fields.get(id);},remove(){}});
 const document={hidden:false,createElement:el,getElementById:()=>({prepend(){}}),addEventListener(k,f){listeners.set(k,f);},removeEventListener(k){listeners.delete(k);}};
 const ui=createSourceSecurityPanel({document,host:{location:{protocol:'http:'}},now:()=>{nowHook?.();return time;},setTimer(fn,ms){const id=++serial;timers.set(id,{fn,ms});return id;},clearTimer:id=>timers.delete(id),api:{securityDashboard({signal}){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});calls.push({signal,resolve,reject});return promise;}}});
 const fire=ms=>{const entry=[...timers].find(([,v])=>v.ms===ms);assert.ok(entry,`timer ${ms}`);timers.delete(entry[0]);entry[1].fn();};
 return {ui,calls,timers,listeners,document,fields,fire,setNowHook:v=>nowHook=v,setTime:v=>time=v};}
const settle=async()=>{for(let i=0;i<5;i++)await Promise.resolve();};
test('active visible source security polls immediately then 2 s after completion, with one lane and 8 s timeout',async()=>{const f=fixture();f.ui.show('security');assert.equal(f.calls.length,1);assert.ok([...f.timers.values()].some(t=>t.ms===8000));assert.equal([...f.timers.values()].some(t=>t.ms===2000),false);await f.ui.query();assert.equal(f.calls.length,1);f.calls[0].resolve(report('R1'));await settle();f.fire(2000);assert.equal(f.calls.length,2);f.fire(8000);assert.equal(f.calls[1].signal.aborted,true);f.calls[1].reject(Object.assign(Error('abort'),{name:'AbortError'}));await settle();assert.match(f.fields.get('#ss-evidence').textContent,/시간 초과/);assert.ok([...f.timers.values()].some(t=>t.ms===2000));f.ui.destroy();assert.equal(f.timers.size,0);});
test('visibility hide and run change revoke old responses and restart on actual source owner events',async()=>{const f=fixture();f.ui.updateTelemetry({runtime:{run_id:'R1'}});f.ui.show('security');f.document.hidden=true;f.listeners.get('visibilitychange')();assert.equal(f.calls[0].signal.aborted,true);assert.equal(f.timers.size,0);f.calls[0].resolve(report('R1'));await settle();assert.equal(f.fields.get('#ss-run').textContent,'—');f.document.hidden=false;f.listeners.get('visibilitychange')();assert.equal(f.calls.length,2);f.ui.updateTelemetry({runtime:{run_id:'R2'}});assert.equal(f.calls[1].signal.aborted,true);assert.equal(f.calls.length,3);f.calls[1].resolve(report('R1'));f.calls[2].resolve(report('R2'));await settle();assert.equal(f.fields.get('#ss-run').textContent,'R2');f.ui.destroy();assert.equal(f.listeners.size,0);});
test('1 s freshness repaint sends no analytical request and hidden/disposed callbacks cannot restart',async()=>{const f=fixture();f.ui.show('security');f.calls[0].resolve(report('R1'));await settle();f.setTime(15000);f.fire(1000);assert.equal(f.calls.length,1);assert.match(f.fields.get('#ss-evidence').textContent,/마지막 수신값/);const callbacks=[...f.timers.values()].map(t=>t.fn);f.ui.show('ground');for(const fn of callbacks)fn();assert.equal(f.calls.length,1);assert.equal(f.timers.size,0);f.ui.destroy();for(const fn of callbacks)fn();assert.equal(f.calls.length,1);});
test('timeout cannot accept ignored-abort late success and keeps source evidence unknown',async()=>{const f=fixture();f.ui.show('security');f.fire(8000);f.calls[0].resolve(report('R1'));await settle();assert.equal(f.fields.get('#ss-run').textContent,'—');assert.match(f.fields.get('#ss-evidence').textContent,/시간 초과/);f.ui.destroy();});
test('source activation reentry cannot publish late report or reschedule hidden observation',async()=>{const f=fixture();f.ui.show('security');f.ui.show('ground');f.calls[0].resolve(report('R1'));await settle();assert.equal(f.timers.size,0);assert.equal(f.fields.get('#ss-run').textContent,'—');f.ui.show('security');assert.equal(f.calls.length,2);f.ui.destroy();f.calls[1].resolve(report('R1'));await settle();assert.equal(f.timers.size,0);});

for(const action of ['leave','destroy'])test(`render callback ${action} cannot send a hidden request or allocate a timeout`,async()=>{const f=fixture();f.ui.show('security');f.calls[0].resolve(report('R1'));await settle();let armed=true;f.setNowHook(()=>{if(armed){armed=false;if(action==='leave')f.ui.show('ground');else f.ui.destroy();}});void f.ui.query();await settle();assert.equal(f.calls.length,1);assert.equal(f.timers.size,0);f.ui.destroy();});
test('completion render callback cannot resurrect polling after destruction',async()=>{const f=fixture();f.ui.show('security');let reads=0;f.setNowHook(()=>{if(++reads===2)f.ui.destroy();});f.calls[0].resolve(report('R1'));await settle();assert.equal(f.calls.length,1);assert.equal(f.timers.size,0);});