import test from 'node:test';
import assert from 'node:assert/strict';
import {createSourceDataPanel} from '../../../user_application/web/scripts/tabs/source_data.js';
import * as model from '../../../user_application/web/scripts/data_management/view_model.js';
function fixture(drawSparkline=null,onContextChange=()=>{},host={}){
 const elements=new Map(),calls=[];const deployment={run_id:'RUN-TEST',scope_id:'scope-1',revision:1,nodes:[{id:'A'}]};
 const report={runtime:{run_id:'RUN-TEST'},deployment,module:{reachable:true,scope_id:'scope-1',scope_contract:'isolated-v1'},overview:{scope_id:'scope-1',scope_contract:'isolated-v1',metrics:{objects:1},policy:{replication:{imagery:3}},jobs:[{id:'JOB-1',kind:'verify',status:'running',started_s:0,eta_s:3}],requests:[{id:'REQ-1',status:'served',served_from:'A',destination:'B',latency_ms:460,object_id:'DM-1'}]},nodes:[{id:'A',name:'Storage A',kind:'onboard',capacity_gb:2000,available:true}],objects:{scope_id:'scope-1',scope_contract:'isolated-v1',total:1,items:[{id:'DM-1',class:'imagery',source:'A',label:'Original product',ref:'A:imagery:1',size_mb:1,version:1,checksum:'0123456789abcdef',tier:'hot',retention_days:365,last_verified_s:15,requests:1,created_s:0,status:'healthy',replicas:[{node:'A',state:'verified',placed_s:0,verified_s:15,lag_s:2.5,ready_s:null}]}]},events:{scope_id:'scope-1',scope_contract:'isolated-v1',items:[]}};
 class Element{constructor(){this.listeners=new Map();this.value='';this.hidden=false;this.html='';}set innerHTML(html){this.html=html;for(const m of html.matchAll(/\bid="([^"]+)"/g))elements.set(m[1],new Element());}get innerHTML(){return this.html;}prepend(child){elements.set(child.id,child);}querySelector(q){return elements.get(q.slice(1));}addEventListener(e,f){this.listeners.set(e,f);}removeEventListener(e){this.listeners.delete(e);}remove(){elements.delete(this.id);}async dispatch(e){return this.listeners.get(e)?.({target:this,preventDefault(){}});}}
 elements.set('screen',new Element());const document={createElement:()=>new Element(),getElementById:id=>elements.get(id)};
 const api={dataDeploymentState:async()=>structuredClone(deployment),dataManagementDashboard:async()=>structuredClone(report),dataManagementAction:async body=>{calls.push(body);return{...body,scope_contract:'isolated-v1',status:'done'};},dataManagementRequest:async body=>{calls.push(body);return{...body,scope_contract:'isolated-v1',status:'served'};}};
 report.overview.sim_elapsed_s=120;report.overview.metrics.ingest_mbps=4;report.overview.metrics.mean_sync_lag_s=2.5;report.overview.metrics.mean_latency_ms=460;
 const panel=createSourceDataPanel({api,model,document,host,drawSparkline,onContextChange});panel.show('data');return{panel,calls,api,report,deployment,get:id=>elements.get('dm-'+id)};
}

test('readonly shared context observes pending/error and preserves original full snapshot, observer cannot corrupt action',async()=>{
 let notifications=0;const f=fixture(null,()=>{notifications++;throw Error('observer failure');});
 let resolve;f.api.dataManagementDashboard=()=>new Promise(r=>resolve=r);
 const wait=f.get('refresh').dispatch('click');await Promise.resolve();await Promise.resolve();assert.equal(f.panel.contextSnapshot().busy,true);assert.equal(f.panel.contextSnapshot().report,null);
 resolve({});await wait;assert.equal(f.panel.contextSnapshot().busy,false);assert.ok(f.panel.contextSnapshot().error);assert.equal(notifications,2);
 const normal=fixture();await normal.get('refresh').dispatch('click');normal.get('object').value='DM-1';await normal.get('object').dispatch('change');
 const context=normal.panel.contextSnapshot();assert.equal(context.selected_id,'DM-1');assert.equal(context.report.objects,undefined);assert.equal(normal.panel.snapshot().objects.items.length,1);context.report.deployment.scope_id='corrupt';assert.equal(normal.panel.contextSnapshot().report.deployment.scope_id,'scope-1');f.panel.destroy();normal.panel.destroy();
});
test('original object checksum/tier are separate from actual replica state and lag; lifecycle job/request reports remain visible',async()=>{
 const f=fixture();await f.get('refresh').dispatch('click');f.get('object').value='DM-1';await f.get('object').dispatch('change');
 assert.match(f.get('detail').innerHTML,/0123456789abcdef/);assert.match(f.get('detail').innerHTML,/2\.5/);assert.match(f.get('detail').innerHTML,/Storage A/);assert.match(f.get('detail').innerHTML,/365/);
 assert.match(f.get('objects').innerHTML,/A/);assert.match(f.get('jobs').innerHTML,/JOB-1/);assert.match(f.get('requests').innerHTML,/REQ-1/);f.panel.destroy();
});
test('replication policy uses selected object class when filter is all, and rejects classless policy before sending',async()=>{
 const f=fixture();await f.get('refresh').dispatch('click');f.get('object').value='DM-1';await f.get('object').dispatch('change');f.get('action').value='set_replication';f.get('replication').value='2';await f.get('action-submit').dispatch('click');
 assert.equal(f.calls[0].class,'imagery');assert.equal(f.calls[0].replication,2);
 f.get('object').value='';await f.get('object').dispatch('change');await f.get('action-submit').dispatch('click');assert.equal(f.calls.length,1);assert.match(f.get('status').textContent,/종류/);f.panel.destroy();
});
test('service uses an available current storage destination and does not publish a foreign scope receipt',async()=>{
 const f=fixture();await f.get('refresh').dispatch('click');f.get('object').value='DM-1';await f.get('object').dispatch('change');f.get('destination').value='undeployed';await f.get('request-submit').dispatch('click');assert.equal(f.calls.length,0);assert.match(f.get('status').textContent,/가용 저장소/);
 await f.get('refresh').dispatch('click');f.get('destination').value='A';f.api.dataManagementRequest=async()=>({scope_id:'foreign',scope_contract:'isolated-v1',status:'served',secret:'must not display'});await f.get('request-submit').dispatch('click');assert.match(f.get('status').textContent,/범위/);assert.equal(f.get('result').textContent,'');f.panel.destroy();
});
test('original local storage-kind and event-severity filters operate without new data writes',async()=>{
 const f=fixture();await f.get('refresh').dispatch('click');f.get('node-kind').value='core';await f.get('node-kind').dispatch('change');assert.doesNotMatch(f.get('nodes').innerHTML,/Storage A/);f.get('node-kind').value='onboard';await f.get('node-kind').dispatch('change');assert.match(f.get('nodes').innerHTML,/Storage A/);f.get('event-severity').value='danger';await f.get('event-severity').dispatch('change');assert.equal(f.calls.length,0);f.panel.destroy();
});
test('original trend renderer receives verified module metrics and repeated SIM time does not duplicate a sample',async()=>{
 const plots=[],f=fixture((canvas,values)=>plots.push({canvas,values}));await f.get('refresh').dispatch('click');await f.get('refresh').dispatch('click');assert.deepEqual(plots.slice(-3).map(p=>p.values),[[4],[2.5],[460]]);assert.match(f.get('trends').textContent,/120/);f.panel.destroy();
});

for(const action of ['verify','heal','rebalance','purge_expired'])test('empty accepted storage catalogue disables and handler rejects '+action+' while policy remains configurable',async()=>{const f=fixture();f.report.overview.metrics.objects=0;f.report.objects.total=0;f.report.objects.items=[];await f.get('refresh').dispatch('click');f.get('action').value=action;await f.get('action').dispatch('change');assert.equal(f.get('action-submit').disabled,true);assert.equal(f.get('request-submit').disabled,true);await f.get('action-submit').dispatch('click');assert.equal(f.calls.length,0);await f.get('refresh').dispatch('click');f.get('action').value='set_replication';f.get('class').value='imagery';f.get('replication').value='2';await f.get('action').dispatch('change');assert.equal(f.get('action-submit').disabled,false);await f.get('action-submit').dispatch('click');assert.equal(f.calls.length,1);assert.equal(f.calls[0].action,'set_replication');f.panel.destroy();});
test('empty accepted catalogue permits explicit filter policy but no object service request',async()=>{const f=fixture();f.report.overview.metrics.objects=0;f.report.objects.items=[];await f.get('refresh').dispatch('click');f.get('action').value='set_filter';f.get('filter').value='{"imagery":true}';await f.get('action').dispatch('change');assert.equal(f.get('action-submit').disabled,false);await f.get('action-submit').dispatch('click');assert.equal(f.calls[0].action,'set_filter');f.get('class').value='imagery';f.get('destination').value='A';await f.get('request-submit').dispatch('click');assert.equal(f.calls.length,1);f.panel.destroy();});
test('failed current query cannot authorize dispatch by clearing error, and stale deployment sends no command',async()=>{const f=fixture();await f.get('refresh').dispatch('click');f.get('action').value='verify';f.api.dataManagementDashboard=async()=>{throw Error('module unavailable');};await f.get('refresh').dispatch('click');assert.equal(f.get('action-submit').disabled,true);await f.get('action-submit').dispatch('click');assert.equal(f.calls.length,0);assert.equal(f.panel.contextSnapshot().error,'module unavailable');f.panel.destroy();const stale=fixture();await stale.get('refresh').dispatch('click');stale.get('action').value='verify';stale.deployment.revision++;await stale.get('action-submit').dispatch('click');assert.equal(stale.calls.length,0);assert.match(stale.panel.contextSnapshot().error,/배치/);stale.panel.destroy();});

const flush=()=>new Promise(resolve=>setImmediate(resolve));
test('technical report disclosures retain user choices while fresh query updates their content',async()=>{
 const f=fixture();
 const module=f.get('module-details'),policy=f.get('policy-details');
 assert.ok(module);assert.ok(policy);
 module.open=true;policy.open=false;
 await f.get('refresh').dispatch('click');
 assert.equal(f.get('module-details'),module);
 assert.equal(f.get('policy-details'),policy);
 assert.equal(module.open,true);assert.equal(policy.open,false);
 assert.match(f.get('module').innerHTML,/scope-1/);
 assert.match(f.get('policy').textContent,/imagery/);
 policy.open=true;module.open=false;
 f.report.overview.policy.replication.imagery=2;
 await f.get('refresh').dispatch('click');
 assert.equal(module.open,false);assert.equal(policy.open,true);
 assert.equal(JSON.parse(f.get('policy').textContent).replication.imagery,2);
 assert.equal(f.calls.length,0);
 f.panel.destroy();
});
function timerHost(){let id=0;const timers=new Map(),cleared=[];return{timers,cleared,setInterval(fn,ms){const key=++id;timers.set(key,{fn,ms});return key;},clearInterval(key){cleared.push(key);timers.delete(key);}};}
test('active data view polls original 3s readonly lifecycle and preserves selected object plus dirty policy/service filters',async()=>{const host=timerHost(),f=fixture(null,()=>{},host);assert.equal(host.timers.size,1);assert.equal([...host.timers.values()][0].ms,3000);await flush();assert.equal(f.panel.snapshot().objects.items.length,1);f.get('object').value='DM-1';await f.get('object').dispatch('change');for(const [id,value]of Object.entries({class:'imagery',search:'draft search',node:'draft node',action:'set_filter',replication:'5',filter:'{"custom":true}',destination:'A','node-kind':'onboard','event-severity':'warning'}))f.get(id).value=value;f.report.overview.jobs[0].progress=.42;let reads=0;f.api.dataManagementDashboard=async()=>{reads++;return structuredClone(f.report);};await [...host.timers.values()][0].fn();assert.equal(reads,1);assert.equal(f.calls.length,0);assert.equal(f.panel.contextSnapshot().selected_id,'DM-1');for(const [id,value]of Object.entries({class:'imagery',search:'draft search',node:'draft node',action:'set_filter',replication:'5',filter:'{"custom":true}',destination:'A','node-kind':'onboard','event-severity':'warning'}))assert.equal(f.get(id).value,value,id);assert.match(f.get('jobs').innerHTML,/42%/);assert.match(f.get('jobs').innerHTML,/<progress[^>]*value="0.42"/);f.panel.destroy();assert.equal(host.timers.size,0);});
test('poll never overlaps a pending query or command and stale hidden/disposed responses cannot publish',async()=>{const host=timerHost(),f=fixture(null,()=>{},host);await flush();const timer=[...host.timers.values()][0].fn;let reads=0,finish;f.api.dataManagementDashboard=()=>{reads++;return new Promise(resolve=>finish=resolve);};const pending=timer();await flush();await timer();assert.equal(reads,1);assert.equal(f.panel.contextSnapshot().busy,true);const before=f.panel.snapshot();f.panel.show('ground');assert.equal(host.timers.size,0);f.report.objects.items[0].label='late hidden';finish(structuredClone(f.report));await pending;assert.deepEqual(f.panel.snapshot(),before);await timer();assert.equal(reads,1);f.panel.destroy();const otherHost=timerHost(),other=fixture(null,()=>{},otherHost);await flush();let completed;other.api.dataManagementDashboard=()=>new Promise(resolve=>completed=resolve);const late=[...otherHost.timers.values()][0].fn();await flush();const old=other.panel.snapshot();other.panel.destroy();completed({...structuredClone(other.report),objects:{...other.report.objects,items:[]}});await late;assert.deepEqual(other.panel.snapshot(),old);assert.equal(otherHost.timers.size,0);});
test('command owns busy lease against poll and job progress unknown/out of range stays unknown',async()=>{const host=timerHost(),f=fixture(null,()=>{},host);await flush();let resolve,reads=0;f.api.dataManagementDashboard=async()=>{reads++;return structuredClone(f.report);};f.api.dataManagementAction=body=>{f.calls.push(body);return new Promise(r=>resolve=()=>r({...body,scope_contract:'isolated-v1'}));};f.get('action').value='verify';const command=f.get('action-submit').dispatch('click');await flush();await [...host.timers.values()][0].fn();assert.equal(reads,0);assert.equal(f.calls.length,1);resolve();await command;assert.equal(reads,1);for(const progress of [undefined,null,NaN,-.1,1.1]){f.report.overview.jobs[0].progress=progress;await [...host.timers.values()][0].fn();assert.match(f.get('jobs').innerHTML,/미확인/);assert.doesNotMatch(f.get('jobs').innerHTML,/<progress/);}f.panel.destroy();});

test('failed poll retains exact query error until successful fresh query, never clears it via policy dispatch',async()=>{const host=timerHost(),f=fixture(null,()=>{},host);await flush();const timer=[...host.timers.values()][0].fn;f.api.dataManagementDashboard=async()=>{throw Error('source module failed');};await timer();f.get('action').value='set_filter';f.get('filter').value='{}';await f.get('action').dispatch('change');assert.equal(f.get('action-submit').disabled,true);await f.get('action-submit').dispatch('click');assert.equal(f.calls.length,0);assert.equal(f.panel.contextSnapshot().error,'source module failed');f.api.dataManagementDashboard=async()=>structuredClone(f.report);await timer();assert.equal(f.panel.contextSnapshot().error,'');assert.equal(f.get('action-submit').disabled,false);f.panel.destroy();});

for(const kind of ['replication','filter','service'])test('pending '+kind+' command captures form intent before deployment await while edits remain for next command',async()=>{const f=fixture();await f.get('refresh').dispatch('click');let resolve,reads=0;f.api.dataDeploymentState=()=>++reads===1?new Promise(r=>resolve=r):Promise.resolve(structuredClone(f.deployment));f.get('class').value='imagery';f.get('replication').value='2';f.get('filter').value='{"imagery":true}';f.get('destination').value='A';f.get('action').value=kind==='replication'?'set_replication':'set_filter';const pending=f.get(kind==='service'?'request-submit':'action-submit').dispatch('click');await Promise.resolve();f.get('class').value='telemetry';f.get('replication').value='5';f.get('filter').value='{"telemetry":false}';f.get('destination').value='changed-destination';f.get('action').value='verify';f.get('object').value='DM-1';await f.get('object').dispatch('change');resolve(structuredClone(f.deployment));await pending;assert.equal(f.calls.length,1);assert.equal(f.calls[0].class,'imagery');assert.equal(f.calls[0].object_id,undefined);if(kind==='replication'){assert.equal(f.calls[0].action,'set_replication');assert.equal(f.calls[0].replication,2);}if(kind==='filter'){assert.equal(f.calls[0].action,'set_filter');assert.deepEqual(f.calls[0].filter,{imagery:true});}if(kind==='service')assert.equal(f.calls[0].destination,'A');assert.equal(f.get('class').value,'telemetry');assert.equal(f.get('replication').value,'5');assert.equal(f.get('filter').value,'{"telemetry":false}');assert.equal(f.panel.contextSnapshot().selected_id,'DM-1');f.panel.destroy();});
test('selected object operation retains original selected object through deployment await',async()=>{const f=fixture();await f.get('refresh').dispatch('click');f.get('object').value='DM-1';await f.get('object').dispatch('change');f.get('action').value='verify';let resolve,reads=0;f.api.dataDeploymentState=()=>++reads===1?new Promise(r=>resolve=r):Promise.resolve(structuredClone(f.deployment));const pending=f.get('action-submit').dispatch('click');await Promise.resolve();f.get('object').value='';await f.get('object').dispatch('change');f.get('class').value='telemetry';resolve(structuredClone(f.deployment));await pending;assert.equal(f.calls.length,1);assert.equal(f.calls[0].object_id,'DM-1');assert.equal(f.calls[0].class,undefined);assert.equal(f.panel.contextSnapshot().selected_id,null);f.panel.destroy();});
