import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createSourceScenarioPanel} from '../../../user_application/web/scripts/tabs/source_scenarios.js';
function fixture({onResume,onReviewFinished,onFollow,onRelease}={}){const fields=new Map(),calls=[],downloads=[],timers=[],created=[];const element=()=>({checked:false,disabled:false,hidden:false,textContent:'',innerHTML:'',prepend(){},listeners:new Map(),addEventListener(k,fn){this.listeners.set(k,fn);},removeEventListener(k){this.listeners.delete(k);},setAttribute(k,v){this[k]=v;},querySelector(id){if(!fields.has(id))fields.set(id,element());return fields.get(id);},remove(){calls.push('remove');},click(){downloads.push({href:this.href,name:this.download});}});const root=element(),document={createElement:()=>{const e=element();created.push(e);return e;},getElementById:()=>root,body:{append:a=>calls.push(a)}};let current='one',auto=true;const record={scenario_id:'poc/<x>',run_id:'RUN:1',phases:{nominal:{utc:'2026-10-07T00:00:00Z'}},events:{fault_at_s:0},log:[{summary:'<unsafe>'}]};const runner={definition:{id:'poc'},view:()=>({phase:'finished',now:0,elapsed:5,speed:1,steps:[{id:'one',title:'first',tab:'communication',tabs:['communication','mission'],flows:[{from:'orb',to:'fabric',icd:'ICD-02',message:'<unsafe>'}],narrativeText:'narrative',checkResults:[]},{id:'two',title:'second',tab:'security',checkResults:[]}],currentStep:current,phases:{},log:[],scenario:{name:'poc'},autoFollow:auto,verdict:{ok:true},events:{fault_at_s:0,fault_link:'A<&B',detour_available_at_s:20,reroute_at_s:25,fault_end_s:40,primary_restored_at_s:50}}),subscribe:()=>()=>{},setAutoFollow:v=>{auto=v;calls.push(['autofollow',v]);},record:()=>record};const blobs=[],revoked=[];const host={Blob,URL:{createObjectURL:blob=>{blobs.push(blob);return 'blob:record';},revokeObjectURL:url=>revoked.push(url)},setTimeout:fn=>timers.push(fn)};const ui=createSourceScenarioPanel({runner,comparisonRows:()=>[],document,host,onResume,onReviewFinished,onFollow,onRelease,onOpenTab:tab=>calls.push(['tab',tab]),moduleName:id=>({orb:'궤도',fabric:'패브릭'}[id]??id)});ui.show('run');return {ui,runner,fields,calls,record,downloads,blobs,timers,revoked,created,get:id=>fields.get('#sc-'+id),step:value=>current=value};}
test('source result download preserves exact runner.record JSON and original sanitized filename',async()=>{const f=fixture();await f.get('download').listeners.get('click')();assert.equal(await f.blobs[0].text(),JSON.stringify(f.record,null,2));assert.equal(f.blobs[0].type,'application/json');assert.deepEqual(f.downloads,[{href:'blob:record',name:'poc/<x>-RUN1.json'}]);assert.equal(f.revoked.length,0);f.timers[0]();assert.deepEqual(f.revoked,['blob:record']);f.ui.destroy();});
test('source stage autoFollow toggle stays distinct from analysis-clock follow',async()=>{const f=fixture();await f.get('auto-follow').listeners.get('click')();assert.deepEqual(f.calls,[['autofollow',false]]);assert.equal(f.get('auto-follow')['aria-pressed'],'false');assert.equal(f.get('follow').disabled,true);f.ui.destroy();});
test('original flows/events and manual tab guide render safe values and delegate existing navigation',async()=>{const f=fixture();assert.match(f.get('guide').innerHTML,/궤도/);assert.match(f.get('guide').innerHTML,/ICD-02/);assert.match(f.get('guide').innerHTML,/&lt;unsafe&gt;/);assert.doesNotMatch(f.get('guide').innerHTML,/<unsafe>/);assert.match(f.get('events').innerHTML,/T\+0/);assert.match(f.get('events').innerHTML,/20 s/);assert.match(f.get('events').innerHTML,/A&lt;&amp;B/);await f.get('steps').listeners.get('click')({target:{closest:()=>({dataset:{gotoTab:'mission'}})}});assert.deepEqual(f.calls,[['tab','mission']]);await f.get('guide').listeners.get('click')({target:{closest:()=>({dataset:{guideClose:''}})}});assert.equal(f.get('guide').hidden,true);f.step('two');f.ui.update();assert.equal(f.get('guide').hidden,false);assert.match(f.get('guide').innerHTML,/second/);f.ui.destroy();});
test('compact source dock persists across nonhome tabs and delegates transport to the same runner',async()=>{const f=fixture(),view=f.runner.view;let phase='paused';f.runner.view=()=>({...view(),phase});f.runner.play=()=>{f.calls.push(['play']);phase='playing';};f.runner.pause=()=>{f.calls.push(['pause']);phase='paused';};f.ui.show('ground');const dock=f.created.find(e=>e.id==='source-scenario-dock'),get=id=>f.fields.get('#sc-dock-'+id);assert.ok(dock);assert.equal(dock.hidden,false);assert.match(get('title').textContent,/first/);assert.equal(get('play').disabled,false);await get('play').listeners.get('click')();assert.deepEqual(f.calls,[['play']]);f.ui.show('mission');assert.equal(f.created.filter(e=>e.id==='source-scenario-dock').length,1);assert.equal(get('pause').disabled,false);await get('pause').listeners.get('click')();await get('return').listeners.get('click')();assert.deepEqual(f.calls,[['play'],['pause'],['tab','run']]);await get('body').listeners.get('click')({target:{closest:()=>({dataset:{guideClose:''}})}});assert.equal(get('guide').hidden,true);f.step('two');f.ui.update();assert.equal(get('guide').hidden,false);f.ui.show('compare');assert.equal(dock.hidden,true);f.ui.destroy();assert.equal(get('play').listeners.size,0);});


test('original dock next/speed/result and collapse reuse the runner and preserve local presentation',async()=>{const f=fixture(),view=f.runner.view;let speed=1;f.runner.view=()=>({...view(),phase:'paused',speed,scenario:{name:'poc',playback:{speeds:[1,5,30]}}});f.runner.skipToNextStep=()=>{f.calls.push(['next']);f.step('two');};f.runner.setSpeed=n=>{f.calls.push(['speed',n]);speed=n;};f.ui.show('ground');const get=id=>f.fields.get('#sc-dock-'+id);assert.ok(get('next')?.listeners.has('click'),'source next shortcut missing');await get('next').listeners.get('click')();assert.match(get('title').textContent,/second/);assert.match(get('speed').innerHTML,/30/);get('speed').value='5';await get('speed').listeners.get('change')();assert.equal(speed,5);await get('result').listeners.get('click')();assert.deepEqual(f.calls,[['next'],['speed',5],['tab','compare']]);await get('collapse').listeners.get('click')();assert.equal(get('controls').hidden,true);assert.equal(get('guide').hidden,true);assert.equal(get('collapse')['aria-expanded'],'false');f.ui.show('security');assert.equal(get('controls').hidden,true);await get('collapse').listeners.get('click')();assert.equal(get('controls').hidden,false);assert.equal(get('guide').hidden,false);assert.equal(get('speed').value,'5');f.ui.destroy();assert.equal(get('next').listeners.size,0);assert.equal(get('speed').listeners.size,0);});

test('result shortcut exposes the comparison after existing navigation completes',async()=>{
 const f=fixture();let scrolled=0;f.get('compare').scrollIntoView=options=>{assert.deepEqual(options,{block:'start'});scrolled++;};
 f.ui.show('mission');await f.fields.get('#sc-dock-result').listeners.get('click')();
 assert.deepEqual(f.calls,[['tab','compare']]);assert.equal(scrolled,1,'result table remains below the viewport');f.ui.destroy();
});

test('scenario hidden panels and collapsed controls override flex presentation',()=>{
 const css=readFileSync(new URL('../../../user_application/web/styles/workspace.css',import.meta.url),'utf8');
 for(const selector of ['#source-scenario-services[hidden]','#source-scenario-services [hidden]','#source-scenario-dock[hidden]','#source-scenario-dock [hidden]'])assert.ok(css.includes(selector));
 assert.match(css,/#source-scenario-dock \[hidden\]\s*\{\s*display:\s*none\s*!important/);
});

test('finished console offers input revalidation and keeps replay transport disabled',async()=>{let validations=0;const f=fixture({onResume:async()=>{validations++;return {validation_kind:'finished_workspace_inputs',playback_authorized:false,utc:'2026-10-07T00:14:44.681000000Z'};}});assert.equal(f.get('resume').textContent,'완료된 실행 입력 재검증');for(const id of ['play','pause','advance','next','speed','speed-apply'])assert.equal(f.get(id).disabled,true,id+' must stay disabled for finished history');await f.get('resume').listeners.get('click')();assert.equal(validations,1);assert.match(f.get('state').textContent,/입력 검증 완료/);assert.match(f.get('state').textContent,/재생 권한을 부여하지/);assert.deepEqual(f.calls,[]);assert.equal(f.get('download').disabled,false);f.ui.destroy();});

test('finished console separates historical equality validation from explicitly reviewed current native inputs',async()=>{let reviews=0;const f=fixture({onReviewFinished:async()=>{reviews++;return {validation_kind:'finished_current_inputs_review',playback_authorized:false,utc:'2026-10-07T00:14:44.681000000Z',changed_fields:['faults','missions']};}});assert.equal(f.get('review-finished').textContent,'완료 실행의 현재 입력 새 검토');assert.equal(f.get('review-finished').disabled,false);await f.get('review-finished').listeners.get('click')();assert.equal(reviews,1);assert.match(f.get('state').textContent,/현재 입력 새 검토 완료/);assert.match(f.get('state').textContent,/이전 완료 결과/);assert.match(f.get('state').textContent,/새 계획/);for(const id of ['play','advance','next','speed-apply'])assert.equal(f.get(id).disabled,true);assert.deepEqual(f.calls,[]);f.ui.destroy();});

test('finished history disables analysis follow while ready/paused follow and existing release remain available',()=>{const f=fixture({onFollow:()=>{},onRelease:()=>{}}),view=f.runner.view;assert.equal(f.get('follow').disabled,true);assert.match(f.get('follow').title,/완료.*조회/);assert.equal(f.get('release').disabled,false);for(const phase of ['ready','paused']){f.runner.view=()=>({...view(),phase});f.ui.update();assert.equal(f.get('follow').disabled,false,phase);assert.equal(f.get('release').disabled,false,phase);}f.ui.destroy();});
