import test from 'node:test';
import assert from 'node:assert/strict';
import {createSourceSecurityPanel} from '../../../user_application/web/scripts/tabs/source_security.js';
function fixture(api){const fields=new Map();let root;const element=()=>({hidden:false,textContent:'',innerHTML:'',dataset:{},listeners:new Map(),addEventListener(k,fn){this.listeners.set(k,fn);},removeEventListener(k){this.listeners.delete(k);},querySelector(id){if(!fields.has(id))fields.set(id,element());return fields.get(id);},remove(){this.removed=true;}});const doc={hidden:false,createElement(){return root=element();},getElementById(){return {prepend(){}};}};const timers=new Map();const ui=createSourceSecurityPanel({api,document:doc,host:{location:{protocol:'http:'}},now:()=>1000,setTimer:fn=>{timers.set(1,fn);return 1;},clearTimer:id=>timers.delete(id)});return {ui,fields,get:id=>fields.get('#ss-'+id),root:()=>root,timers};}
const report={module:{reachable:true,placement:'embedded',implementation:'sim-rule-stand-in',contract_version:'1.0'},overview:{threshold:99,verdict:{authentication:'nominal'},observation:{run_id:'R1',observed_at:'2026-10-07T00:00:00Z',sim_elapsed_s:5,running:false,auth_percent:99.5,throughput_mbps:40,loss_percent:.2,devices:[]}},events:{events:[{observed_at:'2026-10-07T00:00:00Z',message:'<unsafe>'}]},runtime:{run_id:'R1',running:false}};
test('source security is explicit query and renders source verdict without inventing actual security',async()=>{let calls=0;const f=fixture({securityDashboard:async()=>{calls++;return structuredClone(report);}});f.ui.show('security');assert.equal(calls,0);f.ui.updateSocket('open');f.ui.updateTelemetry({runtime:{run_id:'R1',running:false}});await f.ui.query();assert.equal(calls,1);assert.equal(f.get('auth-state').textContent,'SIM 기준 충족');assert.equal(f.get('integrity').textContent,'검증 입력 없음');assert.equal(f.get('received').textContent,'1970-01-01T00:00:01.000Z');assert.match(f.get('events').innerHTML,/&lt;unsafe&gt;/);assert.equal(f.get('flow').dataset.moving,'false');f.ui.destroy();assert.equal(f.timers.size,0);});
test('exit aborts pending query and ignores late success; external errors retain unknown state',async()=>{let resolve,signal;const f=fixture({securityDashboard:options=>{signal=options.signal;return new Promise(r=>resolve=r);}});f.ui.show('security');const pending=f.ui.query();f.ui.show('ground');assert.equal(signal.aborted,true);resolve(report);await pending;f.ui.show('security');assert.equal(f.get('run').textContent,'—');f.ui.destroy();const failed=fixture({securityDashboard:async()=>{throw Error('외부 모듈 응답 없음');}});failed.ui.show('security');await failed.ui.query();assert.match(failed.get('evidence').textContent,/외부 모듈 응답 없음/);assert.equal(failed.get('auth-state').textContent,'미확인');failed.ui.destroy();});
test('SIM run change invalidates observation and does not paint an older pending response',async()=>{let resolve;const f=fixture({securityDashboard:()=>new Promise(r=>resolve=r)});f.ui.show('security');f.ui.updateTelemetry({runtime:{run_id:'R1',running:false}});const pending=f.ui.query();f.ui.updateTelemetry({runtime:{run_id:'R2',running:false}});resolve(report);await pending;assert.equal(f.get('run').textContent,'—');f.ui.destroy();});

test('remote failure retains placement diagnostics and marks retained observations unknown',async()=>{let failed=false;const f=fixture({securityDashboard:async()=>{if(!failed)return structuredClone(report);const error=Error('응답 없음');error.report={module:{reachable:false,placement:'remote',endpoint:'http://security.example',detail:'응답 없음'}};throw error;}});f.ui.show('security');f.ui.updateSocket('open');f.ui.updateTelemetry({runtime:{run_id:'R1'}});await f.ui.query();failed=true;await f.ui.query();assert.equal(f.get('placement').textContent,'외부 HTTP 모듈');assert.equal(f.get('endpoint').textContent,'http://security.example');assert.equal(f.get('auth-state').textContent,'미확인');assert.equal(f.get('flow').dataset.moving,'false');f.ui.destroy();});

test('missing or invalid observation timestamps remain unknown while receive time is Unix milliseconds',async()=>{for(const value of [null,'invalid',Infinity,NaN]){const input=structuredClone(report);input.overview.observation.observed_at=value;const f=fixture({securityDashboard:async()=>input});f.ui.show('security');await f.ui.query();assert.equal(f.get('observed').textContent,'—');assert.equal(f.get('received').textContent,'1970-01-01T00:00:01.000Z');f.ui.destroy();}});
