import test from 'node:test';import assert from 'node:assert/strict';
const point={latitude_deg:36,longitude_deg:127,ellipsoid_height_m:10,virtual:true,ellipsoid:'WGS84'};
const site={key:'S',name:'Station',latitude:36,longitude:127,minElevationDeg:5};
const selected={catalog_number:25544,name:'ISS',normalized_gp_sha256:'a'.repeat(64)};
const timeline={selected,observer:point,minimumElevation:5,utc:'2026-10-07T00:00:00Z',display:{...selected,utc:'2026-10-07T00:00:00Z',observation_utc:'2026-10-07T00:00:00Z',ground_point:point,minimum_elevation_deg:5,range_m:1000000,azimuth_deg:null,observed_elevation_deg:10}};
test('station card consumes native same-owner geometry, missing zenith azimuth stays unknown',async()=>{const {stationCatalogCard}=await import('../../../user_application/web/scripts/orbit/station_card_projection.js');const m=stationCatalogCard(site,timeline,{result:null});assert.equal(m.state,'visible');assert.ok(m.live.some(([k,v])=>k==='방위각 / 고각'&&v==='—° / 10.0°'));assert.ok(m.live.some(([k,v])=>k==='다음 관측창'&&v.includes('미조회')));assert.equal(m.isObserver,true);});
test('other station/hash/UTC geometry cannot impersonate selected observation and unqueried is not no-pass',async()=>{const {stationCatalogCard}=await import('../../../user_application/web/scripts/orbit/station_card_projection.js');const variants=[{site:{...site,latitude:35},t:timeline},...['hash','utc','mask','point'].map(kind=>{const t=structuredClone(timeline);if(kind==='hash')t.display.normalized_gp_sha256='b'.repeat(64);if(kind==='utc')t.display.utc='2026-10-08T00:00:00Z';if(kind==='mask')t.display.minimum_elevation_deg=6;if(kind==='point')t.display.ground_point={...t.display.ground_point,ellipsoid_height_m:100};return {site,t};})];for(const variant of variants){const m=stationCatalogCard(variant.site,variant.t,{result:null});assert.equal(m.state,'unknown');assert.ok(m.live.some(([k,v])=>k==='다음 관측창'&&!v.includes('24 h 내 없음')));}});
test('only verified same-scope complete-none pass result says no pass; partial stays uncertain',async()=>{const {stationCatalogCard}=await import('../../../user_application/web/scripts/orbit/station_card_projection.js');const result={...selected,ground_point:point,minimum_elevation_deg:5,query_start_utc:timeline.utc,status:'none',intervals:[]};assert.ok(stationCatalogCard(site,timeline,{result}).live.some(([k,v])=>k==='다음 관측창'&&v.includes('24 h 내 없음')));for(const r of [{...result,status:'partial'},{...result,normalized_gp_sha256:'b'.repeat(64)}])assert.ok(stationCatalogCard(site,timeline,{result:r}).live.some(([k,v])=>k==='다음 관측창'&&!v.includes('24 h 내 없음')));});
test('GP inspector missing values remain unknown and native projection does not claim velocity/WGS84',async()=>{const {catalogInspectorRows}=await import('../../../user_application/web/scripts/orbit/inspector_policy.js');const rows=catalogInspectorRows({NORAD_CAT_ID:25544,RA_OF_ASC_NODE:0,MEAN_MOTION:15,EPOCH:'2026-10-06T00:00:00Z'},null,{timeline});assert.ok(rows.some(([k,v])=>k==='승교점 적경 °'&&v==='0.000'));assert.ok(rows.some(([k,v])=>k==='분석 UTC − GP epoch h'&&v==='24.0'));assert.ok(rows.some(([k,v])=>k==='속력 TEME km/s'&&v==='미제공'));assert.ok(rows.some(([k,v])=>k==='평균 근점 이각 °'&&v==='미제공'));});

test('native selection clear and missing pass result never dereference null or imply a pass',async()=>{const {stationCatalogCard}=await import('../../../user_application/web/scripts/orbit/station_card_projection.js');for(const t of [{...timeline,selected:null,display:null,utc:''},{...timeline,display:null}]){let card;assert.doesNotThrow(()=>card=stationCatalogCard(site,t,{result:null}));assert.notEqual(card.state,'visible');assert.ok(card.live.some(([k,v])=>k==='다음 관측창'&&!v.includes('24 h 내 없음')));}});

test('inspector native WGS84 and TEME speed use exact sample UTC beside interpolated display UTC',async()=>{const {catalogInspectorRows}=await import('../../../user_application/web/scripts/orbit/inspector_policy.js');const t=structuredClone(timeline);t.display={...t.display,position_m:[7000000,0,0],utc:'2026-10-07T00:00:00.500Z',details_utc:timeline.utc,observation_utc:timeline.utc,interpolated:true,details_version:1,details_profile:'WGS84_ERFA_GC2GD_TEME_SPEED',details_units:{latitude:'deg',longitude:'deg',ellipsoid_height:'m',teme_speed:'km/s'},geodetic:{latitude_deg:0,longitude_deg:0,ellipsoid_height_m:400000,ellipsoid:'WGS84'},teme_speed_km_s:7.7};t.utc=t.display.utc;const rows=catalogInspectorRows({NORAD_CAT_ID:25544},null,{timeline:t});assert.ok(rows.some(([k,v])=>k==='속력 TEME km/s'&&v==='7.700'));assert.ok(rows.some(([k,v])=>k==='상세 native 표본 UTC'&&v===timeline.utc));assert.ok(rows.some(([k,v])=>k==='타원체 고도 km · WGS84'&&v==='400.0'));t.display.details_units.teme_speed='m/s';assert.ok(catalogInspectorRows({NORAD_CAT_ID:25544},null,{timeline:t}).some(([k,v])=>k==='속력 TEME km/s'&&v==='미제공'));});
