import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';
const wait=()=>new Promise(r=>setTimeout(r,2));
async function settle(f){for(let i=0;i<150&&f.evaluate('nodeWorkspace.snapshot().deployment.busy');i++)await wait();}
async function setup(){const records=new Map(),storage={getItem:k=>records.get(k)??null,setItem:(k,v)=>records.set(k,v)};let server={revision:0,run_id:'fixture',scope_id:'fixture:unconfigured',deployment_id:null,nodes:[]},posts=0,gets=0,hold=false,release;const fetch=async(url,o)=>{if(o.method==='POST'){posts++;const p=JSON.parse(o.body);server={revision:1,run_id:'fixture',scope_id:'fixture:deployment:'+p.deployment_id,deployment_id:p.deployment_id,nodes:p.nodes};}else{gets++;if(hold)await new Promise(r=>release=r);}return{ok:true,json:async()=>structuredClone(server)};};const first=fixture(1920,1080,{hash:'#satellite',storage,fetch});await wait();await first.get('node-add').dispatch('click');await first.get('nodes-deploy').dispatch('click');await settle(first);assert.equal(first.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),true);first.dispose();const f=fixture(1920,1080,{hash:'#satellite',storage,fetch});await wait();assert.equal(f.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),false);return{f,records,get server(){return server;},set server(v){server=v;},get posts(){return posts;},get gets(){return gets;},hold(){hold=true;},release(){hold=false;release?.();},button(){const b=f.doc.getElementById('nodes-recheck-saved');assert.ok(b,'explicit saved deployment recheck exists');return b;},dispose(){hold=false;release?.();f.dispose();}};}
test('actual saved receipt reload has explicit GET-only reaccept action',async()=>{const s=await setup();try{const b=s.button(),posts=s.posts,gets=s.gets;assert.equal(b.disabled,false);await b.dispatch('click');await settle(s.f);assert.equal(s.f.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),true);assert.equal(s.posts,posts);assert.equal(s.gets,gets+1);}finally{s.dispose();}});
for(const kind of ['run','revision','equipment','draft','timestamp','dispose','remount'])test('saved recheck cannot approve '+kind+' drift or late response',async()=>{const s=await setup();try{const b=s.button(),posts=s.posts;if(kind==='run')s.server={...s.server,run_id:'other',scope_id:'other:deployment:'+s.server.deployment_id};if(kind==='revision')s.server={...s.server,revision:2};if(kind==='equipment'){s.server=structuredClone(s.server);s.server.nodes[0].equipment[0].enabled=!s.server.nodes[0].equipment[0].enabled;}s.hold();await b.dispatch('click');for(let i=0;i<30&&s.gets<3;i++)await wait();if(kind==='draft')s.f.evaluate('nodeWorkspace.scenarioPorts().store.update(nodeWorkspace.sceneSnapshot().drafts[0].id,{...nodeWorkspace.sceneSnapshot().drafts[0],name:"changed"})');if(kind==='timestamp'){const key='spacetwin-nodes-draft-v1',record=JSON.parse(s.records.get(key));record.nodes[0].updated_at='2026-10-07T01:01:01.000Z';s.records.set(key,JSON.stringify(record));s.f.evaluate('nodeWorkspace.scenarioPorts().store.load({discardLocal:true})');assert.equal(s.f.evaluate('nodeWorkspace.scenarioPorts().store.isDirty()'),false);}if(kind==='dispose')s.f.evaluate('nodeWorkspace.destroy()');if(kind==='remount'){s.f.evaluate("location.hash='#composer'");await s.f.win.dispatch('hashchange');}s.release();await settle(s.f);assert.equal(s.f.evaluate('nodeWorkspace.sceneSnapshot()?.deployment_confirmed??false'),false);assert.equal(s.posts,posts);}finally{s.dispose();}});

test('timestamp-only dirty saved draft is disabled before any recheck GET',async()=>{const s=await setup();try{const key='spacetwin-nodes-draft-v1',record=JSON.parse(s.records.get(key));record.nodes[0].updated_at='2026-10-07T01:01:01.000Z';s.records.set(key,JSON.stringify(record));s.f.evaluate('nodeWorkspace.scenarioPorts().store.load({discardLocal:true})');assert.equal(s.f.evaluate('nodeWorkspace.scenarioPorts().store.isDirty()'),false);const before=s.gets;assert.equal(s.button().disabled,true);await s.button().dispatch('click');await wait();assert.equal(s.gets,before);assert.equal(s.f.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),false);}finally{s.dispose();}});
test('double click shares one in-flight saved-receipt GET and confirmation',async()=>{const s=await setup();try{const b=s.button(),before=s.gets;s.hold();await b.dispatch('click');await b.dispatch('click');for(let i=0;i<30&&s.gets===before;i++)await wait();assert.equal(s.gets,before+1);assert.equal(b.disabled,true);s.release();await settle(s.f);assert.equal(s.f.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),true);assert.equal(s.gets,before+1);}finally{s.dispose();}});

test('mismatched server receipt reports refusal visibly and never approves restored copy',async()=>{const s=await setup();try{s.server={...s.server,revision:s.server.revision+1};await s.button().dispatch('click');await settle(s.f);assert.equal(s.f.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),false);assert.match(s.f.get('deploy-state').textContent,/다릅니다|배치|수락|재확인/);assert.ok(s.f.evaluate('nodeWorkspace.snapshot().deployment.error'));}finally{s.dispose();}});
test('actual draft owner change then revert still irrevocably invalidates pending GET recheck',async()=>{const s=await setup();try{s.hold();await s.button().dispatch('click');for(let i=0;i<30&&s.gets<3;i++)await wait();s.f.evaluate('const saved=nodeWorkspace.sceneSnapshot().drafts[0];nodeWorkspace.scenarioPorts().store.update(saved.id,{...saved,name:"transient"});nodeWorkspace.scenarioPorts().store.update(saved.id,saved)');s.release();await settle(s.f);assert.equal(s.f.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),false);assert.equal(s.posts,1);}finally{s.dispose();}});
