import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './workspace_fixture.mjs';

function inside(f,width,height){const rect=f.get('work-window').getBoundingClientRect();assert.ok(rect.left>=80,'left controls remain past rail');assert.ok(rect.top>=116,'title remains below app header');assert.ok(rect.right<=width-8,`right ${rect.right} <= ${width-8}`);assert.ok(rect.bottom<=height-29,`bottom ${rect.bottom} <= ${height-29}`);}
const key=(f,id,name,shiftKey=false)=>f.get(id).dispatch('keydown',{key:name,shiftKey});

for(const [width,height] of [[1280,720],[1920,1080]]){
  test(`${width}x${height}: keyboard move and resize stay within usable viewport`,async()=>{const f=fixture(width,height);try{for(let i=0;i<100;i++)await key(f,'window-title','ArrowRight',true);for(let i=0;i<100;i++)await key(f,'window-title','ArrowDown',true);inside(f,width,height);for(let i=0;i<100;i++)await key(f,'resize-handle','ArrowRight',true);for(let i=0;i<100;i++)await key(f,'resize-handle','ArrowDown',true);inside(f,width,height);}finally{f.dispose();}});
  test(`${width}x${height}: minimize/restore and expand preserve ground draft/result and one Viewer`,async()=>{const f=fixture(width,height);try{await f.get('visibility-query').dispatch('click');const output=f.get('visibility-result'),html=output.innerHTML;assert.match(html,/가시 구간 없음/);for(let i=0;i<3;i++){await f.get('window-minimize').dispatch('click');await f.get('shelf-restore').dispatch('click');await f.get('window-expand').dispatch('click');await f.get('window-expand').dispatch('click');assert.equal(output.innerHTML,html);assert.equal(f.get('visibility-result'),output);}const field=f.get('ground-height');field.value='321';await field.dispatch('input');const saved=f.snapshot(),before=f.counts();for(let i=0;i<3;i++){await f.get('window-minimize').dispatch('click');assert.equal(f.get('work-window').hidden,true);await f.get('shelf-restore').dispatch('click');assert.equal(f.get('work-window').hidden,false);await f.get('window-expand').dispatch('click');await f.get('window-expand').dispatch('click');}assert.equal(f.get('ground-height'),field);assert.equal(field.value,'321');assert.equal(f.get('visibility-result'),output);assert.deepEqual(f.snapshot(),saved);assert.deepEqual(f.counts(),before);assert.equal(f.viewers.length,1);assert.equal(f.viewers[0].destroyCount,undefined);}finally{f.dispose();}});
}
test('pointer cancellation releases capture/listeners and later moves do not change geometry',async()=>{const f=fixture();try{const title=f.get('window-titlebar');await title.dispatch('pointerdown',{button:0,pointerId:1,clientX:200,clientY:160});await title.dispatch('pointermove',{clientX:240,clientY:180});await title.dispatch('pointercancel');const rect=f.get('work-window').getBoundingClientRect();assert.equal(title.capture,null);for(const event of ['pointermove','pointerup','pointercancel'])assert.equal(title.listeners.get(event)?.size,0);await title.dispatch('pointermove',{clientX:999,clientY:999});assert.deepEqual(f.get('work-window').getBoundingClientRect(),rect);}finally{f.dispose();}});
test('shrinking viewport clamps the existing window size as well as its position',async()=>{const f=fixture(1920,1080);try{Object.assign(f.get('work-window').style,{left:'1000px',top:'440px',width:'850px',height:'600px'});await f.resize(1280,720);inside(f,1280,720);}finally{f.dispose();}});
test('a minimized window restores inside the viewport after a resolution change',async()=>{const f=fixture(1920,1080);try{Object.assign(f.get('work-window').style,{left:'1000px',top:'440px',width:'850px',height:'600px'});await f.get('window-minimize').dispatch('click');await f.resize(1280,720);await f.get('shelf-restore').dispatch('click');inside(f,1280,720);}finally{f.dispose();}});
test('restoring an expanded window clamps saved geometry to the new viewport',async()=>{const f=fixture(1920,1080);try{Object.assign(f.get('work-window').style,{left:'1000px',top:'440px',width:'850px',height:'600px'});await f.get('window-expand').dispatch('click');await f.resize(1280,720);await f.get('window-expand').dispatch('click');inside(f,1280,720);}finally{f.dispose();}});
test('real page exit releases document subscriptions and renderer exactly once; bfcache preserves them',async()=>{const f=fixture();try{await f.win.dispatch('pagehide',{persisted:true});assert.equal(f.viewers[0].destroyCount,undefined);assert.equal(f.timers.size,1);await f.win.dispatch('pagehide',{persisted:false});await f.win.dispatch('pagehide',{persisted:false});assert.equal(f.viewers[0].destroyCount,1);assert.equal(f.timers.size,0);assert.equal(f.frames.size,0);assert.equal(f.viewers[0].errorRemoved,true);assert.ok(f.channels.every(channel=>channel.closed),'workspace BroadcastChannel is released');}finally{f.dispose();}});

test('page exit also detaches an unfinished pointer gesture',async()=>{const f=fixture();try{const title=f.get('window-titlebar');await title.dispatch('pointerdown',{button:0,pointerId:7,clientX:200,clientY:160});await f.win.dispatch('pagehide',{persisted:false});assert.equal(title.listeners.get('pointermove')?.size,0);assert.equal(title.listeners.get('pointerup')?.size,0);assert.equal(title.listeners.get('pointercancel')?.size,0);assert.equal(title.capture,null);}finally{f.dispose();}});

test('orbit assembly disposes request client only on final page exit',async()=>{const f=fixture();try{await f.win.dispatch('pagehide',{persisted:true});assert.equal(f.counts().clientDestroyed,0);await f.win.dispatch('pagehide',{persisted:false});await f.win.dispatch('pagehide',{persisted:false});assert.equal(f.counts().clientDestroyed,1);}finally{f.dispose();}});
