import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {projectWorkspaceContext} from '../../../user_application/web/scripts/workspace_context.js';
import {createOrbitSelection} from '../../../user_application/web/scripts/orbit_selection.js';
const captured=JSON.parse(readFileSync(new URL('../fixtures/workspace_context_poc.json',import.meta.url),'utf8'));
const copy=structuredClone;
test('whole catalogue scene has concise presentation labels without changing full hashed identity or input',()=>{
 const digest='f'.repeat(64),x={display:{key:'scene:'+digest,utc:'2026-10-07T00:00:00.000000000Z'}};const before=structuredClone(x),v=projectWorkspaceContext(x);
 assert.equal(v.text.satellite,'전체 위성 · GP 장면');assert.equal(v.text.contextId,'전체 위성');
 assert.equal(v.identity.domain,'catalog_scene');assert.equal(v.identity.id,digest);assert.equal(v.identity.source,'카탈로그 전체 장면');assert.equal(v.utc.value,x.display.utc);assert.deepEqual(x,before);
 assert.equal(projectWorkspaceContext({display:{...x.display,key:'scene:invalid'}}).identity.domain,'unavailable');
});
test('real selected catalogue name remains unchanged by whole-scene presentation shortening',()=>{
 const digest='a'.repeat(64),utc='2026-10-07T00:00:00.000000000Z',x={display:{key:'catalog:56732:'+digest,utc},catalog:{selected:{catalog_number:56732,normalized_gp_sha256:digest},display:{catalog_number:56732,normalized_gp_sha256:digest,name:'ARKTIKA-M 2',utc,frame:'ITRF',status:'valid',source:'celestrak-cache'},error:''}};
 const v=projectWorkspaceContext(x);assert.equal(v.text.satellite,'ARKTIKA-M 2 · GP 위성');assert.equal(v.text.contextId,'56732');
});
function poc(){const c=copy(captured.context),d=copy(captured.data);return {display:{key:'sim:'+c.deployment.run_id,utc:c.utc,source:'sim'},sim:{runtime:d.runtime,error:'',connection:'open'},nodes:{loaded:true,deployment_confirmed:true,error:'',deployed:c.nodes,drafts:c.nodes,selected_id:c.nodes[0].id,server:c.deployment},data:{report:d,error:'',busy:false},fabric:{status:'accepted',receipt:copy(captured.fabric),error:'',pending:false}};}
test('actual forty-node accepted deployment and last queried data stay SIM, never real reception',()=>{const x=poc(),before=JSON.stringify(x),v=projectWorkspaceContext(x);assert.equal(v.deployment.count,40);assert.equal(v.run.id,captured.data.runtime.run_id);assert.equal(v.identity.domain,'source_sim');assert.equal(v.data.status,'last_verified_query');assert.equal(v.data.elapsed_seconds,captured.data.runtime.elapsed_seconds);assert.match(v.handoff,/실제 RF.*미확인/);assert.equal(JSON.stringify(x),before);assert.equal(v.utc.value,captured.context.utc);assert.doesNotMatch(JSON.stringify(v),/SAT-A|M-204|GS-02|D-731/);});
test('draft node selection does not replace displayed GP; normalized hash and exact UTC must match',()=>{const x=poc(),hash='a'.repeat(64),utc='2026-10-07T00:00:00.000000001Z';x.display={key:'catalog:25544:'+hash,utc};x.catalog={selected:{catalog_number:25544,normalized_gp_sha256:hash},display:{catalog_number:25544,normalized_gp_sha256:hash,utc,frame:'ITRF',status:'valid',source:'celestrak-cache'},error:''};let v=projectWorkspaceContext(x);assert.equal(v.identity.domain,'catalog_gp');assert.equal(v.identity.id,'25544');assert.equal(v.utc.value,utc);x.catalog.display.utc='2026-10-07T00:00:00.000000002Z';assert.equal(projectWorkspaceContext(x).identity.domain,'unavailable');x.catalog.display.utc=utc;x.catalog.selected.normalized_gp_sha256='b'.repeat(64);assert.equal(projectWorkspaceContext(x).identity.domain,'unavailable');});
test('explicit node selection is labeled draft when roster or runtime no longer matches',()=>{const x=poc();x.selection={domain:'source_node',id:x.nodes.selected_id};assert.equal(projectWorkspaceContext(x).identity.domain,'source_node');x.nodes.server.run_id='old';assert.equal(projectWorkspaceContext(x).identity.status,'draft');assert.equal(projectWorkspaceContext(x).data.status,'unavailable');});
test('SIM error and stale data scope/revision cannot imply current accepted state',()=>{for(const mutate of [x=>x.sim.error='offline',x=>x.data.report.deployment.revision++,x=>x.data.report.module.scope_id='old',x=>x.data.busy=true,x=>x.data.error='failed']){const x=poc();mutate(x);assert.equal(projectWorkspaceContext(x).data.status,'unavailable');}const x=poc();x.sim.error='offline';assert.equal(projectWorkspaceContext(x).run.status,'unavailable');assert.equal(projectWorkspaceContext(x).deployment.status,'unavailable');});
test('null/cleared/error display remains unavailable without mock fallback or fabricated time',()=>{for(const x of [{},{display:null},{display:{key:'catalog:1:x',utc:'2026-10-07T00:00:00Z'},catalog:{error:'failed'}}]){const v=projectWorkspaceContext(x);assert.equal(v.identity.domain,'unavailable');assert.equal(v.utc.value,null);assert.match(v.text.clock,/미확인/);}});
test('source module-held mission requires exact current physical context and acceptance hash',()=>{const x=poc(),c=copy(captured.context),id='M1',hash='a'.repeat(64);const context={utc:c.utc,nodes:c.nodes,stations:c.stations,faults:[],deployment:c.deployment,settings:{host:'localhost'},module:{instance:'module1',sequence:4},external:null,missions:[]};x.mission={ready:true,selected:{id,version:1,status:'planned'},context,inspection:{context:copy(context),evidence:{accepted_context:{context_hash:hash}}},module:{reachable:true,exchange_contract:'guarded-v1',instance_id:'module1',accepted_plans:{M1:{mission_id:id,instance_id:'module1',context_hash:hash,mission_version:1,feasible:true}},committed:{}}};assert.equal(projectWorkspaceContext(x).mission.status,'module_accepted_plan');x.mission.context.utc+='0';assert.equal(projectWorkspaceContext(x).mission.status,'draft_or_previous_plan');x.mission.context=copy(context);x.mission.module.instance_id='restart';assert.equal(projectWorkspaceContext(x).mission.status,'draft_or_previous_plan');});
test('fabric receipt requires current native network proof and exact same source-network receipt time',()=>{const x=poc();x.network={verified:true,proof:{status:'valid',utc:x.display.utc,network:{time:x.fabric.receipt.time}}};assert.equal(projectWorkspaceContext(x).communication.status,'last_verified_query');assert.equal(projectWorkspaceContext(x).communication.utc,x.display.utc);x.network.verified=false;assert.equal(projectWorkspaceContext(x).communication.status,'unavailable');x.network.verified=true;x.network.proof.utc+='0';assert.equal(projectWorkspaceContext(x).communication.status,'unavailable');x.network.proof.utc=x.display.utc;x.network.proof.network.time='2000-01-01T00:00:00Z';assert.equal(projectWorkspaceContext(x).communication.status,'unavailable');x.fabric.receipt=null;assert.equal(projectWorkspaceContext(x).communication.status,'unavailable');});
test('source SIM/native-node frame stays unknown without actual GMST receipt while GP is ITRF',()=>{const x=poc();assert.equal(projectWorkspaceContext(x).utc.frame,null);x.selection={domain:'source_node',id:x.nodes.selected_id};assert.equal(projectWorkspaceContext(x).utc.frame,null);});
test('existing saved-orbit selection owner controls identity across selection changes without current-ISS claim',async()=>{
 const utc='2000-06-27T18:50:19.733568000Z',inputs=[{input_id:'saved-one',raw_sha256:'a'.repeat(64),satellite_id:'ISS historical input',source:'saved-vallado',epoch_utc:utc},{input_id:'saved-two',raw_sha256:'b'.repeat(64),satellite_id:'Other saved input',source:'saved-reference',epoch_utc:utc}];let state={input_id:'saved-one',current_utc:utc,revision:1};
 const owner=createOrbitSelection({orbitInputs:async()=>({inputs}),orbitState:async()=>state,selectOrbit:async body=>(state={...state,input_id:body.input_id,revision:state.revision+1})},()=>{},()=> 'selection-request',()=>0);
 await owner.load();const display={key:'stored:saved-one:'+inputs[0].raw_sha256,utc};let v=projectWorkspaceContext({display,stored:owner.snapshot()});assert.equal(v.identity.domain,'stored_orbit');assert.equal(v.identity.source,'saved-vallado');assert.equal(v.utc.frame,'ITRF');assert.equal(v.identity.status,'saved_analysis');await owner.select('saved-two');assert.equal(projectWorkspaceContext({display,stored:owner.snapshot()}).identity.domain,'unavailable');owner.destroy();
});
