import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './workspace_fixture.mjs';import {LEAP_SHA256,createUtcCodec} from '../../../user_application/web/scripts/orbit_utc.js';
const utc='2020-07-12T21:16:01.000416000Z',H='a'.repeat(64),codec=createUtcCodec(LEAP_SHA256),quality={ut1:'final_b',polar_motion:'final_b'};
test('actual station card uses native geometry and explicit existing pass owner, switching visual station never reuses look',async()=>{
 let passCalls=0;const meta={name:'ISS',epoch_utc:utc,source:'celestrak-cache',normalized_gp_sha256:H,eop_sha256:H,leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC',eop_kind:'IERS_A',eop_quality:quality};
 const gp={NORAD_CAT_ID:25544,OBJECT_NAME:'ISS',MEAN_MOTION:15,RA_OF_ASC_NODE:0,EPOCH:utc};
 const f=fixture(1280,720,{hash:'#satellite',satelliteGroups:async()=>({items:[{id:'active',label:'Active'}]}),satellites:async p=>({...p,source:'celestrak-cache',items:[gp],count:1,total:1,filtered_total:1}),satelliteProfile:async()=>({source:'gp-cache',catalog:{NORAD_CAT_ID:25544},gp}),catalogPosition:async p=>({...meta,...p,utc,version:1,status:'valid',position_m:[7e6,1,2]}),catalogSamples:async p=>({...meta,...p,version:1,status:'valid',communication_status:'unknown',units:{position:'m',range:'m',elevation:'deg',azimuth:'deg',time:'UTC'},rows:Array.from({length:p.count},(_,i)=>({utc:codec.advance(p.start_utc,i),position_m:[7e6+i,1,2],elevation_deg:10,range_m:1000000+i,azimuth_deg:null,visible:10>=p.minimum_elevation_deg,eop_quality:quality,status:'valid',error_code:null}))}),catalogVisibility:async p=>{passCalls++;return {...meta,...p,catalog_number:25544,version:1,status:'none',communication_status:'unknown',units:{time:'UTC',elevation:'deg',duration:'s'},intervals:[],contacts:[],errors:[]};}});
 try{for(let i=0;i<12;i++)await Promise.resolve();f.flush();const before=f.snapshot();await f.get('cat-sat-25544').dispatch('click');for(let i=0;i<12;i++)await Promise.resolve();f.flush();f.get('station-select').value='DAEJEON';await f.get('station-select').dispatch('change');await f.get('station-catalog-use').dispatch('click');assert.match(f.get('station-live').innerHTML,/미조회/);assert.equal(passCalls,0);await f.get('cat-time-calculate').dispatch('click');assert.match(f.get('station-live').innerHTML,/1,?000\.0 km/);assert.match(f.get('station-observation-status').textContent,/최소각 충족/);assert.match(f.get('cat-detail').innerHTML,/승교점 적경/);assert.match(f.get('cat-detail').innerHTML,/현재 위치 ITRF/);await f.get('station-pass-query').dispatch('click');assert.equal(passCalls,1);assert.match(f.get('station-live').innerHTML,/조회한 24 h 내 없음/);f.get('station-select').value='JEJU';await f.get('station-select').dispatch('change');assert.match(f.get('station-live').innerHTML,/관측 조건 미적용/);assert.equal(f.get('station-pass-query').disabled,true);assert.match(f.get('station-observation-status').textContent,/미확인/);assert.equal(f.viewers.length,1);assert.equal(f.counts().commands,0);assert.deepEqual(f.snapshot(),before);
 }finally{f.dispose();}
});
