import test from 'node:test';
import assert from 'node:assert/strict';
import {sourceLinkRfDraft} from '../../../user_application/web/scripts/tabs/rf_link_budget.js';
import {fixture} from './workspace_fixture.mjs';
import {createUtcCodec,LEAP_SHA256} from '../../../user_application/web/scripts/orbit_utc.js';
import {orbitElements} from '../../../digital_twin/simulation/browser/node_orbit_definition.js';
import {NODE_COMMUNICATION_METADATA as metadata} from '../../../user_application/web/scripts/nodes/node_timeline.js';
// Real application owners and wiring; HTTP/Cesium/DOM remain controlled test
// adapters. These checks are not live native physics or GPU FPS acceptance.
const codec=createUtcCodec(LEAP_SHA256),utc=codec.advance('2026-10-07T00:00:00Z',0),H='a'.repeat(64),quality={ut1:'final_b',polar_motion:'final_b'};
const base={group:'active',catalog_number:25544,name:'ISS',utc,epoch_utc:utc,source:'celestrak-cache',normalized_gp_sha256:H,eop_sha256:H,leap_sha256:LEAP_SHA256,frame:'ITRF',profile:'WGS72_AFSPC',eop_kind:'IERS_A',eop_quality:quality,position_m:[7000000,0,0]};
const row=stamp=>({utc:stamp,status:'valid',error_code:null,position_m:[7000000,2,3],inertial_position_km:[7000,0,0],lvlh_basis:{x:[1,0,0],y:[0,1,0],z:[0,0,1]},inertial_velocity_km_s:[0,7.5,0],raan_deg:0,argp_deg:0,mean_anomaly_deg:0,sunlit:true,longitude_deg:0,latitude_deg:0,height_km:550});
const settle=async (f,timers)=>{for(let i=0;i<80;i++){for(const [id,job]of [...timers])if(job.ms===0){timers.delete(id);job.fn();}await new Promise(resolve=>setImmediate(resolve));f.flush();}};
for(const [width,height]of[[1280,720],[1920,1080]])test(`actual paused catalog native network connects inspectable SVG ${width}x${height}`,async()=>{
 let now=0,next=0,rfCalls=0;const raf=new Map(),timers=new Map(),requests=[];
 let server={revision:0,run_id:'fixture',scope_id:'fixture:unconfigured',deployment_id:null,nodes:[]};
 const f=fixture(width,height,{hash:'#satellite',rfRequest:async()=>{rfCalls++;throw Error('RF calculation requires explicit operator command');},fetch:async(url,o={})=>{if(o.method==='POST'){const p=JSON.parse(o.body);server={revision:1,run_id:'fixture',scope_id:'fixture:deployment:'+p.deployment_id,deployment_id:p.deployment_id,nodes:p.nodes};}return{ok:true,json:async()=>structuredClone(server)};},planningBootstrap:async()=>({runtime:{mode:'SIM',running:false,speed:1,elapsed_seconds:0,sequence:0,run_id:'fixture',scenario_id:'fixture',active_faults:[]},scenarios:[{id:'fixture',name:'fixture'}],events:[],missions:[]}),catalogNow:()=>now,catalogRequestFrame:fn=>{const id=++next;raf.set(id,fn);return id;},catalogCancelFrame:id=>raf.delete(id),setTimeout:(fn,ms)=>{const id=++next;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),
  catalogSamples:async p=>({...base,...p,version:1,status:'valid',communication_status:'unknown',units:{position:'m',range:'m',elevation:'deg',azimuth:'deg',time:'UTC'},rows:Array.from({length:p.count},(_,i)=>({...row(codec.advance(p.start_utc,i)),position_m:[7000000+i,0,0],elevation_deg:10,range_m:1000,azimuth_deg:0,visible:true,eop_quality:quality}))}),
  nodeSamples:async p=>{requests.push(structuredClone(p));return{schema_version:1,...metadata,request_id:p.request_id,status:'valid',nodes:p.nodes.map(node=>({node_id:node.id,definition_hash:H,rows:Array.from({length:p.count},(_,i)=>row(codec.advance(p.start_utc,i)))}))};},
  nodeTrack:async p=>({schema_version:1,...metadata,request_id:p.request_id,status:'valid',nodes:p.nodes.map(node=>({node_id:node.id,definition_hash:H,period_minutes:Math.round(orbitElements(node.orbit).period/60*1000)/1000,path_visible:true,rows:Array.from({length:121},(_,i)=>row(codec.advance(new Date(Math.trunc(Date.parse(p.center_utc)+(i-60)*(Math.round(orbitElements(node.orbit).period/60*1000)/1000)*60000/120)).toISOString(),0)))}))})});

 try{await settle(f,timers);f.evaluate(`{const store=nodeWorkspace.scenarioPorts().store;const first=store.add({name:'Paused native cohort',bus:'flat_panel'});store.addMany(Array.from({length:39},(_,i)=>({...first,id:'PAUSED-'+i,catalog_number:900002+i,name:'Node '+i,equipment:first.equipment.map(item=>({...item,id:item.id+'-'+i}))})));store.select(first.id);}`);await settle(f,timers);await f.get('nodes-deploy').dispatch('click');await settle(f,timers);assert.equal(f.evaluate('nodeWorkspace.sceneSnapshot().deployment_confirmed'),true);
 f.evaluate(`catalogTimeline.select(${JSON.stringify(base)});catalogTimeline.observer({latitude_deg:0,longitude_deg:0,ellipsoid_height_m:0,virtual:true,ellipsoid:'WGS84'},5)`);await f.evaluate('catalogTimeline.calculate()');await f.evaluate('simPanel.controller.load()');f.evaluate("showWorkspaceOrbit('ground')");await settle(f,timers);await f.get('ground-node-calculate').dispatch('click');await settle(f,timers);
 const native=f.evaluate('nodeWorkspace.networkSnapshot()');assert.equal(native.status,'valid');assert.equal(native.node_definitions.length,40);assert.equal(f.evaluate('nodeClock.read(globe.displayContext()).running'),false);assert.equal(f.evaluate('nodeWorkspace.verifyNetworkSnapshot(nodeWorkspace.networkSnapshot())'),true);const eligible=native.network.links.filter(l=>l.kind!=='ground'||l.state!=='no_radio');assert.ok(eligible.length>0,'native owner provides real inspectable geometric links');const svg=f.get('ground-node-diagram').innerHTML;assert.ok(/data-diagram-link=/.test(svg),JSON.stringify({nativeNodes:native.network.nodes.length,nativeLinks:native.network.links.length,eligible:eligible.length,svgLinks:[...svg.matchAll(/data-diagram-link=/g)].length}));assert.equal(f.viewers.length,1);assert.equal(f.counts().commands,0);assert.equal(f.evaluate('fabric.snapshot().receipt'),null);
 const ground=eligible.find(l=>l.kind==='ground');assert.ok(ground);await f.get('ground-node-diagram').dispatch('click',{target:{closest:()=>({getAttribute:key=>key==='data-diagram-link'?ground.id:null})}});const button=f.doc.getElementById('ground-node-detail-rf-draft');assert.ok(button,'selected native ground geometry has explicit RF draft');await f.get('ground-node-diagram-detail').dispatch('click',{target:button});for(const [key,value]of Object.entries(sourceLinkRfDraft(ground)))assert.equal(f.get('rf-'+key.replaceAll('_','-')).value,value,key);assert.equal(rfCalls,0);assert.equal(f.evaluate('fabric.snapshot().receipt'),null);assert.equal(f.get('ground-node-fabric-route').disabled,true);assert.equal(f.viewers.length,1);
 }finally{await f.win.dispatch('pagehide',{persisted:false});f.dispose();}
});
