"""ICD-08 contract for SIM security observations, not cryptographic verification."""
from typing import Protocol


from foundation.security_errors import SecurityUnavailable


class SecurityLink(Protocol):
    def observe(self, message: dict) -> dict: ...
    def overview(self) -> dict: ...
    def events(self, after: int = 0) -> dict: ...
    def status(self) -> dict: ...
