import {createUtcCodec,LEAP_SHA256} from './orbit_utc.js';
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;};
const condition=value=>value?JSON.stringify([value.group,value.query,value.orbit]):null;
/** Joins existing source callbacks to the existing full-scene owner; never advances time. */
export function createCatalogueSceneTimeBinding({scene,readSource,codec=createUtcCodec(LEAP_SHA256)}={}){
 if(!scene||typeof readSource!=='function')throw new TypeError('existing catalogue scene and time source required');
 let active=false,dead=false,terminal=false,depth=0,observationDepth=0,epoch=0,scope=null,accepted=null,mutating=0,unbound=null,presentationCache=null;
 const presentations=new WeakMap(),controls=new WeakMap();
 const bound=ticket=>!dead&&active&&!depth&&ticket===epoch;
 function own(work){mutating++;try{return work();}finally{mutating--;}}
 function revoke(clear=true){epoch++;scope=null;accepted=null;unbound=null;presentationCache=null;if(clear&&!dead)own(()=>scene.clear());}
 function read(){const ticket=epoch;let s;try{s=readSource();if(!bound(ticket)||!s||!['sim','stored','catalog','catalogue_live'].includes(s.kind)||typeof s.identity!=='string'||!s.identity||typeof s.running!=='boolean'||s.context?.leap_sha256!==LEAP_SHA256||!s.context.key?.startsWith(s.kind==='sim'?'sim:':s.kind+':')||codec.advance(s.context.utc,0)!==s.context.utc)return null;return {...s,context:structuredClone(s.context),conditions:condition(scene.snapshot().context)};}catch{return null;}}
 function same(a,b){return !!a&&!!b&&a.kind===b.kind&&a.identity===b.identity&&a.running===b.running&&a.context.key===b.context.key&&a.context.leap_sha256===b.context.leap_sha256&&a.context.eop_sha256===b.context.eop_sha256&&a.conditions===b.conditions;}
 function current(ticket=epoch){if(!bound(ticket)||!scope)return null;const source=read();if(!bound(ticket)||!same(scope,source)){if(bound(ticket))revoke();return null;}const state=scene.snapshot();if(state.error){terminal=true;revoke(false);return null;}if(!state.enabled||!bound(ticket))return null;return source;}
 async function start(draft){const ticket=epoch,source=read();if(!bound(ticket))return;scope=source;accepted=null;const utc=source?.context.utc??draft;if(source){const again=read();if(!bound(ticket)||!same(source,again)){revoke();return;}}await own(()=>scene.load(utc));if(!bound(ticket))return;if(scene.snapshot().error){terminal=true;revoke(false);}}
 function observe(){if(!active||dead||depth||observationDepth||terminal||mutating)return;const ticket=epoch,source=read();if(!bound(ticket))return;const state=scene.snapshot();if(state.error){terminal=true;revoke(false);return;}if(!source){if(scope)revoke();return;}if(!scope||!same(scope,source)){revoke();if(active&&!dead&&!depth&&!terminal)void start(source.context.utc);return;}const again=read();if(!bound(ticket)||!same(source,again)){if(bound(ticket))revoke();return;}scene.observe(source.context.utc);}
 function proofCurrent(value,map){const p=map.get(value);if(!p)return null;const reject=()=>{map.delete(value);return null;};const source=current(p.epoch);if(!source||p.scope!==scope||p.snapshot!==accepted)return reject();const result=scene.snapshot().result;if(!result||result.utc!==p.snapshot.utc||result.client_request_id!==p.snapshot.client_request_id||result.scene_sha256!==p.snapshot.scene_sha256)return reject();const delta=codec.difference(source.context.utc,p.snapshot.utc);if(!Number.isFinite(delta)||delta<0||!source.running&&delta!==0)return reject();return bound(p.epoch)&&p.scope===scope&&p.snapshot===accepted?source:reject();}
 return Object.freeze({
  async enable(draft){if(dead)return;active=true;terminal=false;revoke();return start(draft);},
  disable(){if(dead)return;active=false;terminal=false;revoke();},observe,
  beginControl(kind){if(dead)return()=>{};if(kind&&!depth&&scope?.kind!==kind&&read()?.kind!==kind){observationDepth++;let released=false;return()=>{if(released)return;released=true;observationDepth=Math.max(0,observationDepth-1);observe();};}if(active&&scene.snapshot().error)terminal=true;depth++;revoke();let released=false;return()=>{if(released)return;released=true;depth=Math.max(0,depth-1);if(!dead&&!depth)observe();};},
  accept(value){accepted=null;unbound=null;presentationCache=null;if(!value)return false;
   const entry=epoch;if(bound(entry)&&!scope){const absent=read(),result=scene.snapshot().result;if(!absent&&bound(entry)&&result&&value.utc===result.utc&&value.client_request_id===result.client_request_id&&value.scene_sha256===result.scene_sha256&&condition(value)===condition(scene.snapshot().context)&&!read()&&bound(entry)){unbound={snapshot:freeze(value),epoch:entry,conditions:condition(value)};return true;}return false;}const ticket=epoch,source=current(ticket),result=scene.snapshot().result;if(!source||!result||value.utc!==result.utc||value.client_request_id!==result.client_request_id||value.scene_sha256!==result.scene_sha256||condition(value)!==source.conditions)return false;const delta=codec.difference(source.context.utc,value.utc);if(!Number.isFinite(delta)||delta<0||!source.running&&delta!==0)return false;const again=current(ticket);if(!again||!same(source,again)||!bound(ticket))return false;accepted=freeze(value);return true;},
  presentation(){const ticket=epoch,source=current(ticket);if(!source||!accepted)return null;if(presentationCache&&presentationCache.snapshot===accepted&&presentationCache.display_utc===source.context.utc&&proofCurrent(presentationCache,presentations))return presentationCache;const value=Object.freeze({presentation_kind:'CATALOGUE_SCENE_TIME_UI_V1',snapshot:accepted,analysis_utc:accepted.utc,display_utc:source.context.utc,source_kind:source.kind,source_key:source.context.key,running:source.running});presentations.set(value,{epoch:ticket,scope,snapshot:accepted});if(!proofCurrent(value,presentations))return null;presentationCache=value;return value;},
  verifyPresentation(value,{utc}={}){try{const source=proofCurrent(value,presentations);if(!source)return false;if(utc!==undefined&&(codec.advance(utc,0)!==utc||codec.difference(utc,value.analysis_utc)<0||!source.running&&utc!==value.analysis_utc)){presentations.delete(value);return false;}const final=proofCurrent(value,presentations);return !!final&&bound(presentations.get(value)?.epoch);}catch{presentations.delete(value);return false;}},
  verifyUnboundSnapshot(value){const p=unbound;if(!p||p.snapshot!==value||!bound(p.epoch))return false;const reject=()=>{if(unbound===p)unbound=null;return false;};try{if(read()||!bound(p.epoch))return reject();const state=scene.snapshot();if(state.error||!state.enabled||condition(state.context)!==p.conditions||state.result?.client_request_id!==value.client_request_id||state.result?.utc!==value.utc||state.result?.scene_sha256!==value.scene_sha256)return reject();return !read()&&bound(p.epoch)&&unbound===p||reject();}catch{return reject();}},
  resolveSource(context){if(!context?.key?.startsWith('scene:'))return null;const ticket=epoch,source=current(ticket);if(!source||!accepted||context.key!==`scene:${accepted.scene_sha256}`||context.utc!==accepted.utc||context.leap_sha256!==accepted.leap_sha256)return null;const value=freeze({kind:source.kind,context:structuredClone(source.context)});controls.set(value,{epoch:ticket,scope,snapshot:accepted});return proofCurrent(value,controls)?value:null;},
  verifySource(value,{context}={}){const p=controls.get(value);if(!p)return false;const source=proofCurrent(value,controls);if(!source||context?.key!==`scene:${p.snapshot.scene_sha256}`||context.utc!==p.snapshot.utc||context.leap_sha256!==p.snapshot.leap_sha256){controls.delete(value);return false;}return !!proofCurrent(value,controls)&&bound(p.epoch);},
  destroy(){if(dead)return;active=false;revoke();dead=true;},
 });
}
