// Operator-facing wording only; never use this to encode commands or records.
const labels={"공용 상황판": "통합 관제 현황", "정상 임무 흐름": "정상 운용 절차", "초기 운용 흐름": "발사 초기 운용", "장애·복구 흐름": "이상 대응 및 복구", "임무·결과": "임무계획 및 결과", "지상 운용": "운용 판단 및 인계", "위성 상태·궤도": "위성 상태 및 궤도", "지상국·통신": "지상국 및 통신", "데이터·산출물": "임무 데이터 관리", "보안·사고": "보안 및 명령 권한", "지상 IT·시설": "지상 시스템 관리", "EM·통합검증": "장비 연동 시험", "모듈 연결 설정과 ICD": "시스템 연동 설정", "장면 구성": "시험 환경 구성", "시나리오 작성": "시험 시나리오 작성", "실행·기록 설계": "모의실험 실행 및 기록", "비교·검증": "시험 결과 평가", "PoC 시나리오": "운용 시나리오 시험", "실행 제어·기준 SIM": "모의실험 제어", "서버 최근 사건 (SIM)": "모의실험 이벤트 기록", "저장 궤도 입력·실제 계산": "궤도 자료 및 전파 계산", "편대 배치": "위성군 구성", "선택 위성 3D 모델": "위성 형상 모델", "위성 카탈로그·기준 조회": "위성 목록 조회", "공용 노드 정의 확인·초안과 수락 배치": "위성 구성 및 적용 상태", "검토한 구성 세팅": "검토한 구성 적용", "정의 목록 조회": "시나리오 목록 조회", "선택 정의 불러오기": "선택 시나리오 불러오기", "시나리오 재생기 해제": "시나리오 재생 종료", "SIM 전진": "시간 진행", "VF-03 결과 JSON 저장": "시험 결과 파일 저장", "서버 새로고침": "상태 새로고침", "한 스텝": "한 단계 진행", "노드 통신망과 지상국 편집": "위성 통신망 및 지상국 구성"};
const terms={"link_loss":"통신 두절","power_drop":"전력 저하","thermal_spike":"온도 급상승","storage_pressure":"저장 공간 부족","latency_spike":"통신 지연 증가","low":"낮음","medium":"보통","high":"높음","preparing":"준비 중","ready":"준비 완료","playing":"재생 중","paused":"일시정지","finished":"종료","stale":"갱신 필요","pause":"일시정지","start":"시작","sequence":"수신 순번","temperature":"온도","attitude_error":"자세 오차","runtime.pause": "재생 일시정지", "runtime.start": "재생 시작", "runtime.speed.changed": "재생 속도 변경", "fault.cleared": "장애 해제", "fault.injected": "장애 모사", "idle": "대기", "running":"수행 중", "planned":"계획됨", "done":"완료", "blocked":"진행 불가", "BLOCKED": "진행 불가", "PASS": "통과", "FAIL": "실패", "INVALID": "판정 불가", "ONLINE": "연결됨", "OFFLINE": "연결 끊김", "LOCKED": "시각 동기화됨", "LOCKING": "시각 동기화 중", "unavailable": "자료 없음", "MOCK-HIL": "모의 장비 시험", "SIM": "모의실험", "ICD": "인터페이스 명세", "ACK": "명령 수신 확인", "EM": "시험용 장비"};
export function presentOperatorText(value){
 let text=String(value).replace(/(?:error )?UTC outside EOP snapshot range/g,'계산 시각이 지구 자전 보정자료의 유효기간을 벗어났습니다. 입력 기준 시각으로 복귀하거나 최신 위성 목록 자료를 사용하세요.');
 const protectedLabels=[...new Set(Object.values(labels))].sort((a,b)=>b.length-a.length);
 for(const [index,label] of protectedLabels.entries())text=text.split(label).join(`\uE000${index}\uE001`);
 for(const [before,after] of Object.entries(labels).sort((a,b)=>b[0].length-a[0].length))text=text.split(before).join(after);
 for(const [before,after] of Object.entries(terms)){const escaped=before.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');text=text.replace(new RegExp('(?<![A-Za-z0-9_.-])'+escaped+'(?![A-Za-z0-9_.-])','g'),after);}
 for(const [index,label] of protectedLabels.entries())text=text.split(`\uE000${index}\uE001`).join(label);
 return text;
}
