const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createCatalogTimePanel(timeline,sites){
 let active=false,panel=null,message='',draft={station:'',height:'0',angle:'5',utc:''},utcDirty=false,sourceKey=null;
 const get=id=>panel?.querySelector('#cat-time-'+id);
 function point(){const site=sites[draft.station],height=Number(draft.height),angle=Number(draft.angle);if(!site||!draft.height.trim()||!draft.angle.trim()||!Number.isFinite(height)||!Number.isFinite(angle))throw Error('관측 지상국·타원체 높이·최소각을 확인하세요.');const p={latitude_deg:site.latitude,longitude_deg:site.longitude,ellipsoid_height_m:height,virtual:true,ellipsoid:'WGS84'};if(!timeline.observer(p,angle))throw Error('관측 지점·최소각 범위 오류');}
 function draw(){
  if(!active)return;const s=timeline.snapshot();
  if(!panel?.isConnected){panel=document.createElement('section');panel.id='catalog-time';panel.className='panel';document.getElementById('screen').prepend(panel);panel.innerHTML=`<header><h2>카탈로그 시간 탐색 · 지상국 관측</h2></header><div class="body"><p>카탈로그 표시 위성을 계산합니다. 저장 궤도 입력·UTC·SIM은 변경하지 않습니다. 지상국 좌표·최소각은 대표 가정이며 높이는 사용자가 입력하는 WGS84 타원체 높이 가정입니다. 실제 시설 높이는 미확인입니다. 실제 통신 미확인.</p><label>관측 지상국 <select id="cat-time-station"><option value="">지상국 선택</option>${Object.values(sites).map(x=>`<option value="${esc(x.key)}">${esc(x.name)}</option>`).join('')}</select></label><label>가정 타원체 높이 m <input id="cat-time-height" type="number" step="any"></label><label>최소 고도각 ° <input id="cat-time-angle" type="number" min="0" max="90" step="any"></label><label>계산 UTC <input id="cat-time-utc" type="text"></label><button id="cat-time-epoch" class="button">GP epoch 초안</button> <button id="cat-time-calculate" class="button">UTC·관측 조건 적용 후 계산</button><div><button id="cat-time-play" class="button">카탈로그 재생</button> <button id="cat-time-pause" class="button">카탈로그 정지</button><label>배속 <select id="cat-time-rate">${[.1,1,10,60].map(x=>`<option value="${x}">${x}×</option>`).join('')}</select></label></div><p id="cat-time-status" role="status"></p><div id="cat-time-result"></div></div>`;
   get('station').addEventListener('change',e=>stage(sites[e.target.value]));
   for(const key of ['height','angle','utc'])get(key).addEventListener('input',e=>{draft[key]=e.target.value;if(key==='utc')utcDirty=true;timeline.invalidate();message='입력 변경됨 · 명시적으로 계산하세요.';draw();});
   get('epoch').addEventListener('click',()=>{draft.utc=timeline.snapshot().selected?.epoch_utc??'';utcDirty=true;timeline.invalidate();draw();});
   get('calculate').addEventListener('click',async()=>{try{message='';point();timeline.seek(draft.utc);utcDirty=false;await timeline.calculate();}catch(e){message=e.message;}draw();});
   get('play').addEventListener('click',()=>timeline.play());get('pause').addEventListener('click',()=>timeline.pause());get('rate').addEventListener('change',e=>timeline.rate(Number(e.target.value)));
  }
  const key=s.selected?.normalized_gp_sha256??null;if(key!==sourceKey){sourceKey=key;utcDirty=false;draft.utc=s.selected?.epoch_utc??'';}
  if(!utcDirty&&s.utc)draft.utc=s.utc;
  for(const key of ['station','height','angle','utc'])if(get(key).value!==draft[key])get(key).value=draft[key];get('rate').value=String(s.rate);
  get('calculate').disabled=!s.selected||s.pending;get('epoch').disabled=!s.selected;get('play').disabled=!s.buffer||s.playing;get('pause').disabled=!s.playing;
  get('status').textContent=s.pending?'카탈로그 Rust 표본 계산 중…':s.error||message||(!s.selected?'카탈로그 위성을 먼저 선택하세요.':s.playing?'카탈로그 표시 시계 재생 중':'관측 조건을 확인한 뒤 계산하세요.');
  const v=s.display;get('result').innerHTML=v?.observation_utc?`<p>표시 UTC ${esc(v.utc)} · ${v.interpolated?'1초 위치·고도각 보간':'native 표본'}<br>관측 수치 UTC ${esc(v.observation_utc)} · 거리·방위각은 해당 native 표본값입니다.</p><dl><dt>거리 km</dt><dd>${(v.range_m/1000).toFixed(6)}</dd><dt>고도각 ° · 관측 표본</dt><dd>${v.observed_elevation_deg.toFixed(6)}</dd><dt>방위각 ° · 북쪽 기준 시계 방향</dt><dd>${v.azimuth_deg===null?'천정에서 방위각 미정':v.azimuth_deg.toFixed(6)}</dd></dl><p>${v.visible?'최소 고도각 충족':'최소 고도각 미충족'} · 기하학적 조건 / 실제 통신 미확인</p><p>GP epoch ${esc(v.epoch_utc)} · ${esc(v.source)} · ${esc(v.eop_quality.ut1)} / ${esc(v.eop_quality.polar_motion)}</p>`:s.selected?'<p>현재 UTC 관측 표본 없음 · 자료 밖이나 실패 구간에서는 위치를 표시하지 않습니다.</p>':'';
 }
 function stage(site){if(!site){draft.station='';timeline.invalidate();draw();return false;}draft.station=site.key;draft.angle=String(site.minElevationDeg);message='대표 좌표·최소각 초안 · 원본 높이는 기준면 미확인으로 복사하지 않습니다.';try{point();}catch(e){message=e.message;}draw();return true;}
 return{stage,show(view){active=view==='satellite';draw();},update:draw,applyDraft(items){let changed=false;for(const item of items){const key=item.id?.replace('cat-time-','');if(['station','height','angle','utc'].includes(key)&&typeof item.value==='string'){draft[key]=item.value;changed=true;if(key==='utc')utcDirty=true;}}if(changed){timeline.invalidate();message='다른 창에서 전달된 초안 · 적용 전';draw();}},destroy(){active=false;}};
}
