// Fixed Korean peninsula viewport, using six normal browser-cached OSM raster tiles.
// Coordinates and station configuration come from the existing ground segment owner.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=64, left=54, top=23, columns=2, rows=3;
export function koreaPoint({latitude,longitude}={}){if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>=85.05112878||Math.abs(longitude)>180)return null;const lat=latitude*Math.PI/180;const x=((longitude+180)/360*size-left)/columns,y=((1-Math.asinh(Math.tan(lat))/Math.PI)/2*size-top)/rows;return x>=0&&x<=1&&y>=0&&y<=1?{x,y}:null;}
export function koreaCoordinate(x,y){if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||x>1||y<0||y>1)return null;return {longitude:(left+x*columns)/size*360-180,latitude:Math.atan(Math.sinh(Math.PI*(1-2*(top+y*rows)/size)))*180/Math.PI};}
export function stationMapMarkup(stations,selectedId,draft=null){const marker=(s,candidate=false)=>{const xy=koreaPoint(s);if(!xy)return '';return `<button type="button" class="gs-map-pin ${candidate?'candidate':s.enabled?'configured':'disabled'} ${s.id===selectedId?'selected':''}" ${candidate?'disabled':`data-map-station="${esc(s.id)}"`} style="left:${xy.x*100}%;top:${xy.y*100}%" aria-label="${esc(candidate?'새 지상국 후보':s.name+' 상태 보기')}"><span aria-hidden="true">${candidate?'+':'●'}</span><b>${esc(candidate?'새 지상국 후보':s.name)}</b></button>`;};return stations.map(s=>marker(s)).join('')+(draft?marker(draft,true):'');}
export function stationMapBaseMarkup(){let tiles='';for(let row=0;row<rows;row++)for(let col=0;col<columns;col++)tiles+=`<img id="ground-node-map-tile-${row*columns+col}" src="https://tile.openstreetmap.org/6/${left+col}/${top+row}.png" alt="" draggable="false" style="left:${col*50}%;top:${row/3*100}%">`;return `<div class="gs-map-topline"><strong>한반도 지상국</strong><span>지점을 선택하거나 새 위치를 지정하세요</span></div><div id="ground-node-map" class="gs-map-frame" aria-label="한반도 지상국 위치 선택 지도">${tiles}<div id="ground-node-map-markers" class="gs-map-markers"></div><a class="gs-map-credit" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a></div>`;}
export function stationStatusMarkup(s){if(!s)return '<div class="gs-station-empty">지도 또는 목록에서 지상국을 선택하세요.</div>';return `<div class="gs-station-heading"><h3>${esc(s.name)}</h3><span class="overview-badge">${s.enabled?'통신망 사용':'사용 안 함'}</span></div><div class="gs-station-metrics"><div><span>위도</span><b>${Number(s.latitude).toFixed(4)}°</b></div><div><span>경도</span><b>${Number(s.longitude).toFixed(4)}°</b></div><div><span>안테나</span><b>${esc(s.dish_m)} m</b></div><div><span>최소 고각</span><b>${esc(s.min_elevation_deg)}°</b></div></div><div class="gs-station-status"><span>실제 연결</span><b>미확인</b><span>지원 대역</span><b>${esc((s.bands??[]).join(' / '))}</b></div>`;}
