import {createUtcCodec} from '../orbit_utc.js';
import {validateRadioResponse} from './orbit_radio.js?v=t048-r3';
import {createRfReceiveProfile,profileMarkup} from './rf_receive_profile.js?v=t039-r1';
import {seriesMarkup} from '/static/visualization/orbit_radio_series.js?v=t053-r2';
const context=s=>JSON.stringify(s&&[s.revision,s.input_id,s.input_hash,s.ground_point,s.minimum_elevation_deg,s.eop_sha256,s.leap_sha256,s.frame,s.profile]);
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createRadioSeries(client,api,notify=()=>{},requestId=()=>crypto.randomUUID()){
 let interval=null,frequency='',result=null,status='idle',error='',generation=0,abort=null,destroyed=false,key=context(client.snapshot().state);
 const snapshot=()=>structuredClone({interval,frequency,result,status,error});
 function cancel(){generation++;abort?.abort();abort=null;result=null;status='idle';error='';}
 function update(){const current=client.snapshot();if(context(current.state)!==key||current.status!=='ready'){key=context(current.state);cancel();interval=null;}}
 function choose(source,index){if(destroyed)return;update();cancel();interval=null;try{const s=client.snapshot().state,row=source?.intervals?.[index],codec=createUtcCodec(s.leap_sha256);if(!s?.input_id||source?.stale!==false||!['complete','partial'].includes(source.status)||context(source)!==context(s)||source.communication_status!=='unknown'||!row||typeof row.start_clipped!=='boolean'||typeof row.end_clipped!=='boolean'||codec.difference(row.end_utc,row.start_utc)<=0||codec.difference(row.end_utc,row.start_utc)>86400)throw Error('현재 선택과 일치하는 유효 가시 구간을 선택하세요.');interval=structuredClone(row);interval.start_utc=codec.advance(row.start_utc,0);interval.end_utc=codec.advance(row.end_utc,0);}catch(exc){status='error';error=exc.message;}notify();}
 async function calculate(){if(destroyed)return;update();cancel();const ticket=generation;try{const selected=client.snapshot(),s=selected.state;if(!interval||selected.status!=='ready')throw Error('지상국 창에서 가시 구간을 계산하고 하나를 선택하세요.');const f=Number(frequency.trim());if(!frequency.trim()||!Number.isFinite(f)||f<=0||f>300000)throw Error('송신 주파수 MHz는 0 초과, 300000 이하이어야 합니다.');const p={client_request_id:requestId(),selection_revision:s.revision,input_id:s.input_id,start_utc:interval.start_utc,end_utc:interval.end_utc,frequency_hz:f*1e6};abort=new AbortController();status='pending';notify();const r=await api.orbitRadioSeries(p,{signal:abort.signal});if(destroyed||ticket!==generation)return;update();if(ticket!==generation)return;
 const codec=createUtcCodec(s.leap_sha256),duration=codec.difference(p.end_utc,p.start_utc),count=Math.min(601,Math.ceil(Math.round(duration*1e9)/1e9)+1),step=duration/(count-1);
 if(!r||context(r)!==context(s)||r.client_request_id!==p.client_request_id||r.frequency_hz!==p.frequency_hz||r.stale!==false||r.start_utc!==p.start_utc||r.end_utc!==p.end_utc||Math.abs(r.duration_seconds-duration)>1e-8||Math.abs(r.step_seconds-step)>1e-8||!Number.isFinite(r.duration_seconds)||!Number.isFinite(r.step_seconds)||!Array.isArray(r.rows)||r.rows.length!==count||!['complete','partial','error'].includes(r.status))throw Error('구간·표본 간격·응답 계약이 일치하지 않습니다.');
 let failures=0;for(let i=0;i<count;i++){const row=r.rows[i];if(!row||typeof row.utc!=='string'||Math.abs(codec.difference(row.utc,p.start_utc)-i*step)>1e-8||i===0&&row.utc!==p.start_utc||i===count-1&&row.utc!==p.end_utc)throw Error('UTC 표본 순서가 일치하지 않습니다.');try{validateRadioResponse({...r,...row},{...p,utc:row.utc},s);}catch(exc){if(row.status!=='error'||row.error_code===null||!exc.message.startsWith('궤도 계산 실패:'))throw exc;}if(row.error_code!==null)failures++;}
 if(r.status!==(failures===count?'error':failures?'partial':'complete'))throw Error('실패 표본과 결과 상태가 일치하지 않습니다.');result=structuredClone(r);status='ready';
 }catch(exc){if(destroyed||ticket!==generation)return;result=null;status=exc.name==='AbortError'?'idle':'error';error=status==='error'?exc.message:'';}if(!destroyed&&ticket===generation){abort=null;notify();}}
 return {snapshot,choose,calculate,update,setFrequency(value,remote=false){if(destroyed)return;if(typeof value==='string'&&(remote||value!==frequency)){frequency=value;cancel();notify();}},cancel(){if(!destroyed){cancel();notify();}},clearInterval(){if(!destroyed){cancel();interval=null;notify();}},destroy(){cancel();interval=null;destroyed=true;}};
}
export function createRadioSeriesPanel(client,api){
 let active=false,panel=null;
 const controller=createRadioSeries(client,api,render);
 const profile=createRfReceiveProfile(api,render,()=>{controller.setFrequency(String(profile.snapshot().profile.frequency_mhz));write();},()=>controller.cancel());
 const get=id=>panel?.querySelector('#series-'+id);
 function write(){if(get('frequency')&&get('frequency').value!==controller.snapshot().frequency)get('frequency').value=controller.snapshot().frequency;}
 function render(){controller.update();if(!active)return;if(!panel?.isConnected){panel=document.createElement('section');panel.id='orbit-radio-series';panel.className='panel';document.getElementById('screen').prepend(panel);panel.innerHTML=`<header><h2>가시 구간 거리·도플러 변화</h2><small>저장 궤도 모델 / 실제 수신 미확인</small></header><div class="body"><p>지상국 창에서 가시 구간을 조회한 뒤 구간의 선택 버튼을 누르세요. 주파수를 입력하고 명시적으로 계산합니다.</p><p id="series-interval"></p><label>구간 송신 주파수 MHz<input id="series-frequency" type="number" step="any"></label><button id="series-profile-load" type="button">구간용 ISS 공식 주파수 불러오기</button><button id="series-profile-apply" type="button">구간 입력에 공식 주파수 적용</button><div id="series-profile"></div><p id="series-origin"></p><button id="series-calculate" type="button">구간 거리·도플러 계산</button><button id="series-cancel" type="button">구간 계산 취소</button><p id="series-status" role="status" aria-live="polite"></p><div id="series-result"></div></div>`;get('frequency').addEventListener('input',e=>{controller.setFrequency(e.target.value);profile.manualFrequency();});get('profile-load').addEventListener('click',()=>profile.load());get('profile-apply').addEventListener('click',()=>profile.apply());get('calculate').addEventListener('click',()=>controller.calculate());get('cancel').addEventListener('click',()=>controller.cancel());}
 const s=controller.snapshot(),p=profile.snapshot();write();get('interval').textContent=s.interval?`선택 UTC ${s.interval.start_utc} → ${s.interval.end_utc}`:'선택한 가시 구간 없음';get('status').textContent=`${{idle:'구간과 주파수를 확인하세요.',pending:'구간 모델 계산 중',ready:'구간 모델 계산 완료',error:'구간 계산 실패'}[s.status]} ${s.error}`;get('calculate').disabled=!s.interval||s.status==='pending';get('profile-apply').disabled=p.status!=='ready';get('origin').textContent=!s.frequency?'주파수 미확인':p.applied&&Number(s.frequency)===p.profile.frequency_mhz?'공식 공지 주파수 · 저장 GP 시점의 운용 여부 미확인':'직접 입력·다른 창 전달 주파수: 사용자 가정';const html=seriesMarkup(s.result,s.interval);if(get('result').innerHTML!==html)get('result').innerHTML=html;const ph=profileMarkup(p);if(get('profile').innerHTML!==ph)get('profile').innerHTML=ph;
 }
 return {choose(source,index){controller.choose(source,index);},clearInterval(){controller.clearInterval();},update:render,show(view){active=['ground','satellite'].includes(view);render();},applyDraft(items,remote=false){for(const item of items)if(item.id==='series-frequency'&&typeof item.value==='string'){controller.setFrequency(item.value,remote);if(remote)profile.manualFrequency();}write();},destroy(){controller.destroy();profile.destroy();}};
}
