import {createScenarioDraftStore,SCENARIO_STEP_KINDS,SCENARIO_FAULT_TYPES,validateScenarioDraft} from '../scenario/authoring.js?v=u028';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createScenarioAuthoringPanel({document,host,storage,readStations=()=>[]}={}){
 let root=null,view=null,dead=false,store,error='',draft,steps=[],removers=[];
 const fresh=()=>({name:'',objective:'',constellation:{planes:1,per_plane:4,altitude_km:550,inclination_deg:53},stations:[],steps:[]});draft=fresh();
 try{store=createScenarioDraftStore(storage);}catch(e){error=e.message;}
 const get=id=>root?.querySelector('#sa-'+id);
 const listen=(id,type,fn)=>{const el=get(id);el.addEventListener(type,fn);removers.push(()=>el.removeEventListener(type,fn));};
 function read(){draft={...draft,name:get('name').value,objective:get('objective').value,constellation:Object.fromEntries(['planes','per_plane','altitude_km','inclination_deg'].map(k=>[k,get(k).value.trim()===''?NaN:Number(get(k).value)])),steps:structuredClone(steps)};return structuredClone(draft);}
 function fields(){get('name').value=draft.name;get('objective').value=draft.objective;for(const [k,v]of Object.entries(draft.constellation))get(k).value=String(v);}
 function status(message){get('status').textContent=message;}
 function paint(){if(!root)return;const items=store?.list()??[];get('choice').innerHTML='<option value="">저장한 시나리오 선택</option>'+items.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');get('choice').value=draft.id??'';get('steps').innerHTML=steps.length?'<ol class="sa-step-list">'+steps.map((s,i)=>`<li><strong>T+${esc(s.at_s)}초</strong><div><b>${esc(s.title)}</b><small>${esc(SCENARIO_STEP_KINDS[s.kind])+(s.fault_type?' / '+esc(SCENARIO_FAULT_TYPES[s.fault_type]):'')}${s.target?' / '+esc(s.target):''}${s.kind==='fault'?' / '+esc(s.duration_s)+'초':''}</small>${s.details?'<small>주입 조건: '+esc(s.details)+'</small>':''}${s.expected?'<small>확인할 결과: '+esc(s.expected)+'</small>':''}</div><button type="button" data-sa-remove="${i}" aria-label="${esc(s.title)} 단계 삭제">삭제</button></li>`).join('')+'</ol>':'<p>시험 단계를 추가하세요.</p>';get('stations').innerHTML=draft.stations.length?draft.stations.map(s=>`<span class="overview-badge">${esc(s.name)}</span>`).join(' '):'<span>지상국 구성 미지정</span>';get('count').textContent=String(draft.constellation.planes*draft.constellation.per_plane)+'기 / '+steps.length+'단계';}
 function attempt(fn){try{fn();}catch(e){status(e.message);}}
 function mount(){root=document.createElement('section');root.id='scenario-authoring';root.className='panel';root.innerHTML=`<header><h2>내 시험 시나리오 작성</h2><span id="sa-count" class="overview-badge"></span></header><div class="body"><div class="sa-toolbar"><button id="sa-new" type="button">빈 시나리오 만들기</button><select id="sa-choice" aria-label="내가 저장한 시나리오"></select><button id="sa-load" type="button">저장한 시나리오 편집</button></div><div class="sa-layout"><section><h3>1. 시험 목적과 구성</h3><label>시나리오 이름<input id="sa-name" maxlength="80" placeholder="예: 한반도 지상국 링크 장애 시험"></label><label>시험 목적<textarea id="sa-objective" maxlength="2000" rows="3" placeholder="어떤 상황에서 무엇을 확인할지 작성하세요"></textarea></label><div class="sa-fields"><label>궤도면 수<input id="sa-planes" type="number" min="1" max="240"></label><label>면당 위성 수<input id="sa-per_plane" type="number" min="1" max="240"></label><label>궤도 고도 km<input id="sa-altitude_km" type="number" min="100" max="50000"></label><label>궤도 경사각 °<input id="sa-inclination_deg" type="number" min="0" max="180"></label></div><h4>지상국 구성</h4><div id="sa-stations"></div><button id="sa-stations-use" type="button">현재 사용 지상국 구성 가져오기</button></section><section><h3>2. 시험 단계 작성</h3><div class="sa-fields"><label>시작 시각 T+초<input id="sa-at" type="number" min="0" max="86400" value="0"></label><label>시험 동작<select id="sa-kind">${Object.entries(SCENARIO_STEP_KINDS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label></div><label>단계 이름<input id="sa-title" maxlength="160" placeholder="예: 정상 상태 측정"></label><div id="sa-fault-fields" hidden><label>장애 종류<select id="sa-fault-type">${Object.entries(SCENARIO_FAULT_TYPES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>장애 대상<input id="sa-target" maxlength="160" placeholder="노드 또는 링크 식별자"></label><label>장애 지속 초<input id="sa-duration" type="number" min="1" max="86400" value="60"></label><label>주입 조건<textarea id="sa-fault-detail" maxlength="1000" rows="2" placeholder="예: 주 링크 단절, 대체 경로는 유지"></textarea></label></div><label>확인할 결과<textarea id="sa-expected" maxlength="1000" rows="2" placeholder="예: 장애 발생 후 10초 내 대체 경로 확보"></textarea></label><button id="sa-step-add" type="button">단계 추가</button><div id="sa-steps"></div></section></div><div class="sa-toolbar"><button id="sa-save" type="button">내 시나리오 저장</button><button id="sa-export" type="button">시나리오 JSON 내보내기</button><span>작성 내용과 서버 저장 상태를 확인하세요.</span></div><p id="sa-status" role="status"></p><details><summary>작성 시나리오와 실행의 연결</summary><p>이 화면은 시험 목적, 구성과 사건 순서를 작성하고 저장합니다. 직접 작성한 정의를 자동 실행기에 연결하는 기능은 아직 없습니다. 아래 예제 실행 기능은 기존 PoC 정의를 사용합니다.</p></details></div>`;document.getElementById('screen').prepend(root);fields();paint();status(error);
 for(const id of ['name','objective','planes','per_plane','altitude_km','inclination_deg'])listen(id,'input',()=>{read();get('count').textContent=String(draft.constellation.planes*draft.constellation.per_plane)+'기 / '+steps.length+'단계';});
 listen('new','click',()=>{read();if((draft.name||steps.length)&&!host.confirm('현재 작성 내용을 비우고 새 시나리오를 만들까요? 저장한 시나리오는 유지됩니다.'))return;draft=fresh();steps=[];fields();paint();status('빈 시나리오를 작성하세요.');});
 listen('load','click',()=>attempt(()=>{const found=store?.list().find(d=>d.id===get('choice').value);if(!found)throw Error('저장한 시나리오를 선택하세요.');read();if((draft.name||steps.length)&&draft.id!==found.id&&!host.confirm('저장하지 않은 작성 내용을 바꾸고 선택한 시나리오를 열까요?'))return;draft=found;steps=structuredClone(found.steps);fields();paint();status('저장한 시나리오를 편집 중입니다.');}));
 listen('stations-use','click',()=>attempt(()=>{draft.stations=structuredClone(readStations()).filter(s=>s.enabled);paint();status('현재 사용 지상국 구성을 작성 내용에 가져왔습니다.');}));
 listen('kind','change',()=>{get('fault-fields').hidden=get('kind').value!=='fault';});
 listen('step-add','click',()=>attempt(()=>{const step={at_s:get('at').value.trim()===''?NaN:Number(get('at').value),title:get('title').value,kind:get('kind').value,expected:get('expected').value};if(step.kind==='fault'){step.fault_type=get('fault-type').value;step.details=get('fault-detail').value;step.target=get('target').value;step.duration_s=get('duration').value.trim()===''?NaN:Number(get('duration').value);}const probe={name:'단계 검증',objective:'단계 검증',constellation:fresh().constellation,stations:[],steps:[step]};const problems=validateScenarioDraft(probe);if(problems.length)throw Error(problems.join(' '));if(steps.length>=128)throw Error('최대 128단계입니다.');steps.push(step);steps.sort((a,b)=>a.at_s-b.at_s);paint();status('시험 단계 추가됨');}));
 listen('steps','click',event=>{const b=event.target?.closest?.('[data-sa-remove]');if(!b)return;const i=Number(b.getAttribute('data-sa-remove'));if(!Number.isInteger(i)||i<0||i>=steps.length)return;steps.splice(i,1);paint();});
 listen('save','click',()=>attempt(()=>{if(!store)throw Error(error||'저장소를 사용할 수 없습니다.');draft=store.save(read());steps=structuredClone(draft.steps);paint();status((storage.snapshot?.().enabled?'로컬 반영, 서버 저장 상태 확인: ':'저장 완료: ')+draft.name);}));
 listen('export','click',()=>attempt(()=>{const value=read(),problems=validateScenarioDraft(value);if(problems.length)throw Error(problems.join(' '));if(!host.URL?.createObjectURL)throw Error('다운로드 연결을 사용할 수 없습니다.');const url=host.URL.createObjectURL(new (host.Blob??globalThis.Blob)([JSON.stringify({...value,schema:'isdc-test-scenario-draft/v1'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=(value.id??'test-scenario')+'.json';document.body.append(a);try{a.click();}finally{a.remove();host.setTimeout(()=>host.URL.revokeObjectURL(url),1000);}status('시나리오 JSON 내보내기');}));
 }
 return {reloadStorage(){try{store=createScenarioDraftStore(storage);error='';paint();}catch(e){error=e.message;if(root)status(error);}},show(next){if(dead)return;if(root?.isConnected)read();view=next;if(next!=='composer'){if(root)root.hidden=true;return;}if(!root||document.getElementById(root.id)!==root){for(const r of removers.splice(0))r();mount();}root.hidden=false;},destroy(){dead=true;for(const r of removers.splice(0))r();root?.remove();}};
}
