// V6 presentation over the reused source mission model/store/scheduler client and UTC timeline.
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LABELS={target:'관측 지점',target_name:'지점 이름',latitude:'위도 °',longitude:'경도 °',max_off_nadir_deg:'최대 비직하각 °',product_mb:'원본 데이터 MB',processing:'궤도상 처리',processing_ratio:'처리 결과 비율',preferred_satellite:'선호 위성',station:'지상국',source_satellite:'데이터 보유 위성',input_mb:'입력 데이터 MB',output_ratio:'출력 비율',source:'출발점',destination:'도착점',volume_mb:'데이터 MB',max_latency_ms:'지연 제한 ms (0: 제한 없음)',external_id:'외부 위성 카탈로그 번호',external_name:'외부 위성 이름',crosslink_rate_mbps:'가정 수신 속도 Mbps',max_range_km:'교차링크 거리 km',image_mb:'갱신 이미지 MB',apply_s:'위성당 적용 시간 s',max_concurrent:'동시 갱신 수',satellites:'대상 위성 ID (쉼표 구분)'};
const serviceViews=new Set(['mission']);
// Port of source mission.js allTasks/renderTimeline and planner affectedTasks.
// Display projection only; accepted module receipts remain with execution.
export function projectMissionSchedule({missions=[],context=null,inspection=null,model,selectedId=null,hours=12,rowFilter='busy'}={}){
 if(!model||![6,12,24].includes(hours))throw Error('source timeline hours must be 6, 12 or 24');
 const now=model.timeOf(context?.utc),current=Number.isFinite(now),historical=model.timeOf(inspection?.request?.time),anchor=current?now:Number.isFinite(historical)?historical:null;
 const tasks=[];for(const mission of missions){if(!mission.plan?.tasks||['draft','aborted'].includes(mission.status))continue;for(const task of mission.plan.tasks)tasks.push({...structuredClone(task),mission_id:mission.id,status:mission.status==='committed'?(current?model.taskStatusAt(task,now):'unknown'):'planned',feasible:mission.plan.feasible!==false});}
 const nodes=context?.nodes??inspection?.request?.satellites??[],windows=inspection?.request?.windows??{},accesses=structuredClone(windows.target_access??[]),busy=new Set([...tasks.map(t=>t.satellite),...accesses.map(w=>w.satellite)]);
 const rows=nodes.filter(n=>rowFilter==='all'||busy.has(n.id)).slice().sort((a,b)=>String(a.name??a.id).localeCompare(String(b.name??b.id),'en',{numeric:true})).map(n=>({id:n.id,label:n.name??n.id,note:n.mode&&n.mode!=='nominal'?n.mode:''}));
 const affected={satellites:[],links:[],tasks:[]},mission=missions.find(m=>m.id===selectedId);
 if(current&&mission?.status==='committed'&&mission.plan?.tasks){const deployed=new Map(nodes.map(n=>[n.id,n])),targets=new Set((context.faults??[]).filter(f=>f.kind==='link_loss'&&f.active!==false).map(f=>String(f.target))),satellites=new Set(),links=new Set();for(const task of mission.plan.tasks){if(model.taskStatusAt(task,now)==='done')continue;const node=deployed.get(task.satellite);let hit=false;if(!node||node.mode!=='nominal'){satellites.add(task.satellite);hit=true;}if(task.kind==='crosslink'&&task.counterpart&&targets.size){const other=deployed.get(task.counterpart),key=[task.satellite,task.counterpart].sort().join('|'),names=[key,task.satellite,task.counterpart,node?.name,other?.name].filter(v=>v!=null).map(String);if(names.some(n=>targets.has(n))){links.add(key);hit=true;}}if(hit)affected.tasks.push(task.id);}affected.satellites=[...satellites];affected.links=[...links];}
 return {current,now:current?now:null,start:anchor===null?null:anchor-30*60000,end:anchor===null?null:anchor-30*60000+hours*3600000,rows,tasks,contacts:structuredClone(windows.contacts??[]),eclipses:structuredClone(windows.eclipses??[]),accesses,deadlines:missions.filter(m=>m.plan||m.id===selectedId).map(m=>({ms:model.timeOf(m.deadline),label:m.name+' 기한',mission_id:m.id})).filter(d=>Number.isFinite(d.ms)),affected};
}
export function createSourceMissionPanel({services,model,layoutTimeline,timelineMarkup,document,host}={}){
 if(!services||!model||typeof layoutTimeline!=='function'||typeof timelineMarkup!=='function'||!document||!host)throw TypeError('source mission presentation owners required');
 let root=null,dead=false,view=null,error='',busy=false,external=false,dirty=false,editId=null,draft=null,abort=null,timelineHours=12,rowFilter='busy',selectedTaskId=null;const removers=[];
 const field=id=>root?.querySelector('#ms-'+id);
 const listen=(id,event,handler)=>{const e=field(id);e?.addEventListener(event,handler);removers.push(()=>e?.removeEventListener(event,handler));};
 const info=()=>{try{return services.context();}catch{return null;}};
 function capture(){if(!root)return;draft={name:field('name').value,kind:field('kind').value,priority:field('priority').value,start:field('start').value,deadline:field('deadline').value,params:Object.fromEntries(Object.keys(model.DEFAULT_PARAMS[field('kind').value]??{}).map(k=>{const f=field('param-'+k);return [k,{value:f?.value??'',checked:!!f?.checked}];}))};}
 function parameters(params={}){
  const kind=field('kind').value,defaults=model.DEFAULT_PARAMS[kind],options=services.editorOptions();if(!defaults)return;
  field('params').innerHTML=Object.entries(defaults).map(([key,value])=>{const v=Object.hasOwn(params,key)?params[key]:value;const name=escape(LABELS[key]??key);
   const items=key==='station'?options.stations.map(s=>[s.id,s.name]):['source_satellite','preferred_satellite'].includes(key)?options.nodes.map(n=>[n.id,n.name]):['source','destination'].includes(key)?[...options.nodes.map(n=>['satellite:'+n.id,'위성 · '+n.name]),...options.stations.map(s=>['station:'+s.id,'지상국 · '+s.name])]:key==='target'?model.TARGET_PRESETS.map(t=>[t.key,t.name]):null;
   if(items){const known=items.some(([id])=>id===v);return `<label>${name}<select id="ms-param-${key}"><option value="">${['source','destination','target'].includes(key)?'선택하세요':'자동 선택'}</option>${!known&&v?`<option value="${escape(v)}" selected>목록에서 확인 필요 · ${escape(v)}</option>`:''}${items.map(([id,label])=>`<option value="${escape(id)}" ${id===v?'selected':''}>${escape(label)}</option>`).join('')}</select></label>`;}
   if(typeof value==='boolean')return `<label><input id="ms-param-${key}" type="checkbox" ${v?'checked':''}> ${name}</label>`;
   return `<label>${name}<input id="ms-param-${key}" type="${typeof value==='number'?'number':'text'}" ${typeof value==='number'?'step="any"':''} value="${escape(Array.isArray(v)?v.join(','):v)}"></label>`;
  }).join('');
  if(kind==='observe'){const e=field('param-target'),fn=()=>{const t=model.TARGET_PRESETS.find(t=>t.key===e.value);if(t){for(const k of ['latitude','longitude'])field('param-'+k).value=t[k];field('param-target_name').value=t.name;dirty=true;capture();}};e.addEventListener('change',fn);removers.push(()=>e.removeEventListener('change',fn));}
  if(kind==='pickup'&&options.external){field('param-external_id').value=String(options.external.catalog_number);field('param-external_name').value=options.external.name??'';}
 }
 function loadEditor(mission=null){editId=mission?.id??null;dirty=false;draft=null;field('kind').value=mission?.kind??'compute';field('name').value=mission?.name??'';field('priority').value=mission?.priority??3;const c=info();const utc=c?.utc;field('start').value=mission?.window_start??utc??'';field('deadline').value=mission?.deadline??(utc?new Date(Date.parse(utc)+2*3600000).toISOString():'');parameters(mission?.params);update();}
 function restoreDraft(){if(!draft)return;field('kind').value=draft.kind;parameters();for(const [id,v] of Object.entries(draft)){if(id!=='params')field(id).value=v;}for(const [k,v] of Object.entries(draft.params)){const f=field('param-'+k);if(f){f.value=v.value;f.checked=v.checked;}}}
 async function action(work){if(dead||busy)return;busy=true;abort=new AbortController();error='';update();try{await work({signal:abort.signal});}catch(e){error=String(e.message);}finally{busy=false;abort=null;if(!dead)update();}}
 function selected(){const id=services.store.selectedId;if(!id)throw Error('임무를 먼저 등록·선택하세요.');return id;}
 function update(){
  if(dead||!root||!serviceViews.has(view))return;
  field('list').innerHTML='<option value="">새 요청</option>'+services.store.missions.map(m=>`<option value="${escape(m.id)}" ${m.id===services.store.selectedId?'selected':''}>${escape(m.name)} · ${escape(model.MISSION_KINDS[m.kind]?.short)} · ${escape(m.status)}</option>`).join('');
  const state=services.execution.snapshot(),mission=services.store.selected,module=services.moduleSnapshot();
  field('module-state').textContent=module?.reachable===true?`군집 모듈 연결 확인 · 마지막 조회 상태 버전 ${module.sequence} · 확정 임무 ${Object.keys(module.committed??{}).length}개`:'군집 모듈 상태 미확인';
  field('status').textContent=[external?'다른 창에서 변경됨 · 편집값을 보존했습니다. 명시적으로 다시 불러오세요.':'',services.store.error,error,state.error,state.status==='idle'?'':state.status,busy?'처리 중':''].filter(Boolean).join(' / ');
  for(const id of ['save','new','duplicate','remove','plan','replan-latest','commit','abort','reload','module'])field(id).disabled=busy||(external&&id!=='reload'&&id!=='module');
  for(const id of ['retry','reconcile'])field(id).disabled=busy||!state.pending;
  field('cancel').disabled=!busy;
  const plan=mission?.plan,inspection=mission&&services.execution.inspection(mission.id),schedule=projectMissionSchedule({missions:services.store.missions,context:info(),inspection,model,selectedId:mission?.id,hours:timelineHours,rowFilter}),name=id=>schedule.rows.find(n=>n.id===id)?.label??id??'—';
  field('verdict').innerHTML=plan?`<p>계획 v${escape(plan.version)} · ${plan.feasible?'편성 가능':'편성 불가'} · ${plan.tasks?.length??0}개 작업 · 계산 UTC ${escape(plan.time)}</p><ul>${(plan.checks??[]).map(c=>`<li>${c.ok?'통과':'확인 필요'} · ${escape(c.label??c.name??'')} · ${escape(c.detail??'')}</li>`).join('')}${(plan.unavailable??[]).map(c=>`<li>제외 위성 · ${escape(name(c.satellite))} · ${escape(c.reason)}</li>`).join('')}</ul><p>${escape((plan.reasons??[]).join(' / '))}</p><p>${schedule.affected.tasks.length?'재구성 필요: '+escape([...schedule.affected.satellites,...schedule.affected.links].map(name).join(', ')):schedule.current?'현재 입력의 재구성 대상 없음':'현재 입력의 재구성 필요 여부 미확인'}</p><p>대안 ${escape(plan.alternatives??0)}개 · ${escape(plan.implementation==='stand_in'?'내장 임시 구현':plan.implementation??'모듈')} ${escape(plan.version_module??plan.version_tag??'')} · 수신 UTC ${escape(plan.received_at??'—')}</p>`:'<p>저장된 계획이 없습니다.</p>';
  field('timeline').innerHTML='';if(schedule.start!==null){const layout=layoutTimeline({rows:schedule.rows,start:schedule.start,end:schedule.end,width:Math.max(600,field('timeline').clientWidth||1200)});field('timeline').innerHTML=timelineMarkup(layout,{...schedule,selectedTaskId,selectedMissionId:mission?.id,kinds:model.TASK_KINDS});}
  field('hours').value=String(timelineHours);field('row-filter').value=rowFilter;field('timeline-state').textContent=`${schedule.rows.length}기 · 전체 활성 임무 작업 ${schedule.tasks.length}개 · ${schedule.current?'현재 분석 UTC':'과거 계획 UTC / 현재 시각 미확인'} · 접속창 ${schedule.contacts.length}개 / 식 ${schedule.eclipses.length}회 / 관측 ${schedule.accesses.length}회 · 창 조회 당시 UTC ${inspection?.request?.time??'미조회'} · 표시 ${timelineHours} h (조회된 native 창 밖은 계산되지 않았습니다.) · 작업 상태는 SIM 계획 시각 추론이며 실제 수행 증거가 아닙니다.`;
  const status=t=>mission?.status==='aborted'?'aborted':mission?.status==='committed'?(schedule.current?model.taskStatusAt(t,schedule.now):'unknown'):'planned',statusLabel=v=>({planned:'예정',running:'진행',done:'완료',aborted:'중단',unknown:'현재 시각 미확인'}[v]??v);
  field('tasks').innerHTML=plan?`<table><thead><tr><th>작업</th><th>위성</th><th>상대</th><th>시작 UTC</th><th>종료 UTC</th><th>길이 min</th><th>크기 MB</th><th>상태</th></tr></thead><tbody>${(plan.tasks??[]).map(t=>`<tr data-ms-task="${escape(t.id)}" class="${t.id===selectedTaskId?'selected':''}" tabindex="0" role="button"><td>${escape(model.TASK_KINDS[t.kind]?.label??t.kind)}</td><td>${escape(name(t.satellite))}</td><td>${escape(name(t.counterpart))}</td><td>${escape(t.start)}</td><td>${escape(t.end)}</td><td>${escape(Number.isFinite(t.duration_s)?(t.duration_s/60).toFixed(1):'—')}</td><td>${escape(t.volume_mb??'—')}</td><td>${escape(statusLabel(status(t)))}</td></tr>`).join('')}</tbody></table>`:'';
  const task=plan?.tasks?.find(t=>t.id===selectedTaskId);field('task-detail').textContent=task?JSON.stringify({...task,mission_id:mission.id,status:status(task)},null,2):'일정표나 작업 행을 선택하면 원본 작업 상세를 표시합니다.';
 }
 function show(next){view=next;if(dead)return;if(!serviceViews.has(next)){capture();if(root)root.hidden=true;return;}
  if(root&&!document.getElementById('source-mission-services')){capture();for(const r of removers.splice(0))r();root=null;}
  if(!root){root=document.createElement('section');root.id='source-mission-services';root.className='panel source-missions';root.innerHTML=`<header><h2>군집 서비스 임무</h2><small>다섯 서비스 · 모의 운용 계획</small></header><div class="body"><p>노드를 배치하고 분석 시계를 정지한 뒤 모듈 상태를 조회하세요. 시간표는 UTC 기준입니다. 수신 장비·실제 통신 성공은 미확인입니다.</p><div class="actions"><label>요청 <select id="ms-list"></select></label><button class="button" id="ms-new" type="button">새 요청</button><button class="button" id="ms-duplicate" type="button">요청 복제</button><button class="button" id="ms-remove" type="button">초안 삭제</button><button class="button" id="ms-reload" type="button">저장 요청 다시 불러오기</button></div><form id="ms-editor"><label>서비스<select id="ms-kind">${Object.entries(model.MISSION_KINDS).map(([k,v])=>`<option value="${k}">${escape(v.label)}</option>`).join('')}</select></label><label>요청 이름<input id="ms-name" required></label><label>우선순위<select id="ms-priority">${Object.entries(model.PRIORITY_LABELS).map(([k,v])=>`<option value="${k}">${escape(v)}</option>`).join('')}</select></label><label>시작 UTC<input id="ms-start" placeholder="YYYY-MM-DDTHH:mm:ssZ" required></label><label>기한 UTC<input id="ms-deadline" placeholder="YYYY-MM-DDTHH:mm:ssZ" required></label><div id="ms-params" class="source-mission-fields"></div><button class="button" id="ms-save" type="submit">요청 저장</button></form><p>배치한 위성·활성 지상국을 목록에서 선택합니다. 빈 선호 위성·지상국은 자동 선택합니다. 처리량·전송률은 모델의 공학적 가정값입니다. 외부 위성 수신은 위성 카탈로그에서 정밀 자료를 선택한 뒤 요청을 작성하세요.</p><p role="status" id="ms-module-state"></p><div class="actions"><button class="button" id="ms-module" type="button">모듈 상태 조회</button><button class="button" id="ms-plan" type="button">계획 계산</button><button class="button" id="ms-replan-latest" type="button">최신 버전 확인 후 새 계획</button><button class="button" id="ms-commit" type="button">계획 확정</button><button class="button" id="ms-abort" type="button">계획 취소</button><button class="button" id="ms-retry" type="button">같은 요청 재시도</button><button class="button" id="ms-reconcile" type="button">미확인 결과 조회</button><button class="button" id="ms-cancel" type="button">현재 요청 대기 취소</button></div><p>새로고침 또는 다른 창의 계획으로 버전이 달라졌다면 최신 버전을 확인하고 현재 위성·지상국 입력으로 새 계획을 계산하세요. 저장된 계획을 자동 승인하지 않습니다. 이미 확정된 작업은 먼저 명시적으로 계획 취소해야 합니다.</p><p role="status" id="ms-status"></p><div id="ms-verdict"></div><div class="actions"><label>표시 범위<select id="ms-hours"><option value="6">6 h</option><option value="12" selected>12 h</option><option value="24">24 h</option></select></label><label>표시 위성<select id="ms-row-filter"><option value="busy">작업 있는 위성</option><option value="all">전체 위성</option></select></label></div><p id="ms-timeline-state"></p><div id="ms-timeline" style="overflow-x:auto"></div><div id="ms-tasks" style="overflow-x:auto"></div><details><summary>선택 작업 상세</summary><pre id="ms-task-detail"></pre></details></div>`;document.getElementById('screen').prepend(root);
   listen('kind','change',()=>{dirty=true;parameters();capture();});listen('editor','input',()=>{dirty=true;capture();});
   listen('hours','change',()=>{const n=Number(field('hours').value);if([6,12,24].includes(n)){timelineHours=n;update();}});listen('row-filter','change',()=>{if(['all','busy'].includes(field('row-filter').value)){rowFilter=field('row-filter').value;update();}});
   const pickTask=e=>{if(e.type==='keydown'&&!['Enter',' '].includes(e.key))return;const target=e.target?.closest?.('[data-timeline-task], [data-ms-task]');if(!target)return;const taskId=target.dataset.timelineTask??target.dataset.msTask,missionId=target.dataset.timelineMission??services.store.selectedId,owner=services.store.missions.find(m=>m.id===missionId&&m.plan?.tasks?.some(t=>t.id===taskId));if(!owner)return;if(owner.id!==services.store.selectedId&&dirty){error='편집값을 저장한 뒤 다른 임무를 선택하세요.';update();return;}e.preventDefault?.();selectedTaskId=taskId;if(owner.id!==services.store.selectedId){services.store.select(owner.id);loadEditor(owner);}else update();};for(const id of ['timeline','tasks']){listen(id,'click',pickTask);listen(id,'keydown',pickTask);}
   listen('list','change',()=>{if(dirty){error='편집 중인 요청을 저장한 뒤 선택을 바꾸세요.';update();return;}try{services.store.select(field('list').value);loadEditor(services.store.selected);}catch(e){error=e.message;update();}});
   listen('new','click',()=>{if(dirty){error='현재 편집값을 먼저 저장하세요.';update();return;}loadEditor();});
   listen('duplicate','click',()=>action(()=>{if(dirty||external)throw Error('편집값을 먼저 저장·확인하세요.');services.store.duplicate(selected());loadEditor(services.store.selected);}));
   listen('remove','click',()=>action(()=>{const id=selected(),m=services.store.find(id);if(dirty||external)throw Error('편집값을 먼저 저장·확인하세요.');if(!['draft','aborted'].includes(m.status))throw Error('수락한 계획을 먼저 취소하세요.');if(host.confirm('선택한 초안을 삭제할까요?')){services.store.remove(id);loadEditor(services.store.selected);}}));
   listen('reload','click',()=>{if(!host.confirm('저장된 요청을 다시 불러오면 현재 편집값이 대체됩니다. 계속할까요?'))return;if(services.store.load()){external=false;loadEditor(services.store.selected);}else update();});
   listen('editor','submit',e=>{e.preventDefault();return action(()=>{if(external)throw Error('다른 창의 변경을 먼저 불러오세요.');const kind=field('kind').value,params={};for(const [k,v] of Object.entries(model.DEFAULT_PARAMS[kind])){const f=field('param-'+k);if(typeof v==='number'){if(!f.value.trim()||!Number.isFinite(Number(f.value)))throw Error((LABELS[k]??k)+' 숫자를 확인하세요.');params[k]=Number(f.value);}else if(typeof v==='boolean')params[k]=f.checked;else if(Array.isArray(v))params[k]=f.value.split(',').map(s=>s.trim()).filter(Boolean);else params[k]=f.value.trim();}const patch={name:field('name').value.trim(),kind,priority:Number(field('priority').value),window_start:field('start').value.trim(),deadline:field('deadline').value.trim(),params};const c=info(),validation=c?{satellites:c.nodes,stations:c.stations}:{};if(editId){if(services.store.find(editId)?.status==='committed')throw Error('확정된 계획을 먼저 취소하세요.');const errors=services.store.update(editId,patch,validation);if(errors.length)throw Error(errors.join(' '));}else{const result=services.store.add(patch,validation);if(result.errors.length)throw Error(result.errors.join(' '));}loadEditor(services.store.selected);});});
   for(const [id,work] of [['module',async options=>{await services.queryModule(options);if(!dirty&&!field('start').value)loadEditor(services.store.selected);}],['plan',options=>{if(dirty)throw Error('편집값을 먼저 저장하세요.');return services.execution.plan(selected(),options);}],['replan-latest',options=>{if(dirty)throw Error('편집값을 먼저 저장하세요.');return services.execution.replanLatest(selected(),options);}],['commit',options=>{if(dirty)throw Error('편집값을 먼저 저장하세요.');return services.execution.commit(selected(),options);}],['abort',options=>services.execution.abort(selected(),options)],['retry',options=>services.execution.retry(options)],['reconcile',options=>services.execution.reconcile(options)]])listen(id,'click',()=>action(work));
   listen('cancel','click',()=>abort?.abort());
   if(draft)restoreDraft();else loadEditor(services.store.selected);
  }
  root.hidden=false;update();
 }
 const changed=()=>update(),removeStore=services.store.subscribe(changed);const storage=e=>{if(e.key==='spacetwin-missions-v1'){external=true;capture();update();}};host.addEventListener('storage',storage);
 return Object.freeze({show,update,hasExternalChange:()=>external,destroy(){if(dead)return;dead=true;abort?.abort();for(const r of removers.splice(0))r();removeStore();host.removeEventListener('storage',storage);root?.remove();}});
}
