// V6 presentation of the senior ICD-08 reports; policy belongs to the runtime module.
import {securityView,transportView} from '../security/view_model.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const utc=value=>{const time=typeof value==='number'?value:typeof value==='string'?Date.parse(value):NaN;return Number.isFinite(time)&&Number.isFinite(new Date(time).getTime())?new Date(time).toISOString():'—';};
export function createSourceSecurityPanel({api,document,host,now=()=>Date.now(),setTimer=(f,t)=>setTimeout(f,t),clearTimer=id=>clearTimeout(id)}={}){
 if(!api||typeof api.securityDashboard!=='function'||!document||!host)throw TypeError('source security presentation ports required');
 let root=null,view=null,dead=false,report=null,receivedAt=null,telemetryAt=null,socket='connecting',error='',runtimeRun=null,runtimeRunning=null,generation=0,request=null,timer=null,freshnessTimer=null,timeoutTimer=null;
 const field=id=>root?.querySelector('#ss-'+id),put=(id,value)=>{const el=field(id);if(el)el.textContent=String(value);};
 function render(){if(!root||dead)return;const value=securityView(report,{now:now(),receivedAt,telemetryAt,socket,error}),observation=report?.overview?.observation,module=report?.module;
  field('flow').dataset.moving=String(view==='security'&&!document.hidden&&value.animate&&runtimeRunning!==false);field('flow').dataset.tone=value.tone;
  for(const [id,text] of Object.entries({'state':value.state,'auth':value.auth,'auth-state':value.authentication,'throughput':value.throughput,'loss':value.loss,'integrity':value.integrity,'device':value.mockDevice,'run':observation?.run_id??'—','observed':utc(observation?.observed_at),'received':utc(receivedAt),'sim':typeof observation?.sim_elapsed_s==='number'?`T+${observation.sim_elapsed_s.toFixed(1)} s`:'—','placement':module?.placement==='remote'?'외부 HTTP 모듈':module?.placement==='embedded'?'내장 SIM 모듈':'미확인','implementation':module?.implementation??'미확인','endpoint':module?.endpoint??(module?.placement==='embedded'?'동일 프로세스 / 계약 호출':'미확인'),'version':module?.contract_version?`ICD-08 v${module.contract_version}`:'수신 대기','threshold':typeof report?.overview?.threshold==='number'?`모듈 인증 기준 ≥ ${report.overview.threshold}%`:'판정 수신 대기','evidence':error||(!value.live&&report?'마지막 수신값입니다. 최신 상태를 확인할 수 없습니다.':'모듈 보고에 따른 SIM 지표입니다. 실제 보안 보증이 아닙니다.')}))put(id,text);
  field('query').disabled=!!request;
  field('events').innerHTML=(report?.events?.events??[]).slice(-40).reverse().map(e=>`<tr><td>${escape(utc(e.observed_at))}</td><td>SIM</td><td>${escape(e.message??e.authentication)}</td></tr>`).join('')||'<tr><td colspan="3">모듈 관측 이력 없음</td></tr>';
 }
 const active=()=>!dead&&view==='security'&&!document.hidden;
 function cancel(){generation++;request?.abort();request=null;for(const id of [timer,freshnessTimer,timeoutTimer])clearTimer(id);timer=freshnessTimer=timeoutTimer=null;}
 function freshness(){if(!active()||freshnessTimer!==null)return;const token=generation;freshnessTimer=setTimer(()=>{freshnessTimer=null;if(token!==generation||!active())return;render();freshness();},1000);freshnessTimer?.unref?.();}
 async function query(){if(!active()||request)return;clearTimer(timer);timer=null;const token=generation,expectedRun=runtimeRun,controller=new AbortController();request=controller;error='';render();if(!active()||token!==generation||request!==controller||controller.signal.aborted)return;const timeout=setTimer(()=>{if(token===generation&&request===controller){error='보안 모듈 응답 시간 초과';controller.abort();render();}},8000);timeoutTimer=timeout;timeout?.unref?.();try{const value=await api.securityDashboard({signal:controller.signal});if(!active()||token!==generation||expectedRun!==runtimeRun||controller.signal.aborted)return;if(runtimeRun&&value?.runtime?.run_id!==runtimeRun)throw Error('현재 SIM 실행과 다른 보안 보고입니다.');if(!value?.module||!value?.overview||!value?.events)throw Error('ICD-08 보고 응답 오류');report=structuredClone(value);receivedAt=now();}catch(e){if(active()&&token===generation){if(e.report?.module)report={...report,module:structuredClone(e.report.module)};error=e.name==='AbortError'?'보안 모듈 응답 시간 초과':String(e.message);}}finally{clearTimer(timeout);if(timeoutTimer===timeout)timeoutTimer=null;if(request===controller)request=null;if(active()&&token===generation){render();if(!active()||token!==generation)return;timer=setTimer(()=>{timer=null;if(token===generation&&active())void query();},2000);timer?.unref?.();}}}
 function activate(){if(!active())return;freshness();void query();}
 function visibility(){if(dead)return;cancel();render();activate();}
 document.addEventListener?.('visibilitychange',visibility);
 function show(next){if(dead)return;let previous=view;view=next;if(next!=='security'){cancel();if(root)root.hidden=true;return;}if(root&&!document.getElementById('source-security-services')){cancel();previous=null;field('query')?.removeEventListener('click',query);root=null;}if(!root){root=document.createElement('section');root.id='source-security-services';root.className='panel source-security';root.innerHTML=`<div class="panel-title">보안 관측 / 선배 ICD-08 SIM 모듈</div><div class="panel-body"><p>선배의 관측·규칙 판정·전환 이력을 조회합니다. 실제 인증·암호화·파일 무결성 검증은 구현되어 있지 않습니다.</p><button id="ss-query" type="button">현재 SIM 보안 관측 조회</button><p id="ss-state" role="status"></p><div id="ss-flow"><dl>${[['auth','인증률 SIM %'],['auth-state','모듈 판정'],['threshold','판정 기준'],['throughput','처리량 Mbps'],['loss','손실 %'],['integrity','무결성'],['device','PQC-TEE MOCK 상태'],['run','SIM 실행'],['sim','SIM 경과'],['observed','관측 UTC'],['received','수신 UTC'],['placement','모듈 위치'],['implementation','구현'],['endpoint','접속점'],['version','계약']].map(([id,label])=>`<dt>${label}</dt><dd id="ss-${id}"></dd>`).join('')}</dl></div><p id="ss-evidence"></p><p>${escape(transportView(host.location?.protocol).protocol)}: ${escape(transportView(host.location?.protocol).detail)}</p><table><thead><tr><th>관측 UTC</th><th>자료</th><th>전환 이력</th></tr></thead><tbody id="ss-events"></tbody></table><p>원본 이력은 최근 200개 전환을 메모리에 보존하며 여기서는 최근 40개를 표시합니다. 영구 기록이 아닙니다.</p></div>`;document.getElementById('screen').prepend(root);field('query').addEventListener('click',query);}root.hidden=false;render();if(previous!=='security')activate();}
 return Object.freeze({show,query,updateTelemetry(payload){if(dead)return;telemetryAt=now();if(['stale','invalid'].includes(socket))socket='open';let changed=false;if(payload?.runtime){const nextRun=payload.runtime.run_id;if(runtimeRun&&nextRun&&nextRun!==runtimeRun){cancel();report=null;receivedAt=null;error='';changed=true;}if(nextRun)runtimeRun=nextRun;runtimeRunning=payload.runtime.running;}render();if(changed)activate();},updateSocket(value){if(dead)return;socket=value;render();},destroy(){if(dead)return;dead=true;cancel();document.removeEventListener?.('visibilitychange',visibility);field('query')?.removeEventListener('click',query);root?.remove();}});
}
