// V6 rendering over the pinned source scenario runner and KPI functions. No runtime or model owner.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createSourceScenarioPanel({runner,comparisonRows,document,host,views=['run','composer','compare']}={}){
 if(!runner||typeof comparisonRows!=='function'||!document||!host)throw TypeError('scenario presentation owners required');
 let root=null,view=null,dead=false,busy=false,error='',listing=[];const removers=[];
 const field=id=>root?.querySelector('#sc-'+id);
 const listen=(id,type,fn)=>{const el=field(id);el.addEventListener(type,fn);removers.push(()=>el.removeEventListener(type,fn));};
 async function act(fn){if(dead||busy)return;busy=true;error='';update();try{await fn();}catch(e){error=e.message;}finally{busy=false;update();}}
 function update(){if(dead||!root)return;const v=runner.view();field('state').textContent=[v.phase,v.runId?`SIM 실행 ${v.runId}`:'실행 없음',error,v.setup?.error].filter(Boolean).join(' / ');field('utc').textContent=`SIM UTC ${new Date(v.now).toISOString()} · T+${Number(v.elapsed).toFixed(1)}s · ${v.running?'진행':'정지'} · ×${v.speed}`;
 field('definition').innerHTML=v.scenario?`<h3>${esc(v.scenario.name)}</h3><p>${esc(v.scenario.objective??'')}</p><p>군집 ${esc(v.scenario.constellation?.planes)}면 × ${esc(v.scenario.constellation?.per_plane)}기 · 지상국 ${esc(v.scenario.stations?.join(', '))}</p><ul>${(v.scenario.missions??[]).map(m=>`<li>${esc(m.name)} · ${esc(m.kind)} · ${m.commit?'세팅 시 확정':'초안'}</li>`).join('')}</ul>`:'<p>시나리오 정의를 명시적으로 불러오세요.</p>';
 field('steps').innerHTML=`<ol>${v.steps.map(s=>`<li><b>${esc(s.title)}</b> · ${esc(s.status)} · ${s.due==null?'시각 미정':`T+${esc(s.due)}s`}<p>${esc(s.narrativeText??'')}</p><ul>${(s.checkResults??[]).map(c=>`<li>${esc(c.label)}: ${c.pending?'미확인':c.ok?'통과':'미달'} · ${esc(c.display)}</li>`).join('')}</ul></li>`).join('')}</ol>`;
 field('speed-options').innerHTML=(v.scenario?.playback?.speeds??[1,2,5,10,30,60]).filter(n=>Number.isFinite(n)&&n>=0.1&&n<=128).map(n=>`<option value="${esc(n)}">×${esc(n)}</option>`).join('');
 const rows=comparisonRows(v.phases);field('compare').innerHTML=rows.length?`<table><thead><tr><th>측정</th><th>정상</th><th>장애</th><th>우회</th><th>복구</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r.label)}</th>${(r.cells??[]).map(x=>`<td>${esc(x.display)}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p>실행 중 수집한 KPI가 없습니다.</p>';
 field('result').textContent=v.verdict?JSON.stringify(v.verdict,null,2):'복구 판정 미확인';field('log').textContent=v.log.map(l=>`T+${l.t}s ${l.icd} ${l.message}: ${l.summary}`).join('\n');for(const id of ['list','load','setup','play','pause','advance','next','speed','speed-apply','stop','restore','follow'])field(id).disabled=busy;
 }
 function show(next){view=next;if(dead)return;if(!views.includes(next)){if(root)root.hidden=true;return;}if(root&&!document.getElementById('source-scenario-services')){for(const r of removers.splice(0))r();root=null;}
 if(!root){root=document.createElement('section');root.id='source-scenario-services';root.className='panel';root.innerHTML=`<header><h2>선배 PoC 시나리오</h2><small>원본 정의·단계 조치·복구 KPI · SIM</small></header><div class="body"><p>세팅은 SIM을 새 실행으로 초기화하고 현재 노드 초안·지상국 구성을 바꾸며 시나리오 임무를 등록합니다. 정의를 확인한 뒤 명시적으로 실행하세요. GP 분석 UTC는 기본적으로 독립입니다. 실제 장비 검증이 아닙니다.</p><button type="button" id="sc-list">정의 목록 조회</button><select id="sc-choice" aria-label="PoC 시나리오"></select><button type="button" id="sc-load">선택 정의 불러오기</button><button type="button" id="sc-setup">검토한 구성 세팅</button><button type="button" id="sc-play">재생</button><button type="button" id="sc-pause">SIM 일시정지</button><input id="sc-seconds" type="number" min="1" max="3600" value="30" aria-label="SIM 전진 초"><button type="button" id="sc-advance">SIM 전진</button><button type="button" id="sc-next">다음 단계 전진</button><input id="sc-speed" type="number" min="0.1" max="128" value="1" step="0.1" list="sc-speed-options" aria-label="SIM 배속"><datalist id="sc-speed-options"></datalist><button type="button" id="sc-speed-apply">배속 적용</button><button type="button" id="sc-stop">시나리오 재생기 해제</button><button type="button" id="sc-restore">저장된 재생 기록 불러오기</button><button type="button" id="sc-follow">분석 시계 SIM 연결</button><p id="sc-state" role="status"></p><p id="sc-utc"></p><div id="sc-definition"></div><div id="sc-steps"></div><div id="sc-compare" style="overflow:auto"></div><pre id="sc-result"></pre><details><summary>ICD 조치 기록</summary><pre id="sc-log"></pre></details></div>`;document.getElementById('screen').prepend(root);
 listen('list','click',()=>act(async()=>{listing=await runner.list();field('choice').innerHTML=listing.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');}));listen('load','click',()=>act(()=>runner.select(field('choice').value)));
 listen('setup','click',()=>act(async()=>{if(!runner.definition)throw Error('정의를 먼저 불러오세요.');if(host.confirm('현재 SIM 실행, 노드 초안, 지상국을 시나리오 구성으로 바꾸고 지정 임무를 확정합니다. 검토한 구성을 적용할까요?'))await runner.setup();}));
 for(const [id,fn] of [['play',()=>runner.play()],['pause',()=>runner.pause()],['next',()=>runner.skipToNextStep()],['stop',()=>runner.stop()],['restore',()=>runner.restore()]])listen(id,'click',()=>act(fn));
 listen('advance','click',()=>act(()=>{const n=Number(field('seconds').value);if(!Number.isFinite(n)||n<1||n>3600)throw Error('전진은 1~3600초입니다.');return runner.advance(n);}));listen('speed-apply','click',()=>act(()=>{const n=Number(field('speed').value);if(!Number.isFinite(n)||n<0.1||n>128)throw Error('배속은 0.1 이상 128 이하입니다.');return runner.setSpeed(n);}));listen('follow','click',()=>act(()=>{if(host.confirm('기존 분석 시계를 SIM UTC에 명시적으로 연결할까요?'))runner.clock.setFollowAnalysis(true);else throw Error('분석 시계 연결을 취소했습니다.');}));
 }
 root.hidden=false;update();}
 const unsubscribe=runner.subscribe(update);return Object.freeze({show,update,destroy(){if(dead)return;dead=true;unsubscribe();for(const r of removers.splice(0))r();root?.remove();}});
}
