// V6 rendering over the pinned source scenario runner and KPI functions. No runtime or model owner.
const checkLabel=v=>({completed:'완료 당시 검증',current:'현재 상태',failed_completed:'완료 당시 검증 미달',legacy_current:'과거 검증 기록 없음 · 현재 상태'}[v]??'검증 기록 미확인');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TAB_LABELS={orbit:'대시보드',nodes:'노드',communication:'통신',data:'데이터',security:'보안',mission:'임무',status:'상태',settings:'설정'};
export function createSourceScenarioPanel({runner,comparisonRows,document,host,onResume,onFollow,onRelease,onStop,onOpenTab,moduleName=id=>id,views=['run','composer','compare']}={}){
 if(!runner||typeof comparisonRows!=='function'||!document||!host)throw TypeError('scenario presentation owners required');
 let root=null,view=null,dead=false,busy=false,error='',listing=[],reviewedDefinition=null;const removers=[];
 const field=id=>root?.querySelector('#sc-'+id);
 const listen=(id,type,fn)=>{const el=field(id);el.addEventListener(type,fn);removers.push(()=>el.removeEventListener(type,fn));};
 let guideDismissedFor=null;
 let dock=null,dockCollapsed=false;const dockRemovers=[];const dockField=id=>dock?.querySelector('#sc-dock-'+id);
 const flows=items=>(items??[]).map(f=>`<span class="sd-flow"><b>${esc(moduleName(f.from))}</b> → <b>${esc(moduleName(f.to))}</b> <em>${esc(f.icd)}</em> <small>${esc(f.message)}</small></span>`).join('');
 const tabs=s=>(s.tabs??[s.tab]).filter(Boolean).map(tab=>`<button class="button" type="button" data-goto-tab="${esc(tab)}" ${typeof onOpenTab==='function'?'':'disabled'}>${esc(TAB_LABELS[tab]??tab)} 보기</button>`).join('');
 async function navigate(event){const button=event.target?.closest?.('[data-goto-tab], [data-guide-close]');if(!button)return;if(button.dataset.guideClose!==undefined){guideDismissedFor=runner.view().currentStep??runner.view().steps[0]?.id;update();return;}const tab=button.dataset.gotoTab;const allowed=runner.view().steps.some(s=>(s.tabs??[s.tab]).includes(tab));if(!allowed||typeof onOpenTab!=='function')return;await act(()=>onOpenTab(tab));}
 function downloadRecord(){if(!runner.view().verdict)throw Error('판정 결과가 아직 없습니다.');if(typeof runner.record!=='function'||!host.URL?.createObjectURL||!host.URL?.revokeObjectURL||typeof host.setTimeout!=='function')throw Error('JSON 다운로드 연결이 없습니다.');const record=runner.record(),blob=new (host.Blob??globalThis.Blob)([JSON.stringify(record,null,2)],{type:'application/json'}),url=host.URL.createObjectURL(blob);try{const link=document.createElement('a');link.href=url;link.download=`${record.scenario_id||'scenario'}-${(record.run_id||'run').replace(/[^A-Z0-9-]/gi,'')}.json`;document.body.append(link);try{link.click();}finally{link.remove();}}finally{host.setTimeout(()=>host.URL.revokeObjectURL(url),1000);}}
 async function act(fn){if(dead||busy)return;busy=true;error='';update();try{await fn();}catch(e){error=e.message;}finally{busy=false;update();}}
 function compactDock(){
  if(dead)return;const v=runner.view(),active=['preparing','ready','playing','paused','finished','stale'].includes(v.phase)&&!views.includes(view);if(!active){if(dock)dock.hidden=true;return;}
  if(dock&&!document.getElementById('source-scenario-dock')){for(const r of dockRemovers.splice(0))r();dock=null;}
  if(!dock){
   dock=document.createElement('aside');dock.id='source-scenario-dock';dock.className='panel';
   dock.innerHTML='<header class="actions"><strong id="sc-dock-state"></strong><button class="button" type="button" id="sc-dock-collapse" aria-expanded="true">접기</button></header><div id="sc-dock-controls" class="actions"><button class="button" type="button" id="sc-dock-play">재생</button><button class="button" type="button" id="sc-dock-pause">SIM 일시정지</button><button class="button" type="button" id="sc-dock-next">다음 단계</button><label>SIM 배속<select id="sc-dock-speed" aria-label="안내 SIM 배속"></select></label><button class="button" type="button" id="sc-dock-result">결과 보기</button><button class="button" type="button" id="sc-dock-return">실행 화면</button><button class="button" type="button" id="sc-dock-auto-follow">단계 자동 이동</button></div><details id="sc-dock-guide"><summary id="sc-dock-title">현재 단계 안내</summary><div id="sc-dock-body"></div></details>';
   const quick=document.getElementById('window-quick');if(typeof quick?.after==='function')quick.after(dock);else document.getElementById('screen').prepend(dock);
   for(const [id,fn] of [['play',()=>runner.play()],['pause',()=>runner.pause()],['next',()=>runner.skipToNextStep()],['result',()=>onOpenTab?.('compare')],['return',()=>onOpenTab?.('run')],['auto-follow',()=>runner.setAutoFollow?.(runner.view().autoFollow!==true)],['collapse',()=>{dockCollapsed=!dockCollapsed;}]]){const el=dockField(id),handler=()=>act(fn);el.addEventListener('click',handler);dockRemovers.push(()=>el.removeEventListener('click',handler));}
   const speed=dockField('speed'),setSpeed=()=>{const value=Number(speed.value);return act(()=>runner.setSpeed(value));};speed.addEventListener('change',setSpeed);dockRemovers.push(()=>speed.removeEventListener('change',setSpeed));
   const el=dockField('body');el.addEventListener('click',navigate);dockRemovers.push(()=>el.removeEventListener('click',navigate));
  }
  dock.hidden=false;const step=v.steps.find(s=>s.id===v.currentStep)??v.steps[0];
  dockField('state').textContent=`${v.scenario?.name??'선배 PoC'} · ${v.phase} · T+${Number(v.elapsed).toFixed(1)} s${error?' / '+error:''}`;
  dockField('play').disabled=busy||!['ready','paused'].includes(v.phase);dockField('pause').disabled=busy||v.phase!=='playing';dockField('next').disabled=busy||!['ready','playing','paused'].includes(v.phase)||typeof runner.skipToNextStep!=='function';
  dockField('speed').disabled=busy||typeof runner.setSpeed!=='function';const speeds=v.scenario?.playback?.speeds??[1,2,5,10,30,60];dockField('speed').innerHTML=speeds.filter(n=>Number.isFinite(n)&&n>=0.1&&n<=128).map(n=>`<option value="${esc(n)}">×${esc(n)}</option>`).join('');dockField('speed').value=String(v.speed);
  dockField('result').disabled=busy||!v.verdict||typeof onOpenTab!=='function';dockField('return').disabled=busy||typeof onOpenTab!=='function';
  dockField('collapse').disabled=busy;dockField('collapse').textContent=dockCollapsed?'펼치기':'접기';dockField('collapse').setAttribute?.('aria-expanded',String(!dockCollapsed));dockField('controls').hidden=dockCollapsed;
  dockField('auto-follow').disabled=busy||typeof runner.setAutoFollow!=='function';dockField('auto-follow').textContent=`단계 자동 이동 ${v.autoFollow?'켜짐':'꺼짐'}`;dockField('auto-follow').setAttribute?.('aria-pressed',String(v.autoFollow===true));
  dockField('title').textContent=step?`${step.title} · ${step.narrativeText??step.narrative??''}`:'현재 단계 없음';dockField('guide').hidden=dockCollapsed||!step||guideDismissedFor===step.id;dockField('body').innerHTML=step?`<p>${esc(step.narrativeText??step.narrative??'')}</p><div>${flows(step.flows)}</div><div class="actions">${tabs(step)}<button class="button" type="button" data-guide-close>안내 닫기</button></div>`:'';
 }
 function update(){if(dead)return;compactDock();if(!root)return;const v=runner.view();field('state').textContent=[v.phase,v.runId?`SIM 실행 ${v.runId}`:'실행 없음',v.phase==='preparing'?(v.setup?.stages??[]).find(([id])=>id===v.setup?.stage)?.[1]:null,error,v.setup?.error].filter(Boolean).join(' / ');field('utc').textContent=`SIM UTC ${new Date(v.now).toISOString()} · T+${Number(v.elapsed).toFixed(1)}s · ${v.running?'진행':'정지'} · ×${v.speed}`;
 if(reviewedDefinition!==runner.definition){reviewedDefinition=runner.definition;field('setup-review').checked=false;}
 field('definition').innerHTML=v.scenario?`<h3>${esc(v.scenario.name)}</h3><p>${esc(v.scenario.objective??'')}</p><p>군집 ${esc(v.scenario.constellation?.planes)}면 × ${esc(v.scenario.constellation?.per_plane)}기 · 지상국 ${esc(v.scenario.stations?.join(', '))}</p><ul>${(v.scenario.missions??[]).map(m=>`<li>${esc(m.name)} · ${esc(m.kind)} · ${m.commit?'세팅 시 확정':'초안'}</li>`).join('')}</ul>`:'<p>시나리오 정의를 명시적으로 불러오세요.</p>';
 field('speed-options').innerHTML=(v.scenario?.playback?.speeds??[1,2,5,10,30,60]).filter(n=>Number.isFinite(n)&&n>=0.1&&n<=128).map(n=>`<option value="${esc(n)}">×${esc(n)}</option>`).join('');
 field('auto-follow').setAttribute?.('aria-pressed',String(v.autoFollow===true));field('auto-follow').textContent=`단계 화면 자동 이동 ${v.autoFollow?'켜짐':'꺼짐'}`;field('auto-follow').disabled=busy||typeof runner.setAutoFollow!=='function';field('download').disabled=busy||!v.verdict||typeof runner.record!=='function';
 const step=v.steps.find(s=>s.id===v.currentStep)??v.steps[0];field('guide').hidden=!step||guideDismissedFor===step.id;field('guide').innerHTML=step?`<header><h3>${esc(step.title)}</h3><button class="button" type="button" data-guide-close aria-label="단계 안내 닫기">×</button></header><p>${esc(step.narrativeText??step.narrative??'')}</p><div>${flows(step.flows)}</div><p>지금 볼 화면: ${esc(TAB_LABELS[step.tab]??step.tab)}</p><div class="actions">${tabs(step)}</div>`:'';
 field('steps').innerHTML=`<ol>${v.steps.map(s=>`<li><b>${esc(s.title)}</b> · ${esc(s.status)} · ${s.due==null?'시각 미정':`T+${esc(s.due)}s`}<p>${esc(s.narrativeText??'')}</p><div>${flows(s.flows)}</div><div class="actions">${tabs(s)}</div><small>${esc(checkLabel(s.checkSource))}${s.checksCapturedElapsed!=null?` · T+${esc(s.checksCapturedElapsed)}s`:''}</small><ul>${(s.checkResults??[]).map(c=>`<li>${esc(c.label)}: ${c.pending?'미확인':c.ok?'통과':'미달'} · ${esc(c.display)} · ${esc(c.rule??'')}</li>`).join('')}</ul></li>`).join('')}</ol>`;
 const e=v.events??{},at=value=>value==null?'—':`T+${esc(value)} s`;field('events').innerHTML=`<h3>사건</h3><dl><dt>장애 주입</dt><dd>${at(e.fault_at_s)} · ${esc(e.fault_link??'')}</dd><dt>대체 경로 확인</dt><dd>${at(e.detour_available_at_s)}${e.detour_available_at_s!=null&&e.fault_at_s!=null?` (재수렴 ${esc(Math.round(e.detour_available_at_s-e.fault_at_s))} s)`:''}</dd><dt>재구성 요청</dt><dd>${at(e.reroute_at_s)}</dd><dt>장애 해제</dt><dd>${at(e.fault_end_s)}</dd><dt>주 경로 복귀</dt><dd>${at(e.primary_restored_at_s)}</dd></dl>`;
 const rows=comparisonRows(v.phases);field('compare').innerHTML=rows.length?`<table><thead><tr><th>측정</th><th>정상</th><th>장애</th><th>우회</th><th>복구</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r.label)}</th>${(r.cells??[]).map(x=>`<td>${esc(x.display)}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p>실행 중 수집한 KPI가 없습니다.</p>';
 field('result').textContent=v.verdict?JSON.stringify(v.verdict,null,2):'복구 판정 미확인';field('log').textContent=v.log.map(l=>`T+${l.t}s ${l.icd} ${l.message}: ${l.summary}`).join('\n');for(const id of ['list','load','setup','play','pause','advance','next','speed','speed-apply','stop','restore','follow'])field(id).disabled=busy;field('resume').disabled=busy||typeof onResume!=='function';field('follow').disabled=busy||typeof onFollow!=='function';field('release').disabled=busy||typeof onRelease!=='function';field('setup-review').disabled=busy||!runner.definition;field('setup').disabled=busy||!runner.definition||!field('setup-review').checked;
 }
 function show(next){view=next;if(dead)return;if(!views.includes(next)){if(root)root.hidden=true;compactDock();return;}if(dock)dock.hidden=true;if(root&&!document.getElementById('source-scenario-services')){for(const r of removers.splice(0))r();root=null;}
 if(!root){root=document.createElement('section');root.id='source-scenario-services';root.className='panel';root.innerHTML=`<header><h2>선배 PoC 시나리오</h2><small>원본 정의·단계 조치·복구 KPI · SIM</small></header><div class="body"><p>세팅은 SIM을 새 실행으로 초기화하고 현재 노드 초안·지상국 구성을 바꾸며 시나리오 임무를 등록합니다. 정의를 확인한 뒤 명시적으로 실행하세요. GP 분석 UTC는 기본적으로 독립입니다. 실제 장비 검증이 아닙니다.</p><div class="actions"><button class="button" type="button" id="sc-list">정의 목록 조회</button><select id="sc-choice" aria-label="PoC 시나리오"></select><button class="button" type="button" id="sc-load">선택 정의 불러오기</button><label><input type="checkbox" id="sc-setup-review"> 불러온 정의를 검토했고, 현재 SIM 실행·노드 초안·지상국 교체와 지정 임무 확정을 확인했습니다.</label><button class="button" type="button" id="sc-setup">검토한 구성 세팅</button><button class="button" type="button" id="sc-play">재생</button><button class="button" type="button" id="sc-pause">SIM 일시정지</button><input id="sc-seconds" type="number" min="1" max="3600" value="30" aria-label="SIM 전진 초"><button class="button" type="button" id="sc-advance">SIM 전진</button><button class="button" type="button" id="sc-next">다음 단계 전진</button><input id="sc-speed" type="number" min="0.1" max="128" value="1" step="0.1" list="sc-speed-options" aria-label="SIM 배속"><datalist id="sc-speed-options"></datalist><button class="button" type="button" id="sc-speed-apply">배속 적용</button><button class="button" type="button" id="sc-stop">시나리오 재생기 해제</button><button class="button" type="button" id="sc-restore">저장된 재생 기록 불러오기</button><button class="button" type="button" id="sc-resume">현재 실행 검증 후 재개 허용</button><button class="button" type="button" id="sc-follow">분석 시계 SIM 연결</button><button class="button" type="button" id="sc-release">분석 시계 현재 시각으로 해제</button><button class="button" type="button" id="sc-auto-follow" aria-pressed="true">단계 화면 자동 이동</button><button class="button" type="button" id="sc-download">VF-03 결과 JSON 저장</button></div><p id="sc-state" role="status"></p><p id="sc-utc"></p><div id="sc-definition"></div><aside id="sc-guide"></aside><div id="sc-events"></div><div id="sc-steps"></div><div id="sc-compare" style="overflow:auto"></div><pre id="sc-result"></pre><details><summary>ICD 조치 기록</summary><pre id="sc-log"></pre></details></div>`;document.getElementById('screen').prepend(root);
 listen('list','click',()=>act(async()=>{listing=await runner.list();field('choice').innerHTML=listing.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');}));listen('load','click',()=>act(()=>runner.select(field('choice').value)));
 listen('setup-review','change',update);
 listen('auto-follow','click',()=>act(()=>runner.setAutoFollow(runner.view().autoFollow!==true)));listen('download','click',()=>act(downloadRecord));listen('guide','click',navigate);listen('steps','click',navigate);
 listen('setup','click',()=>act(async()=>{if(!runner.definition)throw Error('정의를 먼저 불러오세요.');if(!field('setup-review').checked||reviewedDefinition!==runner.definition)throw Error('불러온 구성의 교체 범위를 먼저 확인하세요.');field('setup-review').checked=false;await runner.setup();}));
 listen('resume','click',()=>act(async()=>{if(typeof onResume!=='function')throw Error('재개 검증 연결이 없습니다.');await onResume();}));
 for(const [id,fn] of [['play',()=>runner.play()],['pause',()=>runner.pause()],['next',()=>runner.skipToNextStep()],['stop',()=>typeof onStop==='function'?onStop():runner.stop()],['restore',()=>runner.restore()]])listen(id,'click',()=>act(fn));
 listen('advance','click',()=>act(()=>{const n=Number(field('seconds').value);if(!Number.isFinite(n)||n<1||n>3600)throw Error('전진은 1~3600초입니다.');return runner.advance(n);}));listen('speed-apply','click',()=>act(()=>{const n=Number(field('speed').value);if(!Number.isFinite(n)||n<0.1||n>128)throw Error('배속은 0.1 이상 128 이하입니다.');return runner.setSpeed(n);}));listen('follow','click',()=>act(async()=>{if(typeof onFollow!=='function')throw Error('분석 시계 연결이 없습니다.');await onFollow();}));listen('release','click',()=>act(async()=>{if(typeof onRelease!=='function')throw Error('분석 시계 해제 연결이 없습니다.');await onRelease();}));
 }
 root.hidden=false;update();}
 const unsubscribe=runner.subscribe(update);return Object.freeze({show,update,destroy(){if(dead)return;dead=true;unsubscribe();for(const r of removers.splice(0))r();for(const r of dockRemovers.splice(0))r();dock?.remove();root?.remove();}});
}
